### ISSUE TITLE
minion.d path is not created in debian squeeze using git 0.11

### ISSUE THREAD

**Issue by jorgeecardona** [saltstack/salt-bootstrap#10]
Hi,

I imagine this is pretty small issue, but I think the path /etc/salt/minion.d must be created by the oneliner, I'm currently using this:

```
wget -O - http://bootstrap.saltstack.org | sudo sh -s git 0.11
```

and the path is not created, the rest works perfect.

Bye.

**Comment by thatch45** [comment]
I don't think that directory is required, and this would be a packaging question more than a bootstrap question I think, since the bootstrap relies on packages.
Are you seeing errors wrt /etc/salt/minion.d ?

**Comment by jorgeecardona** [comment]
No it works perfect, but the "one-liner" is not working as a "one-liner"
since I still have to do an extra mkdir /etc/salt/minion.d to have a
working environment. Is just that.

Bye.

On Wed, Dec 26, 2012 at 12:26 AM, Thomas S Hatch
notifications@github.comwrote:

> I don't think that directory is required, and this would be a packaging
> question more than a bootstrap question I think, since the bootstrap relies
> on packages.
> Are you seeing errors wrt /etc/salt/minion.d ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/saltstack/salt-bootstrap/issues/10#issuecomment-11681034.

## 

Jorge Eduardo Cardona

jorgeecardona@gmail.com
jorge@cardona.co

cardona.co
github.com/jorgeecardona

**Comment by thatch45** [comment]
I am confused, what part of the environment is not working? Is it just the fact that you need to make the directory before plopping files into it?

**Comment by jorgeecardona** [comment]
Yes, is just that, is a small thing.

On Wed, Dec 26, 2012 at 12:32 AM, Thomas S Hatch
notifications@github.comwrote:

> I am confused, what part of the environment is not working? Is it just the
> fact that you need to make the directory before plopping files into it?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/saltstack/salt-bootstrap/issues/10#issuecomment-11681081.

## 

Jorge Eduardo Cardona

jorgeecardona@gmail.com
jorge@cardona.co

cardona.co
github.com/jorgeecardona

**Comment by thatch45** [comment]
Thanks for clarifying, I will talk it over with our packages to see what they think.

**Comment by s0undt3ch** [comment]
This is not actually a packaging issue, at least it's not a packaging issue related to salt since @jorgeecardona is trying to install from git.

And @jorgeecardona, since you're installing from git, salt only touches your filesystem on the parts which it really requires it and `conf.d` is not one of those.

So, at most, this is not a bootstrap issue, if @thatch45 agrees, this is a salt issue, ie, if that setting is set, create the directory.

At least this is my opinion about this issue.

**Comment by thatch45** [comment]
hmm, that is a valid argument, maybe we should add it to the verify_env routines

**Comment by ghost** [comment]
I agree with @jorgeecardona that bootstrap should mkdir -p /etc/salt/minion.d if it needs to put files there on the git based setup. I'm not sure if all platforms' packages create the directory for you.

**Comment by s0undt3ch** [comment]
We could add that directory to salt's `verify_env` routine and maybe on git bootstraps create it ourselves?

Everyone agrees?

**Comment by akoumjian** [comment]
I agree it belongs in salt's verify_env routine, doesn't belong in bootstrap script.

**Comment by ghost** [comment]
Sure, I think that's perfect.  I was looking for the minimal-fix method with 'mkdir'. 8)

**Comment by s0undt3ch** [comment]
Yes, the routine should be present in salt itself, though, what if the user wishes to pre-populate that directory before salt is started :\

**Comment by ghost** [comment]
That works great; I do that myself so when I upgrade salt every day I don't loose my config. I haven't (yet) looked at verify_env() but I'm pretty certain it's not going to delete existing .conf files there.
