### ISSUE TITLE
Debian 7 installation error

### ISSUE THREAD

**Issue by wiliamsouza** [saltstack/salt-bootstrap#100]
I can't install on debian 7 box using bootstrap more info here http://pastie.org/7082250
- DEBUG: Running salt-minion by hand outputs:
- DEBUG: /var/log/salt/minion does not exist. Can't cat its contents!
- DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe

**Comment by s0undt3ch** [comment]
Current git develop branch is now aware of Debian 7.
Only git installations are currently supported since there no packages available for it, yet...

```
curl -kL https://github.com/saltstack/salt-bootstrap/raw/develop/bootstrap-salt.sh | sudo sh -s -- git develop
```
