### ISSUE TITLE
aarch64 (arm64) not supported in 2016.11.1 distribution for Ubuntu?

### ISSUE THREAD

**Issue by vielmetti** [saltstack/salt-bootstrap#1004]
### Description of Issue/Question

I'm attempting to bootstrap `salt` on an ARMv8 (aarch64, arm64) machine running Ubuntu 16.04. It doesn't appear that there are packages built for this system, and the attempt to get it running hasn't worked yet (returns errors).

### Setup

aarch64 (ARMv8) 96-core machine at packet.net, running Ubuntu 16.04.

```
# dmesg | grep -i ubuntu
[    0.000000] Linux version 4.4.0-38-generic (buildd@bos01-arm64-006) (gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.2) ) #57-Ubuntu SMP Wed Sep 7 10:19:14 UTC 2016 (Ubuntu 4.4.0-38.57-generic 4.4.19)
```

### Steps to Reproduce Issue
(Include debug logs if possible, `bootstrap-salt.sh -D`.)

```gpgkeys: no key data found for https://repo.saltstack.com/apt/ubuntu/16.04/arm64/latest/SALTSTACK-GPG-KEY.pub
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: key not found
gpg: keyserver communications error: bad public key
gpg: WARNING: unable to fetch URI https://repo.saltstack.com/apt/ubuntu/16.04/arm64/latest/SALTSTACK-GPG-KEY.pub: bad public key
 * ERROR: Failed to run install_ubuntu_git_deps()!!!
 * DEBUG: Cleaning up the Salt Temporary Git Repository
 * DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe
 * DEBUG: Killing logging pipe tee's with pid(s): 24471
```

### Versions and Systems
(`salt --versions-report`, `bootstrap-salt.sh -v`, system type and version,
cloud/VM provider as appropriate.)

I was able to get an older version of `salt` running, so what's running on that machine now is 2015.8.8

Cloud provider is packet.net.

**Comment by dmurphy18** [comment]
@vielmetti Sorry for the delay in replying to this issue, but most staff have been away over the Christmas/New Year break.  

Salt currently only creates packages for ARM on the PI-2 and Pi-3 platforms using the Raspbian OS. The latest can be found under http://repo.saltstack.com/apt/debian/8/armhf/latest, however I just noticed that the Debian maintainers have also just accepted their build for Salt 2016.11.1 into unstable and this might also be useful to you.

Salt currently only packages for Ubuntu on Intel x86_64 platforms.  Note that a version of Salt is provided with Ubuntu 16.04 and I believe this version is from the Debian maintainers and it is probably their version of Salt that you are running.

**Comment by vutny** [comment]
@vielmetti , actually there is a way to install and compile Salt directly from GitHub using bootstrap script.
It should work for Debian 8 and Ubuntu 16 as well. We even have a note in README about this, at least for Debian.
Try the following:
```
sudo /bin/sh bootstrap-salt.sh -r -P git 2016.11
```

**Comment by vielmetti** [comment]
Thanks @vutny - I will try the bootstrap from git approach on Ubuntu 16.04 and report back, perhaps the resolution will be a PR with an update to the README.

**Comment by vielmetti** [comment]
Using this command line

```sudo /bin/sh bootstrap-salt.sh -r -P git 2016.11```

salt successfully bootstraps and runs on Ubuntu 16.04 on aarch64. No exhaustive testing yet, but signs look good.

**Comment by vutny** [comment]
Hi @vielmetti !
We have PR #1029 merged recently which describes the way how to get Salt installed on various architectures, based on your kind feedback.

Would you mind to close this out?

**Comment by vielmetti** [comment]
Looks good to me, @vutny ! I'll close this issue as resolved.

**Comment by rallytime** [comment]
Thank you @vielmetti and @vutny!
