### ISSUE TITLE
bootstrap on Arch Linux is broken due to package rename from salt-zmq to salt

### ISSUE THREAD

**Issue by ek9** [saltstack/salt-bootstrap#1005]
### Description of Issue/Question

bootstrap on Arch Linux is broken due to package rename from salt-zmq to salt

### Setup
Archlinux (after 2016-12-18)

### Steps to Reproduce Issue
Run bootstrap script on any recent archlinux version after  2016-12-18

### Versions and Systems
The package rename happened on 2016-12-18T13:19:01 CET with the new salt version 2016.11.1

The only salt package now is named "salt", which is same as previous "salt-zmq" package:
https://www.archlinux.org/packages/community/any/salt/

Search of "salt" packages in official repositories:
https://www.archlinux.org/packages/?q=salt

**Comment by rallytime** [comment]
Oh, thanks for filing this @ek9 and for submitting the fix!
