### ISSUE TITLE
ERROR: Failed to run install_centos_git_deps()!!!

### ISSUE THREAD

**Issue by thetoolsmith** [saltstack/salt-bootstrap#1019]
salt-minion bootstrap fails to execute on new aws vm with salt-cloud. 
Using centos 7.2 public ami, no changes.
Using salt version 2016.11.1 
I patched one file: https://raw.githubusercontent.com/mlalpho/salt/465053f07f3271706eeb0ca297182879eac1978c/salt/utils/aws.py
Due to this bug here: https://github.com/saltstack/salt/issues/38287

My profile looks like this:
xxx-create-ec2-us-east-1-dev:
provider: xxx-ec2-us-east-1-dev
script_args: '-P git v2016.11.1'
minion:
environment: dev
startup_states: sls
sls_list:
- new-instance
availability_zone: us-east-1b
image: ami-xxxxxxxxx
ssh_username: centos
network_interfaces:
- DeviceIndex: 0
SubnetId: subnet-xxxxxx
allocate_new_eip: False

The stack trace is this:
SaltCloudSystemExit: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /home/centos/.ssh/mykey -p 22 centos@10.0.1.81 'sudo /tmp/.saltcloud-8310720c-f6c4-4c37-aa3c-7ea46733ed7e/deploy.sh -c '"'"'/tmp/.saltcloud-8310720c-f6c4-4c37-aa3c-7ea46733ed7e'"'"' -P git v2016.11.1'' failed. Exit code: 255
[DEBUG ] LazyLoaded json.output
{
"mynode.us-east-1b.dev.org.com": {
"Error": "Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /home/centos/.ssh/mykey -p 22 centos@10.0.1.81 'sudo /tmp/.saltcloud-8310720c-f6c4-4c37-aa3c-7ea46733ed7e/deploy.sh -c '"'"'/tmp/.saltcloud-8310720c-f6c4-4c37-aa3c-7ea46733ed7e'"'"' -P git v2016.11.1'' failed. Exit code: 255"

Running deploy.sh from the new vm console yields a bit more:

[root@ip-10-0-1-81 .saltcloud-8310720c-f6c4-4c37-aa3c-7ea46733ed7e]# ./deploy.sh -P 'git v2016.11.1'
INFO: Running version: 2016.10.25
INFO: Executed by: /bin/sh
INFO: Command line: './deploy.sh -P git v2016.11.1'
INFO: System Information:
INFO: CPU: GenuineIntel
INFO: CPU Arch: x86_64
INFO: OS Name: Linux
INFO: OS Version: 3.10.0-327.10.1.el7.x86_64
INFO: Distribution: CentOS 7.2
INFO: Installing minion
INFO: Found function install_centos_git
INFO: Found function config_salt
INFO: Found function preseed_master
INFO: Found function install_centos_git
INFO: Found function install_centos_git
INFO: Found function install_centos_git
INFO: Found function daemons_running
INFO: Found function install_centos_git
INFO: Running install_centos_git()
python2: can't open file 'setup.py': [Errno 2] No such file or directory
ERROR: Failed to run install_centos_git()!!!

**Comment by thetoolsmith** [comment]
I updated the bootstrap script in my master and got a little further:
>salt-cloud --update-bootstrap

The when provisioning the aws vm, now this bootstrap error:

[DEBUG   ]  *  INFO: Running version: 2017.01.10
 *  INFO: Executed by: /bin/sh
 *  INFO: Command line: '/tmp/.saltcloud-f710b8c0-eea2-4238-9c3d-a258570b3b15/deploy.sh -c /tmp/.saltcloud-f710b8c0-eea2-4238-9c3d-a258570b3b15 -P git v2016.11.1'

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.10.0-327.10.1.el7.x86_64
 *  INFO:   Distribution: CentOS 7.2

 *  INFO: Installing minion
 *  INFO: Found function install_centos_git_deps
 *  INFO: Found function config_salt
 *  INFO: Found function preseed_master
 *  INFO: Found function install_centos_git
 *  INFO: Found function install_centos_git_post
 *  INFO: Found function install_centos_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO
EBUG   ] [0m: Found function install_centos_check_services
 *  INFO: Running install_centos_git_deps()
[DEBUG   ] Loaded plugins: fastestmirror
[DEBUG   ] Connection to 10.0.1.129 closed.
[DEBUG   ] 
 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Disable the repository, so yum won't use it by default. Yum will then
        just ignore the repository until you permanently enable it again or use
        --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>

     4. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so wi
[DEBUG   ] ll have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: base/7/x86_64
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=genclo error was
14: curl#7 - "Failed to connect to 2607:f8f8:700:12::10: Network is unreachable"
 * ERROR: Failed to run install_centos_git_deps()!!!
[ERROR   ] Failed to deploy 'test.us-east-1b.dev.org.com'. Error: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /home/centos/.ssh/MYKEY -p 22 centos@10.0.1.129 'sudo /tmp/.saltcloud-f710b8c0-eea2-4238-9c3d-a258570b3b15/deploy.sh -c '"'"'/tmp/.saltcloud-f710b8c0-eea2-4238-9c3d-a258570b3b15'"'"' -P git v2016.11.1'' failed. Exit code: 1
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 2311, in create_multiprocessing
    local_master=parallel_data['local_master']
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1288, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 2664, in create
    for key, value in six.iteritems(__utils__['cloud.bootstrap'](vm_, __opts__)):
  File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 532, in bootstrap
    deployed = deploy_script(**deploy_kwargs)
  File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 1524, in deploy_script
    if root_cmd(deploy_command, tty, sudo, **ssh_kwargs) != 0:
  File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 2221, in root_cmd
    retcode = _exec_ssh_cmd(cmd, allow_failure=allow_failure, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 1802, in _exec_ssh_cmd
    cmd, proc.exitstatus

**Comment by thetoolsmith** [comment]
After updating the salt bootstrap script, it was simply a network firewall issue on our end.
Problem resolved.

**Comment by rallytime** [comment]
@thetoolsmith I am glad you figured it out.
