### ISSUE TITLE
Solution for "ERROR: Failed to run install_ubuntu_check_services()" when switching between stable & git using bootstrap script

### ISSUE THREAD

**Issue by pepoluan** [saltstack/salt-bootstrap#1023]
### Description of Issue/Question

So, I have been experimenting with salt stable and develop. I switched between the two using `sh bootstrap_salt.sh -L -M -X -P` and `sh bootstrap_salt.sh -L -M -X -P git`, respectively.

I might have made a mistake somewhere, and ended up with this error:

    * ERROR: Failed to run install_ubuntu_check_services()

After this error appeared, no matter which invocation of bootstrap_salt.sh that I used, it never completed successfully.

The error message, though, was preceded by two messages about "masked unit", so that's where I go check. And indeed, both `systemctl status salt-master` and `systemctl status salt-minion` indicated that the _unit file_ for these two services are "masked" (symlinked to `/dev/null`)

### Solution

I simply deleted the symlinks:

- `/etc/systemd/system/salt-master.service` and
- `/etc/systemd/system/salt-minion.service`

and re-run the bootstrap script invocation... and it works!

### SUGGESTION

Probably add some smarts in the `bootstrap_salt.sh` script so that if it detects systemd unit files symlinked to `/dev/null`, it deletes those symlinks before continuing.

### Versions and Systems

```
# sh bootstrap_salt.sh -v
bootstrap_salt.sh -- Version 2017.01.10

# salt --version   # The stable version
salt 2016.11.1 (Carbon)

# salt --version   # The 'develop' version
salt 2016.11.0-685-gf4bf77a (Carbon)
```

**Comment by rallytime** [comment]
HI @pepoluan Can you tell me which distribution you're running the bootstrap script on? That will help troubleshoot this issue.

**Comment by pepoluan** [comment]
@rallytime the Linux distro, you mean?

**Ubuntu 16.04** running on AWS EC2.

**Comment by rallytime** [comment]
@pepoluan Yeah, that was what I meant. Sorry for being a little unclear there. Thanks for providing that information. I'll try to reproduce this and see what I can find. :)
