### ISSUE TITLE
Some INFO: lines not logged

### ISSUE THREAD

**Issue by bewing** [saltstack/salt-bootstrap#1035]
### Description of Issue/Question
Some INFO lines are outputted prior to setting up the logging pipe.  This means that one cannot review the command line used to call salt-bootstrap.sh in the logfile itself, which would make it easier to re-run salt-bootstrap inside a vagrant vm, for git-based installs, as more commits are pushed.

### Versions and Systems
`INFO: Running version: 2017.01.10`

**Comment by rallytime** [comment]
Ah, thanks for pointing that out @bewing. We'll have to get that fixed up.

**Comment by rallytime** [comment]
Hi @bewing - this should be fixed by #1091. Please give that a try if you have a moment.

**Comment by bewing** [comment]
Can confirm that this resolves my original issue, and the following line is now in the log:
` *  INFO: Command line: '/tmp/bootstrap_salt.sh -P -c /tmp -F -c /tmp -k /tmp/minion-seed-keys -M git develop'`
and I can copy/paste it and re-run it to my heart's content.

**Comment by rallytime** [comment]
Thanks for confirming @bewing! The change was just merged into `develop` and will be available in the next stable release. I'll go ahead and close this.
