### ISSUE TITLE
Bootstrap should accept `-s=<param>` syntax

### ISSUE THREAD

**Issue by curiositycasualty** [saltstack/salt-bootstrap#1038]
### Description of Issue/Question

When using the bootstrap script with `-s=30`:
```
* DEBUG: Waiting =30 seconds for processes to settle before checking for them
sleep: invalid time interval ‘=30’
Try 'sleep --help' for more information.
```

**Comment by rallytime** [comment]
@curiositycasualty Can you explain a little more about what you're looking for? The bootstrap script has the `-s` option for sleep, and the `-f` option for shallow cloning. I am not quite sure what the expectation of this issue is. :)

**Comment by curiositycasualty** [comment]
The script parsed "... -s=30 ..." as the value "=30" and failed.

**Comment by rallytime** [comment]
Ah, ok. The title has a different value (-f) so I was confused about what you were looking for. Thanks for the clarification! We will get that fixed.

**Comment by rallytime** [comment]
Oh, @curiositycasualty looking at this again, you just need to pass `-s 30`, not `-s=30`. It works as expected without the `=`. Apologies for not seeing that sooner. I'll go ahead and close this, but we can continue discussion here as needed.

**Comment by virtualguy** [comment]
I believe this was meant as a feature request to add support for the common
syntax in other Linux tools of using '=' when passing parameters. It would
be a nice to have so things are a little more intuitive but it may make
documentation a little messing supporting two ways to specify arguments

**Comment by rallytime** [comment]
Oh, yes, I see what you mean. This isn't something we want to do because of the reasons above. The `-s 30` or even `-s30` syntax will work, but we won't be supporting `-s=30` at this time.

Also, please note that there is a feature request open already about supporting long options in #448.

**Comment by curiositycasualty** [comment]
Thanks for getting back to me, I'll keep an eye on https://github.com/saltstack/salt-bootstrap/issues/448
