### ISSUE TITLE
Set master address

### ISSUE THREAD

**Issue by ghost** [saltstack/salt-bootstrap#104]
Hi,

It would be nice to have the option in the script to set the address of the master.
So to replace the default "master: salt".

example:
saltstack-bootstrap.sh -sm 192.168.0.11 

or

wget -O - http://bootstrap.saltstack.org?sm=192.168.0.11 | sudo sh

**Comment by s0undt3ch** [comment]
This is a duplicate of #85

**Comment by s0undt3ch** [comment]
This is being implemented in #307
