### ISSUE TITLE
CentOS 7.3 ERROR: Failed to run install_centos_stable_deps()!!!

### ISSUE THREAD

**Issue by jdonofrio728** [saltstack/salt-bootstrap#1041]
### Description of Issue/Question
bootstrap-salt.sh script is failing on centos7.3. 
### Setup
(Please provide relevant configs (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible, `bootstrap-salt.sh -D`.)

https://gist.github.com/jdonofrio728/06b120d9321e50ecc5ff4c3bca81d410

### Versions and Systems
(`salt --versions-report`, `bootstrap-salt.sh -v`, system type and version,
cloud/VM provider as appropriate.)

 *  INFO: Running version: 2017.01.10
 *  INFO: Executed by: -
 *  INFO: Command line: './bootstrap-salt.sh -D'

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.10.0-514.10.2.el7.x86_64
 *  INFO:   Distribution: CentOS 7.3

**Comment by rallytime** [comment]
Hi @jdonofrio728 - thanks for letting us know. Does the bootstrap script work at the HEAD of the develop branch? I think we had some fixes around this go in recently. You can grab that [here](https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh).

**Comment by jdonofrio728** [comment]
Hey @rallytime, it does work. I'm can't re-create the issue with the new version. Thanks!

**Comment by rallytime** [comment]
Great! Thanks for trying that and following up!
