### ISSUE TITLE
Installation instructions should include hash verification

### ISSUE THREAD

**Issue by cachedout** [saltstack/salt-bootstrap#1043]
### Description of Issue/Question

There is no way to verify that the file downloaded is the correct one. The bootstrap installation procedure should list the correct SHA256 sum of the script or reference a file which contains that sum.

**Comment by rallytime** [comment]
Good idea. Thanks @cachedout - I will get this added to the installation instructions in the README.

**Comment by rallytime** [comment]
@cachedout I have added some instructions to the README file with the hash verification in PR #1098. Please let me know what you think.

**Comment by cachedout** [comment]
LGTM
