### ISSUE TITLE
salt-bootstrap fails on Ubuntu 17.04 Zesty

### ISSUE THREAD

**Issue by vernondcole** [saltstack/salt-bootstrap#1052]
### Description of Issue/Question

`sudo sh salt-bootstrap.sh`
fails to run on the current version of Ubuntu.

### Setup

Create a new, virgin instance of Ubuntu 17.04.  I used Ubuntu-Mate but that should not be important.

### Steps to Reproduce Issue

Execute the following code snippit, or type the equivalent commands.

    ```(python3)
       import subprocess
       from urllib.request import urlopen

        _salt_install_script = "/tmp/bootstrap-salt.sh"
        print("Downloading Salt Bootstrap to %s" % _salt_install_script)
        with open(_salt_install_script, "w+") as f:
            f.write(urlopen("http://bootstrap.saltstack.com/stable/bootstrap-salt.sh").read().decode())
        print("Success")
        print("Bootstrapping Salt")
        try:
            print("sh %s -X stable" % (_salt_install_script))
            subprocess.call("sudo sh %s -X -M -L -P stable" % (_salt_install_script), shell=True)
            print("Salt Installed")
        except OSError as ex:
            print(ex)
            raise ex
    ```
Results in the following error:

```
Reading state information...
Package gnupg-curl is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'gnupg-curl' has no installation candidate
 * ERROR: Failed to run install_ubuntu_stable_deps()!!!
```

### Versions and Systems

/tmp/bootstrap-salt.sh -- Version 2017.01.10

Welcome to Ubuntu 17.04 (GNU/Linux 4.10.0-19-generic x86_64)

Running on an old HP laptop.

### Analysis

About line 1455 the following code appears:

```(sh)
# Starting from Ubuntu 16.10, gnupg-curl has been renamed to gnupg1-curl.
GNUPG_CURL="gnupg-curl"
if ([ "${DISTRO_NAME_L}" = "ubuntu" ] && [ "${DISTRO_VERSION}" = "16.10" ]); then
    GNUPG_CURL="gnupg1-curl"
fi
```

This wires the script to a single version of Ubuntu.

### Suggested correction

Alter the script to be a lexical string compare rather than an exact compare:

```
$ diff /tmp/bootstrap-salt.sh /tmp/bootstrap-salt1.sh 
1455c1455
< if ([ "${DISTRO_NAME_L}" = "ubuntu" ] && [ "${DISTRO_VERSION}" = "16.10" ]); then
---
> if ([ "${DISTRO_NAME_L}" = "ubuntu" ] && [ ! "${DISTRO_VERSION}" \< "16.10" ]); then
1458d1457
< 
```
##### Explanation

Bash, and, it seems, most other modern shell script engines, support lexical compares of "less than" or "greater than" for strings.  This suggestion makes "not less than" by including a "!" logical not operator.

Older "sh" shells should not be affected, since `"${DISTRO_NAME_L" = "ubuntu"` will fail, and the `&&` should short-circuit any evaluation of the next term.

##### Testing

Tests run:
- Ubuntu Mate 17.04  # the failed target
- Ubuntu server 16.10  # the edge case
- Ubuntu server 16.04  # an earlier LTS
- Raspbian Jessie    # not Ubuntu

Not tested:
- something running sh rather than bash.  (What systems still do that??)

**Comment by vutny** [comment]
@vernondcole We have PR #1051 submitted recently. It should resolve your issue, give a try.

By the way, on all Debian-based distros the default "system" shell (`/bin/sh` symlink) is `dash`, which is POSIX-compliant, fast and stripped down shell without `bash` features.

**Comment by rallytime** [comment]
@vernondcole This is fixed in the `develop` branch and will be available in the next released version of salt-bootstrap. Since this is already fixed, I'll go ahead and close this. Thank you!

**Comment by kiemlicz** [comment]
When is this going to be released?

**Comment by vutny** [comment]
@kiemlicz Just grab it from https://bootstrap.saltstack.com/develop

**Comment by vernondcole** [comment]
Yes, indeed, the /develop version works great!  May I encourage a release sooner rather than later? The script I quoted above, and salt-cloud saltify provider are both broken until the next release.

**Comment by vutny** [comment]
@vernondcole The bootstrap script for Salt Cloud could be easily updated. Check this out:
https://docs.saltstack.com/en/latest/topics/cloud/deploy.html#updating-salt-bootstrap
