### ISSUE TITLE
[develop] CentOS 7 install is broken

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-bootstrap#1061]
### Description of Issue/Question
I ran a quick smoke test against installing the latest HEAD of develop on a CentOS 7 VM from Linode.

Both running the script without arguments (stable packages) and running the script with `git v2016.11.3` failed. The dependencies are all installed, but the daemons are not found to be running/fail to start.
```
Complete!
 *  INFO: Running install_centos_stable_post()
 *  INFO: Running install_centos_check_services()
 *  INFO: Running install_centos_restart_daemons()
 *  INFO: Running daemons_running()
Connection to 45.79.102.21 closed.
 * ERROR: salt-minion was not found running
 * ERROR: Failed to run daemons_running()!!!
 * ERROR: salt-minion was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
```

**Comment by vutny** [comment]
I have successfully bootstrapped Salt on CentOS 7 `@Core` installation with latest `develop` version in both "stable" and "git" mode. Looks like you have some environment specific issue.

**Comment by rallytime** [comment]
Yeah I need to debug this some more. All of the servers we use to run tests with in Linode are failing in this way.

**Comment by rallytime** [comment]
Ok, I can't reproduce this anymore either on a clean VM. Maybe it was something in my salt-cloud config files. Thanks for testing this @vutny and commenting. It is certainly appreciated.
