### ISSUE TITLE
Salt-bootstrap failed in SLES12-SP1-12.1-0

### ISSUE THREAD

**Issue by yogeshprasad** [saltstack/salt-bootstrap#1066]
Hello,
I have tried to run salt-bootstrap in SLES12-SP1-12.1-0 and it is failing.

Logs without -P:
 *  INFO: Running version: 2017.01.10
 *  INFO: Executed by: sh
 *  INFO: Command line: 'bootstrap-salt.sh '

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.12.49-11-default
 *  INFO:   Distribution: suse 12.1

 *  INFO: Installing minion
 *  INFO: Found function install_suse_12_stable_deps
 *  INFO: Found function config_salt
 *  INFO: Found function preseed_master
 *  INFO: Found function install_suse_12_stable
 *  INFO: Found function install_suse_12_stable_post
 *  INFO: Found function install_suse_12_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Found function install_suse_check_services
 *  INFO: Running install_suse_12_stable_deps()
Repository 'SLES12-SP1-12.1-0' is up to date.
Repository 'Python Modules (SLE_12)' is up to date.
Repository 'SaltStack, dependencies, and addons (SLE_12)' is up to date.
All repositories have been refreshed.
 * ERROR: pip based installations were not allowed. Retry using '-P'
--------------------------------------------------------------------------------------
Logs with -P:
 *  INFO: Running version: 2017.01.10
 *  INFO: Executed by: sh
 *  INFO: Command line: 'bootstrap-salt.sh -P'

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.12.49-11-default
 *  INFO:   Distribution: suse 12.1

 *  INFO: Installing minion
 *  INFO: Found function install_suse_12_stable_deps
 *  INFO: Found function config_salt
 *  INFO: Found function preseed_master
 *  INFO: Found function install_suse_12_stable
 *  INFO: Found function install_suse_12_stable_post
 *  INFO: Found function install_suse_12_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Found function install_suse_check_services
 *  INFO: Running install_suse_12_stable_deps()
Repository 'SLES12-SP1-12.1-0' is up to date.
Repository 'Python Modules (SLE_12)' is up to date.
Repository 'SaltStack, dependencies, and addons (SLE_12)' is up to date.
All repositories have been refreshed.
 *  WARN: PyYaml will be installed using pip
Loading repository data...
Reading installed packages...
Package 'python-pip' not found.
'python' is already installed.
No update candidate for 'python-2.7.9-20.2.x86_64'. The highest available version is already installed.
'python-xml' is already installed.
No update candidate for 'python-xml-2.7.9-20.6.x86_64'. The highest available version is already installed.
 * ERROR: Failed to run install_suse_12_stable_deps()!!!

**Comment by rallytime** [comment]
Hi @yogeshprasad Are you running into problems on the `develop` version of the script? @Ch3LL recently fixed some issues with SLES 12 and has this working for her. I am curious if this is already fixed.

**Comment by rallytime** [comment]
Actually it looks like you're running into a different issue.

**Comment by rallytime** [comment]
Hi @yogeshprasad - There have been some updates to the suse support in the latest release (and a couple of useful fixes at the head of the `develop` branch). However, the bootstrap script only supports the versions of operating systems that the distributors support. Since SLES 12 SP 1 is now EOL from SUSE, we are no longer maintaining support for that release version in salt-bootstrap. As such, I am going to close this issue.

If you run into problems with the latest version on a supported version such as SP3 currently, please let us know and we'll get them fixed. Thank you!
