### ISSUE TITLE
Scientific Linux 6.9 bootstrap and yum repo install and upgrade issues

### ISSUE THREAD

**Issue by rtournoy** [saltstack/salt-bootstrap#1067]
### Description of Issue/Question
yum upgrade fails with https://repo.saltstack.com/yum/redhat/6.9/x86_64/latest/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"

Indeed directory 6.9 doesn't exist : https://repo.saltstack.com/yum/redhat/

Unfortunately it is breaking the whole distro update process and I have to disable the salt repository to upgrade SL 6.9 servers.

Please see issue #833 because the same problem was fixed here from SL 6.5 to SL 6.8, until the SL 6.9 was released, now the new directory is HTTP 404.

This is probably only a matter of a symlink here : 
https://repo.saltstack.com/yum/redhat/

Thanks.

### Setup
Scientific Linux 6.9 and Salt: 2016.11.3
SL 6.9 is a REDHAT / CENTOS like distro.

### Steps to Reproduce Issue
- yum -y install https://repo.saltstack.com/yum/redhat/salt-repo-2016.11-1.el7.noarch.rpm
- yum upgrade -y 
- https://repo.saltstack.com/yum/redhat/6.9/x86_64/latest/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"

### Versions and Systems
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 12:06:14)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 6.9 Carbon
        machine: x86_64
        release: 2.6.32-642.15.1.el6.x86_64
         system: Linux
        version: Scientific Linux 6.9 Carbon

**Comment by vutny** [comment]
Hi @rtournoy. Thanks for reporting.

I've fixed the bootstrap script to workaround this in PR #1068. Please give it a try.

**Comment by vutny** [comment]
@dmurphy18 Maybe you could just set the major RHEL release version instead of `$releasever` in the repo URL which set by `salt-repo-*.noarch.rpm` (from [here](https://repo.saltstack.com/yum/redhat/)) ?

**Comment by rtournoy** [comment]
Hi @vutny . Thank you for the fix in PR #1068 , it works now.

**Comment by vutny** [comment]
Glad to help, @rtournoy
