### ISSUE TITLE
Add support for Salt TCP Transport flag

### ISSUE THREAD

**Issue by ljanne** [saltstack/salt-bootstrap#1069]
Please implement a flag that would allow users to bootstrap a minion in TCP Transport mode (instead of ZMQ).

**Comment by vutny** [comment]
It is already implemented! Check out `-j` and `-J` options. All you need to do is this:
```bash
sudo sh bootstrap-salt.sh -j '{"transport": "tcp"}' 
```
Or if you would like to bootstrap Master:
```bash
sudo sh bootstrap-salt.sh -J '{"transport": "tcp"}' -M -N
```

However, ZeroMQ dependencies will be installed in any case.

**Comment by ljanne** [comment]
Wonderful, thanks a lot @vutny !
