### ISSUE TITLE
[DEVELOP] Amazon git install fails due to wrong repo.saltstack.com path

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-bootstrap#1071]
### Description of Issue/Question
Currently on develop (3750240fcf099ab836c3678e9cc4f9be99e154ad) if you try to use the bootstrap script as follows: `sh /tmp/bootstrap-salt.sh -P git v2016.11.4` it fails because it tries to add the repo.saltstack.com as follows: 

```
https://repo.saltstack.com/yum/redhat/6/x86_64/v2016.11.4/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below knowledge base article 
```

As you can see it is trying to add `x86_64/v2016.11.4/repodata/repomd.xml` where v2016.11.4 does not exist on the repo. I think we need to fix this by one of two ways, just add that to be latest when using git install or adding the archive link. I think this was caused by this pr: https://github.com/saltstack/salt-bootstrap/pull/1032 

I think another issue with this is it is using the redhat link instead of the amazon link. After salt version 2016.11 i believe it should be using the amazon native packages. 

I will dive more into this tomorrow. 

### Setup
Amazon 2015.03

**Comment by dmurphy18** [comment]
@Ch3LL That url is incorrect for repo.saltstack.com
 For a specific version it should read as follows I believe

https://repo.saltstack.com/yum/redhat/6/x86_64/archive/2016.11.4/repodata/repomd.xml

**Comment by Ch3LL** [comment]
Right. That is the problem. I need to update the bootstrap so it points to the archive path or latest. Previously we were pointing to latest if user was installing a specific version for amazon. Looking at this now. I need to see if we are pointing to latest in other parts of the script.

**Comment by Ch3LL** [comment]
Okay I need to revisit this tomorrow.

I have this: 

```diff --git a/bootstrap-salt.sh b/bootstrap-salt.sh
index 3f7a769..cf796d9 100755
--- a/bootstrap-salt.sh
+++ b/bootstrap-salt.sh
@@ -4461,7 +4461,11 @@ install_amazon_linux_ami_deps() {
     # Shim to figure out if we're using old (rhel) or new (aws) rpms.
     _USEAWS=$BS_FALSE
 
-    repo_rev="$(echo "${GIT_REV:-$STABLE_REV}"  | sed 's|.*\/||g')"
+    if [ "$ITYPE" = "stable" ]; then
+        repo_rev="$(echo "${STABLE_REV}"  | sed 's|.*\/||g')"
+    else
+        repo_rev="latest"
+    fi
 
     if echo "$repo_rev" | egrep -q '^(latest|2016\.11)$'; then
        _USEAWS=$BS_TRUE
```

But its installing a really old version of python-tornado and salt won't even start. But I think we need to stick with latest for git installs as that is how it is in other sections.

**Comment by Ch3LL** [comment]
```diff --git a/bootstrap-salt.sh b/bootstrap-salt.sh
index 3f7a769..9c87d06 100755
--- a/bootstrap-salt.sh
+++ b/bootstrap-salt.sh
@@ -4461,7 +4461,11 @@ install_amazon_linux_ami_deps() {
     # Shim to figure out if we're using old (rhel) or new (aws) rpms.
     _USEAWS=$BS_FALSE
 
-    repo_rev="$(echo "${GIT_REV:-$STABLE_REV}"  | sed 's|.*\/||g')"
+    if [ "$ITYPE" = "stable" ]; then
+        repo_rev="$(echo "${STABLE_REV}"  | sed 's|.*\/||g')"
+    else
+        repo_rev="latest"
+    fi
 
     if echo "$repo_rev" | egrep -q '^(latest|2016\.11)$'; then
        _USEAWS=$BS_TRUE
@@ -4538,6 +4542,13 @@ install_amazon_linux_ami_git_deps() {
         yum -y install ca-certificates || return 1
     fi
 
+    PIP_EXE='pip'
+    if [ "$(echo "$GIT_REV" | egrep -o '2[0-9]{3}')" -ge 2016 ]; then
+        [ $(which pip2.7) ] || /usr/bin/easy_install-2.7 pip || echoerror "Could not install pip2.7"
+        PIP_EXE='/usr/local/bin/pip2.7'
+        _PY_EXE='python2.7'
+    fi
+
     install_amazon_linux_ami_deps || return 1
 
     ENABLE_EPEL_CMD=""
@@ -4564,7 +4575,7 @@ install_amazon_linux_ami_git_deps() {
         # We're on the develop branch, install whichever tornado is on the requirements file
         __REQUIRED_TORNADO="$(grep tornado "${_SALT_GIT_CHECKOUT_DIR}/requirements/base.txt")"
         if [ "${__REQUIRED_TORNADO}" != "" ]; then
-            __PACKAGES="${__PACKAGES} python-tornado"
+            __PACKAGES="${__PACKAGES} ${pkg_append}-tornado"
         fi
     fi
 
@@ -4573,9 +4584,10 @@ install_amazon_linux_ami_git_deps() {
         yum -y install ${__PACKAGES} ${ENABLE_EPEL_CMD} || return 1
     fi
 
+
     if [ "${__PIP_PACKAGES}" != "" ]; then
         # shellcheck disable=SC2086
-        pip-python install ${__PIP_PACKAGES} || return 1
+        ${PIP_EXE} install ${__PIP_PACKAGES} || return 1
     fi
 
     # Let's trigger config_salt()
```

This is what i have but i need to do some more testing next week.
