### ISSUE TITLE
[DEVELOP] FreeBSD10 Not installing due to failure in install_freebsd_git_deps step

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-bootstrap#1072]
### Description of Issue/Question
Currently on develop (3750240fcf099ab836c3678e9cc4f9be99e154ad) when running `sh /tmp/bootstrap-salt.sh -P git v2016.11.4` on freebsd 10 it fails with the following error:

```
13:26:08                       Extracting swig-2.0.12_2: .......... done
13:26:08                       Updating FreeBSD repository catalogue...
13:26:08                       FreeBSD repository is up to date.
13:26:08                       All repositories are up to date.
13:26:08                       Checking integrity... done (0 conflicting)
13:26:08                       The most recent version of packages are already installed
13:26:08                       pkg: Repository SaltStack missing. 'pkg update' required
13:26:08                       pkg: Repository SaltStack load error: access repo file(/var/db/pkg/repo-SaltStack.sqlite) failed: No such file or directory
13:26:08                       Updating FreeBSD repository catalogue...
13:26:08                       FreeBSD repository is up to date.
13:26:08                       All repositories are up to date.
13:26:08                       pkg: No packages available to install matching 'devel/py-setuptools27' have been found in the repositories
13:26:08                       ?[1;31m * ERROR?[0m: Failed to run install_freebsd_git_deps()!!!
```

I will look more into this tomorrow/friday.

**Comment by Ch3LL** [comment]
Okay I think this is failing because `py-setuptools27` was renamed to `py27-setuptools` to better match other python ports as documented at the end fo the page [here](https://www.freshports.org/devel/py-setuptools27/) 

There was a change here: https://github.com/saltstack/salt-bootstrap/pull/1026 to query the salt dependencies and install those if using a git install. I am not sure if this dependency requirements needs to be changed in the freebsd packages or if there is a better way to handle this. 

The other issue is if i point the install to use the saltstack repo instead of freebsd repo it uninstalls the jinja2 I have on the system and does not start salt due to this issue. @amontalban any ideas on this one? i'm still diving into the issue now but I'm not very knowledgable with freebsd so I'm not sure what the best approach would be to resolve issues like this. Is there another freebsd repo I can add if there is a failure? 

Here is my freebsd version when i run into this issue: 

```root@ch3ll-free5:~ # freebsd-version -u
10.3-RELEASE-p18
```

**Comment by amontalban** [comment]
Hi @Ch3LL,

You're on the right path, please check my comment in https://github.com/saltstack/salt-bootstrap/issues/996#issuecomment-293109252. I recommend applying this PR ( https://github.com/saltstack/salt-bootstrap/compare/develop...Perceptyx:develop) to use FreeBSD repositories for installing packages and possibly removing SaltStack repository because IMHO it's reinventing the wheel specially because 99% of the time the FreeBSD port/package is more up to date than SaltStack repository package.

Let me know if you need help with any testing as we use FreeBSD on a daily basis.

Thanks!

**Comment by Ch3LL** [comment]
@amontalban thanks for your help on this one. I used your diff and it works great! Seems you are right there are a lot of differences between the two, and I am personally okay removing hte saltstack or possibly just adding it as an option/argument. But I would want to handle that in a seperate PR so we can tackle just this issue now. Did you want to submit as a PR? Or I can. We are trying to get a bootstrap release out so if I don't hear from you this morning I will go ahead and submit the PR and make sure to mention you as credit. Thanks for this :)

**Comment by amontalban** [comment]
Hi! Great news that it worked for you, I'm kind of AFK today so if you can create the PR that would be great.

Thanks!

**Comment by Ch3LL** [comment]
Thanks I went ahead and added in #1076. Thanks for all your help :)
