### ISSUE TITLE
VMware's Photon OS support

### ISSUE THREAD

**Issue by nickgarber** [saltstack/salt-bootstrap#1106]
A related request is documented in the Salt/Salt project at [ref:1].

[ref:1] 
https://github.com/saltstack/salt/issues/41921

**Comment by rallytime** [comment]
@nickgarber Apologies for not commenting on this sooner. Thanks for the request. I don't think this is something that we can pick up ourselves right now, but if someone from the community wants to implement it, great! As such, I have approved this as a feature request.

**Comment by nickgarber** [comment]
Hi @rallytime, no worries!


Here are the quick notes I took while setting this up recently. It should
help people to know that it's possible and not complicated to accomplish.
In these notes I used Salt's develop branch, but much of these instructions
could be adjusted and refactored to produce something much more
straight-forward. I'll revisit and clean this up myself unless someone
beats me to it.




procedure :: howto, install Salt on VMware Photon

   - nb, the package managed is tdnf
   -  install Python and Pip
      - install python if is isnt already `tdnf install python git pycrypto python-zmq`
      - install Python module dependencies
      - install pip `cd $(mktemp -d) && curl -O https://bootstrap.pypa.io/get-pip.py && python get-pip.py`
      - install python if is isnt already `tdnf install python`
      - clone from upstream Salt at Github `git clone --depth 1 --single-branch https://github.com/saltstack/salt`
      - enter the working directory and install using setup.py `python setup.py install`
      - this install method doesnt include a service unit, so we'll add that now
         ```
      cat > /etc/systemd/system/salt-minion.service <<EOF
      [Unit]
      Description=The Salt Minion
      After=network.target
      [Service]
      Type=notify
      NotifyAccess=all
      LimitNOFILE=8192
      ExecStart=/bin/salt-minion
      [Install]
      WantedBy=multi-user.target
      EOF
     ```
      - nb, when relying on DNS to identify the salt master, some explicit
      configuration may require additional editing
      ```
      # /etc/resolv.conf
      nameserver 192.168.1.1
      nameserver 192.168.1.2
      search mydomain.tld
     ```
      - (opt.) if DNS is not fully adequate, you can explicitly set the IP address of the Salt Master as below
     ```
      cat > /etc/salt/minion.d/master.conf <<EOF
      master: 192.168.1.100

      EOF
      ```
      - starting the salt-minion.service for the first time will create the file and folder structure under /etc/salt
      - verify a/o set the minion_id in /etc/salt/minion_id as/is desired `echo exmpl-web-t1.mydomain > /etc/salt/minion_id`
      - start the service `systemctl enable --now salt-minion`

**Comment by padmini-st** [comment]
Hi @nickgarber, this is what I was looking for. Very helpful.
Could I request to list out the steps for Photon OS for Salt-master as well.

Thanks

**Comment by nickgarber** [comment]
To run a salt-master on a container-host OS like Photon, why not run it in
a container?

That said, if running a salt-master on the "host" OS is important, it's
certainly possible. I haven't tried it but I believe setting up a
salt-master from source would share many steps with the salt-minion setup.

**Comment by nickgarber** [comment]
Please leave this open. Time permitting I believe I could implement this
myself. The issue will let others know that an interest in the feature has
already been registered and that they can contribute or inquire about
status.

**Comment by rach-sharp** [comment]
As a couple of extra notes following the process above, I also had to install `python-xml` before I could install pip using `get-pip.py`. Once I'd cloned the main branch I also had to explicitly install dependencies from `requirements/base.txt` as well as run `setup.py`.

**Comment by nickgarber** [comment]
I'd like to motion for postponement, (for the final time), in hopes I'll be able to contribute this myself.

**Comment by rallytime** [comment]
Sounds good @nickgarber! Thanks!

**Comment by lomeroe** [comment]
additionaly, the "photon-updates" repo (1.0) has a 2017.7.2 version of the salt packages in it...obviously a little behind, but is at least a fully tdnf managed package and seems to work as expected

**Comment by nickgarber** [comment]
This issue is no longer in my line of sight. 

If it were just me I'd close it but there does seem to be interest.

Under the circumstances may this issue be re-owned?

**Comment by nickgarber** [comment]
I'm no longer associated with this request so will close it. If you wish to re-open or otherwise preserve it please also re-own it. 

Thanks!
