### ISSUE TITLE
Boostrap install in Debian Buster (10)

### ISSUE THREAD

**Issue by speedlight** [saltstack/salt-bootstrap#1112]
Trying to install in a fresh Debian 10 give error about "end-of-life" distro.
/etc/debian_version have buster/sid but is not recgonized yet in the install script.

I change the file to stretch/sid to be able to install :)

**Comment by rallytime** [comment]
Ah, good point. I think we can adjust the bootstrap script to handle upcoming Debian releases in a similar way to what we do with the upcoming Ubuntu releases.

**Comment by speedlight** [comment]
Yes, there are the line for detect from 6 to 9, maybe a more dinamic way to add future version numbers :) I couldnt do a pull request cuz is a fresh install and no test boxes here :)

**Comment by rallytime** [comment]
@speedlight and @vutny I have added some introductory support for Debian 10 (Buster) in PR #1113. Please take a look and let me know what you think.

**Comment by rallytime** [comment]
Fixed in #1113.

**Comment by dereckson** [comment]
When using salt-cloud to spin a Debian Sid image at Scaleway, with `buster/sid` in `/etc/debian_version`, I've the EOL error.

**Comment by rallytime** [comment]
@dereckson What version of the bootstrap script are you running?

**Comment by dereckson** [comment]
The one provided with salt-cloud 2017.7.1 (Nitrogen).

**Comment by rallytime** [comment]
@dereckson Ah. The `2017.7.1` version of Salt includes the `2017.05.24` version of the bootstrap script. This issues wasn't fixed there yet, so you'll need to run the latest stable release of the bootstrap script instead.

You can update your bootstrap version with salt cloud with the `salt-cloud -u` command, which will download the latest stable bootstrap release and place it in the necessary directories for salt-cloud to use.

**Comment by dereckson** [comment]
Hey, thanks for the follow-up :)
