### ISSUE TITLE
tornado version is not being enforced

### ISSUE THREAD

**Issue by aflat** [saltstack/salt-bootstrap#1115]
Doing a bootstrap on a centos6 machine(or any fedora machine) fails to install tornado correctly, causing a stacktrace. See https://github.com/saltstack/salt/issues/42392 for more details. 

I am using bootstrap-salt.sh -P git v2016.3.4 (I have also used v2017.7, same issue) and the salt-minion fails to start. 

```
Starting salt-minion daemon: Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 26, in <module>
    salt_minion()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 158, in salt_minion
    import salt.utils.process
  File "/usr/lib/python2.6/site-packages/salt/utils/process.py", line 249, in <module>
    class ProcessManager(object):
  File "/usr/lib/python2.6/site-packages/salt/utils/process.py", line 374, in ProcessManager
    @gen.coroutine
AttributeError: 'module' object has no attribute 'coroutine'
```
The issue is that tornado 2.2.1 is installed, when reqirement/base.txt states tornado 4.2.1 is required(in both 2016.3.4 and 2017.7) The bootstrap file shows checking of pip installs allowed, but does a "pip install tornado" instead of a "pip install tornado==<version_from_base.txt>" 

Since this is cento6, I can't use the repo.saltstack, as python-tornado is python27-tornado. I can install that, on centos6, with a python of 2.6.6, but it is for python2.7, so I'm probably asking for trouble. It works, but pip installs "should" be cleaner.

Centos 6.6
python 2.6.6
AWS ami from the marketplace
bootstrap-salt.sh: 2016.10.25(the one I happen to be using) up to and including develop branch
Pull request incoming soon.

**Comment by aflat** [comment]
Rabbit hole. 

when using -P git v2016.3.4(or any git version) it takes the latest from repo.saltstack.com, which has changed. I don't think this should be reworked, since it makes sense for developers. using "stable 2016.3" works just fine, since it will use the correct python-tornado rpm. I'll still add a pull request, but it doesn't change much for what I wanted, just changes the pip installs.

**Comment by rallytime** [comment]
@aflat Glad you got it figured out. 

If you're using salt-bootstrap to install salt on CentOS 6 for 2017.7.0+, you might want to take a look at the `-x` and `-y` options, if that's helpful for you. We use that when installing salt on our CentOS 6 test machines to make sure that Python2.7 is available and salt installs correctly. This was implemented in PR #1049. Which, we should update the README instructions to include this information for 2017.7.x installs on CentOS 6.

**Comment by davidjb** [comment]
Fwiw, I see the same problem on CentOS 6 / Python 2.6 with Salt v2016.11.6, just reported in a different way when using salt-call:

```
[root@localhost vagrant]# salt-call --versions
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 374, in salt_call
    import salt.cli.call
  File "/usr/lib/python2.6/site-packages/salt/cli/call.py", line 9, in <module>
    import salt.cli.caller
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 18, in <module>
    import salt.loader
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 29, in <module>
    import salt.utils.event
  File "/usr/lib/python2.6/site-packages/salt/utils/event.py", line 72, in <module>
    import salt.payload
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 17, in <module>
    import salt.crypt
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 52, in <module>
    import salt.transport.client
  File "/usr/lib/python2.6/site-packages/salt/transport/client.py", line 13, in <module>
    from salt.utils.async import SyncWrapper
  File "/usr/lib/python2.6/site-packages/salt/utils/async.py", line 9, in <module>
    import tornado.concurrent
ImportError: No module named concurrent
```

The cause is still the same, the Tornado version installed is 2.2.1 and the `concurrent` module was only added in v3. @aflat Is your PR #1116 likely to fix the issue?

I managed to eventually get Salt installed correctly on CentOS 6 by using: ``sh bootstrap-salt.sh -D -P -y -x python2.7 git v2016.11.6`` but I haven't tested in depth.

**Comment by aflat** [comment]
It did fix it for me, and I had the same concurrent issue, which like you said was added in newer versions of tornado, so it should fix it for you too.

**Comment by davidjb** [comment]
I'll try and test the PR at some point, but that's great if it fixes this issue.  As you said above, this is indeed a rabbit hole...
