### ISSUE TITLE
bootstrap-salt.ps1: needs to handle py2/py3 in installer filenames

### ISSUE THREAD

**Issue by dafyddj** [saltstack/salt-bootstrap#1119]
### Description of Issue/Question

Bootstrap script on Windows gets 404 error while downloading installer.

### Setup
(Please provide relevant configs (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible, `bootstrap-salt.sh -D`.)
```
bootstrap-salt.ps1 -version 2017.7.0
```

### Versions and Systems
(`salt --versions-report`, `bootstrap-salt.sh -v`, system type and version,
cloud/VM provider as appropriate.)
```
PS C:\Users\vagrant> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.34014
BuildVersion                   6.3.9600.16394
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```

**Comment by rallytime** [comment]
@dafyddj Oh, yes. We need to get those paths fixed up. Thank you for letting us know.

FYI @Ch3LL and @twangboy.

**Comment by rallytime** [comment]
Hi @dafyddj - Can you give the changes I made in #1123 a try? I am not very good at Powershell, but wanted to get this fixed. Any help you can give in testing it is greatly appreciated.
