### ISSUE TITLE
unable to specify multiple masters

### ISSUE THREAD

**Issue by partsalliance** [saltstack/salt-bootstrap#1126]
### Description of Issue/Question
I have been unable to use the bootstrap script to set multiple masters for the minion. This is so we can use the multi-master mode.

Does anyone know if it possible to achieve this with the bootstrap script?

### Setup
Running on ubuntu 14.04

### Steps to Reproduce Issue
(Include debug logs if possible, `bootstrap-salt.sh -D`.)
bootstrap-salt.sh -A salt-master.staging.com -A salt-master.testing.com

### Versions and Systems
Version 2016.06.27

**Comment by rallytime** [comment]
Hi @partsalliance - The `-j` option should be able to handle this nicely for you. The `-j` option allows you to pass in a custom minion configuration file as a json dict, which you can use to pass the the two masters in:
```
sh install_salt.sh -j '{"master": ["mymaster1", "mymaster2"], "id": "my-minion-id"}'
```

See #841 for the change. Note that the option will write over your existing minion config (but makes a reasonable attempt to create a .bak file).

**Comment by partsalliance** [comment]
thank you very much.
