### ISSUE TITLE
/etc/salt/minion not overwritting for some reason

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt-bootstrap#1128]
I have been unable to replicate this, but there is an issue where the bootstrap script decides to not overwrite the /etc/salt/minion file with the /tmp/.saltcloud-*/minion file.

```
 *  INFO: Running version: 2017.01.10
 *  INFO: Executed by: /bin/sh
 *  INFO: Command line: '/tmp/.saltcloud-9744066a-c4fb-406c-963b-0864f6c1950f/deploy.sh -c /tmp/.saltcloud-9744066a-c4fb-406c-963b-0864f6c1950f'
```

```
�[1;34m * DEBUG�[0m: Since BS_KEEP_TEMP_FILES=1 we're copying files instead of moving them
�[1;34m * DEBUG�[0m: The passed destination (/etc/salt) is a directory
�[1;34m * DEBUG�[0m: Full destination path is now: /etc/salt/minion
�[1;34m * DEBUG�[0m: Not overwriting /etc/salt/minion with /tmp/.saltcloud-25e147c5-ed25-4cbe-8408-703b24c00b81/minion
```

When I run it, we get the file overwritten correctly.

```
^[[1;32m *  INFO^[[0m: Running config_salt()
^[[1;34m * DEBUG^[[0m: Since BS_KEEP_TEMP_FILES=1 we're copying files instead of moving them
^[[1;34m * DEBUG^[[0m: The passed destination (/etc/salt) is a directory
^[[1;34m * DEBUG^[[0m: Full destination path is now: /etc/salt/minion
^[[1;34m * DEBUG^[[0m: Copying /tmp/.saltcloud//minion to /etc/salt/minion
^[[1;32m *  INFO^[[0m: Running install_ubuntu_stable()
```

The customer is seeing this issue on Ubuntu 14.04 on vmware.

ZD1654

Right now, they have it working by using `-F` as a workaround.

Thanks,
Daniel

**Comment by rallytime** [comment]
Thanks @gtmanfred - I'll see what I can find.

**Comment by rallytime** [comment]
@gtmanfred After looking more into this, I am not able to replicate it either. However, could the `/etc/salt/minion` file is already present on the minion? If that is the case, then this is completely expected behavior. We don't want to overwrite an existing minion config file without explicitly saying so (with `-F`).

**Comment by rallytime** [comment]
That logic is here, by the way: https://github.com/saltstack/salt-bootstrap/blob/ae8df09e13e6aa259e314afe3c739bd1a961d9bc/bootstrap-salt.sh#L2015
