### ISSUE TITLE
-y was used without --force-yes

### ISSUE THREAD

**Issue by ghost** [saltstack/salt-bootstrap#114]
```
Reading package lists...
W: GPG error: http://ppa.launchpad.net lucid Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4759FA960E27C0A6
 *  INFO: Running install_ubuntu_stable()
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  debconf-utils libyaml-0-2 msgpack-python python-crypto python-jinja2
  python-m2crypto python-yaml python-zmq salt-common
Suggested packages:
  python-crypto-dbg python-jinja2-doc
The following NEW packages will be installed:
  debconf-utils libyaml-0-2 msgpack-python python-crypto python-jinja2
  python-m2crypto python-yaml python-zmq salt-common salt-minion
0 upgraded, 10 newly installed, 0 to remove and 117 not upgraded.
Need to get 2,000kB of archives.
After this operation, 9,011kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  python-zmq msgpack-python salt-common salt-minion
E: There are problems and -y was used without --force-yes
 * ERROR: Failed to run install_ubuntu_stable()!!!

```

**Comment by s0undt3ch** [comment]
If you could provide the fill output passing `-D` to the script, that would help a lot.

**Comment by ghost** [comment]
Sorry already solved the problem by modifying the script:

```
763c763
<     apt-get install -y -o DPkg::Options::=--force-confold $@; return $?
---
>     apt-get install -y --force-yes -o DPkg::Options::=--force-confold $@; return $?
```

If I come across the problem again, it will send more info.

**Comment by s0undt3ch** [comment]
```
--force-yes
    Force yes. This is a dangerous option that will cause apt-get to continue without prompting if it is doing something potentially harmful. It should not be used except in very special situations. Using --force-yes can potentially destroy your system! 
```

So, since we don't have any additional information, and since the option is really destructive, we're not implementing your fix for now.

**Comment by hamgua** [comment]
@DDarko 

```
 763c763
 <     apt-get install -y -o DPkg::Options::=--force-confold $@; return $?
 ---
 >     apt-get install -y --force-yes -o DPkg::Options::=--force-confold $@; return $?
```

I use salt in debian,find this problem!google for this so many time!
can you tell me which file i changes for this problem?

**Comment by ghost** [comment]
p1.patch
"""
**\* salt-bootstrap.sh   2013-09-26 08:30:07.529921627 +0200
--- salt-bootstrap.sh   2013-09-26 08:30:38.362157258 +0200

---

**\* 932,938 ****
  #   DESCRIPTION:  (DRY) apt-get install with noinput options
  #-------------------------------------------------------------------------------
  __apt_get_noinput() {
!     apt-get install -y -o DPkg::Options::=--force-confold $@; return $?
  }

--- 932,938 ----
  #   DESCRIPTION:  (DRY) apt-get install with noinput options
  #-------------------------------------------------------------------------------
  __apt_get_noinput() {
!     apt-get install -y --force-yes -o DPkg::Options::=--force-confold $@; return $?
  }
"""

Create file p1.patch containing above.
Download the bootstrap code:
$ wget -O salt-bootstrap.sh http://bootstrap.saltstack.org

Apply the patch to the downloaded code:
$ patch -p1 salt-bootstrap.sh -i p1.patch

You want to set permissions for the script:
$ chmod +x salt-bootstrap.sh

Then you can use this script for quick Salt installation.

**Comment by stephen-mw** [comment]
I would like to encourage the addition of this option. I think it's silly not to include a "--force-yes" even though it's potentially dangerous. The force flag is there because of that reason, not despite it.

This is especially useful for testing when the gpg.key isn't readily available or is simply wrong.
