### ISSUE TITLE
No dependencies installation function found.

### ISSUE THREAD

**Issue by ggmartins** [saltstack/salt-bootstrap#1142]
### Description of Issue/Question

Sorry to bug you guys again. I was installing salt stack on raspbian stretch and got this. It was working for jessie.

**sh bootstrap-salt.sh -r -P git v2016.11.5**
   INFO: Running version: 2017.05.24  (tested with 2017.08.17 too)
   INFO: Executed by: sh
   INFO: Command line: 'bootstrap-salt.sh -r -P git v2016.11.5'

   INFO: System Information:
   INFO:   CPU:          :
   INFO:   CPU Arch:     armv7l
   INFO:   OS Name:      Linux
   INFO:   OS Version:   4.9.41-v7+
   INFO:   Distribution: Raspbian 9.1

   INFO: Installing minion
bootstrap-salt.sh: 1: eval: raspbian_9_debian_base: parameter not set
   INFO: Found function config_salt
   INFO: Found function preseed_master
   INFO: Found function daemons_running
 ERROR: **No dependencies installation function found**. Exiting...
### Setup
rpi3 + internet

### Steps to Reproduce Issue
sh bootstrap-salt.sh -r -P git v2016.11.5

### Versions and Systems
./bootstrap-salt.sh -v
./bootstrap-salt.sh -- Version 2017.08.17
uname -a
Linux raspberrypi 4.9.41-v7+ #1023 SMP Tue Aug 8 16:00:15 BST 2017 armv7l GNU/Linux

**Comment by ggmartins** [comment]
tried it on jessie and didn't work. I don't know how the hell I got it working before.

**Comment by rallytime** [comment]
@ggmartins Support for Raspbian on a Debian 9/Stretch base hasn't been added yet. It was on my radar at some point, but since I hadn't filed an issue for it, I forgot. Thank you for filing this.

@vutny You might be interested in adding this initial support if you have some spare time. :)

**Comment by vutny** [comment]
@rallytime Hmm.. I don't have spare RPi to test at the moment... However, I might be able to emulate it.

Actually, this is a broader issue with generic support of various Debian derivatives. I will try to apply a quick fix to unblock @ggmartins for now. Stay tuned.

**Comment by ggmartins** [comment]
You guys are awesome! Thanks so much for considering fixing it. It's a big research project we are working on and it's only possible because of amazing tools like SS.

**Comment by dmurphy18** [comment]
@ggmartins @rallytime There are plans to support Raspbian on Stretch/Debian 9 as soon as it becomes available

**Comment by vutny** [comment]
@ggmartins I have added basic `git`-only installation support for Raspbian 9 in PR #1146 .
Please give it a try. Since it is based on latest `develop` branch it is also includes couple of prior fixes made for bootstrapping Debian.

**Comment by ggmartins** [comment]
it works! thanks a ton!

**Comment by rallytime** [comment]
Thanks for filing this issue @ggmartins and thank you to @vutny for fixing it so quickly.
