### ISSUE TITLE
Salt Bootstrap fails on Linux Mint > 17

### ISSUE THREAD

**Issue by bertpassek** [saltstack/salt-bootstrap#1147]
Running bootstrap script on Linux Mint distribution fails with following message:

E: Unable to locate package gnupg1-curl
 * ERROR: Failed to run install_ubuntu_git_deps()!!!

I found this line in the script:
`if [ "${DISTRO_VERSION}" = "16.10" ] || [ "$DISTRO_MAJOR_VERSION" -gt 16 ]; then
        GNUPG_CURL="gnupg1-curl"
fi`

DISTRO_NAME_L is ubuntu
DISTRO_MAJOR_VERSION is 18 !!!
DISTRO_VERSION is 16.04

In case of Linux Mint Sarah the distribution version is 18. But it's based on Ubuntu 16.04. So the expression `"$DISTRO_MAJOR_VERSION" -gt 16` is obviously not correct.

Regards

**Comment by bertpassek** [comment]
I guess /etc/lsb-release might be the problem

DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18
DISTRIB_CODENAME=sarah
DISTRIB_DESCRIPTION="Linux Mint 18 Sarah"

**Comment by rallytime** [comment]
HI @bertpassek - Thanks for filing this issue.

Can you tell me what version of the bootstrap script you're running this on? Have you tried the `develop` version of the script? I am thinking this has been fixed with #1139.

**Comment by bertpassek** [comment]
Hi,
i just tried the develop version and it's working fine. We were actually using the salt provisioner for vagrant and boostrap version was v2016...

**Comment by rallytime** [comment]
@bertpassek Awesome! Glad to hear it and thank you for trying that. That fix only went in recently, but it will be available in the next release of the bootstrap script. I'll close this as fixed.
