### ISSUE TITLE
Unable to get the Saltstack repository public key

### ISSUE THREAD

**Issue by alchy58** [saltstack/salt-bootstrap#1149]
### Description of Issue/Question
Using Xen role for installing salt-minion who worked some monthes ago (around 4-6 monthes, I was busy with some stuff), I got issue with unauthenticated packages.
It seems that the salt-bootstrap fails to fetch saltstack repository key :

> Warning: apt-key output should not be parsed (stdout is not a terminal)
> Executing: /tmp/apt-key-gpghome.Z4QywDHSzM/gpg.1.sh --keyserver-options ca-cert-file=/etc/ssl/certs/ca-certificates.crt --fetch-keys https://repo.saltstack.com/apt/debian/9/amd64/latest/SALTSTACK-GPG-KEY.pub
> gpg: keyserver option 'ca-cert-file' is obsolete; please use 'hkp-cacert' in dirmngr.conf
> gpg: requesting key from 'https://repo.saltstack.com/apt/debian/9/amd64/latest/SALTSTACK-GPG-KEY.pub'
> gpg: WARNING: unable to fetch URI https://repo.saltstack.com/apt/debian/9/amd64/latest/SALTSTACK-GPG-KEY.pub: Connection refused

So on the apt-get update I got :

> W: GPG error: https://repo.saltstack.com/apt/debian/9/amd64/latest stretch InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E08A149DE57BFBE
> W: The repository 'https://repo.saltstack.com/apt/debian/9/amd64/latest stretch InRelease' is not signed.

So some packages are not installed :

>  \*  INFO: Running install_debian_9_stable()
> ...
> List of packages to be installed
> ...
> 0 upgraded, 52 newly installed, 0 to remove and 3 not upgraded.
> Need to get 15.6 MB of archives.
> After this operation, 82.5 MB of additional disk space will be used.
> WARNING: The following packages cannot be authenticated!
>   python-jinja2 salt-common salt-minion
> E: There were unauthenticated packages and -y was used without --allow-unauthenticated
>  \* ERROR: Failed to run install_debian_9_stable()!!!

Temporary workaround :

I added the "block saltstack repository key" in my role to add the saltstack repository key before executing bootstrap-salt.sh (in two lines, the pipe seems not to work there).

By the way, the salt-minion is now correctly installed and automatically listed in the unaccepted keys of the master

### Setup
Xen hypervisor without salt at all
The salt-master is on a dedicated VM
The salt-minion is setup using a xen role at the end of the domU creation

Xen role :
```
#!/bin/sh

#
# XEN role.d script to automatically install the salt-minion .deb
# package on XEN VMs.
#
# This script should be placed in /etc/xen-tools/role.d and can
# then be referenced when calling xen-create-image. This only
# works on Debian VMs.
#

prefix=$1

#
#  Source our common functions - this will let us install a Debian package.
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    logMessage Installation problem
fi

logMessage Script $0 starting

installDebianPackage ${prefix} ca-certificates

logMessage Import the SaltStack repository key
chroot ${prefix} wget -O SALTSTACK-GPG-KEY.pub https://repo.saltstack.com/apt/debian/9/amd64/latest/SALTSTACK-GPG-KEY.pub
chroot ${prefix} apt-key add SALTSTACK-GPG-KEY.pub

logMessage Downloading salt-minion
chroot ${prefix} wget -O bootstrap-salt.sh https://bootstrap.saltstack.com

logMessage Installing salt-minion
chroot ${prefix} sh bootstrap-salt.sh -D -i my-minion-id -A [MASTER IP]

chroot ${prefix} sh bootstrap-salt.sh -v

logMessage Script $0 finished
```

### Steps to Reproduce Issue
1) Create the Xen role under /etc/xen-tools/role.d/salt-minion
2) xen-create-image --ip [MINION IP] --role salt-minion --hostname my-minion-id
3) Check xen-tool log /var/log/xen-tools/my-minion-id.log

### Versions and Systems
dom0 : Debian Stretch 9.1 with Xen hypervisor 4.8.1-1+deb9u3 amd64
domU : Debian Stretch 9.1
bootstrap-salt.sh -v : Version 2017.08.17

**Comment by rallytime** [comment]
@vutny Is this something you might be able to look into?

I feel like you made some changes recently to the Debian 9 support.

**Comment by rallytime** [comment]
@alchy58 Actually, can you test this running off the the `develop` branch and let us know how it goes?

**Comment by florianb** [comment]
We're running into the same issue.

---
```
salt 2017.7.2 (Nitrogen)
Operating System: Debian GNU/Linux 9 (stretch)
          Kernel: Linux 4.9.0-3-amd64
    Architecture: x86-64
```

**Comment by florianb** [comment]
It seems like this issue is universal: https://www.google.de/search?q=Warning%3A+apt-key+output+should+not+be+parsed+%28stdout+is+not+a+terminal%29&ie=utf-8

**Comment by tlex** [comment]
Same issue on Ubuntu 16.04, when trying to add the repository with a state:
```
          ID: salt-latest
    Function: pkgrepo.managed
        Name: deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial
      Result: False
     Comment: Failed to configure repo 'deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial': Error: failed to add key from https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub
     Started: 20:40:02.402030
    Duration: 710.702 ms
     Changes:
```
Downloading the same key to a file and then adding it with `- key_url: /file` works.

Probably related to salt/issues/44013

**Comment by brianthelion** [comment]
@rallytime This appears to still be a problem on 2019.2.

**Comment by MikeC-BC** [comment]
still an issue

**Comment by rallytime** [comment]
Looks like I missed the notification the first time around. I'm not involved in this project any more so I can't re-open this. 

@s0undt3ch Can you help out on this one and re-open?
