### ISSUE TITLE
Issues deploying to Amazon linux via salt-cloud.

### ISSUE THREAD

**Issue by Jakis** [saltstack/salt-bootstrap#1155]
### Description of Issue/Question
I'm getting a lot of errors trying to bootstrap salt, but they only seem to happen when the target ami is Amazon linux.  Seems to be related to the way packages/prerequisites are being installed by yum.  

If I substitute the ami for ubuntu and change the ssh user, everything works great, so I think the issue is related to the Amazon Linux Ami/salt-bootstrap. Happy to gather more info if there's anything more I can get that might help.

May be related to #103 

### Setup
```
CloudProfile:
us_west_2_mgz_amzn:
  provider: aws-us-west-2
#  image: ami-9abea4fb # ubuntu Works
#  image: ami-b5a7ea85 # amazon linux 2014 Fails to install
  image: ami-3234a652 # amazon linux 2017 Fails to install
  size: t2.micro
#  ssh_username: ubuntu
  ssh_username: 'ec2-user'
  tag: {'Environment': 'production'}
  sync_after_install: grains
  network_interfaces:
    - DeviceIndex: 0
      AssociatePublicIpAddress: True
      SubnetId: subnet-xxxxxxxxx
      SecurityGroupId:
        - sg-xxxxxxxxxxxx
```

### Steps to Reproduce Issue
Latest ami:
IMAGES x86_64 2017-04-17T08:11:50.000Z Amazon Linux AMI 2017.03.0.20170417 x86_64 HVM EBS True xen ami-3234a652 amazon/amzn-ami-hvm-2017.03.0.20170417-x86_64-ebs amazon machine amzn-ami-hvm-2017.03.0.20170417-x86_64-ebs 137112412989 True /dev/xvda ebs simple available hvm

Salt-cloud debug excerpt:
--> Running transaction check
---> Package PyYAML27.x86_64 0:3.11-2.el6 will be installed
---> Package python27-msgpack.x86_64 0:0.4.6-2.el6 will be installed
---> Package python27-psutil.x86_64 0:5.2.2-1.ius.el6 will be installed
---> Package python27-zmq.x86_64 0:14.5.0-3.el6 wi
Connection to 10.2.0.250 closed.
[DEBUG ] Connection to 10.2.0.250 closed.
ll be installed
--> Processing Dependency: libzmq.so.4()(64bit) for package: python27-zmq-14.5.0-3.el6.x86_64
---> Package salt.noarch 0:2017.7.1-1.el6 will be installed
--> Processing Dependency: python27-tornado >= 4.2.1 for package: salt-2017.7.1-1.el6.noarch
--> Running transaction check
---> Package salt.noarch 0:2017.7.1-1.el6 will be installed
--> Processing Dependency: python27-tornado >= 4.2.1 for package: salt-2017.7.1-1.el6.noarch
---> Package zeromq.x86_64 0:4.0.5-4.el6 will be installed
--> Finished Dependency Resolution
Error: Package: salt-2017.7.1-1.el6.noarch (saltstack-repo)
Requires: python27-tornado >= 4.2.1
Available: python27-tornado-2.2.1-7.8.amzn1.noarch (amzn-main)
python27-tornado = 2.2.1-7.8.amzn1
You could try using --skip-broken to work around the problem
You could try running: rpm -Va --nofiles --nodigest

    ERROR: Failed to run install_amazon_linux_ami_stable()!!!
    [DEBUG ] ll be installed
    --> Processing Dependency: libzmq.so.4()(64bit) for package: python27-zmq-14.5.0-3.el6.x86_64
    ---> Package salt.noarch 0:2017.7.1-1.el6 will be installed
    --> Processing Dependency: python27-tornado >= 4.2.1 for package: salt-2017.7.1-1.el6.noarch
    --> Running transaction check
    ---> Package salt.noarch 0:2017.7.1-1.el6 will be installed
    --> Processing Dependency: python27-tornado >= 4.2.1 for package: salt-2017.7.1-1.el6.noarch
    ---> Package zeromq.x86_64 0:4.0.5-4.el6 will be installed
    --> Finished Dependency Resolution
    Error: Package: salt-2017.7.1-1.el6.noarch (saltstack-repo)
    Requires: python27-tornado >= 4.2.1
    Available: python27-tornado-2.2.1-7.8.amzn1.noarch (amzn-main)
    python27-tornado = 2.2.1-7.8.amzn1
    You could try using --skip-broken to work around the problem
    You could try running: rpm -Va --nofiles --nodigest
    ERROR: Failed to run install_amazon_linux_ami_stable()!!!
    Error: There was a profile error: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /root/ssh-agent/keys/kuali-prod.1 -p 22 ec2-user@10.2.0.250 'sudo /tmp/.saltcloud-72bffc5d-066b-4d15-b120-26cc0b6bac05/deploy.sh -c '"'"'/tmp/.saltcloud-72bffc5d-066b-4d15-b120-26cc0b6bac05'"'"''' failed. Exit code: 1

I'm not using script:, just the default bootstrap process. I'm also seeing this same behavior with AMI:
IMAGES x86_64 2014-10-08T02:10:49.000Z Amazon Linux AMI 2014.09.1 x86_64 HVM EBS xen ami-b5a7ea85 amazon/amzn-ami-hvm-2014.09.1.x86_64-ebs amazon machine amzn-ami-hvm-2014.09.1.x86_64-ebs 137112412989 True /dev/xvda ebs simple available hvm

### Versions and Systems
```02:28 PM|user@server:/etc/salt# salt --versions-report
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.36.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

02:28 PM|user@server:/etc/salt# salt-cloud --version
salt-cloud 2017.7.1 (Nitrogen)

**Comment by rallytime** [comment]
Hi @Jakis - Can you tell me what version of the bootstrap script you're using? It's either in `/etc/salt/cloud.deploy.d/` or it's in `<path-to-your-salt-installations>/salt/cloud/deploy/` and you can find the version by running `sh bootstrap-salt.sh -v`.

**Comment by Jakis** [comment]
Oh nice catch.  I was experiencing this issue with version 2016.08.16.  Now that I've updated to the latest version (which identifies as 2017.08.17), I can no longer reproduce my bug.  

Thanks for looking, I think this one is resolved.

**Comment by rallytime** [comment]
@Jakis Awesome! Glad this is fixed up already with the new version. 👍 

I'll close this. :)
