### ISSUE TITLE
what url to use for windows minion bootstrap?

### ISSUE THREAD

**Issue by mayn** [saltstack/salt-bootstrap#1161]
for windows, what is the recommend location to download a stable `bootstrap-salt.ps1` from?

i.e for *nix everyone uses `https://bootstrap.saltstack.com`

(had a hard time finding it, my apologies if it is glaringly obvious)

thanks.

**Comment by rallytime** [comment]
Hi @mayn - My apologies for not responding here sooner. This one slipped through the cracks!

I am not aware of any very obvious ways to access the file like you can for `bootstrap.saltstack.com`. I would imagine most people just get the [raw link from GitHub](https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.ps1) to get the `bootstrap-salt.ps1` file.

@twangboy Do you know if there is something easier somewhere else? Could/Should it be somewhere easier? This has been an area that I haven't paid much attention to since helping out with the bootstrap script for the last while.

**Comment by twangboy** [comment]
I don't think we have a link to the Windows bootstrap directly like we do for Linux.

**Comment by rallytime** [comment]
@twangboy Do you think this is something we can add or make more useful/helpful for people?

**Comment by twangboy** [comment]
@rallytime I'm sure we could figure something out.

**Comment by mayn** [comment]
Stalebot, I’m just waiting for a resolution

**Comment by rallytime** [comment]
@dwoz You might be interested in this as well, along with @dubb-b.

**Comment by dubb-b** [comment]
I will need to talk to @utahdave about the best way to go about this. But it shouldn't be an issue to add it for the .ps1. Would need to be a different URL i'd imagine.

**Comment by rallytime** [comment]
Yes, it would need to be different.

**Comment by UtahDave** [comment]
@dubb-b Yeah, we can discuss setting up something like:  `https://windowsbootstrap.saltstack.com` or `https://winbootstrap.saltstack.com`. We should confer with @twangboy as well.

**Comment by twangboy** [comment]
I like winbootstrap

**Comment by twangboy** [comment]
@dwoz ^^^

**Comment by dubb-b** [comment]
winbootstrap works for me too

**Comment by rallytime** [comment]
@dubb-b I think `winbootstrap` is just fine. Can we make this happen?

**Comment by dubb-b** [comment]
@rallytime I am back Tuesday, I will get this rolling.

**Comment by dubb-b** [comment]
@rallytime, I talked to Dave B on getting this added. We can do that pretty
easily. My question is are we going to add docs for this?

**Comment by rallytime** [comment]
Yeah, we should. Something added to the `README` file in this repo should be sufficient. Can you or Dave B put that together?

**Comment by rallytime** [comment]
@dubb-b Or I can if it's something simple. I'm just not sure what the details might look like. ^

**Comment by dubb-b** [comment]
@rallytime I was wondering if we needed something either added to this:
https://docs.saltstack.com/en/latest/topics/tutorials/salt_bootstrap.html Or
a new Windows version created?

**Comment by rallytime** [comment]
@dubb-b That's a good idea to add a note there as well. I had forgotten those docs existed.

**Comment by discentem** [comment]
Hi folks, any updates on this? I'd love to see https://winbootstrap.saltstack.com or similar. Also, could we get a published sha256 checksum for the script?

**Comment by rallytime** [comment]
@dubb-b Where are we with this? I can add a step to the release checklist to update the docs for the windows checksum once we have this hosted.

**Comment by dubb-b** [comment]
@rallytime this is something @UtahDave will have to get implemented. Not sure what cycles he has for this ATM.

**Comment by BrandonGDossantos** [comment]
bump

**Comment by bryceml** [comment]
This is up and ready for testing at https://winbootstrap.saltstack.com (stable branch) and https://winbootstrap.saltstack.com/develop (develop branch) .  Don't consider it production ready yet.

**Comment by discentem** [comment]
Is there a published hash somewhere for verifying the download?

**Comment by bryceml** [comment]
It's not published anywhere as far as I know, but it's currently:
md5: e87763e031068953ff2a9a682f6710fe bootstrap-salt.ps1
sha256: 55dde1280909dd60de9b57d41046d632726a9722922917ef726fe747f4c041c4  bootstrap-salt.ps1

**Comment by bryceml** [comment]
The hashes will be documented after https://github.com/saltstack/salt-bootstrap/issues/1338 is fixed.

**Comment by bryceml** [comment]
Closing issue, the TLS settings of repo.saltstack.com still need to be changed https://github.com/saltstack/salt-bootstrap/issues/1338 and this still needs documented https://github.com/saltstack/salt-bootstrap/issues/1345 . We are pulling those into their own issues though.  I believe this can be considered production ready now.
