### ISSUE TITLE
Add kitchen salt tests for bootstrap runs

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-bootstrap#1180]
We need to add kitchen salt tests to PRs as well as the `develop` and `stable` branches for the bootstrap script.

@gtmanfred Please talk to me or @Ch3LL about what we're currently testing in Jenkins right now, and what we need to be adding to the kitchen salt runs.

A rough guideline of support is on the [README](https://github.com/saltstack/salt-bootstrap#supported-operating-systems) page of this repo.

**Comment by gtmanfred** [comment]
this is still being done.

**Comment by rallytime** [comment]
This is fixed in #1279. We can make a new issue in a devops repo to track the jenkins addition.
