### ISSUE TITLE
gnupg2 is just a dummy translation package starting in ubuntu 17.04

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt-bootstrap#1193]
### Description of Issue/Question

With ubuntu >= 17.04 we need to just install gnupg, instead of gnupg2.

ref https://github.com/saltstack/salt-jenkins/issues/709

**Comment by rallytime** [comment]
To note, 17.04 just went EOL at the beginning of this month. However, Ubuntu 17.10 will still have this issue.

**Comment by rallytime** [comment]
This should be fixed with #1196, however note that the PR removes support for 17.04 since it is EOL, but fixes support for 17.10.
