### ISSUE TITLE
Doesn't work with Amazon Linux 2 ami-4f89f53

### ISSUE THREAD

**Issue by nodakai** [saltstack/salt-bootstrap#1194]
### Description of Issue/Question

```
$ sudo bash bootstrap-salt.sh
 *  INFO: Running version: 2017.12.13
 *  INFO: Executed by: bash
 *  INFO: Command line: 'bootstrap-salt.sh '

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   4.9.76-38.79.amzn2.x86_64
 *  INFO:   Distribution: Amazon Linux AMI 2.0

 * ERROR: End of life distributions are not supported.
 * ERROR: Please consider upgrading to the next stable. See:
 * ERROR:     https://aws.amazon.com/amazon-linux-ami/
```

`bash -x` displays sth like this

```
+ __check_end_of_life_versions
+ case "${DISTRO_NAME_L}" in
+ '[' 2 -lt 2012 ']'
+ echoerror 'End of life distributions are not supported.'
```

Apparently the script picked up 2 from "2.0" and complained it's less than 2012.
* https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L1606

Given the new versioning scheme for Amazon Linux 2 series, maybe anything below 10 should pass the check?

### Versions and Systems
```
$ bash install-salt.sh -v
install-salt.sh -- Version 2017.12.13
```

```
$ cat /etc/system-release
Amazon Linux release 2.0 (2017.12) LTS Release Candidate
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2.0 (2017.12)"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2.0"
PRETTY_NAME="Amazon Linux 2.0 (2017.12) LTS Release Candidate"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2.0"
HOME_URL="https://amazonlinux.com/"
```

**Comment by nodakai** [comment]
Hmm, the RPM doesn't support Amazon Linux 2 yet after all... saltstack/salt#45154

**Comment by rallytime** [comment]
@nodakai my apologies for the late response here, but yeah, the packages for Amazon Linux 2 haven't been released yet. Once they are, we definitely should get the bootstrap script to support it.

**Comment by piersf** [comment]
@rallytime is there any date where those packages are going to be made available?

Thanks,

**Comment by rallytime** [comment]
@piersf That's a good question - I am not sure what the plans are for that presently, but I can check.

In the mean time, if someone wants to take a stab at adding git install support for this, that would be a good way to get this working for people until the packages are available.

**Comment by stv-io** [comment]
If it's any help (I can't quote the details, stating solely on memory, based on a quick and dirty test) a `pip install salt` worked without any hiccups for the more recently available AMI for Amazon Linux 2 a few weeks ago.

**Comment by ghost** [comment]
Hi @rallytime , are there any updates re package support for Amazon Linux 2?

I'm currently getting by installing from pip but I would really appreciate the RPMs.

Thanks

**Comment by zychao66** [comment]
I also hit this problem with rpm
finally succeed with pip

**Comment by adminericjacobs** [comment]
Is there any update on getting Amazon Linux 2 RPMs and boot-strap support?

**Comment by rallytime** [comment]
Does anyone here have a moment to test the changes in #1287? (Thanks @mchugh19 for picking this up!)

**Comment by Ch3LL** [comment]
Closing for now as there are no responses, but please let me know if i need to re-open :)

**Comment by lorengordon** [comment]
Just tested with salt-bootstrap 2018.08.15 and still doesn't seem to work...

```
# sh bootstrap-salt.sh git v2018.3.3
 *  INFO: Running version: 2018.08.15
 *  INFO: Executed by: sh
 *  INFO: Command line: 'bootstrap-salt.sh git v2018.3.3'

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   4.14.77-81.59.amzn2.x86_64
 *  INFO:   Distribution: Amazon Linux AMI 2

 * ERROR: End of life distributions are not supported.
 * ERROR: Please consider upgrading to the next stable. See:
 * ERROR:     https://aws.amazon.com/amazon-linux-ami/
```

**Comment by lorengordon** [comment]
Aha, no release yet. If I use what's in the develop branch, it works!

https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh

**Comment by ninjada** [comment]
just got this working with the dev branch bootstrap too.

any eta for when this is going to be released ie. stable branch? been in the process of prepping to upgrade my entire infrastructure and move it to amazon linux 2.

**Comment by Ch3LL** [comment]
We will need to do another release soon for the next feature release of salt but i dont have an exact ETA. Most likely within the next month. As a workaround you can use the develop script
