### ISSUE TITLE
Debian packages broken

### ISSUE THREAD

**Issue by VShell** [saltstack/salt-bootstrap#12]
The Debian Squeeze packages as installed by bootstrap are currently version 0.10.5, and suffer from the bug which has since been fixed by https://github.com/saltstack/salt/pull/2745. As a result, using the pkg module and pkg state is currently impossible without patching Salt after installation, which is obviously not desirable.

Could the package maintainer (@madduck?) either apply this patch to the 0.10.5 package in their repo, or upgrade the package to the latest release?

**Comment by akoumjian** [comment]
We are currently waiting for the sid maintainers to update salt there. Once it has been updated for unstable, madduck is willing to backport whichever version they've built.

**Comment by VShell** [comment]
@akoumjian Is there currently a workaround for this, then, aside from manually patching Salt, or installing from git?

**Comment by akoumjian** [comment]
The other current options for installing salt are:
1. building the debs using [this guide](https://salt.readthedocs.org/en/latest/topics/installation/debian.html?highlight=deb%20package#squeeze)
2. Using pip + installing dependencies separately
3. Installing form git, as you stated.

I do think installing from git is the most viable option at this point with the bootstrap script, which will still take care of installing other packaged dependencies. Using the options "git v0.11.1" will give you the latest stable release.

**Comment by VShell** [comment]
Alright, thanks for that. I will install from git, until the package is fixed.

**Comment by s0undt3ch** [comment]
The bootstrap script now installs `0.12.1-1~bpo60+1~madduck.2`. So I'm closing this ticket. Please re-open if necessary.
