### ISSUE TITLE
Move PR lint tests from old jenkins to new jenkins

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-bootstrap#1207]
The lint checks are set up on a Jenkins master that doesn't do a lot of recent testing besides lint checks for bootstrap PRs. We need to move these checks to the new Jenkins. This will also help start prepping for #1180, as those tests, once created, should run in the new Jenkins, too.

@gtmanfred I just wanted to file this after what we discussed yesterday about moving these to new jenkins instead of using travis like I was originally thinking. Now we can track this task!

**Comment by gtmanfred** [comment]
:+1: sounds good

**Comment by rallytime** [comment]
This is done.
