### ISSUE TITLE
turbolinux

### ISSUE THREAD

**Issue by xkktt** [saltstack/salt-bootstrap#1208]
### Setup
(Please provide relevant configs (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible, `bootstrap-salt.sh -D`.)

### Versions and Systems
(`salt --versions-report`, `bootstrap-salt.sh -v`, system type and version,
cloud/VM provider as appropriate.)

**Comment by rallytime** [comment]
Hi @yatre - Can you fill in a little more information here? What is this issue about?

**Comment by rallytime** [comment]
Closing since we haven't heard back here. Please feel free to reopen with the above questions answered. Thanks!
