### ISSUE TITLE
Kali Linux 2 labeled as EoL by bootstrap-salt.sh

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-bootstrap#1213]
@d4t4king commented on [Thu Mar 29 2018](https://github.com/saltstack/salt/issues/46785)

### Description of Issue/Question
Kali Linux 2 (rolling) labeled as End of Life (EoL) by bootstrap-salt.sh.  bootstrap-salt.sh refuses to install specified version.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Run:
```curl -o bootstrap-salt.sh -L https://bootstrap.saltstack.com
sudo sh bootstrap-salt.sh git
``` 
on any Kali install 2017 or later.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by Ch3LL** [comment]
Looks like we need to add some logic for Kali in this function: `__check_end_of_life_versions` or update the DISTRO_MAJOR_VERSION logic for kali.

In the meantime @d4t4king you can comment out the function call in the script if you need to get it working.


For more reference here is the relevant `bash -x` output:

```
+ __check_end_of_life_versions                                                                        
+ case "${DISTRO_NAME_L}" in                                                                          
+ '[' 1 -lt 7 ']'                                                                                     
+ echoerror 'End of life distributions are not supported.'                                            
+ printf '\033[1;31m * ERROR\033[0m: %s\n' 'End of life distributions are not supported.'             
 * ERROR: End of life distributions are not supported.                                                
```

**Comment by d4t4king** [comment]
> In the meantime @d4t4king you can comment out the function call in the script if you need to get it working.

Tried that.  It fails because the Kali package repository doesn't appear to contain 'gnupg-curl'.

**Comment by onnenon** [comment]
Is there any eta on this fix being implemented?

**Comment by rallytime** [comment]
There isn't anyone working on it that I know of. If someone would like to submit a PR, that would be greatly appreciated.
