### ISSUE TITLE
Installation on FreeBSD 10.4 broken

### ISSUE THREAD

**Issue by aaronm-cloudtek** [saltstack/salt-bootstrap#1215]
### Description of Issue/Question
Fails with `No packages available to install matching 'swig'`

Appears to be the same problem described in #1192 

### Steps to Reproduce Issue
Download bootstrap script from https://bootstrap.saltstack.com and run on FreeBSD 10.4

**Comment by rallytime** [comment]
@aaronm-cloudtek Thanks for the report. Can you try the develop version and confirm if this is fixed or not? If this is the same issue as #1192, then it should be fixed there.

https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh

**Comment by rallytime** [comment]
The PR listed above has now been released with the latest stable. Since I never heard back here, I am going to close this. If the issue persists on the latest stable release, please leave a comment with updated information and I am happy to open this up again.
