### ISSUE TITLE
-b option causes bootstrap-salt.sh not to download git repository

### ISSUE THREAD

**Issue by jheidbrink** [saltstack/salt-bootstrap#1217]
### Description of Issue/Question

When installation type ("$ITYPE") is "git", the "-b" switch prevents bootstrap-salt.sh from downloading the repository (contrary to the documentation). This breaks the installation.

### Steps to Reproduce Issue
Take an Ubuntu 16.04 system with git and python installed. Place the bootstrap-salt.sh somewhere and execute:
`sh bootstrap-salt.sh -D -b git`

### Explanation

First, the `DEPS_INSTALL_FUNC` is set to `__git_clone_and_checkout`. This function is never called because of the check for `$_NO_DEPS` introduced in commit 958fb6.

### output of failing bootstrap-salt.sh call
`sh bootstrap-salt.sh -D -b git`
` *  INFO: Running version: 2017.12.13`
` *  INFO: Executed by: sh`
` *  INFO: Command line: 'bootstrap-salt.sh -D -b git'`
` *  WARN: Running the unstable version of bootstrap-salt.sh`
``
` *  INFO: System Information:`
` *  INFO:   CPU:          GenuineIntel`
` *  INFO:   CPU Arch:     x86_64`
` *  INFO:   OS Name:      Linux`
` *  INFO:   OS Version:   4.14.32-1-lts`
` *  INFO:   Distribution: Ubuntu 16.04`
``
` * DEBUG: Binaries will be searched using the following $PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
` *  INFO: Installing minion`
` *  INFO: Found function __git_clone_and_checkout`
` * DEBUG: DEPS_INSTALL_FUNC=__git_clone_and_checkout`
` * DEBUG: config_ubuntu_16_git_salt not found....`
` * DEBUG: config_ubuntu_16_04_git_salt not found....`
` * DEBUG: config_ubuntu_16_salt not found....`
` * DEBUG: config_ubuntu_16_04_salt not found....`
` * DEBUG: config_ubuntu_git_salt not found....`
` * DEBUG: config_ubuntu_salt not found....`
` *  INFO: Found function config_salt`
` * DEBUG: CONFIG_SALT_FUNC=config_salt`
` * DEBUG: preseed_ubuntu_16_git_master not found....`
` * DEBUG: preseed_ubuntu_16_04_git_master not found....`
` * DEBUG: preseed_ubuntu_16_master not found....`
` * DEBUG: preseed_ubuntu_16_04_master not found....`
` * DEBUG: preseed_ubuntu_git_master not found....`
` * DEBUG: preseed_ubuntu_master not found....`
` *  INFO: Found function preseed_master`
` * DEBUG: PRESEED_MASTER_FUNC=preseed_master`
` * DEBUG: install_ubuntu_16_git not found....`
` * DEBUG: install_ubuntu_16_04_git not found....`
` *  INFO: Found function install_ubuntu_git`
` * DEBUG: INSTALL_FUNC=install_ubuntu_git`
` * DEBUG: install_ubuntu_16_git_post not found....`
` * DEBUG: install_ubuntu_16_04_git_post not found....`
` * DEBUG: install_ubuntu_16_post not found....`
` * DEBUG: install_ubuntu_16_04_post not found....`
` *  INFO: Found function install_ubuntu_git_post`
` * DEBUG: POST_INSTALL_FUNC=install_ubuntu_git_post`
` * DEBUG: install_ubuntu_16_git_restart_daemons not found....`
` * DEBUG: install_ubuntu_16_04_git_restart_daemons not found....`
` * DEBUG: install_ubuntu_16_restart_daemons not found....`
` * DEBUG: install_ubuntu_16_04_restart_daemons not found....`
` * DEBUG: install_ubuntu_git_restart_daemons not found....`
` *  INFO: Found function install_ubuntu_restart_daemons`
` * DEBUG: STARTDAEMONS_INSTALL_FUNC=install_ubuntu_restart_daemons`
` * DEBUG: daemons_running_ubuntu_16_git not found....`
` * DEBUG: daemons_running_ubuntu_16_04_git not found....`
` * DEBUG: daemons_running_ubuntu_16 not found....`
` * DEBUG: daemons_running_ubuntu_16_04 not found....`
` * DEBUG: daemons_running_ubuntu_git not found....`
` * DEBUG: daemons_running_ubuntu not found....`
` *  INFO: Found function daemons_running`
` * DEBUG: DAEMONS_RUNNING_FUNC=daemons_running`
` * DEBUG: install_ubuntu_16_git_check_services not found....`
` * DEBUG: install_ubuntu_16_04_git_check_services not found....`
` * DEBUG: install_ubuntu_16_check_services not found....`
` * DEBUG: install_ubuntu_16_04_check_services not found....`
` * DEBUG: install_ubuntu_git_check_services not found....`
` *  INFO: Found function install_ubuntu_check_services`
` * DEBUG: CHECK_SERVICES_FUNC=install_ubuntu_check_services`
` *  INFO: Running install_ubuntu_git()`
`python: can't open file 'setup.py': [Errno 2] No such file or directory`
` * ERROR: Failed to run install_ubuntu_git()!!!`

**Comment by rallytime** [comment]
@jheidbrink Just to be sure, do you still see that problem when you specify a specific git branch/sha/tag?

Something like:
```
sh bootstrap-salt.sh -D -b git develop
```
or
```
sh bootstrap-salt.sh -D -b git v2017.7.5
```

**Comment by jheidbrink** [comment]
@rallytime Yes, I get the same problem when specifying a ref.

**Comment by rallytime** [comment]
@jheidbrink OK, thanks for filing and for confirming. :)
