### ISSUE TITLE
Change Tornado Version to upstream again once 5.0 is supported in salt

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-bootstrap#1220]
### Description of Issue/Question
Due to the discussion in https://github.com/saltstack/salt/issues/45790, the following changes was made to the bootstrap script: https://github.com/saltstack/salt-bootstrap/pull/1219

Once Tornado 5.0 is supported in SaltStack, we should revert #1219. This issue is just a reminder for that.

**Comment by The-Loeki** [comment]
Tornado 5 (seems) still not supported on Py3; saltstack/salt-jenkins#995

**Comment by The-Loeki** [comment]
Issue moved to https://github.com/saltstack/salt/issues/51883
