### ISSUE TITLE
Add Ubuntu 18.04 Support

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-bootstrap#1225]
Ubuntu 18 recently dropped, but support for it hasn't been added yet.

**Comment by Artem261992** [comment]
Could you say please, on which version of python will the official release of salt for Ubuntu 18.04 work?

**Comment by rallytime** [comment]
Hi @Artem261992 - for the bootstrap script, just Py2 will be supported initially. Py3 support through bootstrap is not supported for any distro yet, though I am working on that presently.

For regular salt packages, Py2 and Py3 will be supported through repo.saltstack.com. Those will be available when 2017.7.6 and 2018.3.1 are released.

**Comment by jeffdyke** [comment]
Is 2018.3.1 going to include full support for 18.04 or will it come later?  it sounds like yes, and is there a guestimate on a release date that includes support for 18.04.
