### ISSUE TITLE
Salt minion daemon enabled twice on Ubuntu 14.04

### ISSUE THREAD

**Issue by calc84maniac** [saltstack/salt-bootstrap#1233]
### Description of Issue/Question
I noticed when deploying Salt (stable) on Ubuntu 14.04 that I was getting inconsistent pillar query results and multiple job return events from the same minion. It appears that both the legacy init.d daemon and upstart daemon were enabled at the same time.

This appears to have been caused directly by `install_ubuntu_stable_post()`, which always enables the init.d daemon if systemctl is not present, regardless of the presence of upstart. In contrast, `install_ubuntu_git_post()` will not enable the init.d daemon if upstart is available.

### Steps to Reproduce Issue
Deploy a minion normally on Ubuntu 14.04, using a stable package (for example, 2018.3.0).

### Versions and Systems
Script version: 2018.04.25

**Comment by rallytime** [comment]
@calc84maniac Is this happening on the latest release, `v2018.04.25`, as well?

**Comment by calc84maniac** [comment]
I just confirmed that it does, yes. (Technically my old script was somewhere between the two releases because I had needed the wait_for_apt improvement.) I'll update the issue description.

**Comment by rallytime** [comment]
Thanks for checking. :)

**Comment by rallytime** [comment]
Hey @calc84maniac - I have not tested this, but could you try out this patch? I didn't have a box handy this evening to test this on, but I thought you might be able to try this really quickly.

Can you add the following statement to the `install_ubuntu_stable_post()` function, in between the first `if` and `elif` clauses? Basically right above [this line](https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh?utf8=%E2%9C%93#L2862) on the current `develop` branch:
```
        elif [ -f /sbin/initctl ] && [ -f /etc/init/salt-${fname}.conf ]; then
            # Upstart support is available and it knows about our service
            /sbin/initctl status salt-$fname > /dev/null 2>&1
            if [ $? -ne 0 ]; then
                # Everything is in place and upstart gave us an error code - Fail
                return 1
            fi
```

Let me know how that goes or if you have any questions. Thanks!
