### ISSUE TITLE
SmartOS dependency conflict

### ISSUE THREAD

**Issue by siepkes** [saltstack/salt-bootstrap#1237]
The function which installs dependencies on SmartOS (`install_smartos_deps`) explicitly installs the package `py27-crypto`. However when pkgsrc is used later on to install the `salt` package this fails because the `salt` package now depends on `py27-cryptodome` which conflicts with `py27-crypto`.

The 18.1.0 SmartOS image (` 221635c4-3b85-11e8-b6ba-23f68c9bf2c4`) has a recent enough version of pkgsrc for this problem to manifest itself.

**Comment by rallytime** [comment]
Hi @siepkes - that package name just hasn't been updated in bootstrap to match the one in the package. Do you want to make a pull request?

@sjorge You are probably interested in this one.

**Comment by siepkes** [comment]
@rallytime I'm somewhat uncertain how to handle the situation because I think in older versions of pkgsrc the `salt` package might still need to use the `py27-crypto` package (ie. has the `py27-crypto` package specified as dep). I will probably break the LTS SmartOS images if I change the package in the bootstrap script to `py27-cryptodome`. 

I think the definitive fix would be when installing salt via pkgsrc to just let pkgsrc do the dependency resolution and not explicitly install those dependencies at all in the bootstrap script. And only if salt is not installed via pkgsrc install those deps explicitly. Is that an idea?

**Comment by sjorge** [comment]
@rallytime @siepkes I have not worked with salt-bootstrap before as I simply roll my own packages...

```
awk -F/ '/SmartOS/ { print $6 }' /opt/local/etc/pkgin/repositories.conf
```

Can be used to check the pkgsrc branch, so some filtering on this to figure out which set of package is needed should be possible.

Although as @siepkes mentioned in the new comment, just letting pkgin deal with it would probably be better! We can also abuse pkgin for the git install to get the dependancies were we will need them. I have some code for that somewhere... let me look that up.

```
    for dep in $(pkgin show-deps salt | grep '^\s' | grep -v '\snot'); do
      pkgin -y in ${dep}
    done

```

Found it

**Comment by siepkes** [comment]
I must admit I'm not terribly familiar with the bootstrap script. I'm a user because Hashicorp Packer uses it by default when using salt. However I worked around this issue by manually installing salt with pkgsrc:

```json
    "provisioners": [
        {
            "type": "shell",
            "inline": ["pkgin -y install salt; [[ -d /srv ]] || mkdir /srv"]
        },
        {
            "type": "salt-masterless",
            "skip_bootstrap": "true",
            "bootstrap_args": "-X",
            "salt_call_args": "--id=mysql-percona-57-cluster",
            "local_state_tree": "../../salt/states/base"
        },
```
So with the disclaimer I just made that I really don't know what I'm talking about ;-) I'm somewhat puzzled as to what the bootstrap script expects from SmartOS. Basically if there is pkgsrc you can just do `pkgin -y install salt`. If there is no pkgsrc then you also can't use pkgsrc to install dependencies to manually install salt?

**Comment by rallytime** [comment]
To be perfectly honest, I have not had much occasion to delve into the SmartOS code. Initial support for SmartOS was added in 2013. If I remember correctly, that was well before @sjorge was awesome enough to start doing the community packaging for SmartOS, so the bootstrap script was probably never adjusted for this change.

Now, I don't know very much about the ins-and-outs of SmartOS, but how this works for other distros, in a general fashion as there are of course many caveats, is basically the following:

1. Stable installations come directly from repo.saltstack.com (think CentOS 7, Ubuntu 14/16, Debian 8, etc). The repo file is downloaded and placed where it needs to be (`/etc/yum.repos.d/saltstack.repo` for example) and the salt packages are installed from there.
2. Git installations use the packages provided by the distro package mirrors. So the various versions of `python-zmq`, `python-PyYAML`, `python-tornado`, etc etc etc come from the various distro package maintainers. Once the dependencies are met, then salt can be cloned and used.

My apologies for not having more insight here with SmartOS, but maybe that helps @siepkes?
