### ISSUE TITLE
arm64 installation from repositories is not allowed, even with custom repos

### ISSUE THREAD

**Issue by alexandruavadanii** [saltstack/salt-bootstrap#1240]
### Description of Issue/Question

Upstream commit [5] broke Salt bootstrap on AArch64, by
introducing an architecture condition that is too strict to allow
Debian package installation (even if we provide our own repo) at [1].
Note that since most packages required by Salt are arch-indep (with some exceptions for RAET, see [2]),
we actually use the amd64 repos just fine with Salt in OPNFV on AArch64.

We (OPNFV) add "arm64" to the list of supported architectures on the fly to circumvent this,
but this needs some ugly hacks (e.g. [3, 4], as the bootstrap script is fetched using
`curl` from <salt-master-setup.sh> in certain scenarios (e.g. while using salt-formula-salt to
provision the virtual control plane virtual machines).

### Setup
Ubuntu 16.04 (arm64), but it applies to any Debian distro on arm64 really.

### Steps to Reproduce Issue
N/A

### Versions and Systems
2018.04.25 (but it affects everything past commit [5]).

[1] https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L1293
[2] https://jira.opnfv.org/browse/ARMBAND-382
[3] https://github.com/opnfv/fuel/blob/master/mcp/patches/scripts/0001-salt-master-setup.sh-Allow-arm64-salt-bootstrap.patch
[4] https://github.com/opnfv/armband/blob/master/patches/opnfv-fuel/0003-mcp-salt-formulas-armband-Extend-libvirt_domain.patch#L85
[5] https://github.com/saltstack/salt-bootstrap/commit/caa6d7d

**Comment by rallytime** [comment]
@alexandruavadanii Thanks for filing this. Would you like to submit a PR to fix this?

**Comment by alexandruavadanii** [comment]
@rallytime Sure, the code is not the hard part :) But I wanted to ask first what the logic behind that check would be. I can think of at least 3 different ways:
- print a warning for any unsupported architectures, but don't fail (that works for me, but it's a bit loose);
- skip arch check if `-R` is passed (that doesn't work for me since I rely on amd64 repos on arm64 too, but if really needed I could pass `-R` just to get past this);
- add an exception for arm64 only and let the script continue;
My understanding is that Salt will officially add arm64 repo metadata in the future, so the third option should be future-proof.
If you have other suggestions, I'd be happy to hear and try to implement them.

**Comment by rallytime** [comment]
@alexandruavadanii I like the 3rd option. As long as there some helpful code comments and also maybe an update to the README about what is expected, then that should suffice.

👍

**Comment by alexandruavadanii** [comment]
Great! I am swamped for today/tomorrow but will try to submit a PR this week.

**Comment by rallytime** [comment]
@alexandruavadanii Thanks! Looking forward to it!

**Comment by alexandruavadanii** [comment]
Sorry for the delay. 
I did a bit more than just allow installation on arm64, I made it also default to re-using the amd64 repositories. All arch-specific packages needed by Salt are actually fetched from Ubuntu, so this should be all that's needed for a working Salt on arm64 (this is how we have been installing Salt on arm64 for a few months now in OPNFV).
