### ISSUE TITLE
bootstrap.saltstack.com is IPv4 only

### ISSUE THREAD

**Issue by chrisnew** [saltstack/salt-bootstrap#1252]
### Setup
* have a host in IPv6-only land
* try to bootstrap SaltStack using https://bootstrap.saltstack.com

### Steps to Reproduce Issue

```
# curl -L https://bootstrap.saltstack.com | sh 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to 138.197.226.47: Network is unreachable
```

### Versions and Systems
most recent as of today

**Comment by rallytime** [comment]
Hi @chrisnew - Thank you filing this. This is because we host the script on Digital Ocean and their load balancers do not yet support IPv6. As soon as they do, we can switch that over.

@KaiSforza Can you keep an eye on this so that once IPv6 is supported, we can get bootstrap.saltstack.com set up correctly as well?

**Comment by chrisnew** [comment]
Thanks for explaining and keeping track!

Right now I got a workaround in place: I simply mirror your script on one of my IPv6 enabled hosts. :)

**Comment by KaiSforza** [comment]
Yeah, I'll keep my eye out on the digital ocean side!

**Comment by rallytime** [comment]
@dubb-b Adding you to this issue to be aware of on your side.

**Comment by dubb-b** [comment]
@rallytime Dave will have to see if this can be done. Adding him to the ticket.

**Comment by UtahDave** [comment]
IPv6 still not available for loadbalancers on Digitalocean

**Comment by bryceml** [comment]
repo.saltstack.com and bootstrap.saltstack.com now support IPv6.  We plan on moving to cloudfront soon (April 16th is our goal) and they will still have IPv6 when we do that.

rsync.repo.saltstack.com will only have IPv4 until further notice, but we can probably get it to support IPv6 at some point this year.
