### ISSUE TITLE
Debian Squeeze

### ISSUE THREAD

**Issue by synotna** [saltstack/salt-bootstrap#126]
I'm having trouble bootstrapping with a fresh debian squeeze install, trying with both default and with git develop and with -P git develop

```
root@debian:~# wget -O - http://bootstrap.saltstack.org | sh
--2013-05-14 18:30:37--  http://bootstrap.saltstack.org/
Resolving bootstrap.saltstack.org (bootstrap.saltstack.org)... 74.208.29.198
Connecting to bootstrap.saltstack.org (bootstrap.saltstack.org)|74.208.29.198|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.github.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh [following]
--2013-05-14 18:30:37--  https://raw.github.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh
Resolving raw.github.com (raw.github.com)... 199.27.76.133
Connecting to raw.github.com (raw.github.com)|199.27.76.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 95188 (93K) [text/plain]
Saving to: `STDOUT'

 0% [                                       ] 0           --.-K/s               *  INFO: PIPED THROUGH sh -- Version 1.5.4

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     i686
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.2.0-4-486
 *  INFO:   Distribution: Debian 7.0

 *  INFO: Installing minion
100%[======================================>] 95,188       406K/s   in 0.2s

2013-05-14 18:30:39 (406 KB/s) - written to stdout [95188/95188]

 *  INFO: Found function install_debian_7_deps
 *  INFO: Found function install_debian_restart_daemons
 *  INFO: Found function daemons_running
 * ERROR: No installation function found. Exiting...
```

or with:

```
root@debian:~# wget -O - http://bootstrap.saltstack.org | sh -s -- -P git develop
--2013-05-14 18:31:44--  http://bootstrap.saltstack.org/
Resolving bootstrap.saltstack.org (bootstrap.saltstack.org)... 74.208.29.198
Connecting to bootstrap.saltstack.org (bootstrap.saltstack.org)|74.208.29.198|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.github.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh [following]
--2013-05-14 18:31:45--  https://raw.github.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh
Resolving raw.github.com (raw.github.com)... 199.27.76.133
Connecting to raw.github.com (raw.github.com)|199.27.76.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 95188 (93K) [text/plain]
Saving to: `STDOUT'

 0% [                                       ] 0           --.-K/s               *  INFO: PIPED THROUGH sh -- Version 1.5.4
100%[======================================>] 95,188       361K/s   in 0.3s

2013-05-14 18:31:46 (361 KB/s) - written to stdout [95188/95188]


 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     i686
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.2.0-4-486
 *  INFO:   Distribution: Debian 7.0

 *  INFO: Installing minion
 *  INFO: Found function install_debian_7_git_deps
 *  INFO: Found function install_debian_7_git
 *  INFO: Found function install_debian_git_post
 *  INFO: Found function install_debian_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Running install_debian_7_git_deps()
 *  WARN: PyZMQ will be installed from PyPi in order to compile it against ZMQ3
 *  WARN: This is required for long term stable minion connections to the master.
Hit http://ftp.debian.org experimental Release.gpg
Hit http://ftp.debian.org experimental Release
Hit http://ftp.de.debian.org wheezy Release.gpg
Hit http://ftp.de.debian.org wheezy-updates Release.gpg
Hit http://ftp.debian.org experimental/main Sources/DiffIndex
Hit http://ftp.de.debian.org wheezy Release
Hit http://ftp.debian.org experimental/main i386 Packages/DiffIndex
Hit http://ftp.de.debian.org wheezy-updates Release
Hit http://security.debian.org wheezy/updates Release.gpg
Hit http://ftp.debian.org experimental/main Translation-en/DiffIndex
Hit http://ftp.de.debian.org wheezy/main Sources
Hit http://ftp.de.debian.org wheezy/main i386 Packages
Hit http://ftp.de.debian.org wheezy/main Translation-en
Hit http://ftp.de.debian.org wheezy-updates/main Sources
Hit http://security.debian.org wheezy/updates Release
Hit http://ftp.de.debian.org wheezy-updates/main i386 Packages
Hit http://ftp.de.debian.org wheezy-updates/main Translation-en
Hit http://security.debian.org wheezy/updates/main Sources
Hit http://security.debian.org wheezy/updates/main i386 Packages
Hit http://security.debian.org wheezy/updates/main Translation-en
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Package libzmq3 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libzmq3' has no installation candidate
E: Unable to locate package libzmq3-dev
 * ERROR: Failed to run install_debian_7_git_deps()!!!

```

**Comment by s0undt3ch** [comment]
I think this issue is already solve but not yet in the stable branch.

Could you please try:

``` bash
wget -O - https://raw.github.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh | sh -s
```

Or for ZM3 support:

``` bash
wget -O - https://raw.github.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh | sh -s -P
```

Closing as invalid, please, **do** re-open if the above commands still fail for you.

**Comment by s0undt3ch** [comment]
And it's on Wheezy not Squeeze, right? At least that's what your logs show...

**Comment by synotna** [comment]
Apologies, it is wheezy. I'll test first thing tomorrow, thanks!

Best regards,
Antony

**Comment by s0undt3ch** [comment]
No need for the apologies, was just trying to make sure ;)

**Comment by synotna** [comment]
root@debian:~# wget -O - https://raw.github.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh | sh -s
--2013-05-15 14:09:27--  https://raw.github.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh
Resolving raw.github.com (raw.github.com)... 199.27.76.133
Connecting to raw.github.com (raw.github.com)|199.27.76.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 98560 (96K) [text/plain]
Saving to: `STDOUT'

 0% [                                       ] 0           --.-K/s               \*  INFO: PIPED THROUGH sh -- Version 1.5.4
-  WARN: Running the unstable version of bootstrap-salt.sh
-  INFO: System Information:
-  INFO:   CPU:          GenuineIntel
-  INFO:   CPU Arch:     i686
-  INFO:   OS Name:      Linux
-  INFO:   OS Version:   3.2.0-4-486
-  INFO:   Distribution: Debian 7.0
-  INFO: Installing minion
  100%[======================================>] 98,560       148K/s   in 0.7s

2013-05-15 14:09:28 (148 KB/s) - written to stdout [98560/98560]
-  INFO: Found function install_debian_7_deps
-  INFO: Found function install_debian_restart_daemons
-  INFO: Found function daemons_running
- ERROR: No installation function found. Exiting...

**Comment by s0undt3ch** [comment]
We're still having issues with both Debian 6 and 7 installations, though, this error is unfamiliar...

... Investigating.

## 

Pedro Algarvio @ phone

----- Reply message -----
De: "synotna" notifications@github.com
Para: "saltstack/salt-bootstrap" salt-bootstrap@noreply.github.com
Cc: "Pedro Algarvio" pedro@algarvio.me
Assunto: [salt-bootstrap] Debian Squeeze (#126)
Data: qua, Mai 15, 2013 13:09
root@debian:~# wget -O - https://raw.github.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh | sh -s

--2013-05-15 14:09:27--  https://raw.github.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh

Resolving raw.github.com (raw.github.com)... 199.27.76.133

Connecting to raw.github.com (raw.github.com)|199.27.76.133|:443... connected.

HTTP request sent, awaiting response... 200 OK

Length: 98560 (96K) [text/plain]

Saving to: `STDOUT' 

0% [                                       ] 0           --.-K/s               \*  INFO: PIPED THROUGH sh -- Version 1.5.4 

WARN: Running the unstable version of bootstrap-salt.sh 
INFO: System Information: 
INFO:   CPU:          GenuineIntel 
INFO:   CPU Arch:     i686 
INFO:   OS Name:      Linux 
INFO:   OS Version:   3.2.0-4-486 
INFO:   Distribution: Debian 7.0 
INFO: Installing minion

100%[======================================>] 98,560       148K/s   in 0.7s 
2013-05-15 14:09:28 (148 KB/s) - written to stdout [98560/98560] 

INFO: Found function install_debian_7_deps 
INFO: Found function install_debian_restart_daemons 
INFO: Found function daemons_running 
ERROR: No installation function found. Exiting... 

&mdash;

**Comment by synotna** [comment]
Looks like you fixed those issues!
-  INFO: Salt installed!

**Comment by s0undt3ch** [comment]
Nice!
