### ISSUE TITLE
Consider raising minimal apache-libcloud version to 2.0.0

### ISSUE THREAD

**Issue by max-arnold** [saltstack/salt-bootstrap#1290]
### Description of Issue/Question

`salt/modules/libcloud_*.py` depend on `apache-libcloud>=2.0.0`, so please consider bumping the pinned version number from 0.14.0 https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L253.to 2.0.0 https://github.com/saltstack/salt/blob/develop/salt/modules/libcloud_dns.py#L43

See https://github.com/saltstack/salt/pull/50296#pullrequestreview-169774921 for more details.

**Comment by rallytime** [comment]
Hi @max-arnold - There are other files in Salt that depend on the 0.14 version [see here](https://github.com/saltstack/salt/blob/cf8456528382ab76950d7f6b5f6249da4471f265/salt/cloud/libcloudfuncs.py#L51).

I hesitate to increase the minimum version without knowing what that effect that will have on the cloud-providers that use the `libcloudfuncs.py` file in salt. 

Furthermore, the `_LIBCLOUD_MIN_VERSION="0.14.0"` shouldn't be a pinned version, but a minimum version. We check for a `>=` value. So if a newer version is available to install via pip, then that will be installed over the minimum.

**Comment by max-arnold** [comment]
I guess it makes no sense to leave this issue open.
