### ISSUE TITLE
Bunsenlabs Debian derivative support

### ISSUE THREAD

**Issue by kevinquinnyo** [saltstack/salt-bootstrap#1299]
### Description of Issue/Question
Doesn't support Bunsenlabs debian derivative

### Setup
(Please provide relevant configs (Be sure to remove sensitive info).)
```
$> sudo find /etc/ -name \*-release -print -exec cat {} \;
/etc/lsb-release
DISTRIB_ID="BunsenLabs"
DISTRIB_DESCRIPTION="BunsenLabs GNU/Linux 9.5 (Helium)"
DISTRIB_RELEASE="9.5"
DISTRIB_CODENAME="helium"
/etc/os-release
ANSI_COLOR="0;34"
BUG_REPORT_URL="https://github.com/BunsenLabs"
HOME_URL="https://bunsenlabs.org"
ID=bunsenlabs
ID_LIKE="debian"
NAME="BunsenLabs GNU/Linux"
PRETTY_NAME="BunsenLabs GNU/Linux 9.5 (Helium)"
SUPPORT_URL="https://forums.bunsenlabs.org"
VERSION="9.5 (Helium)"
VERSION_ID="9.5"
[22:52:33] ~/dev/kenv 
$> command lsb_release -a
No LSB modules are available.
Distributor ID:	BunsenLabs
Description:	BunsenLabs GNU/Linux 9.5 (Helium)
Release:	9.5
Codename:	helium
```
### Steps to Reproduce Issue
(Include debug logs if possible, `bootstrap-salt.sh -D`.)
Use this OS, and try the commands listed here:
https://docs.saltstack.com/en/latest/topics/tutorials/quickstart.html#bootstrap-salt-minion

Which are at the time of writing:
```
curl -L https://bootstrap.saltstack.com -o bootstrap_salt.sh
sudo sh bootstrap_salt.sh
```
### Versions and Systems
(`salt --versions-report`, `bootstrap-salt.sh -v`, system type and version,
cloud/VM provider as appropriate.)

N/A

So this is pretty minor and I'm using a derivative debian distro that is probably very uncommon.  I was able to resolve this by patching the `bootstrap_salt.sh` file I downloaded via the url listed above, but it seems to be different than the `bootstrap-salt.sh` file listed in this repo.  Probably a difference in the branch/release.

Anyway, the diff that fixes this for me is simple:

```
$> diff bootstrap_salt.sh /tmp/bootstrap_salt.sh 
1428c1428
<     DEBIAN_DERIVATIVES="(cumulus_.+|devuan|kali|linuxmint|raspbian|bunsenlabs)"
---
>     DEBIAN_DERIVATIVES="(cumulus_.+|devuan|kali|linuxmint|raspbian)"
1438d1437
<     bunsenlabs_9_debian_base="9.0"
1464,1467d1462
<                 ;;
<             bunsenlabs)
<                 _major=$(echo "$DISTRO_VERSION" | sed 's/^\([0-9]*\).*/\1/g')
<                 _debian_derivative="bunsenlabs"
```

Where `/tmp/bootstrap_salt.sh` is the original file, unmodified.

I'd be happy to add a PR for this if someone can tell me where, or if someone else already knows, feel free to patch it.

Again, I know I'm using a pretty obscure debian derivative, but the fix seems pretty simple so I thought you might want it.

**Comment by kevinquinnyo** [comment]
https://github.com/saltstack/salt-bootstrap/pull/1300 I just realized the unstable develop branch is not that much different than the file I downloaded from the docs, so I went ahead and applied the same changes based on develop here.

I tested it locally and it worked, but that's all.

**Comment by kevinquinnyo** [comment]
Before I move on to what I was installing salt for in the first place, I wonder if it would be a good idea to add a command line option (with requisite warnings/caveats, etc) that let's the user "force" a distro alias + major version?

For a superficial distro like 'bunsenlabs' which is really just a rebranded plain debian with some pre-configured goodies, it would be cool if i could do something like:

```
sudo sh bootrap-salt.sh --force-dsitro=debian --force-major-version=9.0
```

Maybe?  I'd be willing to attempt that if there's interest.

**Comment by Ch3LL** [comment]
I think that would be a great idea if its easy to implement :) also thanks for the PR! We greatly appreciate it
