### ISSUE TITLE
SUSE 15 doesn't work

### ISSUE THREAD

**Issue by damianw2** [saltstack/salt-bootstrap#1320]
bootstrap-salt.sh script doesn't work with SUSE 15.

Reproduce: bootstrap-salt.sh -D

### Versions and Systems
bootstrap-salt.sh -- Version 2018.08.15

**Comment by LuishXY** [comment]
Please see if you are running into dependency issues.
https://github.com/saltstack/salt-bootstrap/issues/1254#issue-339908362

**Comment by smarlowucf** [comment]
This is still an issue with latest bootstrap script:

```
INFO: Installing minion
INFO: Found function config_salt
INFO: Found function preseed_master
INFO: Found function daemons_running
INFO: Found function install_suse_check_services
ERROR: No dependencies installation function found. Exiting...
```

**Comment by claudekenni** [comment]
same here with SLES15 not OpenSuSE. 
The codeblock for SLES15 is missing.

I guess it would need something like this 

https://github.com/saltstack/salt-bootstrap/blob/2c628c59d480baca0f66b4e7699b198c48ed2d9e/bootstrap-salt.sh#L6130-L6162

**Comment by noelmcloughlin** [comment]
Happens on Tumbleweed
