### ISSUE TITLE
chokes on Debian 7 / wheezy with madduck.net packages

### ISSUE THREAD

**Issue by jedd** [saltstack/salt-bootstrap#133]
Experimentation so far suggests Debian 7 / wheezy is content with a sources.list.d fragment like this:

 deb http://debian.saltstack.com/debian unstable main

 I'm unsure how we feel about using packages with the appellation of unstable (though these do appear to be functionally stable, 0.15.x releases)

 Anyway,  output follows showing Rackspace salt-cloud 0.8.8 run, and updated salt-bootstrap script.

```
root@admin:~# salt-cloud -p debian jeddi_deb --keep-tmp
[INFO    ] Configuration file path: /etc/salt/cloud                                                    
[INFO    ] salt-cloud starting                                                                         
[INFO    ] Creating Cloud VM jeddi_deb                                                                     
[INFO    ] Rendering deploy script: /usr/local/lib/python2.7/dist-packages/saltcloud/deploy/Debian.sh      
Warning: Permanently added '162.13.0.140' (ECDSA) to the list of known hosts.                              
Warning: Permanently added '162.13.0.140' (ECDSA) to the list of known hosts.                              
Warning: Permanently added '162.13.0.140' (ECDSA) to the list of known hosts.                                
deb http://backports.debian.org/debian-backports squeeze-backports main                                      
deb http://debian.madduck.net/repo squeeze-backports main                                                    
OK                                                                                                             
Get:1 http://security.debian.org wheezy/updates Release.gpg [836 B]                                            
Get:2 http://debian.madduck.net squeeze-backports Release.gpg [836 B]                                          
Get:3 http://security.debian.org wheezy/updates Release [102 kB]                                               
Get:4 http://debian.madduck.net squeeze-backports Release [13.4 kB]                                            
Get:5 http://backports.debian.org squeeze-backports Release.gpg [1,571 B]                                      
Get:6 http://backports.debian.org squeeze-backports Release [109 kB]                                           
Get:7 http://backports.debian.org squeeze-backports/main amd64 Packages [381 kB]                               
Get:8 http://debian.madduck.net squeeze-backports/main amd64 Packages [3,525 B]                                 
Hit http://mirror.rackspace.com wheezy Release.gpg                                                              
Get:9 http://backports.debian.org squeeze-backports/main Translation-en [243 kB]                                
Get:10 http://security.debian.org wheezy/updates/main Sources [10.8 kB]                                          
Get:11 http://security.debian.org wheezy/updates/main amd64 Packages [13.4 kB]                                   
Get:12 http://security.debian.org wheezy/updates/main Translation-en [11.3 kB]                                   
Ign http://debian.madduck.net squeeze-backports/main Translation-en_US                                           
Hit http://mirror.rackspace.com wheezy Release                                                                  
Ign http://debian.madduck.net squeeze-backports/main Translation-en                                             
Hit http://mirror.rackspace.com wheezy/main Sources                                                            
Hit http://mirror.rackspace.com wheezy/main amd64 Packages
Hit http://mirror.rackspace.com wheezy/main Translation-en
Fetched 891 kB in 1s (715 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 salt-minion : Depends: salt-common (= 0.12.1-1~bpo60+1~madduck.2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
[INFO    ] Salt installed on jeddi_deb
[INFO    ] Created Cloud VM jeddi_deb with the following values:
[INFO    ]   private_ips: []
[INFO    ]   {redacted}
[INFO    ]   image: None
[INFO    ]   _uuid: None
[INFO    ]   driver: <libcloud.compute.drivers.openstack.OpenStack_1_1_NodeDriver object at 0x2e19dd0>
[INFO    ]   state: 3
[INFO    ]   {redacted}
[INFO    ]   size: None
[INFO    ]   {redacted}
[INFO    ]   name: jeddi_deb

jeddi_deb:
    ----------
    _uuid:
        None
    driver:
    extra:
        ----------
        created:
            2013-05-16T22:33:26Z
        flavorId:
            2
        hostId:

        imageId:
            {redacted}
        key_name:
            None
        metadata:
            ----------
        password:
            {redacted}
        tenantId:
            {redacted}
        updated:
            2013-05-16T22:33:26Z
        uri:
            {redacted}
    id:
        {redacted}
    image:
        None
    name:
        jeddi_deb
    private_ips:
    public_ips:
        - {redacted}
        - {redacted}
    size:
        None
    state:
        3


```

**Comment by s0undt3ch** [comment]
@jedd `/usr/local/lib/python2.7/dist-packages/saltcloud/deploy/Debian.sh`?

Are you setting script in your cloud configuration? If so, remove it, you'll only use the bootstrap script then.

Still, the sable version of the script will also fail on Debian 7, the unstable though, should work.

**Comment by s0undt3ch** [comment]
To get the unstable version, while it's not stable, into your salt cloud setup, either _hack_ it:

```
wget -O /usr/local/lib/python2.7/dist-packages/saltcloud/deploy/bootstrap-salt.sh \
    https://raw.github.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh
```

Or, which version of salt cloud are you running?

**Comment by s0undt3ch** [comment]
Sorry, 0.8.8

**Comment by s0undt3ch** [comment]
Ok, no need to hack it, 0.8.8 supports `cloud.deploy.d`, so:

```
$ mkdir /etc/salt/cloud.deploy.d
$ wget -O /etc/salt/cloud.deploy.d/bootstrap-salt.sh \
    https://raw.github.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh
```

And your cloud configuration should **not** have `script` set.

**Comment by jedd** [comment]
If I use an Ubuntu script type, such as this:

```
ubuntu_lts:
  provider: sm-rackspace
  image: Ubuntu 12.04 LTS (Precise Pangolin)
  size: 512MB Standard Instance
  script: Ubuntu
  minion:
    grains:
      env: dev

```

... then it works.

Removing the **script: Debian** entry from my other profile:

```
debian:
  provider: sm-rackspace
  image: Debian 7 (Wheezy)
  size: 512MB Standard Instance
  # script: Debian
  # script: bootstrap-salt
  deploy: True
  minion:
    grains:
      env: dev

```

 ... generates a different kind of problem:

```
[INFO    ] Configuration file path: /etc/salt/cloud
[INFO    ] salt-cloud starting
[INFO    ] Creating Cloud VM jeddi_deb
[INFO    ] Rendering deploy script: /usr/local/lib/python2.7/dist-packages/saltcloud/deploy/bootstrap-salt.sh
Warning: Permanently added '95.138.175.69' (ECDSA) to the list of known hosts.
Warning: Permanently added '95.138.175.69' (ECDSA) to the list of known hosts.
Warning: Permanently added '95.138.175.69' (ECDSA) to the list of known hosts.
 *  INFO:  /tmp/deploy.sh -- Version 1.5.4

 *  INFO: System Information:
 *  INFO:   CPU:          AuthenticAMD
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.2.0-4-amd64
 *  INFO:   Distribution: Debian 7.0

 *  INFO: Installing minion
 *  INFO: Found function install_debian_7_deps
 *  INFO: Found function config_salt
 *  INFO: Found function preseed_master
 *  INFO: Found function install_debian_restart_daemons
 *  INFO: Found function daemons_running
 * ERROR: No installation function found. Exiting...
```

 ... it was the last line there - the **No Installation function found** -- that led me to experiment with script: settings.

I'll play with the **cloud.deploy.d** stuff now -- I hadn't spotted that before - thanks for the heads up.

**Comment by jedd** [comment]
Btw, is the intention that **cloud.deploy.d/** files, if they exist, will also override the scripts located at (in my case) **/usr/local/lib/python2.7/dist-packages/saltcloud/deploy/** - specifically the **Debian.sh** script?

I've just hacked the one in dist-packages/saltcloud/deploy .. and it works fine now, but obviously it'll conflict with any subsequent git updates.

**Comment by joehealy** [comment]
> Experimentation so far suggests Debian 7 / wheezy is content with a sources.list.d fragment like this:
> 
> deb http://debian.saltstack.com/debian unstable main
> 
> I'm unsure how we feel about using packages with the appellation of unstable (though these do appear to be functionally stable, 0.15.x releases)

You can use:

deb http://debian.saltstack.com/debian wheezy-saltstack main

**Comment by s0undt3ch** [comment]
@jedd, simply omit the script setting, the Debian, and Ubuntu and all other scripts still exist for those that have not yet migrated to the bootstrap script. Or extra/special needs with the older scripts. So:

``` yaml
ubuntu_lts:
  provider: sm-rackspace
  image: Ubuntu 12.04 LTS (Precise Pangolin)
  size: 512MB Standard Instance
  #script: Ubuntu
  minion:
    grains:
      env: dev
```

Regarding `cloud.deploy.d/` is does not override but it's first in the search path. So, any scripts in there will be found first(in comparison to the packaged scripts).

**Comment by s0undt3ch** [comment]
Also, for Debian 7, you need the dev version of the bootstrap script, will become the stable one in the next couple of days...

``` bash
$ mkdir /etc/salt/cloud.deploy.d
$ wget -O /etc/salt/cloud.deploy.d/bootstrap-salt.sh \
    https://raw.github.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh
```

**Comment by jedd** [comment]
Thank you both .. all working nicely over here now.

@s0undt3ch Could I cast a recommendation / vote that Debian 6 (squeeze) support remains in there, perhaps Debian6 and Debian7 deploy scripts being shipped concurrently?  The development branch of bootstrap-salt.sh seems to have dropped support for anything other than wheezy/sid, which a) goes against the spirit of Debian's 'long term support' policy of one year after release of the subsequent version, and b) will annoy people still needing to run both variants while they complete their migration.

**Comment by joehealy** [comment]
I'll be supporting squeeze as long as I can. I expect that bootstrap
support will remain as long as it is realistic to be deploying new squeeze
machines...

**Comment by s0undt3ch** [comment]
@jedd salt-cloud distribution deploy scripts like [Debian.sh](https://github.com/saltstack/salt-cloud/blob/develop/saltcloud/deploy/Debian.sh), [Ubuntu.sh](https://github.com/saltstack/salt-cloud/blob/develop/saltcloud/deploy/Ubuntu.sh) or [RHEL5.sh](https://github.com/saltstack/salt-cloud/blob/develop/saltcloud/deploy/RHEL5.sh), etc are deprecated and won't be further developed, unless there's a reasonable reason with a pull request for it. All those deploy scripts functionality is now packed into boostrap-salt.sh, this project, and still exist to allow the users to migrate to the bootstrap script when they see fit, and not be forced to.

Regarding the supported versions, both Debian [6](https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L1266) and [7](https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L1326) are supported and will be as long as we can deploy it, like @joehealy said.
