### ISSUE TITLE
-x python3 flag is not supported on FreeBSD

### ISSUE THREAD

**Issue by sticky-note** [saltstack/salt-bootstrap#1330]
### Description of Issue/Question
-x python3 doesn't work as expected on FreeBSD
Script doesn't take into account this flag whereas py36-salt is available on official FreBSD pkg repository

### Setup
FreeBSD ( 9|10|11|12 ) vanilla vagrant box or bare-metal install

### Steps to Reproduce Issue
Perform an install via bootstrap-salt.sh with `-x python3` flag on FreeBSD ( 9|10|11|12 ) without `py36-salt` already installed.

### Versions and Systems
All supported FreeBSD versions.
All bootstrap-salt.sh versions.

A simple `pkg install py36-salt` should work as expected on FreeBSD ( 10|11|12 ).
No tested yet on FreeBSD >= 9.1 && < 10

Relevant lines are:
L5214: ... `py27-yaml` ...
L5245: ... `py-salt`...
L5249: ... `lang/python` ...
L5255: ... `www/py-requests` ...
L5263: ... `www/py-tornado4` ...
L5307 & L5313 & L5322 ( & L5332 -> #1329 ): ... `sysutils/py-salt`
L5340: ... `python2` ...
L5364: ... `"https://raw.githubusercontent.com/freebsd/freebsd-ports/master/sysutils/py-salt/files/${script}.in"` ...

And maybe more

**Comment by gtmanfred** [comment]
This will be a feature request, and will need to be fixed by the community.  The salt core team only implemented -x python3 for ubuntu, debian, centos and fedora (git installations) 

https://github.com/saltstack/salt-bootstrap#python-3-support
