### ISSUE TITLE
Typos in usage text

### ISSUE THREAD

**Issue by wolfpackmars2** [saltstack/salt-bootstrap#1331]
### Description of Issue/Question
bootstrap-salt.sh -h shows ${BS_FALSE} as default for -d option

### Setup
N/A

### Steps to Reproduce Issue
sh bootstrap-salt.sh -h

### Versions and Systems
develop

**Comment by s0undt3ch** [comment]
It has been a while since I wrote that, but the idea is to actually show the env variable name, not the value, to suggest how you can tweak it.

**Comment by wolfpackmars2** [comment]
Closed PR - works as intended.
