### ISSUE TITLE
Bootstrap for SUSE 15 needs updated

### ISSUE THREAD

**Issue by doesitblend** [saltstack/salt-bootstrap#1336]
### Description of Issue/Question
If I try to install Salt on SLES 15 using the option on the website titled "Bootstrap - Multi-Platform", I get the following error:
"awk: fatal: cannot open file `/etc/SuSE-release' for reading (No such file or directory)"

This error occurs because as of SLES 15, /etc/SuSE-release has been removed in favor of /etc/os-release.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
try to run the bootstrap script to install Salt on SUSE Leap 15.

### Versions Report
Unable to provide since Salt is not installed.

SUSE Leap 15.

**Comment by Ch3LL** [comment]
I'm closing here as this is a bootstrap issue i transferred it to the salt-bootstrap repo. thanks

**Comment by Ch3LL** [comment]
i got a bit confused heh sorry this is the bootsrap repo. The transfer issue has changed a bit how they do it in Github.

**Comment by Ch3LL** [comment]
@doesitblend can you provide the bootstrap version. You can run `bootstrap-salt.sh -v` to provide this information.

Also can you paste the exact command you are running when you run into this issue?

**Comment by claudekenni** [comment]
+1
There is no SLES 15 block in the bootstrap script like this one for SLES12

https://github.com/saltstack/salt-bootstrap/blob/2c628c59d480baca0f66b4e7699b198c48ed2d9e/bootstrap-salt.sh#L6130-L6162

```
sh bootstrap-salt.sh -v
bootstrap.sh -- Version 2019.02.27
```
