### ISSUE TITLE
Need to patch bootstrap with support for Tornado4 on Debian 10 and Redhat 8 for Salt 2019.2

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt-bootstrap#1360]
### Description of Issue/Question
Debian 10 and Redhat 8 utilize Python 3 and Tornado v5.x, which Salt 2019.2 branch cannot handle.  For the Salt 2019.2 branch packages, Salt has been patched to allow it to function with Tornado4, supplied on Debian 10, and will be available as a package on Redhat 8 from SaltStack.

Need to have bootstrap on these platforms to do similar as the packages for Salt 2019.2 branch.

This will not be an issue with the Neon release since Salt will have support for Tornado v5.x .

**Comment by tjyang** [comment]
Please [address centos 8 bootstrap](https://github.com/saltstack/salt-bootstrap/issues/1371) issue also.

**Comment by dmurphy18** [comment]
@tjyang will treat Redhat 8 and Centos 8 similarly

**Comment by dmurphy18** [comment]
Need to check support for Amazon Linux 2 on Python 2 and Python 3

**Comment by dmurphy18** [comment]
see also https://github.com/saltstack/salt-bootstrap/issues/1353 for stable fix, for git install patch file for Debian 10 and Redhat 8 to use Tornado4 https://github.com/saltstack/salt-pack-py3/blob/develop/file_roots/pkg/salt/2019_2_1/rhel8/sources/salt-py3-2019.2.1-tornado4.patch

(Debian 10 is built/packaged with quilt as part of spec file, raw patch file is above)

**Comment by Ch3LL** [comment]
with the release of 2019.2.2 i tested on debian 10 and it setup the appropriate repo.saltstack.com repo and installed the appropriate tornado package:

```
root@buster:~# salt --versions
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.3 (default, Apr  3 2019, 05:39:12)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10.0 
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-5-amd64
         system: Linux
        version: debian 10.0 
```

so as far as i can see we do not need to update the script for debian10 stable installs

**Comment by Ch3LL** [comment]
git install on debian 10 is failing here:

```
+ python3 setup.py --salt-config-dir=/etc/salt --salt-cache-dir=/var/cache/salt install --install-layout=deb
Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    import distutils.dist
ModuleNotFoundError: No module named 'distutils.dist'
+ return 1
+ echoerror 'Failed to run install_debian_git()!!!'
+ printf '\033[1;31m * ERROR\033[0m: %s\n' 'Failed to run install_debian_git()!!!'
 * ERROR: Failed to run install_debian_git()!!!
```

looking into this now

**Comment by Ch3LL** [comment]
fixed also by https://github.com/saltstack/salt-bootstrap/pull/1380
and https://github.com/saltstack/salt-bootstrap/pull/1378
