### ISSUE TITLE
Epel repo regular expression incorrect syntax

### ISSUE THREAD

**Issue by kondotak** [saltstack/salt-bootstrap#1368]
Line 3675: if yum repolist | grep -q "^[!]\\?${_EPEL_REPO}/"; then

The regular expression "^[!]\\?${_EPEL_REPO}/" will never find a match because it has an extra slash at the end.  I removed slash on the salt master's bootstrap-salt.sh that it copies over to minion when using salt-cloud to create minion and it now successfully finds the alternate repo specified in the env_var BS_EPEL_REPO

suggest:

change: 
if yum repolist | grep -q "^[!]\\?${_EPEL_REPO}/"; then

to:
if yum repolist | grep -q "^[!]\\?${_EPEL_REPO}"; then

![image](https://user-images.githubusercontent.com/17506502/64498026-62fe7180-d280-11e9-9d20-96650b603d6d.png)

![image](https://user-images.githubusercontent.com/17506502/64498015-537f2880-d280-11e9-8ff0-af288bce1d71.png)

**Comment by vutny** [comment]
That extra slash was added for some parsing safety because previously `yum repolist` command showed EPEL repo entries with arch suffix like this:
```
epel/x86-64
```
To be on a safe side, the trailing slash could be substituted with `\W` expression (non-alphanumeric character).

Would you mind to submit a PR, @kondotak ?

**Comment by bryceml** [comment]
I marked this Info Needed since we need to know what the correct behavior is and if @kondotak is willing to open a pr.

**Comment by noelmcloughlin** [comment]
I encountered the same problem (trying to work around a different issue).
```
+ yum repolist
+ grep -q '^[!]\?base/'
```

**Comment by dmurphy18** [comment]
@kondotak Closing this due to age (2019), and probably Python 2.7 and RHEL 6 ro 7 which are both EOL.  Please feel free to reopen if other matters relevant to this issue come to light.
