### ISSUE TITLE
Bootstrap fails on raspbian debian buster 10 lite

### ISSUE THREAD

**Issue by DirkLaurenz** [saltstack/salt-bootstrap#1372]
### Description of Issue/Question
Bootstrap fails on raspbian debian 10

### Setup
clean debian 10 buster raspbian lite install

### Steps to Reproduce Issue
root@bh01:~# ./bootstrap-salt.sh -A salt01 -i bh01
 *  INFO: Running version: 2019.05.20
 *  INFO: Executed by: /bin/sh
 *  INFO: Command line: './bootstrap-salt.sh -A salt01 -i bh01'

 *  INFO: System Information:
 *  INFO:   CPU:          :
 *  INFO:   CPU Arch:     armv7l
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   4.19.57-v7+
 *  INFO:   Distribution: Raspbian 10

 *  INFO: Installing minion
 *  INFO: Found function config_salt
 *  INFO: Found function preseed_master
 *  INFO: Found function daemons_running
 * ERROR: No dependencies installation function found. Exiting...

(Include debug logs if possible, `bootstrap-salt.sh -D`.)
root@bh01:~# ./bootstrap-salt.sh -D
 *  INFO: Running version: 2019.05.20
 *  INFO: Executed by: /bin/sh
 *  INFO: Command line: './bootstrap-salt.sh -D'

 *  INFO: System Information:
 *  INFO:   CPU:          :
 *  INFO:   CPU Arch:     armv7l
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   4.19.57-v7+
 *  INFO:   Distribution: Raspbian 10

 * DEBUG: Binaries will be searched using the following $PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
 *  INFO: Installing minion
 * DEBUG: install_raspbian_10_stable_deps not found....
 * DEBUG: install_raspbian_10_deps not found....
 * DEBUG: install_raspbian_stable_deps not found....
 * DEBUG: install_raspbian_deps not found....
 * DEBUG: DEPS_INSTALL_FUNC=null
 * DEBUG: config_raspbian_10_stable_salt not found....
 * DEBUG: config_raspbian_10_salt not found....
 * DEBUG: config_raspbian_stable_salt not found....
 * DEBUG: config_raspbian_salt not found....
 *  INFO: Found function config_salt
 * DEBUG: CONFIG_SALT_FUNC=config_salt
 * DEBUG: preseed_raspbian_10_stable_master not found....
 * DEBUG: preseed_raspbian_10_master not found....
 * DEBUG: preseed_raspbian_stable_master not found....
 * DEBUG: preseed_raspbian_master not found....
 *  INFO: Found function preseed_master
 * DEBUG: PRESEED_MASTER_FUNC=preseed_master
 * DEBUG: install_raspbian_10_stable not found....
 * DEBUG: install_raspbian_stable not found....
 * DEBUG: INSTALL_FUNC=null
 * DEBUG: install_raspbian_10_stable_post not found....
 * DEBUG: install_raspbian_10_post not found....
 * DEBUG: install_raspbian_stable_post not found....
 * DEBUG: install_raspbian_post not found....
 * DEBUG: POST_INSTALL_FUNC=null
 * DEBUG: install_raspbian_10_stable_restart_daemons not found....
 * DEBUG: install_raspbian_10_restart_daemons not found....
 * DEBUG: install_raspbian_stable_restart_daemons not found....
 * DEBUG: install_raspbian_restart_daemons not found....
 * DEBUG: STARTDAEMONS_INSTALL_FUNC=null
 * DEBUG: daemons_running_raspbian_10_stable not found....
 * DEBUG: daemons_running_raspbian_10 not found....
 * DEBUG: daemons_running_raspbian_stable not found....
 * DEBUG: daemons_running_raspbian not found....
 *  INFO: Found function daemons_running
 * DEBUG: DAEMONS_RUNNING_FUNC=daemons_running
 * DEBUG: install_raspbian_10_stable_check_services not found....
 * DEBUG: install_raspbian_10_check_services not found....
 * DEBUG: install_raspbian_stable_check_services not found....
 * DEBUG: install_raspbian_check_services not found....
 * DEBUG: CHECK_SERVICES_FUNC=null
 * ERROR: No dependencies installation function found. Exiting...
 * DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe
 * DEBUG: Removing the temporary apt error file /tmp/apt_error.zcIv
 * DEBUG: Killing logging pipe tee's with pid(s): 765

### Versions and Systems
root@bh01:~# ./bootstrap-salt.sh -v
./bootstrap-salt.sh -- Version 2019.05.20

Raspberry PI 3+
raspbian buster lite

**Comment by dmurphy18** [comment]
@DirkLaurenz Closing this since Raspbian and Debian 10 are EOL and no longer supported
