### ISSUE TITLE
fix bootstrap.sh for FreeBSD

### ISSUE THREAD

**Issue by kgbsd** [saltstack/salt-bootstrap#1377]
### Description of Issue/Question
https://github.com/saltstack/salt-bootstrap/pull/1376
bootstrap FreeBSD did not work, failed with logic and dependency hell
FreeBSD has py36-salt packages which handle all dependencies, etc - simple as pkg install -y py36-salt and then enabling it.
Don't need dependency or git hacks - leave it for ports/packages to be managed properly.

### Setup
Fresh install of FreeBSD vm in google cloud, but I'm sure same issue for anywhere.

### Steps to Reproduce Issue
try to bootstrap FreeBSD vm.

### Versions and Systems
py36-salt-2019.2.0_2
/usr/local/lib/python3.6/site-packages/salt/cloud/deploy/bootstrap-salt.sh -- Version 2019.01.08

**Comment by sticky-note** [comment]
A workaround to get it work:
```
pkg install -y ca_root_nss py36-salt 
```
before bootstrapping  with the bootstrap.sh

**Comment by vutny** [comment]
I guess this was fixed by #1376 and could be closed.

Ping @s0undt3ch @Ch3LL

**Comment by s0undt3ch** [comment]
Thank You @vutny!
