### ISSUE TITLE
centos8 : No match for argument: python34-PyYAML

### ISSUE THREAD

**Issue by gaetanquentin** [saltstack/salt-bootstrap#1379]
### Description of Issue/Question
pyyaml package not correctly identified
bootstrap fails

### Setup
lxd 3.18
packer 
centos 8.0
sudo sh bootstrap.sh -x python3 stable 2019.2.2

### Steps to Reproduce Issue
- install centos8 in lxd for example
- download bootstrap
- sudo sh bootstrap.sh -x python3 stable 2019.2.2

Error
------------
    centos-8-salt-2019-2-pfi: Extra Packages for Enterprise Linux 8 - x86_64  1.1 MB/s | 3.1 MB     00:02
    centos-8-salt-2019-2-pfi: SaltStack archive/2019.2.2 Release Channel for  162 kB/s | 225 kB     00:01
    centos-8-salt-2019-2-pfi: Package chkconfig-1.11-1.el8.x86_64 is already installed.
    centos-8-salt-2019-2-pfi: No match for argument: python34-PyYAML
    centos-8-salt-2019-2-pfi: Error: Unable to find a match
    centos-8-salt-2019-2-pfi:  * ERROR: Failed to run install_centos_stable_deps()!!!

the real package name on centos 8 is python3-pyyaml.x86_64

**Comment by Ch3LL** [comment]
can you see if https://github.com/saltstack/salt-bootstrap/pull/1380 fixes your issue please?

centos 8 bootstrap stable tests are now passing with that fix.

**Comment by gaetanquentin** [comment]
pb still here:
```
[root@packer-centos-8-salt-2019-2-pfi ~]# sudo sh /tmp/install_salt.sh -x python3  git develop
 *  INFO: Running version: 2019.10.03
 *  INFO: Executed by: sh
 *  INFO: Command line: '/tmp/install_salt.sh -x python3 git develop'
 *  INFO: Detected -x option. Using python3 to install Salt.

 *  INFO: System Information:
 *  INFO:   CPU:          AuthenticAMD
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   4.15.0-55-generic
 *  INFO:   Distribution: CentOS 8.0

 *  INFO: Installing minion
 *  INFO: Found function install_centos_git_deps
 *  INFO: Found function config_salt
 *  INFO: Found function preseed_master
 *  INFO: Found function install_centos_git
 *  INFO: Found function install_centos_git_post
 *  INFO: Found function install_centos_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Found function install_centos_check_services
 *  INFO: Running install_centos_git_deps()
Last metadata expiration check: 0:01:46 ago on Mon Nov  4 13:50:49 2019.
warning: /var/tmp/rpm-tmp.a2k4pD: Header V3 RSA/SHA256 Signature, key ID 2f86d6a1: NOKEY
Retrieving https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
Verifying...                          ########################################
Preparing...                          ########################################
Updating / installing...
epel-release-8-7.el8                  ########################################
Cache was expired
20 files removed
CentOS-8 - AppStream                            3.5 MB/s | 6.3 MB     00:01    
CentOS-8 - Base                                  13 MB/s | 7.9 MB     00:00    
CentOS-8 - Extras                               7.5 kB/s | 2.1 kB     00:00    
Extra Packages for Enterprise Linux 8 - x86_64  1.9 MB/s | 3.2 MB     00:01    
SaltStack latest Release Channel for RHEL/CentO  94 kB/s | 225 kB     00:02    
Package chkconfig-1.11-1.el8.x86_64 is already installed.
No match for argument: python34-PyYAML
Error: Unable to find a match
 * ERROR: Failed to run install_centos_git_deps()!!!
[root@packer-centos-8-salt-2019-2-pfi ~]# yum search PyYAML
============================================================================================================ Name Matched: PyYAML ============================================================================================================
python2-pyyaml.x86_64 : YAML parser and emitter for Python
python3-pyyaml.i686 : YAML parser and emitter for Python
python3-pyyaml.x86_64 : YAML parser and emitter for Python
```

**Comment by Ch3LL** [comment]
can you clarify how you grabbed the new changes? Just want to verify you are using the file https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh  since its not released yet.

**Comment by gaetanquentin** [comment]
i got the develop branch:
sudo sh /tmp/install_salt.sh -x python3  git develop

**Comment by gaetanquentin** [comment]
ok i have understood: 

/tmp/install_salt.sh is the old bootstrap itself and contains the problem: it is installed by packer.
i though that using these args ( -x python3  git develop)  would bypass the script and download fresh things

so i have refreshed the script
and now the problem it this:
Installed:
[ ...]
  perl-threads-1:2.21-2.el8.x86_64                                              
  perl-threads-shared-1.58-2.el8.x86_64                                         

Complete!
 *  WARN: The git revision being installed does not match a Salt version tag. Shallow cloning disabled
Cloning into 'salt'...
Checking out files: 100% (5320/5320), done.
Switched to a new branch 'develop'
Branch 'develop' set up to track remote branch 'develop' from 'origin'.
 *  INFO: Cloning Salt's git repository succeeded
 * ERROR: You need to allow pip based installations (-P) for Tornado <5.0 in order to install Salt on Python 3

  Usage :  bootstrap-salt.sh [options] <install-type> [install-type-args]

**Comment by gaetanquentin** [comment]
so with "-P  git develop" it is ok

**Comment by Ch3LL** [comment]
yeah we had to require a pip installation to install the correct version of tornado if doing a git install. I should have clarified this, but I will update the docs to reflect this. This is only temporary until we allow salt to work with tornado version 5 and 6. Centos8 does not have a tornado 4 package for python3 available.  It does have python3-tornado4, but this requires editing the salt code to be "import tornado4" instead of "import tornado" so pip installing the package was the best temporary workaround for now.

**Comment by Ch3LL** [comment]
are you okay closing based off this information?

**Comment by gaetanquentin** [comment]
yes

**Comment by gaetanquentin** [comment]
oups: last test:
 *  INFO: Running version: 2019.11.04
 *  INFO: Executed by: sh
 *  INFO: Command line: '/tmp/install_salt.sh -x python3 -N git develop'
 *  WARN: Nothing to install or configure
