### ISSUE TITLE
Speed up git clone on bootstrap from git

### ISSUE THREAD

**Issue by marcinkuzminski** [saltstack/salt-bootstrap#138]
We've been working on optimizing speed of machine bootstrap and here are my proposals. Open fo discussion.

Instead of doing full history fetch when doing `git clone`, code should do a shallow clone with --depth=1 from my tests this increases the speed of whole operation a lot.

There's also the case when the repo is there bootstrap does git fetch, this can get a `--unshallow` flag which would update the repo with all history. This would be slower, but i think most cases you do bootstrapping on new machines only.

Another option would be to actually ditch clone totally and simply fetch salt archives on each bootstrap. That solution would get rid of the fetch totally. It has some downsides that you actually need a wget/curl on a machine to do that.

Any thoughts about that ?

**Comment by s0undt3ch** [comment]
Sorry for the long time to reply.

I'm in favor of speeding up the salt cloning process, though, salt needs it's full tags to report proper versioning.
That said, `wget` or `curl` based downloads are inappropriate since you would only get salt to report it's version like `0.15.0` and not `0.15.0-686-g234c2bd` like a git based install.

Shallow clonning would need a second step to get all tags.
Would this suite your needs?

**Comment by marcinkuzminski** [comment]
Ahh wasn't aware of version extracting based on a tags. 

A quick test showed there's little benefit from that approach:

```
time git clone https://github.com/saltstack/salt.git
Cloning into 'salt'...
git clone https://github.com/saltstack/salt.git  2.80s user 1.26s system 11% cpu 34.787 total

-------------------

echo "git clone --depth=1 https://github.com/saltstack/salt.git && cd salt && git fetch --depth=1 --tags" > fetch.sh
time fetch.sh
...
./fetch.sh  1.04s user 0.73s system 6% cpu 29.043 total

```

But i don't get why tags are needed ?

another (maybe little bit crazy) would be to use `curl https://api.github.com/repos/saltstack/salt/tags` somehow to speed up things

**Comment by s0undt3ch** [comment]
Hmm...

I've been spinning up quite a few git based machines, and cloning isn't **that** slow that we need to curl tags or some other _black magic_. It should remain simple enough that it wont break easily.

So, I guess it will stay the same.
Cool?

**Comment by marcinkuzminski** [comment]
agree, more complexity is not a better solution here. We're going to stick to a little modified version where it does a shallow clone. It's suits our needs (we're really fighting for every second in our deployment)

**Comment by s0undt3ch** [comment]
Ok, but remember that salt's version reporting will be compromised.
You'll get away fine if your checking out specific version tag, ie `v0.15.1` for example.

**Comment by marcinkuzminski** [comment]
Why is the versioning so important ?

**Comment by s0undt3ch** [comment]
In case you ran into trouble and you need to file an issue against salt, that's one of the things most important to us. That way we know what code you are running on your end. If the version you're reporting is not accurate, we might loose quite some time chasing ghosts.

**Comment by marcinkuzminski** [comment]
Then it's not a problem, because actually we're doing cloning by hash only in the bootstrap script, and upgrade it always manually. It's to risky for us to have different versions across multiple servers.

Thanks for all the feedback.

**Comment by s0undt3ch** [comment]
That's why I said you'd get away with shallow cloning a git tag, since the tag will be the version salt reports :)

**Comment by s0undt3ch** [comment]
Well, you and us :smiley:
