### ISSUE TITLE
CentOS6_x64 tag: v2018.3.4 salt-minion: ERROR: Failed to run install_centos_git()!!!

### ISSUE THREAD

**Issue by FrantisekLee** [saltstack/salt-bootstrap#1382]
### Description of Issue/Question
I have latest clean install CentOS6_x64. I only downloaded latest bootstrap-sat.sh and i wanted to install salt-minion from tag: v2018.3.4. because i still use salt-master 2018.
When i try to install latest version salt-minion without tag (v2019.2.2), everything works.
Problem is, when i want to install older salt-minion version with git parameter and tag: v2018.3.4

### Setup
[root@localhost ~]# git clone https://github.com/saltstack/salt-bootstrap.git /tmp/salt-bootstrap
Initialized empty Git repository in /tmp/salt-bootstrap/.git/
remote: Enumerating objects: 83, done.
remote: Counting objects: 100% (83/83), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 9151 (delta 51), reused 56 (delta 28), pack-reused 9068
Receiving objects: 100% (9151/9151), 3.49 MiB | 2.20 MiB/s, done.
Resolving deltas: 100% (5543/5543), done.

[root@localhost ~]# /tmp/salt-bootstrap/bootstrap-salt.sh -H https://proxy1.mycompany.sk:8080 git v2018.3.4
 *  INFO: Running version: 2019.10.03
 *  INFO: Executed by: /bin/sh
 *  INFO: Command line: '/tmp/salt-bootstrap/bootstrap-salt.sh -H https://proxy1.mycompany.sk:8080 git v2018.3.4'
 *  WARN: Running the unstable version of bootstrap-salt.sh

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   2.6.32-754.23.1.el6.x86_64
 *  INFO:   Distribution: CentOS 6.10

 *  INFO: Using http proxy https://proxy1.mycompany.sk:8080
 *  INFO: Installing minion
 *  INFO: Found function install_centos_git_deps
 *  INFO: Found function config_salt% (55/55), done.
remote: Total 9151 (delta 51), reused 56 (delta 28), pack-reused 9068
Receiving objects: 100% (9151/9151), 3.49 MiB | 2.20 MiB/s, done.
Resolving deltas: 100% (5543/5543), done.

[root@localhost ~]# /tmp/salt-bootstrap/bootstrap-salt.sh -H https://proxy1.mycompany.sk:8080 git v2018.3.4

    INFO: Running version: 2019.10.03

    INFO: Executed by: /bin/sh

 *  INFO: Found function preseed_master
 *  INFO: Found function install_centos_git
 *  INFO: Found function install_centos_git_post
 *  INFO: Found function install_centos_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Found function install_centos_check_services
 *  INFO: Running install_centos_git_deps()
warning: /var/tmp/rpm-tmp.ko0zNJ: Header V3 RSA/SHA256 Signature, key ID 0608b895: NOKEY
Retrieving https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm

Loaded plugins: fastestmirror
Cleaning repos: base epel extras saltstack updates
9 metadata files removed
3 sqlite files removed
0 metadata files removed
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: ftp.cvut.cz
 * epel: epel.besthosting.ua
 * extras: ftp.cvut.cz
 * updates: ftp.energotel.sk
Package chkconfig-1.3.49.5-1.el6.x86_64 already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package PyYAML.x86_64 0:3.10-3.1.el6 will be installed
--> Processing Dependency: libyaml-0.so.2()(64bit) for package: PyYAML-3.10-3.1.el6.x86_64
---> Package yum-utils.noarch 0:1.1.30-42.el6_10 will be installed
--> Processing Dependency: libxml2-python for package: yum-utils-1.1.30-42.el6_10.noarch
--> Running transaction check
---> Package libxml2-python.x86_64 0:2.7.6-21.el6_8.1 will be installed
---> Package libyaml.x86_64 0:0.1.3-4.el6_6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

Installing:
 PyYAML               x86_64       3.10-3.1.el6             base          157 k
 yum-utils            noarch       1.1.30-42.el6_10         updates       114 k
Installing for dependencies:
 libxml2-python       x86_64       2.7.6-21.el6_8.1         base          325 k
 libyaml              x86_64       0.1.3-4.el6_6            base           52 k

Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
Warning: RPMDB altered outside of yum.
  Installing : libxml2-python-2.7.6-21.el6_8.1.x86_64                       1/4 
  Installing : libyaml-0.1.3-4.el6_6.x86_64                                 2/4 
  Installing : PyYAML-3.10-3.1.el6.x86_64                                   3/4 
  Installing : yum-utils-1.1.30-42.el6_10.noarch                            4/4 
  Verifying  : libyaml-0.1.3-4.el6_6.x86_64                                 1/4 
  Verifying  : PyYAML-3.10-3.1.el6.x86_64                                   2/4 
  Verifying  : yum-utils-1.1.30-42.el6_10.noarch                            3/4 
  Verifying  : libxml2-python-2.7.6-21.el6_8.1.x86_64                       4/4 

Installed:
  PyYAML.x86_64 0:3.10-3.1.el6        yum-utils.noarch 0:1.1.30-42.el6_10       

Dependency Installed:
  libxml2-python.x86_64 0:2.7.6-21.el6_8.1    libyaml.x86_64 0:0.1.3-4.el6_6   

Complete!
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: ftp.cvut.cz
 * epel: epel.besthosting.ua
 * extras: ftp.cvut.cz
 * updates: ftp.energotel.sk
Package ca-certificates-2018.2.22-65.1.el6.noarch already installed and latest version
Nothing to do
 *  INFO: Git revision matches a Salt version tag, shallow cloning enabled.
Initialized empty Git repository in /tmp/git/salt/.git/
Note: checking out 'v2018.3.4'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at d0cad3e... Merge pull request #51553 from twangboy/update_libsodium
 *  INFO: Cloning Salt's git repository succeeded
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: ftp.cvut.cz
 * epel: epel.besthosting.ua
 * extras: ftp.cvut.cz
 * updates: ftp.energotel.sk
Resolving Dependencies
--> Running transaction check
---> Package m2crypto.x86_64 0:0.20.2-9.el6 will be installed
---> Package python-crypto.x86_64 0:2.0.1-22.el6 will be installed
---> Package python-futures.noarch 0:2.1.6-1.el6 will be installed
---> Package python-jinja2.x86_64 0:2.2.1-3.el6 will be installed
--> Processing Dependency: python-babel >= 0.8 for package: python-jinja2-2.2.1-3.el6.x86_64
--> Processing Dependency: python-setuptools for package: python-jinja2-2.2.1-3.el6.x86_64
---> Package python-msgpack.x86_64 0:0.4.6-1.el6 will be installed
---> Package python-requests.noarch 0:2.6.0-4.el6 will be installed
--> Processing Dependency: python-urllib3 >= 1.10.2-1 for package: python-requests-2.6.0-4.el6.noarch
--> Processing Dependency: python-chardet >= 2.2.1-1 for package: python-requests-2.6.0-4.el6.noarch
---> Package python-tornado.noarch 0:2.2.1-7.el6 will be installed
--> Processing Dependency: python-backports-ssl_match_hostname for package: python-tornado-2.2.1-7.el6.noarch
---> Package python-zmq.x86_64 0:14.3.1-1.el6 will be installed
--> Processing Dependency: libzmq.so.3()(64bit) for package: python-zmq-14.3.1-1.el6.x86_64
--> Running transaction check
---> Package python-babel.noarch 0:0.9.4-5.1.el6 will be installed
---> Package python-backports-ssl_match_hostname.noarch 0:3.4.0.2-5.el6 will be installed
--> Processing Dependency: python-backports for package: python-backports-ssl_match_hostname-3.4.0.2-5.el6.noarch
---> Package python-chardet.noarch 0:2.2.1-1.el6 will be installed
---> Package python-setuptools.noarch 0:0.6.10-4.el6_9 will be installed
---> Package python-urllib3.noarch 0:1.10.2-3.el6 will be installed
--> Processing Dependency: python-six for package: python-urllib3-1.10.2-3.el6.noarch
---> Package zeromq3.x86_64 0:3.2.5-1.el6 will be installed
--> Processing Dependency: libpgm-5.1.so.0()(64bit) for package: zeromq3-3.2.5-1.el6.x86_64
--> Running transaction check
---> Package openpgm.x86_64 0:5.1.118-3.el6 will be installed
---> Package python-backports.x86_64 0:1.0-5.el6 will be installed
---> Package python-six.noarch 0:1.9.0-2.el6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

Installing:
 m2crypto                              x86_64   0.20.2-9.el6       base   471 k
 python-crypto                         x86_64   2.0.1-22.el6       base   159 k
 python-futures                        noarch   2.1.6-1.el6        epel    30 k
 python-jinja2                         x86_64   2.2.1-3.el6        base   466 k
 python-msgpack                        x86_64   0.4.6-1.el6        epel    69 k
 python-requests                       noarch   2.6.0-4.el6        base    96 k
 python-tornado                        noarch   2.2.1-7.el6        epel   433 k
 python-zmq                            x86_64   14.3.1-1.el6       epel   467 k
Installing for dependencies:
 openpgm                               x86_64   5.1.118-3.el6      epel   165 k
 python-babel                          noarch   0.9.4-5.1.el6      base   1.4 M
 python-backports                      x86_64   1.0-5.el6          base   5.5 k
 python-backports-ssl_match_hostname   noarch   3.4.0.2-5.el6      base    12 k
 python-chardet                        noarch   2.2.1-1.el6        base   230 k
 python-setuptools                     noarch   0.6.10-4.el6_9     base   336 k
 python-six                            noarch   1.9.0-2.el6        base    28 k
 python-urllib3                        noarch   1.10.2-3.el6       base   103 k
 zeromq3                               x86_64   3.2.5-1.el6        epel   338 k

Transaction Summary

warning: rpmts_HdrFromFdno: Header V3 RSA/SHA256 Signature, key ID 0608b895: NOKEY
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
Importing GPG key 0x0608B895:
 Userid : EPEL (6) <epel@fedoraproject.org>
 Package: epel-release-6-8.noarch (installed)
 From   : /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : python-backports-1.0-5.el6.x86_64                           1/17 
  Installing : python-backports-ssl_match_hostname-3.4.0.2-5.el6.noarch    2/17 
  Installing : python-babel-0.9.4-5.1.el6.noarch                           3/17 
  Installing : python-setuptools-0.6.10-4.el6_9.noarch                     4/17 
  Installing : python-chardet-2.2.1-1.el6.noarch                           5/17 
  Installing : python-six-1.9.0-2.el6.noarch                               6/17 
  Installing : python-urllib3-1.10.2-3.el6.noarch                          7/17 
  Installing : openpgm-5.1.118-3.el6.x86_64                                8/17 
  Installing : zeromq3-3.2.5-1.el6.x86_64                                  9/17 
  Installing : python-zmq-14.3.1-1.el6.x86_64                             10/17 
  Installing : python-requests-2.6.0-4.el6.noarch                         11/17 
  Installing : python-jinja2-2.2.1-3.el6.x86_64                           12/17 
  Installing : python-tornado-2.2.1-7.el6.noarch                          13/17 
  Installing : python-futures-2.1.6-1.el6.noarch                          14/17 
  Installing : python-crypto-2.0.1-22.el6.x86_64                          15/17 
  Installing : m2crypto-0.20.2-9.el6.x86_64                               16/17 
  Installing : python-msgpack-0.4.6-1.el6.x86_64                          17/17 
  Verifying  : python-tornado-2.2.1-7.el6.noarch                           1/17 
  Verifying  : openpgm-5.1.118-3.el6.x86_64                                2/17 
  Verifying  : python-jinja2-2.2.1-3.el6.x86_64                            3/17 
  Verifying  : python-six-1.9.0-2.el6.noarch                               4/17 
  Verifying  : python-msgpack-0.4.6-1.el6.x86_64                           5/17 
  Verifying  : python-chardet-2.2.1-1.el6.noarch                           6/17 
  Verifying  : python-setuptools-0.6.10-4.el6_9.noarch                     7/17 
  Verifying  : m2crypto-0.20.2-9.el6.x86_64                                8/17 
  Verifying  : python-babel-0.9.4-5.1.el6.noarch                           9/17 
  Verifying  : python-zmq-14.3.1-1.el6.x86_64                             10/17 
  Verifying  : python-requests-2.6.0-4.el6.noarch                         11/17 
  Verifying  : python-crypto-2.0.1-22.el6.x86_64                          12/17 
  Verifying  : zeromq3-3.2.5-1.el6.x86_64                                 13/17 
  Verifying  : python-urllib3-1.10.2-3.el6.noarch                         14/17 
  Verifying  : python-backports-ssl_match_hostname-3.4.0.2-5.el6.noarch   15/17 
  Verifying  : python-futures-2.1.6-1.el6.noarch                          16/17 
  Verifying  : python-backports-1.0-5.el6.x86_64                          17/17 

Installed:
  m2crypto.x86_64 0:0.20.2-9.el6         python-crypto.x86_64 0:2.0.1-22.el6    
  python-futures.noarch 0:2.1.6-1.el6    python-jinja2.x86_64 0:2.2.1-3.el6     
  python-msgpack.x86_64 0:0.4.6-1.el6    python-requests.noarch 0:2.6.0-4.el6   
  python-tornado.noarch 0:2.2.1-7.el6    python-zmq.x86_64 0:14.3.1-1.el6       

Dependency Installed:
  openpgm.x86_64 0:5.1.118-3.el6                                                
  python-babel.noarch 0:0.9.4-5.1.el6                                           
  python-backports.x86_64 0:1.0-5.el6                                           
  python-backports-ssl_match_hostname.noarch 0:3.4.0.2-5.el6                    
  python-chardet.noarch 0:2.2.1-1.el6                                           
  python-setuptools.noarch 0:0.6.10-4.el6_9                                     
  python-six.noarch 0:1.9.0-2.el6                                               
  python-urllib3.noarch 0:1.10.2-3.el6                                          
  zeromq3.x86_64 0:3.2.5-1.el6                                                  

Complete!
 *  INFO: Running config_salt()
 *  INFO: Running install_centos_git()
2018.3.4
Traceback (most recent call last):
  File "setup.py", line 1256, in <module>
    setup(distclass=SaltDistribution)
  File "/usr/lib64/python2.6/distutils/core.py", line 113, in setup
    _setup_distribution = dist = klass(attrs)
  File "setup.py", line 910, in __init__
    self.update_metadata()
  File "setup.py", line 916, in update_metadata
    attrvalue = getattr(self, attrname, None)
  File "setup.py", line 1020, in _property_install_requires
    install_requires = _parse_requirements_file(SALT_REQS)
  File "setup.py", line 231, in _parse_requirements_file
    if not _check_ver(platform.python_version(), _parse_op(op), _parse_ver(ver)):
  File "setup.py", line 207, in _check_ver
    return getattr(operator, '__{}__'.format(op))(pyver, wanted)
ValueError: zero length field name in format
 * ERROR: Failed to run install_centos_git()!!!

### Steps to Reproduce Issue
[root@localhost ~]# /tmp/salt-bootstrap/bootstrap-salt.sh -D -H https://proxy1.mycompany.sk:8080 git v2018.3.4
 *  INFO: Running version: 2019.10.03
 *  INFO: Executed by: /bin/sh
 *  INFO: Command line: '/tmp/salt-bootstrap/bootstrap-salt.sh -D -H https://proxy1.mycompany.sk:8080 git v2018.3.4'
 *  WARN: Running the unstable version of bootstrap-salt.sh

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   2.6.32-754.23.1.el6.x86_64
 *  INFO:   Distribution: CentOS 6.10

 * DEBUG: Binaries will be searched using the following $PATH: /usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
 *  INFO: Using http proxy https://proxy1.mycompany.sk:8080
 *  INFO: Installing minion
 * DEBUG: install_centos_6_git_deps not found....
 * DEBUG: install_centos_6_10_git_deps not found....
 * DEBUG: install_centos_6_deps not found....
 * DEBUG: install_centos_6_10_deps not found....
 *  INFO: Found function install_centos_git_deps
 * DEBUG: DEPS_INSTALL_FUNC=install_centos_git_deps
 * DEBUG: config_centos_6_git_salt not found....
 * DEBUG: config_centos_6_10_git_salt not found....
 * DEBUG: config_centos_6_salt not found....
 * DEBUG: config_centos_6_10_salt not found....
 * DEBUG: config_centos_git_salt not found....
 * DEBUG: config_centos_salt not found....
 *  INFO: Found function config_salt
 * DEBUG: CONFIG_SALT_FUNC=config_salt
 * DEBUG: preseed_centos_6_git_master not found....
 * DEBUG: preseed_centos_6_10_git_master not found....
 * DEBUG: preseed_centos_6_master not found....
 * DEBUG: preseed_centos_6_10_master not found....
 * DEBUG: preseed_centos_git_master not found....
 * DEBUG: preseed_centos_master not found....
 *  INFO: Found function preseed_master
 * DEBUG: PRESEED_MASTER_FUNC=preseed_master
 * DEBUG: install_centos_6_git not found....
 * DEBUG: install_centos_6_10_git not found....
 *  INFO: Found function install_centos_git
 * DEBUG: INSTALL_FUNC=install_centos_git
 * DEBUG: install_centos_6_git_post not found....
 * DEBUG: install_centos_6_10_git_post not found....
 * DEBUG: install_centos_6_post not found....
 * DEBUG: install_centos_6_10_post not found....
 *  INFO: Found function install_centos_git_post
 * DEBUG: POST_INSTALL_FUNC=install_centos_git_post
 * DEBUG: install_centos_6_git_restart_daemons not found....
 * DEBUG: install_centos_6_10_git_restart_daemons not found....
 * DEBUG: install_centos_6_restart_daemons not found....
 * DEBUG: install_centos_6_10_restart_daemons not found....
 * DEBUG: install_centos_git_restart_daemons not found....
 *  INFO: Found function install_centos_restart_daemons
 * DEBUG: STARTDAEMONS_INSTALL_FUNC=install_centos_restart_daemons
 * DEBUG: daemons_running_centos_6_git not found....
 * DEBUG: daemons_running_centos_6_10_git not found....
 * DEBUG: daemons_running_centos_6 not found....
 * DEBUG: daemons_running_centos_6_10 not found....
 * DEBUG: daemons_running_centos_git not found....
 * DEBUG: daemons_running_centos not found....
 *  INFO: Found function daemons_running
 * DEBUG: DAEMONS_RUNNING_FUNC=daemons_running
 * DEBUG: install_centos_6_git_check_services not found....
 * DEBUG: install_centos_6_10_git_check_services not found....
 * DEBUG: install_centos_6_check_services not found....
 * DEBUG: install_centos_6_10_check_services not found....
 * DEBUG: install_centos_git_check_services not found....
 *  INFO: Found function install_centos_check_services
 * DEBUG: CHECK_SERVICES_FUNC=install_centos_check_services
 *  INFO: Running install_centos_git_deps()
warning: /var/tmp/rpm-tmp.ub1qlw: Header V3 RSA/SHA256 Signature, key ID 0608b895: NOKEY
Retrieving https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm

Loaded plugins: fastestmirror
Cleaning repos: base epel extras saltstack updates
9 metadata files removed
3 sqlite files removed
0 metadata files removed
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: ftp.cvut.cz
 * epel: epel.besthosting.ua
 * extras: ftp.cvut.cz
 * updates: ftp.energotel.sk
Package chkconfig-1.3.49.5-1.el6.x86_64 already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package PyYAML.x86_64 0:3.10-3.1.el6 will be installed
--> Processing Dependency: libyaml-0.so.2()(64bit) for package: PyYAML-3.10-3.1.el6.x86_64
---> Package yum-utils.noarch 0:1.1.30-42.el6_10 will be installed
--> Processing Dependency: libxml2-python for package: yum-utils-1.1.30-42.el6_10.noarch
--> Running transaction check
---> Package libxml2-python.x86_64 0:2.7.6-21.el6_8.1 will be installed
---> Package libyaml.x86_64 0:0.1.3-4.el6_6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

Installing:
 PyYAML               x86_64       3.10-3.1.el6             base          157 k
 yum-utils            noarch       1.1.30-42.el6_10         updates       114 k
Installing for dependencies:
 libxml2-python       x86_64       2.7.6-21.el6_8.1         base          325 k
 libyaml              x86_64       0.1.3-4.el6_6            base           52 k

Transaction Summary

Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
Warning: RPMDB altered outside of yum.
  Installing : libxml2-python-2.7.6-21.el6_8.1.x86_64                       1/4 
  Installing : libyaml-0.1.3-4.el6_6.x86_64                                 2/4 
  Installing : PyYAML-3.10-3.1.el6.x86_64                                   3/4 
  Installing : yum-utils-1.1.30-42.el6_10.noarch                            4/4 
  Verifying  : libyaml-0.1.3-4.el6_6.x86_64                                 1/4 
  Verifying  : PyYAML-3.10-3.1.el6.x86_64                                   2/4 
  Verifying  : yum-utils-1.1.30-42.el6_10.noarch                            3/4 
  Verifying  : libxml2-python-2.7.6-21.el6_8.1.x86_64                       4/4 

Installed:
  PyYAML.x86_64 0:3.10-3.1.el6        yum-utils.noarch 0:1.1.30-42.el6_10       

Dependency Installed:
  libxml2-python.x86_64 0:2.7.6-21.el6_8.1    libyaml.x86_64 0:0.1.3-4.el6_6   

Complete!
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: ftp.cvut.cz
 * epel: epel.besthosting.ua
 * extras: ftp.cvut.cz
 * updates: ftp.energotel.sk
Package ca-certificates-2018.2.22-65.1.el6.noarch already installed and latest version
Nothing to do
 * DEBUG: Installed git version: 1.7.1
 *  INFO: Git revision matches a Salt version tag, shallow cloning enabled.
 * DEBUG: Shallow cloning not possible. Required git version not met.
Initialized empty Git repository in /tmp/git/salt/.git/
 * DEBUG: Checking out v2018.3.4
Note: checking out 'v2018.3.4'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at d0cad3e... Merge pull request #51553 from twangboy/update_libsodium
 *  INFO: Cloning Salt's git repository succeeded
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: ftp.cvut.cz
 * epel: epel.besthosting.ua
 * extras: ftp.cvut.cz
 * updates: ftp.energotel.sk
Resolving Dependencies
--> Running transaction check
---> Package m2crypto.x86_64 0:0.20.2-9.el6 will be installed
---> Package python-crypto.x86_64 0:2.0.1-22.el6 will be installed
---> Package python-futures.noarch 0:2.1.6-1.el6 will be installed
---> Package python-jinja2.x86_64 0:2.2.1-3.el6 will be installed
--> Processing Dependency: python-babel >= 0.8 for package: python-jinja2-2.2.1-3.el6.x86_64
--> Processing Dependency: python-setuptools for package: python-jinja2-2.2.1-3.el6.x86_64
---> Package python-msgpack.x86_64 0:0.4.6-1.el6 will be installed
---> Package python-requests.noarch 0:2.6.0-4.el6 will be installed
--> Processing Dependency: python-urllib3 >= 1.10.2-1 for package: python-requests-2.6.0-4.el6.noarch
--> Processing Dependency: python-chardet >= 2.2.1-1 for package: python-requests-2.6.0-4.el6.noarch
---> Package python-tornado.noarch 0:2.2.1-7.el6 will be installed
--> Processing Dependency: python-backports-ssl_match_hostname for package: python-tornado-2.2.1-7.el6.noarch
---> Package python-zmq.x86_64 0:14.3.1-1.el6 will be installed
--> Processing Dependency: libzmq.so.3()(64bit) for package: python-zmq-14.3.1-1.el6.x86_64
--> Running transaction check
---> Package python-babel.noarch 0:0.9.4-5.1.el6 will be installed
---> Package python-backports-ssl_match_hostname.noarch 0:3.4.0.2-5.el6 will be installed
--> Processing Dependency: python-backports for package: python-backports-ssl_match_hostname-3.4.0.2-5.el6.noarch
---> Package python-chardet.noarch 0:2.2.1-1.el6 will be installed
---> Package python-setuptools.noarch 0:0.6.10-4.el6_9 will be installed
---> Package python-urllib3.noarch 0:1.10.2-3.el6 will be installed
--> Processing Dependency: python-six for package: python-urllib3-1.10.2-3.el6.noarch
---> Package zeromq3.x86_64 0:3.2.5-1.el6 will be installed
--> Processing Dependency: libpgm-5.1.so.0()(64bit) for package: zeromq3-3.2.5-1.el6.x86_64
--> Running transaction check
---> Package openpgm.x86_64 0:5.1.118-3.el6 will be installed
---> Package python-backports.x86_64 0:1.0-5.el6 will be installed
---> Package python-six.noarch 0:1.9.0-2.el6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

Installing:
 m2crypto                              x86_64   0.20.2-9.el6       base   471 k
 python-crypto                         x86_64   2.0.1-22.el6       base   159 k
 python-futures                        noarch   2.1.6-1.el6        epel    30 k
 python-jinja2                         x86_64   2.2.1-3.el6        base   466 k
 python-msgpack                        x86_64   0.4.6-1.el6        epel    69 k
 python-requests                       noarch   2.6.0-4.el6        base    96 k
 python-tornado                        noarch   2.2.1-7.el6        epel   433 k
 python-zmq                            x86_64   14.3.1-1.el6       epel   467 k
Installing for dependencies:
 openpgm                               x86_64   5.1.118-3.el6      epel   165 k
 python-babel                          noarch   0.9.4-5.1.el6      base   1.4 M
 python-backports                      x86_64   1.0-5.el6          base   5.5 k
 python-backports-ssl_match_hostname   noarch   3.4.0.2-5.el6      base    12 k
 python-chardet                        noarch   2.2.1-1.el6        base   230 k
 python-setuptools                     noarch   0.6.10-4.el6_9     base   336 k
 python-six                            noarch   1.9.0-2.el6        base    28 k
 python-urllib3                        noarch   1.10.2-3.el6       base   103 k
 zeromq3                               x86_64   3.2.5-1.el6        epel   338 k

Transaction Summary

warning: rpmts_HdrFromFdno: Header V3 RSA/SHA256 Signature, key ID 0608b895: NOKEY
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
Importing GPG key 0x0608B895:
 Userid : EPEL (6) <epel@fedoraproject.org>
 Package: epel-release-6-8.noarch (installed)
 From   : /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : python-backports-1.0-5.el6.x86_64                           1/17 
  Installing : python-backports-ssl_match_hostname-3.4.0.2-5.el6.noarch    2/17 
  Installing : python-babel-0.9.4-5.1.el6.noarch                           3/17 
  Installing : python-setuptools-0.6.10-4.el6_9.noarch                     4/17 
  Installing : python-chardet-2.2.1-1.el6.noarch                           5/17 
  Installing : python-six-1.9.0-2.el6.noarch                               6/17 
  Installing : python-urllib3-1.10.2-3.el6.noarch                          7/17 
  Installing : openpgm-5.1.118-3.el6.x86_64                                8/17 
  Installing : zeromq3-3.2.5-1.el6.x86_64                                  9/17 
  Installing : python-zmq-14.3.1-1.el6.x86_64                             10/17 
  Installing : python-requests-2.6.0-4.el6.noarch                         11/17 
  Installing : python-jinja2-2.2.1-3.el6.x86_64                           12/17 
  Installing : python-tornado-2.2.1-7.el6.noarch                          13/17 
  Installing : python-futures-2.1.6-1.el6.noarch                          14/17 
  Installing : python-crypto-2.0.1-22.el6.x86_64                          15/17 
  Installing : m2crypto-0.20.2-9.el6.x86_64                               16/17 
  Installing : python-msgpack-0.4.6-1.el6.x86_64                          17/17 
  Verifying  : python-tornado-2.2.1-7.el6.noarch                           1/17 
  Verifying  : openpgm-5.1.118-3.el6.x86_64                                2/17 
  Verifying  : python-jinja2-2.2.1-3.el6.x86_64                            3/17 
  Verifying  : python-six-1.9.0-2.el6.noarch                               4/17 
  Verifying  : python-msgpack-0.4.6-1.el6.x86_64                           5/17 
  Verifying  : python-chardet-2.2.1-1.el6.noarch                           6/17 
  Verifying  : python-setuptools-0.6.10-4.el6_9.noarch                     7/17 
  Verifying  : m2crypto-0.20.2-9.el6.x86_64                                8/17 
  Verifying  : python-babel-0.9.4-5.1.el6.noarch                           9/17 
  Verifying  : python-zmq-14.3.1-1.el6.x86_64                             10/17 
  Verifying  : python-requests-2.6.0-4.el6.noarch                         11/17 
  Verifying  : python-crypto-2.0.1-22.el6.x86_64                          12/17 
  Verifying  : zeromq3-3.2.5-1.el6.x86_64                                 13/17 
  Verifying  : python-urllib3-1.10.2-3.el6.noarch                         14/17 
  Verifying  : python-backports-ssl_match_hostname-3.4.0.2-5.el6.noarch   15/17 
  Verifying  : python-futures-2.1.6-1.el6.noarch                          16/17 
  Verifying  : python-backports-1.0-5.el6.x86_64                          17/17 

Installed:
  m2crypto.x86_64 0:0.20.2-9.el6         python-crypto.x86_64 0:2.0.1-22.el6    
  python-futures.noarch 0:2.1.6-1.el6    python-jinja2.x86_64 0:2.2.1-3.el6     
  python-msgpack.x86_64 0:0.4.6-1.el6    python-requests.noarch 0:2.6.0-4.el6   
  python-tornado.noarch 0:2.2.1-7.el6    python-zmq.x86_64 0:14.3.1-1.el6       

Dependency Installed:
  openpgm.x86_64 0:5.1.118-3.el6                                                
  python-babel.noarch 0:0.9.4-5.1.el6                                           
  python-backports.x86_64 0:1.0-5.el6                                           
  python-backports-ssl_match_hostname.noarch 0:3.4.0.2-5.el6                    
  python-chardet.noarch 0:2.2.1-1.el6                                           
  python-setuptools.noarch 0:0.6.10-4.el6_9                                     
  python-six.noarch 0:1.9.0-2.el6                                               
  python-urllib3.noarch 0:1.10.2-3.el6                                          
  zeromq3.x86_64 0:3.2.5-1.el6                                                  

Complete!
 *  INFO: Running config_salt()
 * DEBUG: The passed destination(/etc/salt) is a directory
 * DEBUG: Full destination path is now: /etc/salt/minion
 * DEBUG: Moving /tmp/git/salt/conf//minion to /etc/salt/minion
 *  INFO: Running install_centos_git()
2018.3.4
Traceback (most recent call last):
  File "setup.py", line 1256, in <module>
    setup(distclass=SaltDistribution)
  File "/usr/lib64/python2.6/distutils/core.py", line 113, in setup
    _setup_distribution = dist = klass(attrs)
  File "setup.py", line 910, in __init__
    self.update_metadata()
  File "setup.py", line 916, in update_metadata
    attrvalue = getattr(self, attrname, None)
  File "setup.py", line 1020, in _property_install_requires
    install_requires = _parse_requirements_file(SALT_REQS)
  File "setup.py", line 231, in _parse_requirements_file
    if not _check_ver(platform.python_version(), _parse_op(op), _parse_ver(ver)):
  File "setup.py", line 207, in _check_ver
    return getattr(operator, '__{}__'.format(op))(pyver, wanted)
ValueError: zero length field name in format
 * ERROR: Failed to run install_centos_git()!!!
 * DEBUG: Cleaning up the Salt Temporary Git Repository
 * DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe
 * DEBUG: Removing the temporary apt error file /tmp/apt_error.KOIzmU

### Versions and Systems
./salt-bootstrap.sh -v =>  ./salt-bootstrap.sh -- Version 2019.10.03

[root@localhost salt-bootstrap]# cat /etc/*release*
CentOS release 6.10 (Final)
cpe:/o:centos:linux:6:GA

**Comment by s0undt3ch** [comment]
v2018.3.4 is no longer supported. Closing.
