### ISSUE TITLE
Opensuse 15.0 tests failed

### ISSUE THREAD

**Issue by vutny** [saltstack/salt-bootstrap#1386]
### Description of Issue/Question
Current tests against the tip of  `develop` branch are failing because of Opensuse 15.0 container provisioning:
```
STDERR: The command '/bin/sh -c zypper install -y sudo openssh which curl' returned a non-zero code: 139
```

### Setup
CI tests at drone.io: https://drone.saltstack.com/saltstack/salt-bootstrap/248/10/4

Also, it seems Ubuntu tests are kinda stuck. Ping @Ch3LL

**Comment by vutny** [comment]
Works now, thanks!
Some old PR jobs are still stuck, probably someone need to cancel them:
https://drone.saltstack.com/saltstack/salt-bootstrap/258
https://drone.saltstack.com/saltstack/salt-bootstrap/255
https://drone.saltstack.com/saltstack/salt-bootstrap/248

@Ch3LL @s0undt3ch ?

**Comment by s0undt3ch** [comment]
Jobs have been cancelled.
It also seems like the last develop job passed https://drone.saltstack.com/saltstack/salt-bootstrap.

Good enough to close the ticket?

**Comment by vutny** [comment]
All good, thanks!

**Comment by vutny** [comment]
Seems like Opensuse Leap 15.0 is flaky:
```
Retrieving repository 'openSUSE-Leap-15.0-Non-Oss' metadata [...done]
Building repository 'openSUSE-Leap-15.0-Non-Oss' cache [....done]
Retrieving repository 'openSUSE-Leap-15.0-Oss' metadata [..
STDERR: The command '/bin/sh -c zypper install -y sudo openssh which curl' returned a non-zero code: 139
```

**Comment by vutny** [comment]
The last what I seen on Drone CI is this:
```

Retrieving: perl-Error-0.17025-lp150.1.6.noarch.rpm [/tmp/kitchen/bootstrap.sh: line 5922:   778
Segmentation fault      (core dumped) zypper --non-interactive "${@}"
--
```
It could be specific for the container environment which Drone uses.

**Comment by Ch3LL** [comment]
should be fixed by https://github.com/saltstack/salt-bootstrap/pull/1408
