### ISSUE TITLE
Drone CI: Your License Limit Is Exceeded

### ISSUE THREAD

**Issue by vutny** [saltstack/salt-bootstrap#1389]
### Description of Issue/Question
Drone build at https://drone.saltstack.com/saltstack/salt-bootstrap shows:
"Your License Limit Is Exceeded" at the bottom of the page.

Looks like it was a trial installation or so. Not sure how it would affect future PRs.

Ping @s0undt3ch @Ch3LL

**Comment by Ch3LL** [comment]
thanks for letting us know. i'll let @s0undt3ch comment here as he is more familiar with this area, but I do believe we are not going to be using drone anymore so we will probably need to migrate the tests.

**Comment by s0undt3ch** [comment]
FYI, Eventually we'll move out from drone. We haven't made any progress on that end yet though.
