### ISSUE TITLE
No Support of Python3 with Amazon Linux 2

### ISSUE THREAD

**Issue by johnvox** [saltstack/salt-bootstrap#1391]
### Description of Issue/Question
Hello, I can't managed to install salt with python3 support on AmazonLinux 2

### Setup
(Please provide relevant configs (Be sure to remove sensitive info).)
Tested on Amazon Linux AMI  amzn2-ami-hvm-2.0.20191116.0-x86_64-gp2 (ami-00068cd7555f543d5) 

### Steps to Reproduce Issue
curl -o /tmp/bootstrap-salt.sh -L https://bootstrap.saltstack.com
sh /tmp/bootstrap-salt.sh -x python3

### Versions and Systems
salt -V
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.16 (default, Sep 13 2019, 20:28:21)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.14.152-127.182.amzn2.x86_64
         system: Linux
        version: Not Installed

**Comment by dmurphy18** [comment]
@Ch3LL Can confirm this to be the case

**Comment by dmurphy18** [comment]
Working on this since nightly builds also needs this resolved.

**Comment by dmurphy18** [comment]
Closing since fix is merged into develop
