### ISSUE TITLE
Drone CI: which configuration file is in use and how to update it properly?

### ISSUE THREAD

**Issue by vutny** [saltstack/salt-bootstrap#1395]
### Description of Issue/Question
This is a question: which file serves as a source of configuration for Drone CI,
`.drone.yml` or `.drone.jsonnet`?
If some of it is legacy, we need to drop it to avoid confusion and duplication of efforts. If the one of it is somehow generated from the other one, it should be documented how to make this conversion.

Also it appears that after the changes was made to the CI configs, all subsequent builds require manual approval from authorized person to kick off the build.

@s0undt3ch, could we change the CI behavior somehow to allow config changes applied automatically once being propagated to the `develop`? Because for now the build for the tip of `develop` is stuck:
https://drone.saltstack.com/saltstack/salt-bootstrap/282

**Comment by s0undt3ch** [comment]
`.drone.jsonnet` is used to generate `.drone.yml`

#1396 fixes this issue.
