### ISSUE TITLE
Installing Salt on Amazon Linux 2 ARM

### ISSUE THREAD

**Issue by blade2005** [saltstack/salt-bootstrap#1405]
### Description of Issue/Question
Unable to install salt on Amazon Linux 2 ARM64. This issue seems to be because there's no compile packages for amazon linux https://repo.saltstack.com/yum/amazon/2/

### Setup
None

### Steps to Reproduce Issue
Run `curl -L https://bootstrap.saltstack.com | sudo sh -s -- "$@" git develop`

### Versions and Systems
```
# uname -r
4.14.152-127.182.amzn2.aarch64
```

**Comment by acornett** [comment]
Is there any plan to support the amazon arm platform in the near future?

**Comment by bryceml** [comment]
We would like to, not sure when that will happen.
Ubuntu 20.04 and Debian 10 all their dependencies provided by the os, so you can point to the amd64 repos and just use them since the dependencies are all there

It would be something like 

```
deb [arch=amd64] https://repo.saltproject.io/py3/debian/10/amd64/latest buster main
```
in your repo file.  This works because there are only architecture independent packages in the repos for those 2.

Centos/Rhel have some dependencies provided by us or by epel.  Amazon Linux has the most dependencies that are provided by us so it will be the hardest one to support.

When we move to tiamat based packages, it should be much easier to provide support for arm64.  We aren't currently packaging arm64 versions of the tiamat based packages yet but would like to as soon as we can.

**Comment by snago** [comment]
We also ran into this problem and would like to be able to bootstrap the graviton based EC2 instance types (c6g, m6g, etc) when running Amazon Linux 2.

> When we move to tiamat based packages, it should be much easier to provide support for arm64. We aren't currently packaging arm64 versions of the tiamat based packages yet but would like to as soon as we can.

Are there any issues for this progress that I can follow somewhere?

**Comment by arthurpetitpierre** [comment]
@bryceml is there anything AWS can do to help, like providing access to Graviton2 based instances ? Or patches to your build pipelines?

**Comment by bryceml** [comment]
> @bryceml is there anything AWS can do to help, like providing access to Graviton2 based instances ? Or patches to your build pipelines?

One thing that would make it easier is if amazon linux itself provided rpms for all of the dependencies of salt: https://repo.saltproject.io/py3/amazon/2/x86_64/latest/

Amazon linux by far has the most dependencies that we have to build ourselves.  It appears that only python3.7 is in the amazon linux repos, and no other python packages.

We also could have easily use the python3.6 rpms from epel if amazon linux had stayed on python3.6 and stayed compatible with the epel packages as well.

**Comment by bryceml** [comment]
> We also ran into this problem and would like to be able to bootstrap the graviton based EC2 instance types (c6g, m6g, etc) when running Amazon Linux 2.
> 
> > When we move to tiamat based packages, it should be much easier to provide support for arm64. We aren't currently packaging arm64 versions of the tiamat based packages yet but would like to as soon as we can.
> 
> Are there any issues for this progress that I can follow somewhere?

https://gitlab.com/saltstack/open/salt-pkg/-/issues

with https://gitlab.com/saltstack/open/salt-pkg/-/issues/1 and https://gitlab.com/saltstack/open/salt-pkg/-/issues/29 being major blockers.

**Comment by ripesensor** [comment]
https://github.com/saltstack/salt/issues/59779

Seems like this should be supported, and it is as long as you:
```
sudo sed -i 's/\$basearch/arm64/' /etc/yum.repos.d/salt.repo
```
And then re-run the bootstrap command.

Maybe we can get an alias; even the packages use `aarch64`:
```shell
Running transaction
  Installing : salt-3006.3-0.aarch64                                        1/2 
  Installing : salt-minion-3006.3-0.aarch64                                 2/2 
  Verifying  : salt-minion-3006.3-0.aarch64                                 1/2 
  Verifying  : salt-3006.3-0.aarch64                                        2/2 

Installed:
  salt-minion.aarch64 0:3006.3-0                                                

Dependency Installed:
  salt.aarch64 0:3006.3-0                                                       

Complete!
 *  INFO: Running install_amazon_linux_ami_2_onedir_post()
 *  INFO: Running install_amazon_linux_ami_2_check_services()
 *  INFO: Running install_amazon_linux_ami_2_restart_daemons()
 *  INFO: Running daemons_running_onedir()
 *  INFO: Salt installed!
```

**Comment by dmurphy18** [comment]
@blade2005  Closing this as fixed in release of the bootstrap 2024-07-12, see https://github.com/saltstack/salt-bootstrap/actions/workflows/ci.yml.  Please feel free to reopen if other matters relevant to this issue come to light.
