### ISSUE TITLE
oot

### ISSUE THREAD

**Issue by pr0xxy** [saltstack/salt-bootstrap#1409]
### Setup
(Please provide relevant configs (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible, `bootstrap-salt.sh -D`.)

### Versions and Systems
(`salt --versions-report`, `bootstrap-salt.sh -v`, system type and version,
cloud/VM provider as appropriate.)

**Comment by s0undt3ch** [comment]
Invalid.
