### ISSUE TITLE
Install script does not work on Debian 7

### ISSUE THREAD

**Issue by tomasfejfar** [saltstack/salt-bootstrap#141]
```
root@worker1:~# ./install.sh
 *  INFO: /bin/sh ./install.sh -- Version 1.5.4

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.2.0-4-amd64
 *  INFO:   Distribution: Debian 7.0

 *  INFO: Installing minion
 *  INFO: Found function install_debian_7_deps
 *  INFO: Found function install_debian_restart_daemons
 *  INFO: Found function daemons_running
 * ERROR: No installation function found. Exiting...
```

The error message does not say much about what the problem might be, so let me know if you need more info.

**Comment by tomasfejfar** [comment]
Also with:
`wget -O - http://bootstrap.saltstack.org | sudo sh`
it fails with:
`Nelze zapsat do „-“ (Roura přerušena (SIGPIPE)).` - transated as `Cannot write to "-" (Pipe interrupted (SIGPIPE))`

**Comment by tomasfejfar** [comment]
Seems like a known issue: https://github.com/saltstack/salt-bootstrap/issues/100 but the error is different

**Comment by s0undt3ch** [comment]
This issue is solved in the unstable version of the script, please try:

```
wget -O - https://raw.github.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh | sudo sh
```

**Comment by tomasfejfar** [comment]
Thank you. 

It would be nice to suggest this in docs - like "if this does not work for you, you can try the dev version of install script"...

**Comment by s0undt3ch** [comment]
Your suggestion has been accepted, please [look here](https://github.com/saltstack/salt-bootstrap#i-found-a-bug). :smile:

**Comment by tomasfejfar** [comment]
That's nice :) Thank you.
