### ISSUE TITLE
The bootstrap script should install the python3 version of salt without needing to provide -x python3 on oses that don't support python2

### ISSUE THREAD

**Issue by bryceml** [saltstack/salt-bootstrap#1418]
### Description of Issue/Question
Debian 10, Rhel 8, and Fedora 32 we no longer support python2 on.  We should not require `-x python3` in order for it to correctly install a salt on those oses by default.  For oses that don't support python2, it should automatically install the python3 version.

**Comment by darkn3rd** [comment]
The default should be python3.  Python2 is offiicially deprecated in 2020.  

If users need compatibility to `python2`, then they could specify `-x python2`.

**Comment by bryceml** [comment]
Debian 10, Rhel 8, and Fedora 32 all default to py3 now.
