### ISSUE TITLE
sha256sum does not match value published on readme for 2020.01.21

### ISSUE THREAD

**Issue by wkral** [saltstack/salt-bootstrap#1419]
### Description of Issue/Question
Getting a different sha256sum for the downloaded script, security practices say I shouldn't trust it. Probably just a mistake but needs to be fixed.

### Steps to Reproduce Issue

```
$ curl -o bootstrap-salt.sh -L https://bootstrap.saltstack.com
$ sha256sum bootstrap-salt.sh
```
Output does not match published sha256sum execution

### Versions and Systems
2020.01.21

**Comment by wkral** [comment]
@s0undt3ch You had the last commit publishing the value, perhaps you can look at this?

**Comment by wkral** [comment]
Further investigation yields that the published value on the README is from the `develop` branch and the version we're getting from bootstrap.saltstack.com is showing the value from the `stable` branch.

**Comment by s0undt3ch** [comment]
Bah! Yes, I got the SHA from the wrong branch.

Thank you for pointing that out.

**Comment by s0undt3ch** [comment]
Thank You. Fixed.

**Comment by wkral** [comment]
Thanks for fixing that quickly.
