### ISSUE TITLE
Bootstrap fails on Debian 7.0

### ISSUE THREAD

**Issue by JannKleen** [saltstack/salt-bootstrap#142]
I'm on the current version of Debian 7.0, using wheezy, wheezy security updates and wheezy-updates...

When running `root@debian:~# wget -O - http://bootstrap.saltstack.org | sh`:
https://gist.github.com/JannKleen/5637190

When running `python -c 'import urllib; print urllib.urlopen("http://bootstrap.saltstack.org").read()' | sh -s -- git develop`:
https://gist.github.com/JannKleen/5637208

And when running with -P as the last command told me to:
`root@debian:~# python -c 'import urllib; print urllib.urlopen("http://bootstrap.saltstack.org").read()' | sh -s -- -P git develop`
https://gist.github.com/JannKleen/5637220

**Comment by JannKleen** [comment]
sorry, dupe of #100

**Comment by s0undt3ch** [comment]
Yes, Debian 7 support is not in the stable branch. To get develop version of the string, please [look here](https://github.com/saltstack/salt-bootstrap#i-found-a-bug).
