### ISSUE TITLE
Feature Request: Unable to pin minor version 3000

### ISSUE THREAD

**Issue by sblaisot** [saltstack/salt-bootstrap#1436]
### Description of Issue/Question

Before 3000, one could use `salt-bootstrap stable 2019.2` to install with pin-to-major repo `2019.2` and receive any patchlevel update in the 2019.2 series or use `salt-bootstrap stable 2019.2.0` to install with pin-to-minor repo `archives/2019.2.0` and stay forever on 2019.2.0 without getting any update.

This pin-to-major/pin-to-minor was implicit from different version numbers.

Now, with salt 3000+, pin-to-major and pin-to-minor repo have the same name `3000` (either plain `3000` or `archives/3000` repos) and you have no way to select pin-to-minor `archives/3000` repo using salt-bootstrap.

I think i would be better to make this selection explicit with a new parameter asking for pin-to-minor repo rather than relying on version number liek it previously was.

So I'm asking for a way to install salt 3000 with salt-bootstrap from `archives/3000` repo using a new salt-bootstrap parameter.

**Comment by ghost** [comment]
The script checks for hardcoded versions here: https://github.com/saltstack/salt-bootstrap/blob/9f2f1b56fbc0d0264ed75e97cda4e39e9529792e/bootstrap-salt.sh#L606

Maybe it just need to be added that the newest version is 3000.2.

**Comment by max-arnold** [comment]
5 months passed, 3001.1 is out, and again any scripted 3001 install became non-reproducible. Here is a fix: https://github.com/saltstack/salt-bootstrap/pull/1491

**Comment by max-arnold** [comment]
The fix was merged, so I guess this issue can be closed

**Comment by s0undt3ch** [comment]
Yep, this is fixed.
