### ISSUE TITLE
Support OmniOS (IllumOS derivative)

### ISSUE THREAD

**Issue by robinsmidsrod** [saltstack/salt-bootstrap#144]
It'd be nice if OmniOS could be supported in the installer. It is a Solaris-based system that uses IPS packaging, same as OpenIndiana.

See http://omnios.omniti.com/wiki.php/Packaging for more details on how to package for OmniOS.

I believe the information below is what you need to at least detect the distro correctly.

```
# /sbin/uname -X
System = SunOS
Node = nas
Release = 5.11
KernelID = omnios-d3950d8
Machine = i86pc
BusType = <unknown>
Serial = <unknown>
Users = <unknown>
OEM# = 0
Origin# = 1
NumCPU = 8

# cat /etc/release
  OmniOS v11 r151006
  Copyright 2012-2013 OmniTI Computer Consulting, Inc. All rights reserved.
  Use is subject to license terms.
```

**Comment by s0undt3ch** [comment]
Is there any cloud service providing an image of OmniOS?

**Comment by robinsmidsrod** [comment]
@s0undt3ch Yes, I believe there are EC2 AMIs available. Details here: http://omnios.omniti.com/wiki.php/Installation#IntheCloud

**Comment by s0undt3ch** [comment]
Cool!!! I'll see if I spin one up to at least have the script properly detect OmniOs.

## 

Pedro Algarvio @ phone

----- Reply message -----
De: "Robin Smidsrød" notifications@github.com
Para: "saltstack/salt-bootstrap" salt-bootstrap@noreply.github.com
Cc: "Pedro Algarvio" pedro@algarvio.me
Assunto: [salt-bootstrap] Support OmniOS (IllumOS derivative) (#144)
Data: qua, Jun 19, 2013 20:59
@s0undt3ch Yes, I believe there are EC2 AMIs available. Details here: http://omnios.omniti.com/wiki.php/Installation#IntheCloud 

&mdash;

**Comment by s0undt3ch** [comment]
Quoting @robinsmidsrod on #169 so the comment does not get lost.

---

@s0undt3ch Well, technically it's using the same system as OpenIndiana (and traditional Solaris I guess), which are IPS packages. More details here: http://omnios.omniti.com/wiki.php/Packaging

It can also run any traditional Solaris 10 binary, so if you already have that in your script, I believe you should be able to point it at those. If not, a typical from source build that works on Solaris and OpenIndiana _should_ also work here. The packages available from opencsw.org also work using the opencsw.org installer. Not sure exactly what kind of package manager you'd want to support, as the IPS package manager is for the core OS, but opencsw seems to have a lot more packages available for Solaris, which also work on OmniOS.

I've never built salt from source and I'm quite a newbie with it comes to all things Solaris/OpenIndiana/OmniOS, but I am fairly decent at testing. Could you give me a quick overview of what I'd need to test and how?

The install functions are all shell code, right? In terms of installing services, it's all standard Solaris SMF (which I also suck at). In terms of installing packages from the standard repos, you can read more about that here: http://omnios.omniti.com/wiki.php/GeneralAdministration#PackageManagement

Hopefully some of this is helpful in getting something done.

**Comment by robinsmidsrod** [comment]
@s0undt3ch Actually, using the method mentioned in http://docs.saltstack.com/topics/installation/solaris.html does work for OmniOS as well. I've managed to install salt using pkgutil -i py_salt. Switching OpenCSW from testing to unstable made it install a bunch of other services on the system, which I'm not sure how will affect the system, but things _seem_ to still work as expected.

Though my efforts where stopped during startup of salt-minion. I'm getting these errors in the log, and for some reason communication is not working although the key seems to have been accepted. test.ping does not give a response.

```
[INFO    ] Loaded configuration file: /etc/salt/minion
[INFO    ] Setting up the Salt Minion "nas.smidsrod.lan"
[DEBUG   ] Missing configuration file: /etc/salt/minion
[DEBUG   ] loading grain in ['/var/cache/salt/minion/extmods/grains', '/opt/csw/lib/python/site-packages/salt/grains']
[DEBUG   ] Skipping /var/cache/salt/minion/extmods/grains, it is not a directory
[TRACE   ] Added core.append_domain to grain
[TRACE   ] Added core.get_server_id to grain
[TRACE   ] Added core.hostname to grain
[TRACE   ] Added core.id_ to grain
[TRACE   ] Added core.ip4 to grain
[TRACE   ] Added core.locale_info to grain
[TRACE   ] Added core.os_data to grain
[TRACE   ] Added core.path to grain
[TRACE   ] Added core.pythonpath to grain
[TRACE   ] Added core.pythonversion to grain
[TRACE   ] Added core.saltpath to grain
[TRACE   ] Added core.saltversion to grain
[TRACE   ] Added opts.opts to grain
[TRACE   ] Added extra.config to grain
[TRACE   ] Added extra.shell to grain
[CRITICAL] Failed to load grains defined in grain file core.os_data in function <function os_data at 0x87ac8b4>, error:
Traceback (most recent call last):
  File "/opt/csw/lib/python/site-packages/salt/loader.py", line 787, in gen_grains
    ret = fun()
  File "/opt/csw/lib/python/site-packages/salt/grains/core.py", line 662, in os_data
    grains.update(_sunos_cpudata(grains))
  File "/opt/csw/lib/python/site-packages/salt/grains/core.py", line 237, in _sunos_cpudata
    grains['cpu_model'] = __salt__['cmd.run'](kstat_info).split()[1].strip()
IndexError: list index out of range

[CRITICAL] Failed to load grains defined in grain file core.ip4 in function <function ip4 at 0x87ac994>, error:
Traceback (most recent call last):
  File "/opt/csw/lib/python/site-packages/salt/loader.py", line 787, in gen_grains
    ret = fun()
  File "/opt/csw/lib/python/site-packages/salt/grains/core.py", line 747, in ip4
    ips = salt.utils.socket_util.ip4_addrs()
  File "/opt/csw/lib/python/site-packages/salt/utils/socket_util.py", line 307, in ip4_addrs
    ifaces = interfaces()
  File "/opt/csw/lib/python/site-packages/salt/utils/socket_util.py", line 298, in interfaces
    ifaces = _interfaces_ifconfig(cmd)
NameError: global name 'cmd' is not defined

[DEBUG   ] Attempting to authenticate with the Salt Master at 10.1.1.2
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[INFO    ] Authentication with master successful!
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Decrypting the current master AES key
```

Going a bit deeper seems to indicate that kstat (solaris perf counters) segfaults, which seems like a big problem and is probably the reason for the first cpu_model failure. I've done a zfs rollback on the rpool to undo all of these changes, but the segfault seems to persist. I'm going to hunt this issue further and get back to you.

**Comment by robinsmidsrod** [comment]
@s0undt3ch This is the output from runnin truss on kstat -p. https://gist.github.com/robinsmidsrod/5844493 I've sent an email to the OmniOS discuss mailing-list about the issue. Let's see what they have to say first. Preliminary findings suggest that kstat -p doesn't segfault on a default install of r151006, but it seems like it happens once you install iSCSI target system and enable it (in some way).

**Comment by s0undt3ch** [comment]
@robinsmidsrod you kept digging into this! Thanks!! You do seem to at least know a bit more than me about the subject ;)

The `IndexError` is taken care of in current development branch, a regex is used instead, [see here](https://github.com/saltstack/salt/blob/develop/salt/grains/core.py#L302).

The code triggering the `NameError` has also changed.

What version of salt was installed?

**Comment by robinsmidsrod** [comment]
@s0undt3ch According to http://www.opencsw.org/packages/CSWpy-salt/ it seems 0.14.0.

But the core problem was that the kstat command failed with a segfault, and because of that you didn't get the output you expected during kstat_info, right? Maybe the kstat_info call should account for an unexpected exit code from kstat and bail out if one occurs?

About the segfault, I got this preliminary feedback from Garrett D'Amore, an IllumOS developer on the omnios-discuss mailing-list: "I've noticed lately that kstat seems to segfault when asked for a non existent stat. I have not had time to investigate further and I can't yet confirm that this problem exists in current illumos.  I will look soon though."

Here is the thread in case you'd like to follow it: http://lists.omniti.com/pipermail/omnios-discuss/2013-June/000974.html

**Comment by s0undt3ch** [comment]
0.14 is old :)
Don't know which but at least 0.15.90(0.16.0 rc) handles a misbehaving call of kstat.

**Comment by robinsmidsrod** [comment]
I've had a chat with a developer for OmniOS, and he's given me a patched version of kstat that actually doesn't segfault. So that fix should arrive soonish. According to http://docs.saltstack.com/topics/installation/solaris.html Romeo Theriault romeot@hawaii.edu is the maintainer of the OpenCSW package of salt. Maybe it's possible to poke him to get an updated version out?

**Comment by s0undt3ch** [comment]
@romeotheriault Think you can help out regarding the issues being discussed here?

**Comment by rrtj3** [comment]
Sure, I can work on getting the latest version on early this week. Does the latest stable version have the fix?

**Comment by robinsmidsrod** [comment]
@romeotheriault Maybe a coordinated push to get 0.16.0 out into opencsw when it's ready for release would be the best thing, since 0.15.90 is technically an RC and should probably not be released to a stable repo? Then again, py_salt is in the unstable OpenCSW repo, so maybe it doesn't really matter that much. What do you think, @s0undt3ch ? What's the ETA on 0.16.0?

**Comment by s0undt3ch** [comment]
@thatch45 what's the ETA on 0.16.0?

**Comment by robinsmidsrod** [comment]
@s0undt3ch I just want to inform you that the kstat segfault issue was fixed in version r151006i of OmniOS, which was released to stable branch on 28 June 2013, so that should no longer give us any issues.

**Comment by s0undt3ch** [comment]
Cool! 0.16.0 is also out already.

**Comment by s0undt3ch** [comment]
Is this working ok for you now?

**Comment by robinsmidsrod** [comment]
@s0undt3ch To be honest, I haven't had time to verify it. I haven't played around with OmniOS and Saltstack for ages (no time, unfortunately). If anyone else has access to an OmniOS environment that had the issue it would be great if they could test out as well.

**Comment by vutny** [comment]
@robinsmidsrod @s0undt3ch This issue is too old. I guess you can close it now and reopen if necessary.

**Comment by robinsmidsrod** [comment]
Unfortunately, I've stopped using OmniOS, so I don't have the environment around anymore to test it out. Feel free to reopen if you have both a test environment and a problem with the issue.
