### ISSUE TITLE
Could you kindly add Ubuntu 20.04?

### ISSUE THREAD

**Issue by yitzhakbg** [saltstack/salt-bootstrap#1444]
### Description of Issue/Question
I know this is a bit early (approx. 3 weeks) but would be nice if you could add Ubuntu 20.04 and recognize Pop!OS. Thank you very much in advance.
I'm running Pop!OS which I upgraded to Ubuntu 20.04, getting:
CHECK_SERVICES_FUNC_NAMES=install_pop_20_stable_check_services install_pop_20_04_stable_check_services install_pop_20_check_services install_pop_20_04_check_services install_pop_stable_check_services  
etc...

**Comment by myii** [comment]
@yitzhakbg Looking forward to `20.04` here as well but there are still some fixes needed to get Salt working properly on Python 3.8...

**Comment by geoffjukes** [comment]
Now that 20.04 has shipped, I'm hoping this ticket gets some love :)

**Comment by OrangeDog** [comment]
Note that salt-formulas can't do any testing on 20.04 without this, and there are a bunch of things that don't work there as well.

To my disappointment there wasn't even a ticket working on Python 3.8, which blocks this. There is now: #1460

**Comment by wolfpackmars2** [comment]
Looks like this will be resolved soon with the planned release of Salt v3001.
Ref https://github.com/saltstack/salt-bootstrap/issues/1456#issuecomment-635285018

**Comment by yitzhakbg** [comment]
sounds great

**Comment by WarrenWilkinson** [comment]
I'm spawning lxc focal fossil containers using salt-cloud... I seem to need the bootstrap argument "-x python3", but other than that it seems to be working.

**Comment by bryceml** [comment]
once https://github.com/saltstack/salt-bootstrap/pull/1480 is released to stable you shouldn't need `-x python3` either.  Using `-x python3` should keep working though.
