### ISSUE TITLE
bootstrap_salt.ps1 unable to download installer.

### ISSUE THREAD

**Issue by wildk1w1** [saltstack/salt-bootstrap#1450]
### Description of Issue/Question
Running the script to install salt-minion on Windows 20012R2 and 2016 results in a failed download with the error:
```
Using Bootstrap Options: -pythonVersion 3 -master  172.16.251.10 -minion minion3.test.local
Bootstrapping Salt... (this may take a while)
Service defaulting to run.
Downloading Salt minion installer Salt-Minion-2018.3.4-Py3-AMD64-Setup.exe
WARNING: Retrying download in 2 seconds. Retry # 1
WARNING: Retrying download in 2 seconds. Retry # 2
WARNING: Retrying download in 2 seconds. Retry # 3
WARNING: Retrying download in 2 seconds. Retry # 4
The request was aborted: Could not create SSL/TLS secure channel.
At C:\tmp\bootstrap_salt.ps1:74 char:5
+     $webclient.DownloadFile($url, $file)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], WebException
    + FullyQualifiedErrorId : WebException


IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     ErrorRecord                              System.Object
The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
```

To resolve the issue added 

**_[Net.ServicePointManager]::SecurityProtocol = "tls12"_**

### Setup
(Please provide relevant configs (Be sure to remove sensitive info).)
Using Vagrant to do the provisioning.

salt.bootstrap_options = "-pythonVersion 3 -master  #{net_ip}.10 -minion #{vmname}.#{domain}"
### Steps to Reproduce Issue
(Include debug logs if possible, `bootstrap-salt.sh -D`.)

### Versions and Systems
(`salt --versions-report`, `bootstrap-salt.sh -v`, system type and version,
cloud/VM provider as appropriate.)

**Comment by twangboy** [comment]
@s0undt3ch I thought that was in there already

**Comment by twangboy** [comment]
https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.ps1#L105

**Comment by wildk1w1** [comment]
Hi Shane,

I think Vagrant have a dedicated salt provisioner with their own bootstrap
powershell script.
I've opened a case with them to look into it as well.

**Comment by bryceml** [comment]
@wildk1w1 any update?  do you have a link to an issue or pr we can follow up on?

**Comment by bryceml** [comment]
https://github.com/hashicorp/vagrant/issues/11522

Looks like they're handling it there, so we can close here.
