### ISSUE TITLE
Cumulus 4.1

### ISSUE THREAD

**Issue by AmbicaY** [saltstack/salt-bootstrap#1453]
### Description of Issue/Question
Salt minion installation is failing on Cumulus 4.1

### Setup
Cumulus Buster

### Steps to Reproduce Issue
echo "deb http://ftp.us.debian.org/debian/ buster main contrib non-free" >> /etc/apt/sources.list
curl -L https://bootstrap.saltstack.com -o install_salt.sh
sh install_salt.sh -P -A <salt_master_ip> -i cumulus-ztp4 stable 2019.2.2

**Comment by s0undt3ch** [comment]
Does the boostrap script properly detect Cumulus?

**Comment by darylturner** [comment]
`lsb_release -si` is slightly different from Cumulus 3.
On Cumulus 4.1 it's
```
root@cumulus:mgmt:/home/cumulus# lsb_release -si
Cumulus-Linux                                  
```

On Cumulus 3 it's
```
root@cumulus:~$ lsb_release -si
Cumulus Linux                       
```

After all of the functions to simplify and translate the name are run it no longer matches in the debian_derivatives function. I've got a working version that I will create a PR for but I've not yet checked this back against Cumulus 3.

**Comment by darylturner** [comment]
@AmbicaY - does this fix resolve your issue? Change has been merged into develop branch. Maybe this issue can be closed.
