### ISSUE TITLE
 * ERROR: Failed to run install_ubuntu_git_deps()!!!

### ISSUE THREAD

**Issue by hemantaltair** [saltstack/salt-bootstrap#1456]
### Description of Issue/Question
 * ERROR: Failed to run install_ubuntu_git_deps()!!!

### Setup
It fails in bootstarp itself

### Steps to Reproduce Issue
sudo sh install_salt.sh -P -A xx.xx.xx.xx -i xx-xx-xx-xx git v2019.2.2

### Versions and Systems
bootstrap-salt.sh -- Version 2020.02.24

 *  INFO: Running version: 2020.02.24
 *  INFO: Executed by: sh
 *  INFO: Command line: 'install_salt.sh -P -A xx.xx.xx.xx -i xx.xx.xx.xx git v2019.2.2'

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   5.3.0-1020-azure
 *  INFO:   Distribution: Ubuntu 18.04

 *  INFO: Installing minion
 *  INFO: Found function install_ubuntu_git_deps
 *  INFO: Found function config_salt
 *  INFO: Found function preseed_master
 *  INFO: Found function install_ubuntu_git
 *  INFO: Found function install_ubuntu_git_post
 *  INFO: Found function install_ubuntu_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Found function install_ubuntu_check_services
 *  INFO: Running install_ubuntu_git_deps()
Hit:1 http://azure.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://azure.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://azure.archive.ubuntu.com/ubuntu bionic-backports InRelease
Get:4 https://repo.saltstack.com/apt/ubuntu/18.04/amd64/latest bionic InRelease [2120 B]
Hit:5 http://security.ubuntu.com/ubuntu bionic-security InRelease
Get:6 https://repo.saltstack.com/apt/ubuntu/18.04/amd64/latest bionic/main amd64 Packages [2363 B]
Err:6 https://repo.saltstack.com/apt/ubuntu/18.04/amd64/latest bionic/main amd64 Packages
  File has unexpected size (2368 != 2363). Mirror sync in progress? [IP: 99.84.221.60 443]
  Hashes of expected file:
   - Filesize:2363 [weak]
   - SHA256:dd0cad2f6f71b3b614c98079e224875b09890b600ec25b1c1ac303838a93e2c4
   - SHA1:729e88199fdc7b9c400ab14e4da27c916c606ce4 [weak]
   - MD5Sum:00067b47c2915cbcd91310e813b6df9c [weak]
  Release file created at: Mon, 30 Mar 2020 17:06:48 +0000
Fetched 2120 B in 0s (4526 B/s)
Reading package lists...
 * ERROR: Failed to run install_ubuntu_git_deps()!!!

**Comment by dmurphy18** [comment]
Please retry  the repo.saltstack.com is finally finished sync'ing for point releases 2019.2.4 and 3000.2 and the repo should now work properly for those and other releases

**Comment by bryceml** [comment]
Are you using Ubuntu 20.04 ?

**Comment by pmurley** [comment]
I am having this same issue currently. Fresh install of Ubuntu 20.04. Is there a workaround?

**Comment by s0undt3ch** [comment]
No, no workaround.

Or better.

Yes, wait for Salt Sodium release, v3001, not yet released. The only Salt version that officially supports Py3.8

Or, provide your own Py3.7 somehow and install Salt using that version.

Or install salt using Python 2, but to upgrade to Sodium you'll have to remove that salt installation.

That's about it right now.

**Comment by hemantaltair** [comment]
@bryceml os log version is in description
INFO: Distribution: Ubuntu 18.04

**Comment by wolfpackmars2** [comment]
not related to 20.04.
@hemantaltair have you tried again? I think @dmurphy18 is on the right track - it looks like a sync issue with the repo. Does the problem still exist?

**Comment by SeLLeRoNe** [comment]
Hey guys, I am trying to install saltstack on an Ubuntu 14.04, we do have an aws instance create script which post-installation runs:
sh /tmp/install_salt.sh -i $HOSTNAME -P git v2015.8

It seems that now that isn't working anymore, the connection to repo.saltstack.com seems to fail

I have been digging a little and I tried to update to python3, once I did that I had the same error as this thread ( * ERROR: Failed to run install_ubuntu_git_deps()!!!)

I would like to ask:
- Is Ubuntu 14.04 no longer supported (or maybe the version 2015.8 isn't somehow?)

If the above is false:
- Do I need to use Python 3 now or I should be able to run that command I posted above and the error is somewhere else?

Thanks
Andrea

**Comment by SeLLeRoNe** [comment]
Just an update, my problem was fixed specifying the archive repository on the command line.

Andrea

**Comment by bryceml** [comment]
@hemantaltair can this issue be closed now? or is there still something that doesn't work?
