### ISSUE TITLE
bootstrap script fails on KDE neon (Ubuntu 18.04 base)

### ISSUE THREAD

**Issue by ender8282** [saltstack/salt-bootstrap#1458]
### Description of Issue/Question

Attempting to run the bootstrap script fails on KDE Neon. The two relevant error lines from the outputs are:

salt.sh: 1: eval: neon_18_ubuntu_base: parameter not set
 * ERROR: No dependencies installation function found. Exiting...

### Steps to Reproduce Issue
Boot KDE Neon live CD
Download salt bootstrap
$ sudo sh bootstrap-salt.sh

### Versions and Systems
bootstrap 2020.02.24
KDE Neon live CD 20200430-1117

To be clear the script properly identifies the distribution.  It is just missing a line that associates neon with ubuntu 18.04.  

PR to follow.

**Comment by s0undt3ch** [comment]
The required changes have been merged.
Please reopen or open a new issue of needed.
