### ISSUE TITLE
Support Python 3.8

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt-bootstrap#1460]
Bootstrap has many of the same issues as the salt (use of removed and deprecated APIs), but still not fixed on master.

See also https://github.com/saltstack/salt/issues/55835

**Comment by wolfpackmars2** [comment]
This should probably be tracked with the salt repo. #1444 tracks support for 20.04 in salt-bootstrap. Close as duplicate of saltstack/salt#55835 ?

**Comment by bryceml** [comment]
@OrangeDog can this be closed now?

**Comment by OrangeDog** [comment]
I don't know. I just created the issue after others pointed out there were still errors and deprecation warnings.

**Comment by bryceml** [comment]
I'm going to assume since it now supports ubuntu 20.04 that we can say this is fixed.

**Comment by OrangeDog** [comment]
The README still talks about Python 3 as if it's limited and rare, but is in fact is all that Salt now supports.

**Comment by bryceml** [comment]
Sounds like we need to update the README then explaining how it decides to use python3.  I'll re-open this.

**Comment by bryceml** [comment]
https://github.com/saltstack/salt-bootstrap/issues/1527 is related.

**Comment by krionbsd** [comment]
Python3 is the only python version being supported right now
