### ISSUE TITLE
Salt bootstrap script copying all salt binaries to /usr/bin

### ISSUE THREAD

**Issue by Scratchy888** [saltstack/salt-bootstrap#1461]
### Description of Issue/Question
When running these two commands:

curl -o bootstrap-salt.sh -L https://bootstrap.saltstack.com
sudo sh bootstrap-salt.sh git v2019.2.5

It used to only install the salt-minion and ONLY copy over the binaries needed for the salt-minion (salt-call, salt-minion and salt-proxy).
Right now the script is copying all of the binaries it seems. Binaries copied over are: 
salt-api
salt-call
salt-cloud
salt-cp
salt-key
salt-master
salt-minion
salt-proxy
salt-run
salt-ssh
salt-syndic
salt-unity

### Steps to Reproduce Issue
Run:
curl -o bootstrap-salt.sh -L https://bootstrap.saltstack.com
sudo sh bootstrap-salt.sh git v2019.2.5

### Versions and Systems
salt 2018.3.4 and 2019.2.5

**Comment by krionbsd** [comment]
@Scratchy888 2019.2.5 is EoL, I assume it can be closed now
