### ISSUE TITLE
Feature request: Machine readable checksums

### ISSUE THREAD

**Issue by clkamp** [saltstack/salt-bootstrap#1475]
### Description of Issue/Question

Please provide the checksum of the script also in machine readable format. You also provide the checksums here outband, so it would be nice, if they would be available e.g. in a text file with each line one checksum so one could automatically check those.

**Comment by s0undt3ch** [comment]
This is an awesome suggestion, we'll try to address this ASAP.

**Comment by bryceml** [comment]
There are now machine readable checksums in the repo on the stable branch as well as from 

https://bootstrap.saltstack.com/sha256
https://winbootstrap.saltstack.com/sha256
