### ISSUE TITLE
Allow disabling existing repositories to install Salt

### ISSUE THREAD

**Issue by doesitblend** [saltstack/salt-bootstrap#1477]
### Description of Issue/Question
Testing the bootstrap script with Saltify recently I wasn't able to use either the `-r` or `-R` options to ignore existing repository configurations for CentOS 7. The custom script I am using is just a downloaded copy of the bootstrap script with `salt-cloud -u` and then renamed to test using the custom script argument.

### Setup
Please see the attached Saltify configuration for usage.

[saltify.tar.gz](https://github.com/saltstack/salt-bootstrap/files/4773682/saltify.tar.gz)

### Steps to Reproduce Issue
Have a saltstack repository already configured and point it to a random URL, or update the configuration here to point to a random host.

Then execute with the following:

```
# salt-cloud -m /etc/salt/cloud.maps.d/hyperv.conf -P
```

### Versions and Systems
(`salt --versions-report`, `bootstrap-salt.sh -v`, system type and version,
cloud/VM provider as appropriate.)

**Comment by dmurphy18** [comment]
@doesitblend Closing this since RHEL 7 is EOL and no longer supported.  Please feel free to reopen if other matters relevant to this issue come to light.
