### ISSUE TITLE
-R and -x python3 flags are incompatible on centos

### ISSUE THREAD

**Issue by bryceml** [saltstack/salt-bootstrap#1481]
### Description of Issue/Question
You can't install old releases from archive.repo.saltstack.com on centos by specifying `-R archive.repo.saltstack.com -x python3`

This should be able to work with any url, not just archive.repo.saltstack.com

it currently crashes with 
```
 * ERROR: Detected -r or -R option while installing Salt packages for Python 3.
 * ERROR: Python 3 packages for Salt require the EPEL repository to be installed.
 * ERROR: The -r and -R options are incompatible with -x and Python 3 bootstrap installs.
 * ERROR: Failed to run install_centos_stable_deps()!!!
```

@dmurphy18 might know more about the situation.

**Comment by dmurphy18** [comment]
From my rply in community slack:

With Py 3.4 so close to EOL it did not make sense to backport to Salt packages from EPEL that would soon be going out of date.
With the move to Py 3.6 (and the issues that happened with breaking EPEL packages too from Redhat, there was a certain amount of turbulence which fortunately has now settled down)
and Salt now no longer needs EPEL when installing into Centos 7 Py 3.6 environments

**Comment by bryceml** [comment]
Sounds like we're good to remove that hard block then.

**Comment by bryceml** [comment]
This just needs merged from develop to stable now.

**Comment by dmurphy18** [comment]
someone else should do that since I have not done it
