### ISSUE TITLE
rhel7 and oraclelinux7 require optional rpms repos when installing from git

### ISSUE THREAD

**Issue by bryceml** [saltstack/salt-bootstrap#1486]
Rhel7 and oraclelinux7 now have python3 in the repos (not python36 like we had in epel, however the python3 package provides python36), but the python3-devel package is in the optional rpms for both rhel7 and oraclelinux7.  Centos7 provides python3-devel by default it seems.

We should enable those repos if we are installing salt from git.  We should probably respect the -r flag.

https://github.com/saltstack/salt-bootstrap/issues/1449 might be related.

**Comment by bryceml** [comment]
We should also consider testing oraclelinux7 in the github actions since we don't have to worry about registration or anything and it has similar issues to rhel7 which are different from centos7.

**Comment by bryceml** [comment]
noting this here for others:

to enable optional rpms for oracle linux 7:

```bash
yum-config-manager --enable ol7_optional_latest
```

before the bootstrap script

**Comment by myii** [comment]
Thanks for sharing that workaround, @bryceml.  The failing `oraclelinux-7` build is now passing:

* https://gitlab.com/myii/salt-image-builder/-/pipelines/166602413

**Comment by dmurphy18** [comment]
@bryceml Closing this since RHEL 7 is EOL and no longer supported
