### ISSUE TITLE
Fedora 32/33 fail but salt is installed and functioning

### ISSUE THREAD

**Issue by furlongm** [saltstack/salt-bootstrap#1488]
### Description of Issue/Question
Fedora 32 claims installation has failed, but salt is installed and functioning.

### Setup
Fedora 32

### Steps to Reproduce Issue
```
$ bootstrap-salt.sh -X -d -x python3
...
 * ERROR: You need to allow pip based installations (-P) for Tornado <5.0 in order to install Salt
```
### Versions and Systems
```Salt Version:
           Salt: 3001rc1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.9.8
         pygit2: Not Installed
         Python: 3.8.3 (default, May 29 2020, 00:00:00)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 18.1.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: fedora 32
         locale: utf-8
        machine: x86_64
        release: 5.3.18-lp152.19-default
         system: Linux
        version: Fedora 32
```

```
bootstrap-salt.sh -- Version 2020.06.23`
```

**Comment by bryceml** [comment]
I believe it shows the error because there are edge cases where it doesn't work, even though it works for most use cases.  I believe @dwoz is working on making salt compatible with a newer version of tornado and has more information about it.

**Comment by furlongm** [comment]
So looks like https://github.com/saltstack/salt/pull/56169 would fix this, when it gets merged/released?

**Comment by bryceml** [comment]
> So looks like [saltstack/salt#56169](https://github.com/saltstack/salt/pull/56169) would fix this, when it gets merged/released?

Yeah, either in that PR or another one that does the same thing.  I heard they might have to go straight to tornado 6, I don't remember the details though.

**Comment by furlongm** [comment]
FWIW the same issue on Fedora 34.

**Comment by asdorsey** [comment]
This issue persists on Fedora 35.

**Comment by dmurphy18** [comment]
@furlongm Closing this since Fedora 32 is long EOL
