### ISSUE TITLE
Bootstrap fails on Debian 10

### ISSUE THREAD

**Issue by laundry-96** [saltstack/salt-bootstrap#1493]
### Description of Issue/Question
Bootstrap fails on Debian 10 because it installs the wrong repository.

Since I'm using salt-cloud, I have removed some of the tidbits, but here is the output from the bootstrap script:
` *  INFO: Running version: 2020.02.24
 *  INFO: Executed by: 
 *  INFO: Command line: '/tmp/.saltcloud-60ab1e28-2d0c-4c6c-b62d-fd8ddb419a6a/deploy.sh -c /tmp/.saltcloud-60ab1e28-2d0c-4c6c-b62d-fd8ddb419a6a'

 *  INFO: System Information:
 *  INFO:   CPU:          AuthenticAMD
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   5.4.41-1-pve
 *  INFO:   Distribution: Debian 10.5

 *  INFO: Installing minion
 *  INFO: Found function install_debian_deps
 *  INFO: Found function config_salt
 *  INFO: Found function preseed_master
 *  INFO: Found function install_debian_stable
 *  INFO: Found function install_debian_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Found function install_debian_check_services
 *  INFO: Running install_debian_deps()
Hit:1 http://security.debian.org buster/updates InRelease
Hit:2 http://ftp.us.debian.org/debian buster InRelease
Hit:3 http://ftp.us.debian.org/debian buster-updates InRelease
Hit:4 http://download.proxmox.com/debian/pve buster InRelease
Ign:5 https://repo.saltstack.com/apt/debian/10/amd64/latest buster InRelease
Err:6 https://repo.saltstack.com/apt/debian/10/amd64/latest buster Release
  404  Not Found [IP: 143.204.202.71 443]
Reading package lists...Connection to 192.168.1.5 closed.

 * ERROR: Failed to run install_debian_deps()!!!
Error: There was a profile error: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none  -p 22 root@192.168.1.5 '/tmp/.saltcloud-60ab1e28-2d0c-4c6c-b62d-fd8ddb419a6a/deploy.sh -c '"'"'/tmp/.saltcloud-60ab1e28-2d0c-4c6c-b62d-fd8ddb419a6a'"'"''' failed. Exit code: 1`

As you can see, it attempts to use "https://repo.saltstack.com/apt/debian/10/amd64/latest", but according to https://repo.saltstack.com/#debian, we should be using "https://repo.saltstack.com/py3/debian/10/amd64/latest".

A fix for this is changing line 3311 to:
`__PY_VERSION_REPO="py3"`
instead of "apt".

### Setup
(Please provide relevant configs (Be sure to remove sensitive info).)
Just run bootstrap-salt.sh on a debian 10 machine, and you'll run into the issue.

### Steps to Reproduce Issue
(Include debug logs if possible, `bootstrap-salt.sh -D`.)

### Versions and Systems
(`salt --versions-report`, `bootstrap-salt.sh -v`, system type and version,
cloud/VM provider as appropriate.)

**Comment by bryceml** [comment]
you appear to have an older version of the bootstrap script.  This was fixed since then if I remember right.  Can you update and let us know if that fixes the problem?

**Comment by laundry-96** [comment]
Hey! I'm on Fedora Server 32, and the latest packages that are available (and installed) are: 

- salt.noarch              3001rc1-2
- salt-cloud.noarch   3001rc1-2
- salt-master.noarch 3001rc1-2

Is there any way I can get the latest builds on Fedora 32?

**Comment by bryceml** [comment]
There is 3001.4 available now.  I package salt for fedora and there were python dependency issues with 3002 on fedora32.  I probably could have patched the requirement files to use older dependencies and it probably would have worked, but I chose to stick on the safer side.

**Comment by bryceml** [comment]
I'm closing this since I haven't heard back in a while, feel free to re-open it if needed.
