### ISSUE TITLE
The documentation on the readme for the bootstrap script should make more use of stable instead of git. 

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt-bootstrap#1524]
### Description of Issue/Question

Currently, the readme on the github link uses lots of examples of git. however, when using the bootstrap script in production environments this is not what should be used. And without reading more in-depth documentation one would think git is the only operation. 

most of the examples should be a mix of git and stable. with a section explaining that these refer to the different kinds of installs. 
And that for production you most likely want stable. while this documentation does exist elsewhere not many are going to go looking for that documentation when there is documentation right here.

### Steps to Reproduce Issue
Just read the README on the github page.

**Comment by ScriptAutomate** [comment]
This would also help prevent problems like https://github.com/saltstack/salt/issues/59366 coming up. We need to make it clearer that people should be using `stable`, and that people should only be using `git` if they have special use cases perhaps around testing new features that haven't been included in a release yet.

**Comment by sagetherage** [comment]
Interesting, the readme is dated and oddly enough the use of the word `stable` seems more correct, but we stopped using it at some point and it can be controversial when we use it instead of `latest` in Salt, so not to confuse this here, but to simply point it out or plus one - the readme needs updating in this repo, for sure!

**Comment by whytewolf** [comment]
@sagetherage the use of stable in this context is actually an option to the bootstrap script. latest is a version stable is the method of that release. so `bootstrap.sh stable 3001` would point to the 3001 repo. whereas `bootstap.sh git v3001.1` would install from git

And while the readme has been updated to include references to stable. it isn't made clear that stable would be the preferred and better option to use production environment.

**Comment by sagetherage** [comment]
yes, I made a strange reference. I mean I agree with this issue and we need to fix it.

**Comment by dmurphy18** [comment]
@whytewolf Closing since merged in update of README
