### ISSUE TITLE
Remove unsupported versions of Ubuntu and Debian

### ISSUE THREAD

**Issue by jpacura** [saltstack/salt-bootstrap#1528]
### Description of Issue/Question

Saltstack has removed the repository for Ubuntu 14.04, so installing on 14.04 will attempt and fail. 

Ubuntu 17.04, 17.10, 18.10, 19.04, and 19.10 are all end-of-life, and support should be removed from them per the readme:

> Non-LTS Ubuntu releases are not supported once the release reaches End-of-Life as defined by Ubuntu's release schedule.

Debian 8 is end-of-life, and the saltstack repos have been removed, which causes installation to attempt and fail. 

### Setup
Docker containers of all of these versions of Ubuntu and Debian

### Steps to Reproduce Issue
run `sh bootstrap-salt.sh` from the develop branch on these containers

**Comment by jpacura** [comment]
I can't self-assign this, but I am currently working on it

**Comment by bryceml** [comment]
@sagetherage this is all good to do right?

**Comment by bryceml** [comment]
Closing since the PR got merged.
