### ISSUE TITLE
Failing: `yum` is not available in Oracle Linux 8 by default (need to use `dnf` instead)

### ISSUE THREAD

**Issue by myii** [saltstack/salt-bootstrap#1537]
### Description of Issue/Question

We've been building pre-salted images of Oracle Linux 7 & 8 for a while now but it has stopped working for the latter in the last couple of days.

* https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/pipelines/254965423/builds

Spoke to @javierbertoli and he found some info.

https://www.howtoforge.com/centos-8-package-management-with-dnf-on-the-command-line/

> DNF stands for Dandified YUM is a software package manager for RPM-based Linux distributions. It is used to install, update and remove packages in the Fedora/RHEL/CentOS operating system. **It is the default package manager of Fedora 22, CentOS8 and RHEL8**.

* Emphasis above is mine.
* Checked the `oraclelinux:8` image and confirmed that `dnf` is available there.

Thought it would be worth introducing Oracle Linux testing here so tried it out:

* https://github.com/myii/salt-bootstrap/runs/1893703371?check_suite_focus=true

As you can see, all failing due to `yum` not being present.

### Setup
As linked above.

### Steps to Reproduce Issue
As linked above.

### Versions and Systems
As linked above.

**Comment by chruck** [comment]
I had the same problem with docker image `oraclelinux:8`.  Unlike `centos:8`, the OracleLinux docker image is missing the `yum` package, which, among other files, has a symlink for `yum` to `dnf`.  I notice that something has been merged before this comment, but I've only tested the stable version of `salt-bootstrap`.
My workaround was to `dnf install -y yum` before running `salt-bootstrap`.  However, I am hoping that the above merge switches from using deprecated `yum` to `dnf`.

**Comment by myii** [comment]
> My workaround was to `dnf install -y yum` before running `salt-bootstrap`. However, I am hoping that the above merge switches from using deprecated `yum` to `dnf`.

@chruck Unfortunately, the above merge was simply to introduce Oracle Linux 7 CI testing.  I had a look at solving this properly and it would take a fair bit of effort, which may be misplaced since this bootstrap will be replaced by Tiamat-based builds in the (relatively) near future.  The whole CentOS 8 situation is also unsettled, so that's another reason to be cautious.

However, your workaround would be really simple to apply and I could introduce the Oracle LInux 8 CI testing here as well.  Is that a decent compromise in the meantime?
