### ISSUE TITLE
Is there a way to determine if a newer version of saltstack exists?

### ISSUE THREAD

**Issue by dachshund-digital** [saltstack/salt-bootstrap#1552]
Is there a way to determine if a newer version of saltstack exists?  Need to automate method to determine when, say version 3004 has been published.  Linux CLI method to do check would be preferred way if possible.  Would to avoid web page scrap to determine when new version has been published.

**Comment by bryceml** [comment]
you can install `latest` which will always install the latest version.

You could also check if the repo file for the version exists, such as https://repo.saltproject.io/py3/debian/10/amd64/3003/dists/buster/Release or https://repo.saltproject.io/py3/redhat/8/x86_64/3003/repodata/repomd.xml

something like

```bash
if curl -fsSo /dev/null https://repo.saltproject.io/py3/debian/10/amd64/3004/dists/buster/Release
then 
  echo 3004 is available
else
  echo 3004 is not available
fi
```

That's the best I can think of right now.

**Comment by dachshund-digital** [comment]
Cool, thanks for the information, I also did a query to the apt repo for the OS (Dbian 10) and got the latest (stable) version as well.  I but since the OS distro maybe dated, much prefer your approach.  However, I can't seem to get a list of available versions?  Would that not be the most flexible?  Apparently the design/structure of the repo web site will not let someone grab a list of available versions?  So you have to guess what the next version available will be?
