### ISSUE TITLE
Salt minion fails to start in Amazon Linux 2 with urllib3 version conflict

### ISSUE THREAD

**Issue by prandelicious** [saltstack/salt-bootstrap#1564]
### Description of Issue/Question

The bootstrap script was able to install all packages but it fails to start the salt-minion service with this error:

```
salt-minion[4031]: Traceback (most recent call last):
salt-minion[4031]: File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666,
salt-minion[4031]: ws.require(__requires__)
salt-minion[4031]: File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 984,
salt-minion[4031]: needed = self.resolve(parse_requirements(requirements))
salt-minion[4031]: File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 875,
salt-minion[4031]: raise VersionConflict(dist, req).with_context(dependent_req)
salt-minion[4031]: pkg_resources.ContextualVersionConflict: (urllib3 1.25.6 (/usr/lib/python3.7/
salt-minion[4031]: During handling of the above exception, another exception occurred:
salt-minion[4031]: Traceback (most recent call last):
salt-minion[4031]: File "/usr/bin/salt-minion", line 6, in <module>
salt-minion[4031]: from pkg_resources import load_entry_point
salt-minion[4031]: File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3147,
salt-minion[4031]: @_call_aside
salt-minion[4031]: File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3131,
salt-minion[4031]: f(*args, **kwargs)
salt-minion[4031]: File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3160,
salt-minion[4031]: working_set = WorkingSet._build_master()
salt-minion[4031]: File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 668,
salt-minion[4031]: return cls._build_from_requirements(__requires__)
salt-minion[4031]: File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 681,
salt-minion[4031]: dists = ws.resolve(reqs, Environment())
salt-minion[4031]: File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 870,
salt-minion[4031]: raise DistributionNotFound(req, requirers)
salt-minion[4031]: pkg_resources.DistributionNotFound: The 'urllib3<1.24,>=1.21.1' distribution
systemd[1]: salt-minion.service: main process exited, code=exited, status=1/FAILURE
systemd[1]: Failed to start The Salt Minion.
systemd[1]: Unit salt-minion.service entered failed state.
systemd[1]: salt-minion.service failed.
```

### Setup
`cat /etc/os-release`
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

### Steps to Reproduce Issue
`curl -fsSL https://bootstrap.saltproject.io -o install_salt.sh`
`sh install_salt.sh -P -x python3`

Output of /tmp/bootstrap-salt.log:

```
 *  INFO: Running version: 2021.03.02
 *  INFO: Executed by: sh
 *  INFO: Command line: 'install_salt.sh -P -x python3'
 *  INFO: Detected -x option. Using python3 to install Salt.

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   4.14.231-173.361.amzn2.x86_64
 *  INFO:   Distribution: Amazon Linux AMI 2

 *  INFO: Installing minion
 *  INFO: Found function install_amazon_linux_ami_2_deps
 *  INFO: Found function config_salt
 *  INFO: Found function preseed_master
 *  INFO: Found function install_amazon_linux_ami_2_stable
 *  INFO: Found function install_amazon_linux_ami_2_stable_post
 *  INFO: Found function install_amazon_linux_ami_2_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Found function install_amazon_linux_ami_2_check_services
 *  INFO: Running install_amazon_linux_ami_2_deps()
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
Package yum-utils-1.1.31-46.amzn2.0.1.noarch already installed and latest version
Nothing to do
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
Package python3-m2crypto-0.31.0-4.amzn2.x86_64 already installed and latest version
Package python3-pyyaml-4.2-0.1.b5.amzn2.x86_64 already installed and latest version
Package python3-crypto-2.6.1-26.amzn2.x86_64 already installed and latest version
Package python3-jinja2-2.10-8.amzn2.noarch already installed and latest version
Package procps-ng-3.3.10-26.amzn2.x86_64 already installed and latest version
Package python3-msgpack-0.5.6-7.amzn2.x86_64 already installed and latest version
Package python3-requests-2.19.1-5.amzn2.noarch already installed and latest version
Package python3-zmq-17.0.0-5.amzn2.x86_64 already installed and latest version
Nothing to do
 *  INFO: Running install_amazon_linux_ami_2_stable()
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
Resolving Dependencies
--> Running transaction check
---> Package salt-minion.noarch 0:3003-1.amzn2 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package          Arch        Version             Repository               Size
================================================================================
Installing:
 salt-minion      noarch      3003-1.amzn2        saltstack-py3-repo       39 k

Transaction Summary
================================================================================
Install  1 Package

Total download size: 39 k
Installed size: 72 k
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
Warning: RPMDB altered outside of yum.
  Installing : salt-minion-3003-1.amzn2.noarch                              1/1
  Verifying  : salt-minion-3003-1.amzn2.noarch                              1/1

Installed:
  salt-minion.noarch 0:3003-1.amzn2

Complete!
 *  INFO: Running install_amazon_linux_ami_2_stable_post()
 *  INFO: Running install_amazon_linux_ami_2_check_services()
 *  INFO: Running install_amazon_linux_ami_2_restart_daemons()
Job for salt-minion.service failed because the control process exited with error code. See "systemctl status salt-minion.service" and "journalctl -xe" for details.
 *  INFO: Running daemons_running()
 * ERROR: salt-minion was not found running
 * ERROR: Failed to run daemons_running()!!!
 * ERROR: salt-minion was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
 ``` 

### Versions and Systems
install_salt.sh -- Version 2021.03.02

AWS EC2 x86_64 instance
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

**Comment by snardone** [comment]
Same issue, salt-minion 3002.6 on Amazon Linux 2. Temporary workaround was to downgrade python3-requests.

`sudo yum downgrade python3-requests-2.14.2-2.amzn2.0.2`

Looking for a better solution.

**Comment by bryceml** [comment]
Is this still an issue?  I believe this should be fixed now.  Can this be closed?

**Comment by alpana17** [comment]
I am still facing the issue...
` *  INFO: Running install_amazon_linux_ami_2_deps()
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
https://repo.saltproject.io/py3/amazon/2/aarch64/latest/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.


 One of the configured repositories failed (SaltStack Python 3 repo for Amazon Linux 2),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=saltstack-py3-repo ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable saltstack-py3-repo
        or
            subscription-manager repos --disable=saltstack-py3-repo

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=saltstack-py3-repo.skip_if_unavailable=true

failure: repodata/repomd.xml from saltstack-py3-repo: [Errno 256] No more mirrors to try.
https://repo.saltproject.io/py3/amazon/2/aarch64/latest/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
https://repo.saltproject.io/py3/amazon/2/aarch64/latest/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.


 One of the configured repositories failed (SaltStack Python 3 repo for Amazon Linux 2),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=saltstack-py3-repo ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable saltstack-py3-repo
        or
            subscription-manager repos --disable=saltstack-py3-repo

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=saltstack-py3-repo.skip_if_unavailable=true

failure: repodata/repomd.xml from saltstack-py3-repo: [Errno 256] No more mirrors to try.
https://repo.saltproject.io/py3/amazon/2/aarch64/latest/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
 * ERROR: Failed to run install_amazon_linux_ami_2_deps()!!!`
