### ISSUE TITLE
Debian 11 repo support

### ISSUE THREAD

**Issue by smitelli** [saltstack/salt-bootstrap#1614]
More of a to-do item than a bug, but...

In [this block](https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L3353-L3359) of bootstrap-salt.sh, the Debian release/codename are hacked to 10/`buster` in the case where the system is running Debian version 11. Apparently this was due to lack of upstream packages for this release in the past.

Since that time, the official Salt repo has added [Debian 11](https://repo.saltproject.io/#debian) packages, suggesting this special case is no longer required.

Happy to volunteer to test this in any way I can. Thanks!

**Comment by jpacura** [comment]
I'll be happy to take care of this if nobody else is already working on it

**Comment by jpacura** [comment]
I created a pull request that will use the native repositories for Debian 11, and also adds best-effort support for Debian Testing using the Debian 11 packages. I have tested this PR using Debian 11 and Debian Testing Docker containers. Please test this PR and let me know if I need to make any changes to it

**Comment by categulario** [comment]
I wonder if a similar fix can be applied to fix the problem I just faced trying to install salt on debian 12:

```
 *  INFO: Running install_debian_onedir_deps()
Hit:1 http://security.debian.org/debian-security bookworm-security InRelease
Hit:2 http://deb.debian.org/debian bookworm InRelease
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease
Ign:4 https://repo.saltproject.io/salt/py3/debian/12/amd64/latest stretch InRelease
Err:5 https://repo.saltproject.io/salt/py3/debian/12/amd64/latest stretch Release
  404  Not Found [IP: 2600:9000:2156:8000:14:e045:6d80:93a1 443]
Reading package lists...
 * ERROR: Failed to run install_debian_onedir_deps()!!!
```

**Comment by dmurphy18** [comment]
@smitelli  Closing this as fixed in release of the bootstrap 2024-07-12, see https://github.com/saltstack/salt-bootstrap/actions/workflows/ci.yml.  Please feel free to reopen if other matters relevant to this issue come to light.
