### ISSUE TITLE
salt-cloud configs in /tmp/ not copied over for Ubuntu

### ISSUE THREAD

**Issue by techhat** [saltstack/salt-bootstrap#17]
I was testing salt-cloud with an older version of salt-bootstrap (sorry, I don't know which one) and was able to successfully spin up an Ubuntu box on the HP cloud service, and have the configs copied over for me. Then, realizing I was running an older version, I updated to the latest git. Now it still installs salt properly, but does not copy over the config files.

Looking at the source, I'm not sure this will currently work for anything but Debian.

**Comment by akoumjian** [comment]
Is it not running the config_minion() function? It should grab the default config_minion() function here: https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt-minion.sh#L914

As long as you pass the script the `--config-dir` option it should execute the config function and copies the files into place.

**Comment by techhat** [comment]
Is the --config-dir option required for this?

**Comment by akoumjian** [comment]
Yes, in fact it was added specifically with salt-cloud in mind. Normally when you are bootstrapping the default setting is to generate new keys & copy over the template minion config.

**Comment by akoumjian** [comment]
Alternatively, when you are scping the keys/config over, you could just place them at whatever their final destination should be.

**Comment by techhat** [comment]
Looks like I was previously using a version that was incorrectly using config-dir automatically. I have updated salt-cloud correctly, and it seems to work admirably.
