### ISSUE TITLE
Archlinux Salt Old

### ISSUE THREAD

**Issue by teburd** [saltstack/salt-bootstrap#170]
The bootstrap script installs a semi-old version of salt (0.13.1) where as the newer version solves some bugs that I found with pecl.installed

Would be nice to have up to date archlinux salt packages or use the aur.archlinux.org package build files as described on the saltstack site.

**Comment by techhat** [comment]
We'll want to ping @cedwards, who manages both intothesaltmine.org and the AUR packages.

**Comment by s0undt3ch** [comment]
The latest version of salt, `0.16.2`, is in [AUR](https://aur.archlinux.org/packages/salt/) now. Closing. Please reopen if necessary.

**Comment by s0undt3ch** [comment]
And 0.16.2 is now also in http://intothesaltmine.org/archlinux/

So this is fixed.
