### ISSUE TITLE
Create deb and rpm packages

### ISSUE THREAD

**Issue by s0undt3ch** [saltstack/salt-bootstrap#173]

**Comment by vutny** [comment]
@s0undt3ch Looks like this was resolved long time ago :-)

**Comment by vutny** [comment]
@jfindlay How about to close this? Thanks.

**Comment by jfindlay** [comment]
@vutny, it is possible.  @s0undt3ch, did you intend to create deb and rpm packages for bootstrap itself?

**Comment by s0undt3ch** [comment]
It was an idea when we didn't host the script through HTTPS. But this never really got interest from anyone. Let's close it.
