### ISSUE TITLE
FreeBSD 9.1 salt-bootstrap error

### ISSUE THREAD

**Issue by chadhs** [saltstack/salt-bootstrap#174]
I tried with the development version as well and it errors out on the package repository since the pkgng FreeBSD package mirror does not contain any packages other than pkg.

https://gist.github.com/chadhs/07d3c4d3d68ab9043b5e#file-freebsd-9-1-salt-bootstrap-error

**Comment by s0undt3ch** [comment]
Yes, this is expected, notice the warning line:

```
WARN: The installation will, most likely fail since pkgbeta.freebsd.org does not yet contain any packages
pkg.txz 
```

You have to provide your own `PACKAGESITE` environment variable while the pkgbeta repo is not fixed.

You can try ftp://ftp.pcbsd.org/pub/mirror/packages/9.1-RELEASE/amd64

**Comment by chadhs** [comment]
10-4, i'll make part of our FreeBSD bootstrap process to inject our PACKAGESITE into pkg.conf once I have our package repo built.

**Comment by s0undt3ch** [comment]
You can also do, for example:

``` bash
PACKAGESITE=http://foo.bar bootstrap-salt.sh -D
```

The script [will do that for you](https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L2096) :)

**Comment by chadhs** [comment]
awesome!

s0undt3ch, if we wanted to be lame — for now — could we also alter it to use pkg_\* legacy pkg tools vs pkgng?  on my existing "fleet" I'm not read to do the irreversible `pkg2ng`

**Comment by s0undt3ch** [comment]
Well, I'm not a FreeBSD user, most FreeBSD code was submitted by others. That said, I think that an effort was made to use pkg and not pkgng if the first is found on the system. But I also think that a migration is done.

Anyway, we accept pull requests :)
Meaning, clone our repo, change the code to do what you need without breaking existing code and we'll gladly accept it.

Let me know if you need any help while hacking our script.

## 

Pedro Algarvio @ phone

----- Reply message -----
De: "Chad Stovern" notifications@github.com
Para: "saltstack/salt-bootstrap" salt-bootstrap@noreply.github.com
Cc: "Pedro Algarvio" pedro@algarvio.me
Assunto: [salt-bootstrap] FreeBSD 9.1 salt-bootstrap error (#174)
Data: ter, Jul 2, 2013 20:19
awesome!

s0undt3ch, if we wanted to be lame — for now — could we also alter it to use pkg_\* legacy pkg tools vs pkgng?  on my existing "fleet" I'm not read to do the irreversible pkg2ng

&mdash;

**Comment by chadhs** [comment]
excellent thanks!  =)

**Comment by s0undt3ch** [comment]
Anytime!!!

## 

Pedro Algarvio @ phone

----- Reply message -----
De: "Chad Stovern" notifications@github.com
Para: "saltstack/salt-bootstrap" salt-bootstrap@noreply.github.com
Cc: "Pedro Algarvio" pedro@algarvio.me
Assunto: [salt-bootstrap] FreeBSD 9.1 salt-bootstrap error (#174)
Data: ter, Jul 2, 2013 21:10
excellent thanks!  =) 

&mdash;

**Comment by chadhs** [comment]
The ultimate of laziness er uh efficiency–related shenanigans:

## Bootstrapping my Bootstrap — FreeBSD

91bootstrap.sh script sitting at the root of my poudriere pkgng repo:

```
#!/bin/sh
export PACKAGESITE="http://pkg.colo.example.com/91release-default" ; fetch -o - http://bootstrap.saltstack.org | sh ; echo "master: maestro.example.com" >> /usr/local/etc/salt/minion && service salt_minion restart
```

from a brand new box

```
fetch -o - http://pkg.colo.example.com/91bootstrap.sh | sh
```

Then I can just go accept my key on the master and I'm all set!

**Comment by s0undt3ch** [comment]
You know that you can upload a configuration file to a temporary directory, set the bootstrap script to look at that directory and the minion and/or master will configured with that(those) file(s)?

You can even point to the bootstrap script to an [URL](https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L159) of a compressed file which it will extract to a temporary directory and used the files within to configure the master and/or minion.

**Comment by chadhs** [comment]
fantastic.  just grabbed the dev version of the bootstrap script and was looking at the args this weekend.
