### ISSUE TITLE
Installing with for a different Python version than the one used by the OS

### ISSUE THREAD

**Issue by JeremieCharest** [saltstack/salt-bootstrap#176]
How can we install salt for a different Python version than the one used by the OS. I'm on CentOs 6.4 which use Python 2.6 by default but I need Python 2.7 without changing the python2 or python symlink.

I looked in the bootstrap-salt.sh, under the CentOs section, the following commands can be use "yum -y install PyYAML m2crypto python-crypto...." or "python2 setup.py install" which in my case won't do what I want.

What can I do to specified which Python version to install dependencies into it?

**Comment by s0undt3ch** [comment]
Well, salt requires a minimum of python 2.6. Aside from that, there's currently no way to specify an alternative python version to the script. We accept pull requests though... So, if you can implement what you need without breaking existing functionality, we'll gladly merge your changes.

## 

Pedro Algarvio @ phone

----- Reply message -----
De: "evilNullPointer" notifications@github.com
Para: "saltstack/salt-bootstrap" salt-bootstrap@noreply.github.com
Assunto: [salt-bootstrap] Installing with for a different Python version than the one used by the OS (#176)
Data: qua, Jul 3, 2013 15:34
How can we install salt for a different Python version than the one used by the OS. I'm on CentOs 6.4 which use Python 2.6 by default but I need Python 2.7 without changing the python2 or python symlink. 

I looked in the bootstrap-salt.sh, under the CentOs section, the following commands can be use "yum -y install PyYAML m2crypto python-crypto...." or "python2 setup.py install" which in my case won't do what I want. 

What can I do to specified which Python version to install dependencies into it? 

&mdash;

**Comment by JeremieCharest** [comment]
Thanks for the answer. We will downgrade our requirements to 2.6 to unified our environments because we are time and budget limited.
