### ISSUE TITLE
salt-bootstrap installation from git on FreeBSD installs some files to the "wrong" location

### ISSUE THREAD

**Issue by chadhs** [saltstack/salt-bootstrap#178]
salt-bootstrap installation from git on FreeBSD installs some files to the "wrong" location.

i made sure to run the development bootstrap script against the development git tree of salt as per the issue instructions.

when installing a minion or a master the pki stuff is created under /etc/salt/ and the master or minion configs are placed under /usr/local/etc/salt/ (as they should be).

anything not part of the canonical system should be installed under /usr/local/ like the ports tree version (sysutils/py-salt) does.

let me know if any other info is needed; thank you.  =)

**Comment by s0undt3ch** [comment]
Well, I have all the information necessary.
The bootstrap script does not configure the salt master and/or minion. It only places the configurations/keys provided by the user(if any) on the right place.

Are you also providing the minion keys to the script?

**Comment by s0undt3ch** [comment]
Hmm, I think I found a bug, which should have been catch already.

Still, need the info above :)

**Comment by s0undt3ch** [comment]
#179 has made some changes on how the PKI_DIR setting is handled, could you re-try the dev script?

**Comment by chadhs** [comment]
s0undt3ch i was merely running the bootstrap script with no additional options and also with the -M & -N to install a "master" — not providing any keys etc to the script.

I have two VMs on my Mac that I have snapshot'd just after a virgin FreeBSD 9.1-RELEASE-p4 build.  Vanilla install with only the root user, no other packages etc.  These are my perpetual test subjects for testing bootstrap deployment techniques FYI.

I'll retry and report back thnx.

**Comment by chadhs** [comment]
just retried it for minion and master

`fetch -o - https://raw.github.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh | sh -s -- git v0.16.0`

`fetch -o - https://raw.github.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh | sh -s -- -M -N git v0.16.0`

the /usr/local/etc/salt/pki paths are created in both instances but the /etc/salt/pki path is as well and the actual files get populated in /etc/salt/pki in the case of the master, and in both places in case of the minion / no options install.

master screenshot: http://orbt.io/Q5cx.png
minion screenshot: http://orbt.io/Q6aO.png

**Comment by s0undt3ch** [comment]
Ok.
It will fail though. We don't touch the configuration file, not the default ones, nor the user provided one's. This means that the pki setting will pointing to salt's default which are not proper for FreeBSD.

Your only alternative is to provide a configuration file to the script.

## 

Pedro Algarvio @ phone

----- Reply message -----
De: "Chad Stovern" notifications@github.com
Para: "saltstack/salt-bootstrap" salt-bootstrap@noreply.github.com
Cc: "Pedro Algarvio" pedro@algarvio.me
Assunto: [salt-bootstrap] salt-bootstrap installation from git on FreeBSD installs some files to the "wrong" location (#178)
Data: dom, Jul 7, 2013 22:42
s0undt3ch i was merely running the bootstrap script with no additional options and also with the -M & -N to install a "master" — not providing any keys etc to the script.

I have two VMs on my Mac that I have snapshot'd just after a virgin FreeBSD 9.1-RELEASE-p4 build.  Vanilla install with only the root user, no other packages etc.  These are my perpetual test subjects for testing bootstrap deployment techniques FYI.

I'll retry and report back thnx.

&mdash;

**Comment by chadhs** [comment]
Passing in a master config that defines the appropriate paths for FreeBSD?

**Comment by s0undt3ch** [comment]
Yes, just read your last comment... As supposed, it failed.

**Comment by s0undt3ch** [comment]
Exactly.

**Comment by s0undt3ch** [comment]
Since no configuration file is passed, and none exists, at least properly configured, salt default settings are used, which aren't proper for FreeBSD

**Comment by chadhs** [comment]
I'll do some more tinkering tonight, report back, then close this ticket.  once i get it working as expected would it warrant an example in the readme?  at a minimum i'll post a gist or something in this ticket — thanks man.

**Comment by chadhs** [comment]
@s0undt3ch forgive my combination of failure to parse & tiredness? but I'm not understanding what optarg allows me to pass in the config option.

I've also been studying the ports tree build and it appears they're achieving what I'm looking for by altering the setup.py for salt.

screenshot: http://orbt.io/Q5pC.png

EDIT:
patch file screenshot (from the 0.15.3 FreeBSD port):
http://orbt.io/Q6TB.png

**Comment by s0undt3ch** [comment]
Yep. I also started thinking on applying the patch from the ports tree but that would still not be enough.
We might still need to add an extra patch to the source code to update the default configuration to the proper paths...

I'll see what I can do ;)

**Comment by chadhs** [comment]
I made a tarball of the current port dir that contains all the maintainers patches etc and uploaded to my app.net file storage if you or anyone else working on salt would care to look at what they are doing:

http://orbt.io/Q8hl.gz

**Comment by s0undt3ch** [comment]
Thanks!

**Comment by gravyboat** [comment]
@s0undt3ch Now that https://github.com/saltstack/salt/pull/6890 is done, can this issue be closed?

**Comment by s0undt3ch** [comment]
Yep! For versions lower than 0.17 the source is patched, >= 0.17 the paths are properly passed to the setup script.

**Comment by s0undt3ch** [comment]
This is still on the develop version of the bootstrap script.
