### ISSUE TITLE
Bootstrap git

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt-bootstrap#18]
Would it be possible to have salt-bootstrap install git so it can clone and install a specific branch or commit hash?

Or is this functionality already included?

**Comment by UtahDave** [comment]
I'm sorry. I got off my behind and actually took a cursory glance at the source, and git is already installed by salt-bootstrap.

Sorry for the noise.

**Comment by akoumjian** [comment]
We should make it more clear in the docs what parameters you can pass to bootstrap.
