### ISSUE TITLE
SHA256 in README is wrong for 2022-03-15

### ISSUE THREAD

**Issue by cwacekINV** [saltstack/salt-bootstrap#1812]
### Setup
The README says that the SHASUM is `8f65952c3435f441e7f793941d5162d3ec2033a9ef82722ff1da67a2ef860a2f`. 

It's actually `ed66dc9e71aed7602b9ae548f8535131831026f934f19f868fdefbe6a3ab9bf9`. Unclear where the discrepancy is from. 

### Steps to Reproduce Issue

```
$ wget https://raw.githubusercontent.com/saltstack/salt-bootstrap/v2022.03.15/bootstrap-salt.sh
$ shasum -a256 bootstrap-salt.sh
ed66dc9e71aed7602b9ae548f8535131831026f934f19f868fdefbe6a3ab9bf9  bootstrap-salt.sh
```

### Versions and Systems
N/A

**Comment by driskell** [comment]
If you're accessing it using that URL it goes to the tagged version which it seems is not the full release. I do think it used to be recommended to use that URL but yes going forwards I don't think it's the right way and isn't documented anymore.

E.g. for 2022.08.13 you can see the repository file at that tag is still unstable flagged:
https://github.com/saltstack/salt-bootstrap/blob/v2022.08.13/bootstrap-salt.sh#L587

You should use the release asset link which has that line removed, and is listed in the GitHub releases downloads:
https://github.com/saltstack/salt-bootstrap/releases/download/v2022.03.15/bootstrap-salt.sh

Latest is:
https://github.com/saltstack/salt-bootstrap/releases/download/v2022.08.13/bootstrap-salt.sh

**Comment by dmurphy18** [comment]
@cwacekINV Can you retry with the latest bootstrap script which has been heavily updated this July, noting that support for older EOL version of Salt has been dropped. If the latest version of the bootstrap script resolves your issues, please consider closing this issue.

**Comment by dmurphy18** [comment]
Closing this since the bootstrap script have been updated since then, no longer using Kitchen and now use GitHub Actions.

Please reopen if you encounter futher issues.
