### ISSUE TITLE
bootstrap script not working

### ISSUE THREAD

**Issue by danielduduta** [saltstack/salt-bootstrap#1813]
### Description of Issue/Question
bootstrap script not working
### Setup
(Please provide relevant configs (Be sure to remove sensitive info).)
https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh
### Steps to Reproduce Issue
wget https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh
sh bootstrap-salt.sh -P stable 3003.3
* ERROR: https://repo.saltproject.io/py3/debian/10/amd64/archive/3003.3/salt-archive-keyring.gpg failed to download to /tmp/salt-gpg-BoYnlREp.pub
 * ERROR: Failed to run install_debian_deps()!!!

### Versions and Systems
Linux  4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux

**Comment by krionbsd** [comment]
3003.3 was moved to `archive` because of security issues:
https://saltproject.io/security_announcements/salt-security-advisory-release/ please use 3003.4 instead.
