### ISSUE TITLE
bootstrap-salt.ps1 stopped working with -version argument

### ISSUE THREAD

**Issue by shoemocker** [saltstack/salt-bootstrap#1815]
### Description of Issue/Question
The powershell bootstrap script seems to have stopped working with the -version argument

If you look at where it says downloading salt minion installer it says the remote server returned an error 404 not found

This was working in the past and doesn't seem to work anymore. Even tried the new 3003.4 and still the same issue.

### Setup
Any windows server or windows desktop

### Steps to Reproduce Issue
PS C:\Users\mschumaker> Invoke-WebRequest -Uri https://winbootstrap.saltproject.io -OutFile C:\bootstrap-salt.ps1
PS C:\Users\mschumaker> C:\bootstrap-salt.ps1 -master salt.domaingoeshere.com -version 3003.3
Get-ItemProperty: C:\bootstrap-salt.ps1:190
Line |
 190 |  $RootDir = If ((Get-ItemProperty $SaltRegKey).root_dir -ne $null) {
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'HKLM:\SOFTWARE\Salt Project\Salt' because it does not exist.

Downloading Salt minion installer Salt-Minion-3003.3-Py3-AMD64-Setup.exe
MethodInvocationException: C:\bootstrap-salt.ps1:268
Line |
 268 |      $webclient.DownloadFile($url, $file)
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not
     | Found."

Installing Salt minion
Start-Process: C:\bootstrap-salt.ps1:287
Line |
 287 |      Start-Process C:\Windows\Temp\$saltExe -ArgumentList "/S $paramet …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This command cannot be run due to the error: The system cannot find the file specified.

### Versions and Systems
3003.3

**Comment by mlasevich** [comment]
Not sure why this is closed, but as of last weekend you can no longer use version aliases (`3003` or `3003.4`) - you have to use EXACT version - `3003.4-1`
