### ISSUE TITLE
Bootstrap cannot download general version ids, only very specific ones

### ISSUE THREAD

**Issue by mlasevich** [saltstack/salt-bootstrap#1816]
Reopening #1815 

Upon looking into it, it looks like only aliases stopped working - so:
* `3003` does not work (was working until end of last week)
* `3003.4` does not work
* `3003.4-1` works

This may be due to something changing on the repo side :-/

**Comment by mlasevich** [comment]
Looking at the lack of changes in recent weeks, it is likely a repo issue

**Comment by dmurphy18** [comment]
Looking at the repo to see what is happening

**Comment by dmurphy18** [comment]
See the problem and fixing it

**Comment by dmurphy18** [comment]
The fix is now live, so closing this.
If you continue to see problem, please re-open it and I shall try to address it
