### ISSUE TITLE
Bootstrap fails for cloud deployment using git on ubuntu 18.04 LTS minion

### ISSUE THREAD

**Issue by justinegreene** [saltstack/salt-bootstrap#1817]
### Description of Issue/Question
This seems similar to 

https://github.com/saltstack/salt-bootstrap/commit/f7fcdd2d48f929e03e9f2083371fd7dc4568e74e

but for Ubuntu 18.04.6 LTS.

I am unable to upgrade my master to 3004.1 so I needed to pin my minion version at 3004 since both 3004.1 and 3003.1 are not backwards compatible.  The repos do not seem to have 3004 (3004.0) available by version (tried 3003, but 3003.4 has the same compatibility issue and 3003.3 does not seem to be available by version either), so I needed to install using git and the commit associated with the 3004 release (if I have missed something here with pinning an older version I apologize).  When running the installation using git, it failed with an error that indicating that I need to run:

`sudo apt-get gcc python3-dev`

Which is easy if running bootstrap.sh from the console, but not from a cloud install.  Resolved the issue by following:

`    # Additionally install procps and pciutils which allows for Docker bootstraps. See 366#issuecomment-39666813
    __PACKAGES="${__PACKAGES} procps pciutils"`

with

`    # and install packages required for git compiling
    __PACKAGES="${__PACKAGES} gcc python3-dev"`

in bootstrap.sh.  I am not sure if this is the best way (maybe a conditional to only run for git installs) but it did resolve the problem, and allow 3004 to install properly and install my instance to be created properly.

### Setup
Saltmaster:
Ubuntu v16.04 LTS
Salt-master v3001.8
bootstrap.sh v2022.03.15 and v2021.09.17 both had the issue
the following added to /etc/salt/cloud to specify the 3004 tag (3004.0):
`script_args: git bac2d1e6aeea8f12dd1712207b87ea2695f35b7c`

### Steps to Reproduce Issue
Install new instance on GCP specifying a git commit. Though I imagine this will be an issue with any configuration as it has to do with the packages that bootstrap is installing.

`sudo salt-cloud -p [profile] [machine-name]`

### Versions and Systems
mastere:
$ salt --versions-report
Salt Version:
           Salt: 3001.8

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
         Jinja2: 2.8
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.7
         pygit2: Not Installed
         Python: 3.5.2 (default, Jan 26 2021, 13:30:48)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 17.1.2
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: ubuntu 16.04 Xenial Xerus
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-1098-gcp
         system: Linux
        version: Ubuntu 16.04 Xenial Xerus

bootstrap:
./bootstrap-salt.sh -- Version 2022.03.15

Google cloud building an ubuntu 18.04.6 LTS image.

**Comment by dmurphy18** [comment]
@justinegreene Closing this sinc eUbuntu 18.04 is no longer supported and is EOL
