### ISSUE TITLE
Ubuntu 22.04 LTS repo not found when using bootstrap script.

### ISSUE THREAD

**Issue by eedgar** [saltstack/salt-bootstrap#1821]
### Description of Issue/Question
New Ubuntu 22.04 LTS released
### Setup
(Please provide relevant configs (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible, `bootstrap-salt.sh -D`.)
use ubuntu 22.04 and try to install using packages.  

### Versions and Systems
(`salt --versions-report`, `bootstrap-salt.sh -v`, system type and version,
cloud/VM provider as appropriate.)

Upstream 22.04 repo not created yet.  the script should either fallback to 20.04 or have the repo be created.

**Comment by krionbsd** [comment]
yes, repo doesn't exist because no packages were done for 22.04. 22.04 was released a couple of days ago, fix to fallback to 20.04 will be merged soon

**Comment by eedgar** [comment]
@krionbsd Thanks,  I figured a fix would come soon.  I just wanted to report the issue, in case someone wasn't aware of it.

Thanks for the timely response.

**Comment by krionbsd** [comment]
Temporary fix as fallback to 20.04 packages is merged into develop branch

**Comment by russellballestrini** [comment]
I hit this snag today, looking for a work around.

will try pulling from develop branch.

Can confirm fix made it into develop branch!

That said, I also needed to delete the following file:

```
rm /etc/apt/sources.list.d/salt.list
```

before installing the minion, running:

```
git clone https://github.com/saltstack/salt-bootstrap.git
cd salt-bootstrap
bash salt-boostrap.sh
```

working!

**Comment by ekristen** [comment]
It's been 3 months. When will there be 22.04 repos?

**Comment by sbogun** [comment]
Hey, Ubuntu 22.04 is standard since months. Why do you not provide the saltstack packages?

**Comment by mherrb** [comment]
Is this the sign that the free and open source version of saltstack is slowly abandonned by VMware ? I hope not.

**Comment by Foorack** [comment]
@mherrb No. I believe I have found the reason. Reportedly salt-master has a critical bug with Python 3.10, which comes shipped with 22.04 by default. This means we must wait for 3005 to hit stable (it is only at 3005rc2 yet) before 22.04 can be added to repo.
https://github.com/saltstack/salt/issues/62202#issuecomment-1221165594

**Comment by Foorack** [comment]
> Hey, Ubuntu 22.04 is standard since months. Why do you not provide the saltstack packages?

@sbogun Because according to this issue https://github.com/saltstack/salt/issues/62229, Salt is currently broken on 22.04. We must wait for 3005 to hit stable. Not super familiar with the inner workings of this project, but the milestone for 3005 is **98% done**: https://github.com/saltstack/salt/milestone/115

**Comment by morgana2313** [comment]
`curl -Ls https://bootstrap.saltstack.com | sh /dev/stdin -FXPdq stable` on ubuntu 22.04 gives me v3005 now:

```
Salt Version:
          Salt: 3005

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.3
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.11.0
        pygit2: Not Installed
        Python: 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 22.3.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 22.04 Jammy Jellyfish
        locale: utf-8
       machine: x86_64
       release: 4.15.0-147-generic
        system: Linux
       version: Ubuntu 22.04 Jammy Jellyfish
```

**Comment by garethgreenaway** [comment]
Salt 3005 has packages available for 22.04 so it's not install-able from the bootstrap script, so I'm going to close this one out.

**Comment by tarcisiomiranda** [comment]
## Install salt 3004.2 on Ubuntu 22.04
```
curl -Ls https://bootstrap.saltstack.com | sh /dev/stdin -FXPdq stable 3004.2
```

@morgana2313 Thx

**Comment by morgana2313** [comment]
Dank voor uw bericht.

Ik ben afwezig tot 8 januari 2023 en lees sporadisch mijn mail.

Voor dringende zaken kunt u contact opnemen met mijn collega's via 070 891 9 891 of via ***@***.***
