### ISSUE TITLE
Remove Ubuntu 16.04 as supported OS, or fix script

### ISSUE THREAD

**Issue by pnickerson-cashstar** [saltstack/salt-bootstrap#1822]
### Description of Issue/Question
I have seen around that Salt Project no longer officially supports Ubuntu 16.04. However, the Salt bootstrap documentation indicates it is. And running the bootstrap script on Ubuntu 16.04 results in a download error.

### Setup
Ubuntu 16.04.7 LTS (Xenial Xerus)
AWS AMI ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20210928

### Steps to Reproduce Issue
```
./bootstrap-salt.sh -x python3
...
 * ERROR: https://repo.saltproject.io/py3/ubuntu/16.04/amd64/latest/salt-archive-keyring.gpg failed to download to /tmp/salt-gpg-100DzMMc.pub
 * ERROR: Failed to run install_ubuntu_stable_deps()!!!
```

### Versions and Systems
`./bootstrap-salt.sh -- Version 2022.03.15`

The bootstrap script attempts to access https://repo.saltproject.io/py3/ubuntu/16.04/amd64/, but that directory no longer exists. The script code under "`Ubuntu versions not supported`" indicates that it expects to be able to run on Ubuntu 16.04.

The documentation at https://github.com/saltstack/salt-bootstrap#ubuntu-and-derivatives explicitly states that 16.04 is supported, and 16.04 is mentioned elsewhere on that page too.

The script and documentation should either be updated to no longer support Ubuntu 16.04 (script should fail gracefully), or the script should be modified to use the archive repository at `archive.repo.saltproject.io`.

**Comment by dmurphy18** [comment]
@pnickerson-cashstar  Closing this as fixed in release of the bootstrap 2024-07-12, see https://github.com/saltstack/salt-bootstrap/actions/workflows/ci.yml.  Please feel free to reopen if other matters relevant to this issue come to light.
