### ISSUE TITLE
Windows Bootstrap Failing on New Installs

### ISSUE THREAD

**Issue by doesitblend** [saltstack/salt-bootstrap#1827]
### Description of Issue/Question
The latest version of the Windows bootstrap script checks for a registry key that will not exist if Salt is not already installed. The code producing the error seems to be on line 190 of the script. 

### Setup
Deploy a fresh Windows VM

### Steps to Reproduce Issue
Run the bootstrap script with the options shown in the second image attached

### Versions and Systems
Bootstrap version: 2022.03.15

![win_bootstrap_1](https://user-images.githubusercontent.com/31517589/168632435-8413d7e2-b13a-4503-85f7-12088a1da4ed.png)
![win_bootstrap_2](https://user-images.githubusercontent.com/31517589/168632432-4a4bc831-ee24-4046-be00-be56bf48fe52.png)

**Comment by twangboy** [comment]
This probably needs to be wrapped in a Try/Except block...

**Comment by doesitblend** [comment]
@twangboy One recommendation I received on how to resolve this was the following:
> The Get-ItemProperty call probably needs its -ErrorAction set to “SilentlyContinue”.

This may be an alternative to the existing code, but I'm not very familiar with Powershell and its best practices.

**Comment by twangboy** [comment]
That would probably work too, but the variable would be empty. So, set it first, then SilentlyContinue.

**Comment by Tesbarmix1** [comment]
> ### Description of Issue/Question
> The latest version of the Windows bootstrap script checks for a registry key that will not exist if Salt is not already installed. The code producing the error seems to be on line 190 of the script. 
> 
> ### Setup
> Deploy a fresh Windows VM
> 
> ### Steps to Reproduce Issue
> Run the bootstrap script with the options shown in the second image attached
> 
> ### Versions and Systems
> Bootstrap version: 2022.03.15
> 
> ![win_bootstrap_1](https://user-images.githubusercontent.com/31517589/168632435-8413d7e2-b13a-4503-85f7-12088a1da4ed.png)
> ![win_bootstrap_2](https://user-images.githubusercontent.com/31517589/168632432-4a4bc831-ee24-4046-be00-be56bf48fe52.png)
> 
> 
>

**Comment by austinbrowder** [comment]
I think the bigger issue here is that this causes problems for windows bootstraping in 3005.1+ because the default location the minion looks for confs is nolonger c:\salt.
https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/windows.html#install-windows

**Comment by dmurphy18** [comment]
@doesitblend Can you retry with the latest bootstrap script which has been heavily updated this July, noting that support for older EOL version of Salt has been dropped. If the latest version of the bootstrap script resolves your issues, please consider closing this issue.

**Comment by dmurphy18** [comment]
@doesitblend No response, since Jul, gets it closed, you know where Shane and I sit ;)
