### ISSUE TITLE
Unable to pin version using onedir with 3005

### ISSUE THREAD

**Issue by wwimberly** [saltstack/salt-bootstrap#1861]
### Description of Issue/Question
When trying to pin the version for a onedir deploy I am seeing the following error.
`script_args: onedir 3005.0`
```text
* ERROR: https://repo.saltproject.io/salt/py3/ubuntu/20.04/amd64/minor/3005/salt-archive-keyring.gpg failed to download to /tmp/salt-gpg-GVRRzy8b.pub
* ERROR: Failed to run install_ubuntu_onedir_deps()!!!
```
The url mentioned in the error https://repo.saltproject.io/salt/py3/ubuntu/20.04/amd64/minor/3005/salt-archive-keyring.gpg doesn't exist but https://repo.saltproject.io/salt/py3/ubuntu/20.04/amd64/minor/3005-1/salt-archive-keyring.gpg does.

I see the same behavior when using `script_args: onedir 3005`.

`script_args: onedir` works as expected.

### Setup
(Please provide relevant configs (Be sure to remove sensitive info).)

The following is the relevant section from the salt-cloud config.

```yaml
script: bootstrap-salt
script_args: onedir 3005.0
```
### Steps to Reproduce Issue
(Include debug logs if possible, `bootstrap-salt.sh -D`.)

### Versions and Systems
(`salt --versions-report`, `bootstrap-salt.sh -v`, system type and version,
cloud/VM provider as appropriate.)

```text
# salt --versions-report
Salt Version:
          Salt: 3005
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.13 (main, Aug 23 2022, 18:31:04)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-125-generic
        system: Linux
       version: Ubuntu 20.04 focal
```
```text
/etc/salt/cloud.deploy.d# sh bootstrap-salt.sh -v
bootstrap-salt.sh -- Version 2022.08.13
```

**Comment by wwimberly** [comment]
The equivalent url to the gpg key for non-onedir does not include the `-1` on the version part of the url.

Non-onedir gpg key url: https://repo.saltproject.io/py3/ubuntu/20.04/amd64/archive/3005/salt-archive-keyring.gpg
Onedir gpg key url: https://repo.saltproject.io/salt/py3/ubuntu/20.04/amd64/minor/3005-1/salt-archive-keyring.gpg

**Comment by zyxep** [comment]
i've got the same bug.
it would also be nice to have support for major releases.
https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/ubuntu.html
