### ISSUE TITLE
The 'salt==3005' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by ahutchens-rave** [saltstack/salt-bootstrap#1862]
### Description of Issue/Question
Fresh installations of Salt will not start after 3005 release, giving the following error:

=====================
```
[root@salttest ~]# /usr/bin/salt-minion
Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3239, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'salt==3005' distribution was not found and is required by the application
```
=====================

### Setup
Salt is being installed via bootstrap script on Rocky 8.6 as follows:

=====================
```
curl -L https://bootstrap.saltstack.com -o install_salt.sh && /bin/sh install_salt.sh -A qa-master
mkdir -p /etc/salt/pki/minion
curl -sSk https://qa-master:8000/keys \
        -d mid=$HOSTNAME \
        -d username=******* \
        -d password=******** \
        -d eauth=pam \
    | tar -C /etc/salt/pki/minion -xf -

mkdir -p /etc/salt/minion.d
printf "master: qa-master.qa.raveu.net\nid: $HOSTNAME" > /etc/salt/minion.d/id.conf
```
=====================

This has been successful for some time now, and just started throwing errors recently.

### Steps to Reproduce Issue

Unsure how to reproduce other than spinning up a brand new Rocky 8.6 machine and running the bootstrap script.

### Versions and Systems
[bootstrap.txt](https://github.com/saltstack/salt-bootstrap/files/9472659/bootstrap.txt)

```
[root@salttest ~]# ./bootstrap-salt.sh -v
./bootstrap-salt.sh -- Version 2022.08.13
[root@salttest ~]# cat /etc/redhat-release
Rocky Linux release 8.4 (Green Obsidian)
```
NOTE: Some are 8.4, others are 8.6 (with the same issues)
Running on ESX

**Comment by ahutchens-rave** [comment]
Not sure what's up with the formatting, sorry; Daithi requested this be assigned to @dmurphy18 in Slack

**Comment by dmurphy18** [comment]
@ahutchens-rave Closing this since Salt 3005 is EOL, if you want to install 3005 with bootstrap.sh, then please use a version of the bootstrap script which is close to that release date, current version of the bootstrap script only support 3006 and up, that is, versions of Salt that are supported (onedir).  Please feel free to reopen if other matters relevant to this issue come to light.
