### ISSUE TITLE
Does not exist https://dl.fedoraproject.org/pub/epel/epel-next-release-latest-7.noarch.rpm

### ISSUE THREAD

**Issue by xa2099** [saltstack/salt-bootstrap#1864]
### Setup
Running bootstrap on OEL 7.

### Steps to Reproduce Issue

- Run bootstrap installer on OEL 7.

The line in code:
`epel_next_repo_url="${HTTP_VAL}://dl.fedoraproject.org/pub/epel/epel-next-release-latest-${DISTRO_MAJOR_VERSION}.noarch.rpm"`

Produces:
`https://dl.fedoraproject.org/pub/epel/epel-next-release-latest-7.noarch.rpm`

This URL does not exist.

![2022-09-08 10 43 51](https://user-images.githubusercontent.com/37461099/189152529-c07a3de3-b19c-4fe8-8cd1-b1615cda38ea.png)

**Comment by garethgreenaway** [comment]
@xa2099 Thanks for the report.  In the bootstrap code we attempt to install both epel RPMs, the epel-release and the epel-next-release.  I see when attempting to install on CentOS 7 that yum reports that the epel-next-release is unavailable but is able to install the epel-release RPM.  Does OEL7 not report this error and install the epel-release RPM?

**Comment by xa2099** [comment]
I am realizing that this may not be an error as it feels first when it reads "Cannot open:". Then "Skipping". 

Perhaps a different message that explains that the behavior is somewhat expected and acceptable.

![2022-09-13 23 25 20](https://user-images.githubusercontent.com/37461099/190052988-5d034bdf-8840-4a8c-847b-9dd8131f6843.png)

**Comment by garethgreenaway** [comment]
@xa2099 I believe that particular message is coming from YUM / DNF when it's trying to install the EPEL packages.

**Comment by xa2099** [comment]
If the messaging can be changed to indicate that this may be optional it would be clear to the user.

**Comment by dmurphy18** [comment]
@xa2099 Closing this since RHEL 7 and derivatives are EOL, unless pay for the privilege of extended support.
