### ISSUE TITLE
Salt 3005: Can't install Salt via Salt Cloud on CentOS9 due to missing SALTSTACK-GPG-KEY2.pub in repository (wrong location?)

### ISSUE THREAD

**Issue by morsik** [saltstack/salt-bootstrap#1865]
Bootstrap script has this code (in `__install_saltstack_rhel_onedir_repository`:

```bash
    base_url="${HTTP_VAL}://${_REPO_URL}/${_ONEDIR_DIR}/${__PY_VERSION_REPO}/redhat/${DISTRO_MAJOR_VERSION}/\$basearch/${ONEDIR_REV}/"
    if [ "${DISTRO_MAJOR_VERSION}" -eq 9 ]; then
        gpg_key="SALTSTACK-GPG-KEY2.pub"
    else
        gpg_key="SALTSTACK-GPG-KEY.pub"
    fi


```

But `SALTSTACK-GPG-KEY2.pub` is is in different location in repo: https://repo.saltproject.io/salt/py3/redhat/9/x86_64/3005/

Bootstrap script tries to download it from https://repo.saltproject.io/salt/py3/redhat/9/x86_64/SALTSTACK-GPG-KEY2.pub instead, so there's clear mismatch between where file is located and from where it should be downloaded. This is kinda strange, because it looks like deploy script is looking for correct location, so… what's going on?!

```
 * ERROR: Failed to run install_centos_onedir_deps()!!!
[DEBUG   ]  * ERROR: https://repo.saltproject.io/salt/py3/redhat/9/x86_64/SALTSTACK-GPG-KEY2.pub failed to download to /tmp/salt-gpg-jJ6dLvK9.pub
```

Looks like this URL bug is only in `onedir` installation method:
[onedir](https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L4494) vs [standard packages](https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L4440)

**Comment by morsik** [comment]
Interesting thing, I'm trying to spin up instance using Salt Cloud and it fails with this weird error. But when I actually ran command that Salt Cloud ran, it worked. Very strange…

```
ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /home/morsik/.ssh/id_rsa -oConnectTimeout=15  -p 22 root@666.666.666.666 /tmp/.saltcloud-31e86f46-4ec3-4078-9ab9-cce732eed8e1/deploy.sh -c "'/tmp/.saltcloud-31e86f46-4ec3-4078-9ab9-cce732eed8e1'" -S -M -k "'/tmp/.saltcloud-31e86f46-4ec3-4078-9ab9-cce732eed8e1/preseed-minion-keys'" onedir
```

**Comment by garethgreenaway** [comment]
@morsik Thanks for the report.  I believe this one should have been fixed by this PR. https://github.com/saltstack/salt-bootstrap/pull/1863

**Comment by garethgreenaway** [comment]
Closing this one out, if the problem persists please let us know.  Thanks!
