### ISSUE TITLE
In salt-cloud for ubuntu 22.04 bad entry for netplan

### ISSUE THREAD

**Issue by shadoutmapes** [saltstack/salt-bootstrap#1875]
### Description of Issue/Question
Script still puts default gateway in the netplan config yaml as GATEWAY4:"default gw"
Ubuntu has deprecated this and the new way is  to use the routes statement.  I believe this is backwards compatible and could be change for all netplan based distros.  
                                                                                     
### Setup
(Please provide relevant configs (Be sure to remove sensitive info).)
Basic in any normal deployment of ubuntu 22.04 and on.
### Steps to Reproduce Issue
(Include debug logs if possible, `bootstrap-salt.sh -D`.)

### Versions and Systems
(`salt --versions-report`, `bootstrap-salt.sh -v`, system type and version,
cloud/VM provider as appropriate.)

**Comment by dmurphy18** [comment]
@shadoutmapes  Closing this as fixed in release of the bootstrap 2024-07-12, see https://github.com/saltstack/salt-bootstrap/actions/workflows/ci.yml.  Please feel free to reopen if other matters relevant to this issue come to light.
