### ISSUE TITLE
Add tests for OneDir releases of Salt

### ISSUE THREAD

**Issue by ggiesen** [saltstack/salt-bootstrap#1878]
### Description of Issue/Question
Based on what I see in here:

https://github.com/saltstack/salt-bootstrap/blob/e5fca869980b0993f389866ec3da477a6eaa17d4/.github/workflows/ci.yml#L241-L252

There do not appear to be any tests against any of the OneDir versions of Salt, which is how the issue for #1876 most likely was missed. I don't understand the tests very well, if it's just possible to just modify the instances line to add `onedir-latest` or `onedir-3005`, or if you actually need to build new containers for testing, but this definitely needs to be addressed.

**Comment by ggiesen** [comment]
Looks like @garethgreenaway is fixing this in #1880

**Comment by garethgreenaway** [comment]
Closed by https://github.com/saltstack/salt-bootstrap/pull/1880
