### ISSUE TITLE
yum-based systems call 'yum update'

### ISSUE THREAD

**Issue by cwacek** [saltstack/salt-bootstrap#189]
The issue is that `yum update` isn't like `apt-get update`. It actually goes and upgrades packages. If there are updates pending, or some other package has a broken dependency, then the whole install fails because of elements unrelated to salt.

Unless I've missed something, the goal of that call is to make sure the EPEL repository is updated, for which `yum makecache` should be sufficient.

**Comment by s0undt3ch** [comment]
Since I'm an Ubuntu guy, I need to call in a RH/Ferora expert.
@herlo, I'm about to switch from `yum update` to `yum makecache` because it seems the right thing to do and I believe @cwacek. Do you seen any future issues with this change?

**Comment by herlo** [comment]
@s0undt3ch, what is the use case? I am not sure it makes sense unless you are just trying to make sure the latest metadata is available when doing an update/install.

**Comment by cwacek** [comment]
@herlo @s0undt3ch I'm not actually sure it's necessary at all. I just assumed someone had put it in there because they thought it was necessary (ala `apt-get update`), and I didn't want to suggest completely removing it.

**Comment by herlo** [comment]
AUIU, apt-get update does the same thing as yum update. They both check upstream repositories for upgradeable packages and then install said packages. Maybe I am not understanding your issue?

**Comment by cwacek** [comment]
@herlo That's not correct. To quote the apt-get man page: 

```
update
           update is used to resynchronize the package index files from their sources. The indexes
           of available packages are fetched from the location(s) specified in
           /etc/apt/sources.list. For example, when using a Debian archive, this command retrieves
           and scans the Packages.gz files, so that information about new and updated packages is
           available. An update should always be performed before an upgrade or dist-upgrade.
           Please be aware that the overall progress meter will be incorrect as the size of the
           package files cannot be known in advance.
```

To quote the yum man page:

```
update If  run without any packages, update will update every currently installed package.
```

`apt-get upgrade` is the equivalent to `yum update`. Salt shouldn't be running `yum update` when it installs unless there's a very specific use case.

**Comment by herlo** [comment]
@cwacek ahh, I see kind of what you are getting at here. My previous point still holds then, I wanted to understand the point of this use case. If you are saying that pkg.install should not use yum update, I'm with you, but I don't see how pkg.latest would be incorrect in using yum update <pkgname>, for instance.

Can you give me the use case you are using to argue this here? It's really what will make more sense. I actually think we're in violent agreement, btw.

**Comment by cwacek** [comment]
@herlo I think we are too. I was specifically referring to the use of `yum update` in the salt-bootstrap.sh script. I just looked at yumpkg and it looks file (doesn't even use update).

**Comment by vimalloc** [comment]
I would also like to see the yum update removed from bootstrap-salt.sh. I ran into a situation where trying to bootstrap salt upgraded a totally unrelated package which caused issues.

**Comment by atoponce** [comment]
It definitely should NOT be calling "-y" when doing the bootstrap. Let the administrator decide if the system should be upgraded.

**Comment by techhat** [comment]
I would agree with @atoponce in some circumstances. In others, I want `-y` to be called. The bootstrap script should give the user the option to choose from the command line.

**Comment by cwacek** [comment]
That's why I'm inclined to remove the update line entirely unless someone can think of a reason to keep it. The install lines need '-y' or they'll hang all the time.

I intend to test this change in a vm, but haven't had the time just yet.

**Comment by s0undt3ch** [comment]
In order not to break previous functionality, not upgrading the full system prior to installing salt will be an optional flag and not expected behavior.

@atoponce This is supposed to be an automated installation script, you run it and you should expect a system running salt in the end. Like such, **all**  system calls should **not** require user intervention. If that's required, it's a bug in the script.

**Comment by vimalloc** [comment]
I would argue that it is a bug in the script to update packages unrelated to salt as well. If I run this script on a production box, I want to have salt installed, nothing more. I don't want new version of bind, apache, whatever that have nothing to do with salt upgraded. And I really don't want any of those daemons restarted.

**Comment by s0undt3ch** [comment]
@vimalloc That's why I'm making that an optional flag.

**Comment by vimalloc** [comment]
@s0undt3ch Ok that works fine then. Sorry, that wasn't clear to me on the closed pull request.

**Comment by s0undt3ch** [comment]
@vimalloc No worries! See #199.

I'm still evaluating if we should break previous behavior and have `-U` run the system upgrade procedures instead of the opposite(not running the system upgrade procedures).

**Comment by s0undt3ch** [comment]
Ok, I've decided.

No upgrades shall be done to the system unless `-U` is passed to the script.

**Comment by s0undt3ch** [comment]
This **breaks** previous RedHat based distributions expectation of a fully upgraded system when salt was installed, which was the previous behavior.

**Comment by vimalloc** [comment]
I think I like that way more, less chances of someone accidentally causing problems with their system while installing salt cause they didn't fully read the docs. But either way, as long as there is an option for not upgrading the system I am very happy!

Thanks @s0undt3ch :)

**Comment by cwacek** [comment]
@s0undt3ch Thanks. I think that's a good solution.
