### ISSUE TITLE
Add 3006 version

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-bootstrap#1891]
### Description of Issue/Question
Add the 3006 version to the bootstrap and use onedir by default if 3006 is being used.

**Comment by dmurphy18** [comment]
@Ch3LL  Closing this as fixed in release of the bootstrap 2024-07-12, see https://github.com/saltstack/salt-bootstrap/actions/workflows/ci.yml.  Please feel free to reopen if other matters relevant to this issue come to light.
