### ISSUE TITLE
[Almalinux 9] Bootstrap failed because Salt-Minion service is not enabled

### ISSUE THREAD

**Issue by SndR85** [saltstack/salt-bootstrap#1892]
### Description of Issue/Question

When using the Salt-bootstrap script it failed to install Salt-minion as onedir package because the service is not enabled. It install the salt-minion from the Saltstack repository. After installing the script will check if the service has been enabled. If it isn't enabled the script will exit 1.

### Setup

Install an empty, clean Almalinux 9 VM, with the default systemd installed. Don't install epel-release. Download the bootstrap-script from:

```
$ curl -o bootstrap-salt.sh -L https://bootstrap.saltproject.io
$ chmod +x bootstrap-salt.sh
```

### Steps to Reproduce Issue

Run the bootstrap script with onedir:

```
$ ./bootstrap-salt.sh onedir
 *  INFO: Running version: 2022.10.04
 *  INFO: Executed by: /bin/sh
 *  INFO: Command line: './bootstrap-salt.sh onedir'

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   5.14.0-162.6.1.el9_1.x86_64
 *  INFO:   Distribution: AlmaLinux 9.1

 *  INFO: Installing minion
 *  INFO: Found function install_almalinux_onedir_deps
 *  INFO: Found function config_salt
 *  INFO: Found function preseed_master
 *  INFO: Found function install_almalinux_onedir
 *  INFO: Found function install_almalinux_restart_daemons
 *  INFO: Found function daemons_running_onedir
 *  INFO: Found function install_almalinux_check_services
 *  INFO: Running install_almalinux_onedir_deps()
...
 *  INFO: Running install_almalinux_check_services()
 * ERROR: Failed to run install_almalinux_check_services()!!!
```

### Versions and Systems

Bootstrap stable version.

**Comment by lkubb** [comment]
For the record, this should have been fixed already (it's not in a stable release though):

https://github.com/saltstack/salt-bootstrap/issues/1883
https://github.com/saltstack/salt-bootstrap/pull/1884
