### ISSUE TITLE
Bootstrap.sh does not download the latest release if it hasn't been approved in EPEL.

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt-bootstrap#190]
Currently the bootstrap.sh script does not pull down the latest stable release if it hasn't completed all testing in EPEL and is available in the main repo. As an example the latest release was delayed until today (history for this latest release is [here](https://admin.fedoraproject.org/updates/salt-0.16.0-1.el6)). So the bootstrap script will pull the old version, and you can't update to the lateste. SEJeff_work has suggested to simply add a flag to enable epel-testing.

**Comment by SEJeff** [comment]
ie: `yum --enablerepo=epel-testing install salt{,-minion,master}`

**Comment by gravyboat** [comment]
as an update to SEJeff's command: 
<code> yum --enablerepo=epel-testing install salt{,-minion,-master,-api}</code>

**Comment by s0undt3ch** [comment]
@gravyboat have a chance to test bootstraping from https://raw.github.com/s0undt3ch/salt-bootstrap/develop/bootstrap-salt.sh

Passing `testing` should install from `epel-testing` instead of `epel`.

```
curl -L https://raw.github.com/s0undt3ch/salt-bootstrap/develop/bootstrap-salt.sh | sudo sh -s -- testing
```
