### ISSUE TITLE
Error when installing salt minion on photon os

### ISSUE THREAD

**Issue by AntRobinson** [saltstack/salt-bootstrap#1907]
I am trying to install a salt minion on a photon os VM using the bootstrap script, however I get the following error:

` * ERROR: No dependencies installation function found. Exiting...`

I believe I have all the dependencies installed.

Thanks

**Comment by garethgreenaway** [comment]
@AntRobinson Current release does not include support for Photon but the next release (available soon) will include that.

**Comment by dmurphy18** [comment]
@AntRobinson  Closing this as fixed in release of the bootstrap 2024-07-12, see https://github.com/saltstack/salt-bootstrap/actions/workflows/ci.yml.  Please feel free to reopen if other matters relevant to this issue come to light.
