### ISSUE TITLE
Ubuntu-22.04 Repo added - Warning about Non-LTS Ubuntu can be removed

### ISSUE THREAD

**Issue by xenion1987** [saltstack/salt-bootstrap#1915]
Due to this closed issue (https://github.com/saltstack/salt/issues/62202), the warning ` *  WARN: Non-LTS Ubuntu detected, but stable packages requested. Trying packages for previous LTS release. You may experience problems.` can be removed and the fallback variables are not needed anymore for the case `"$DISTRO_MAJOR_VERSION" -eq 22`

https://github.com/saltstack/salt-bootstrap/blob/9fa32bd95c23c8ba74bc5647aacc2054f6fc2f3e/bootstrap-salt.sh#L3025-L3029

**Comment by xenion1987** [comment]
Oh, there is already a PR for this issue: https://github.com/saltstack/salt-bootstrap/pull/1914

**Comment by dmurphy18** [comment]
@Xenion1987  Closing this as fixed in release of the bootstrap 2024-07-12, see https://github.com/saltstack/salt-bootstrap/actions/workflows/ci.yml.  Please feel free to reopen if other matters relevant to this issue come to light.
