### ISSUE TITLE
Bootstrap-salt.sh 3006 error

### ISSUE THREAD

**Issue by simon-xu-gao** [saltstack/salt-bootstrap#1919]
### Description of Issue/Question
Running bootstrap-salt.sh, would not install due to an error. Worked one I downgraded to the previous stable version (boostrap-salt.sh stable 3005)

### Setup
(Please provide relevant configs (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
Running version: 2023.04.06
Executed by: sh
Command line: '/tmp/bootstrap-salt.sh '
Running the unstable version of bootstrap-salt.sh
/tmp/bootstrap-salt.sh: 620: 1: parameter not set

### Versions and Systems
Ubuntu-22.04 via Windows WSL.

**Comment by connectwise-cody-krukauskas** [comment]
also experiencing this same issue trying to launch Ubuntu 22.04 EC2 machines via salt-cloud on a 3006 master.

**Comment by Arderos** [comment]
Same here

**Comment by garethgreenaway** [comment]
Thanks for the report.  We just released a new version of the bootstrap script, can you try the latest version and see if that resolves the issue for you?  Thanks!

**Comment by neomancernz** [comment]
Good afternoon. I just downloaded redownloaded the script via curl, I am getting the same issue. (stable 3005 worked)

Debian 11 container
![image](https://user-images.githubusercontent.com/128402973/233810691-d6b06ac8-2d69-4f87-bc78-db98634d9f88.png)

**Comment by simon-xu-gao** [comment]
> Thanks for the report. We just released a new version of the bootstrap script, can you try the latest version and see if that resolves the issue for you? Thanks!

Original issue was also freshly downloaded off of bootstrap.saltproject.io

Getting the same issue running version 2023.04.21 directly from the git repo:

```
$ git clone https://github.com/saltstack/salt-bootstrap.git  
$ cd salt-bootstrap/
$ bash bootstrap-salt.sh 
 *  INFO: Running version: 2023.04.21
 *  INFO: Executed by: bash
 *  INFO: Command line: 'bootstrap-salt.sh '
 *  WARN: Running the unstable version of bootstrap-salt.sh
bootstrap-salt.sh: line 620: $1: unbound variable
```

**Comment by garethgreenaway** [comment]
Thanks everyone, I was able to reproduce it.  Also appears to show a missing window in our testing for bootstrap.
This diff should fix it and we'll make sure the fix is available in the next bootstrap release.

```
diff --git a/bootstrap-salt.sh b/bootstrap-salt.sh
index 2b056a2..83f9df8 100755
--- a/bootstrap-salt.sh
+++ b/bootstrap-salt.sh
@@ -617,7 +617,7 @@ if [ "$ITYPE" = "git" ]; then
 elif [ "$ITYPE" = "stable" ]; then
     if [ "$#" -eq 0 ];then
         ONEDIR_REV="latest"
-        _ONEDIR_REV="$1"
+        _ONEDIR_REV="latest"
         ITYPE="onedir"
     else
         if [ "$(echo "$1" | grep -E '^(nightly|latest|3006)$')" != "" ]; then
@@ -3097,7 +3097,6 @@ __install_saltstack_ubuntu_onedir_repository() {
     if [ "$(echo "${ONEDIR_REV}" | grep -E '(3004|3005)')" != "" ]; then
       __apt_key_fetch "${SALTSTACK_UBUNTU_URL}salt-archive-keyring.gpg" || return 1
     elif [ "$(echo "${ONEDIR_REV}" | grep -E '(latest|nightly)')" != "" ]; then
-      __apt_key_fetch "${SALTSTACK_UBUNTU_URL}salt-archive-keyring.gpg" || \
       __apt_key_fetch "${SALTSTACK_UBUNTU_URL}SALT-PROJECT-GPG-PUBKEY-2023.gpg" || return 1
     else
       __apt_key_fetch "${SALTSTACK_UBUNTU_URL}SALT-PROJECT-GPG-PUBKEY-2023.gpg" || return 1
```

**Comment by skob** [comment]
can you plz tell when fix must be released?
do we need to create local version of bootstrap?..

**Comment by corwinon** [comment]
> can you plz tell when fix must be released? do we need to create local version of bootstrap?..

No need to create a local version, you can use one of the previous working versions:
https://github.com/saltstack/salt-bootstrap/releases/tag/v2023.04.06
https://github.com/saltstack/salt-bootstrap/releases/tag/v2022.10.04

**Comment by s0undt3ch** [comment]
This issue has been fixed in the latest release
https://github.com/saltstack/salt-bootstrap/releases/tag/v2023.04.26
