### ISSUE TITLE
Readme: Salt's Supported Operating Systems 

### ISSUE THREAD

**Issue by Selected6280** [saltstack/salt-bootstrap#1922]
In GITs [readme ](https://github.com/saltstack/salt-bootstrap/blob/stable/README.rst) the link [Salt's Supported Operating Systems](http://get.saltstack.com/rs/304-PHQ-615/images/SaltStack-Supported-Operating-Systems.pdf) is broken.

**Comment by dmurphy18** [comment]
Need to go through the README and update as needed
