### ISSUE TITLE
Vagrant provisioning is failing

### ISSUE THREAD

**Issue by iamnswamyg** [saltstack/salt-bootstrap#1923]
### Setup
I used the [salt-vagrant-demo](https://github.com/UtahDave/salt-vagrant-demo.git) for setting my vagrant based salt environment

### Steps to Reproduce Issue
vagrant up

### Error Its producing 
Using Bootstrap Options: -P -c /tmp -x python3 -F -c /tmp -k /tmp/minion-seed-keys -M -N stable
Bootstrapping Salt... (this may take a while)
 *  INFO: Running version: 2023.04.06
 *  INFO: Executed by: 
 *  INFO: Command line: 'bootstrap-salt.sh -P -c /tmp -x python3 -F -c /tmp -k /tmp/minion-seed-keys -M -N stable'
 *  WARN: Running the unstable version of bootstrap-salt.sh
bootstrap-salt.sh: 620: 1: parameter not set
==> master: Removing domain...
==> master: Deleting the machine folder
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/tmp/bootstrap_salt.sh -P -c /tmp -x python3 -F -c /tmp -k /tmp/minion-seed-keys -M -N stable

Stdout from the command:

 *  INFO: Running version: 2023.04.06
 *  INFO: Executed by: 
 *  INFO: Command line: 'bootstrap-salt.sh -P -c /tmp -x python3 -F -c /tmp -k /tmp/minion-seed-keys -M -N stable'
 *  WARN: Running the unstable version of bootstrap-salt.sh
bootstrap-salt.sh: 620: 1: parameter not set

Stderr from the command:

**Comment by garethgreenaway** [comment]
@iamnswamyg Thanks for the report.  This issue has been fixed in the unreleased, development version of bootstrap script and will be available in the next release.

**Comment by dmurphy18** [comment]
@iamnswamyg Please retry this with the just released 2024-07-16 version of the bootstrap script which has undergone major revision, and if this resolves your issue, please consider closing it.

**Comment by dmurphy18** [comment]
@iamnswamyg Closing this due to unresponsive, please feel free to reopen if more information is provided.
