### ISSUE TITLE
bootstrap-salt.sh needs to know about new URL hierarchy at repo.saltproject.io

### ISSUE THREAD

**Issue by BenArgyle** [saltstack/salt-bootstrap#1924]
We're trying to deploy a Salt minion to RHEL 9 using the deploy.sh (bootstrap-salt.sh "ScriptVersion="2022.08.12") that comes with the VMWare VCF SaltConfig setup.  This file appears to be constructing the salt.repo file and populating it with 

```
[saltstack]
name=SaltStack archive/3005.1 Release Channel for RHEL/CentOS $releasever
baseurl=https://repo.saltproject.io/py3/redhat/9/$basearch/archive/3005.1/
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://repo.saltproject.io/py3/redhat/9/$basearch/archive/3005.1/SALTSTACK-GPG-KEY2.pub,
enabled=1
enabled_metadata=1
```
We've since discovered that https://repo.saltproject.io/py3/redhat/9/x86_64/archive/3005.1/repodata/repomd.xml (and the GPG keys, etc.) doesn't exist.  In fact https://repo.saltproject.io/py3/redhat/9/ doesn't exist.  Directory hierarchies for RHEL 7 and 8, at the same level, do.  We get clean Salt minion deployments on those OS versions.

After asking on the IRC channel libera/#salt we were told about https://repo.saltproject.io/salt/py3/redhat/9/ (which also contains hierarchies for 7 and 8 at the same level), however this URL (i.e. with /salt/ prepended) isn't known about by deploy.sh.

Can we please

1) be told why things were changed for RHEL 9, and either
2) please can at least a symlink from https://repo.saltproject.io/py3/redhat/9 to https://repo.saltproject.io/salt/py3/redhat/9 be put in place (probably need them for all the other OSes too), or
3) the deploy.sh/boostrap-salt.sh be changed to take account of the change of URL for RHEL 9 (and I assume all other OSes past, present, and future)?

With thanks,

Ben

**Comment by BenArgyle** [comment]
Ah, I seem to have discovered __install_saltstack_rhel_onedir_repository() which seems to do what I need.  Now to discover _why_ it isn't being used.  Apologies.

**Comment by s0undt3ch** [comment]
@BenArgyle can we close this then?

**Comment by s0undt3ch** [comment]
It also looks like you're using an old bootstrap salt release.
Upgrading to the latest is really important if you're trying to install the latest salt release, 3006.0

**Comment by BenArgyle** [comment]
Yes, I'll close this issue.  And apologies for opening it in the first place.  The problem is VMWare, not Salt (-:
