### ISSUE TITLE
Bug: _ONEDIR_DIR missing for CentOS/AlmaLinux/RockyLinux/etc. in bootstrap-salt.sh

### ISSUE THREAD

**Issue by schories** [saltstack/salt-bootstrap#1930]
### Description
- _ONEDIR_DIR missing in bootstrap-salt.sh for CentOS/AlmaLinux/RockyLinux/etc.
- therefore salt repo URL is set wrong, resulting in a failed installation: 

```
Errors during downloading metadata for repository 'saltstack':
  - Status code: 404 for https://repo.saltproject.io/py3/redhat/9/x86_64/3005/repodata/repomd.xml (IP: 143.204.98.62)
Error: Failed to download metadata for repo 'saltstack': Cannot download repomd.xml: Cannot download repodata/repomd.xml:
```

### Steps to Reproduce Issue
./bootstrap-salt.sh -P stable 3005

### Versions and Systems
[v2023.04.26](https://github.com/saltstack/salt-bootstrap/releases/tag/v2023.04.26)
https://github.com/saltstack/salt-bootstrap/commit/9cd478022dd372459ea5e4d83f90908a55180129)

### Root Causes
_ONEDIR_DIR missing in URL:
- https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L4618
- https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L4590

Will provide a fix with separate PR, hopefully closing this issue.

**Comment by dmurphy18** [comment]
@schories  Closing this as fixed in release of the bootstrap 2024-07-12, see https://github.com/saltstack/salt-bootstrap/actions/workflows/ci.yml.  Please feel free to reopen if other matters relevant to this issue come to light.
