### ISSUE TITLE
Bug: daemons_running in bootstrap-salt.sh fails for AlmaLinux 9

### ISSUE THREAD

**Issue by schories** [saltstack/salt-bootstrap#1931]
### Description of Issue
- AlmaLinux 9 has the salt minion running in/as: /opt/saltstack/salt/run/run minion
- however, the check effectively looks for "salt-minion" only: https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L9313

### Setup
./bootstrap-salt.sh -P stable 3005

### Versions and Systems
[v2023.04.26](https://github.com/saltstack/salt-bootstrap/releases/tag/v2023.04.26)
https://github.com/saltstack/salt-bootstrap/commit/9cd478022dd372459ea5e4d83f90908a55180129

Root Cause:

grep looks for "salt-" only, which won't work for AlmaLinux 9
- https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L9313

Will provide a fix with separate PR, hopefully closing this issue.

**Comment by dmurphy18** [comment]
@schories  Closing this as fixed in release of the bootstrap 2024-07-12, see https://github.com/saltstack/salt-bootstrap/actions/workflows/ci.yml.  Please feel free to reopen if other matters relevant to this issue come to light.
