### ISSUE TITLE
https://repo.saltproject.io/bootstrap/stable/bootstrap-salt.sh still shows version "2023.04.26"

### ISSUE THREAD

**Issue by hegyre** [saltstack/salt-bootstrap#1937]
### Description of Issue/Question

Hello,

The bootstrap script at https://repo.saltproject.io/bootstrap/stable/bootstrap-salt.sh (at this time of writing) looks like not the exact same as the git release https://github.com/saltstack/salt-bootstrap/releases/download/v2023.06.28/bootstrap-salt.sh , despite being updated at 2023-06-28 20:30:02+00:00
After a file comparison, only 2 lines differs:

Website version:
line 26: __ScriptVersion="2023.04.26"
line 594: echowarn "Running the unstable version of ${__ScriptName}"

git release version:
line 26: __ScriptVersion="2023.06.28"
line 594: N/A

While other things are up-to-date, it could induce into errors the people that investigates and creates tickets where it comes to indicate the script version (including myself).

**Comment by dmurphy18** [comment]
@hegyre  Closing this as fixed in release of the bootstrap 2024-07-12, see https://github.com/saltstack/salt-bootstrap/actions/workflows/ci.yml.  Please feel free to reopen if other matters relevant to this issue come to light.
