### ISSUE TITLE
opensuse leap 15.4 goes eol in november. 15.5 is out now. update kitchen and tests?

### ISSUE THREAD

**Issue by ITJamie** [saltstack/salt-bootstrap#1946]
### Description of Issue/Question

opensuse leap 15.4 goes eol in new. leap 15.5 is out (and has newer python)
should we update kitchen and tests now?

**Comment by dmurphy18** [comment]
@ITJamie Closing this since recent release v2024.12.09 now has support for Opensuse Tumbleweed, Leap and SLES 15 sp6
