### ISSUE TITLE
Bootstrap installation via git fails due to Setuptools release 68.2.0

### ISSUE THREAD

**Issue by kevincua-umbocv** [saltstack/salt-bootstrap#1963]
**Description**
salt-bootstrap installation fails via git tag suddenly on september 7 UTC

**Setup**
installation process is like this
```
curl -o /tmp/bootstrap-salt.sh -L https://bootstrap.saltproject.io
bash /tmp/bootstrap-salt.sh -X -x python3 git v3004.2 && rm -f /tmp/bootstrap-salt.sh
```
using ubuntu arm64 (ubuntu/images/hvm-ssd/ubuntu-focal-20.04-arm64-server-20210503 ami-0b616f288e67f2f4b)
using an ec2 instance
Fails on both python3.8 and Python3.9 with pip version 20.0.2

**Steps to Reproduce the behavior**
perform this on ubuntu arm64
```
curl -o /tmp/bootstrap-salt.sh -L https://bootstrap.saltproject.io
bash /tmp/bootstrap-salt.sh -X -x python3 git v3004.2 && rm -f /tmp/bootstrap-salt.sh
```
(Include debug logs if possible and relevant)

**Expected behavior**
Until a few days or so ago, the previous command would result in a new minion, my-new-minion, running Ubuntu 20.04.

**error code**
```
failed to download salt dependencies 
* info: installing downloaded salt dependencies 
* invalid requirement: '/tmp/git/deps/*' it looks like a path.
```

**Cause of Issue**
https://pypi.org/project/setuptools/68.2.0/
Setup tools released a new version which breaks salt-bootstrap installation via git.

**Temporary Solution(for me)**
bind setuptools version to older version before 68.2 in salt boostrap script
```
if [ "$_PY_MAJOR_VERSION" -eq 3 ]; then
    # We also lock setuptools to <45 which is the latest release to support both py2 and py3
    _setuptools_dep="${_setuptools_dep},<68.2"
fi
````

**Comment by zerog2k** [comment]
also hit us as well (also on ubuntu 20.04)
our alternative solution, pin to older stable bootstrap tag:
```
 wget -O /tmp/install_salt.sh https://github.com/saltstack/salt-bootstrap/releases/download/v2023.08.03/bootstrap-salt.sh
bash /tmp/install_salt.sh -x python3 -q -P -S -M stable 3005.1
```

**Comment by kevincua-umbocv** [comment]
@zerog2k sadly i'm on arm and for some reason salt removed all the arm64 gpg keys for 3005, but kept them for amd64 so i cannot install via stable
https://repo.saltproject.io/salt/py3/ubuntu/20.04/arm64/

**Comment by dmurphy18** [comment]
@kevincua-umbocv Can you please retry this with the just released version of the bootstrap script, 2024-07-16, which has undergone major revision. If this resolves your issue, please consider closing it.

**Comment by dmurphy18** [comment]
@kevincua-umbocv Actually updated script 2024-07-18, has updated README where pre-3006 releases are no longer supported, and the script has Arm64 support for all supported platforms.
Just installed 3006.8 via Git on Rocky Linux 9 without issues, apart from systemd support in the container.

**Comment by kevincua-umbocv** [comment]
Will close the issue, but no one is really managing our salt master setup so we can't really update our current version
