### ISSUE TITLE
Errors when running bootstrap on alpine

### ISSUE THREAD

**Issue by marccardinal** [saltstack/salt-bootstrap#1971]
### Description of Issue/Question

Bootstrap failure on `alpine:3:18` with `v3006.3`.

### Steps to Reproduce Issue

1. Launch a new alpine container using:

```
docker run -it alpine:3.18 sh
```

2. At the container's prompt, run:

```
apk --no-cache add curl
curl -L https://bootstrap.saltproject.io | sh -s -- -M -N git v3006.3
```

The above results in:

```
Successfully installed salt-3006.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 *  INFO: Checking if Salt can be imported using python3

Installed Salt Version: 3006.3
Installed Salt Package Path: /usr/lib/python3.11/site-packages/salt

 *  INFO: Running install_alpine_linux_post()
 * ERROR: https://github.com/saltstack/salt/raw/master/pkg/alpine/salt-api failed to download to /etc/init.d/salt-api
 * ERROR: Failed to get OpenRC init script for Linux from https://github.com/saltstack/salt/raw/master/pkg/alpine/salt-api.
 * ERROR: Failed to run install_alpine_linux_post()!!!
/ #
```

Running the same command targeting the `v3005.3` tag yields the same results given that the reference to the underlying `salt` repo is done without tag and it would use whatever the state of `master` is at the time.

This stems from this section of the bootstrap file: https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L6047-L6048 and indeed if we look at the state of the salt repo between the `3005.x` and `3006.x` branches we see that the `alpine` folder disappeared:

https://github.com/saltstack/salt/tree/3005.x/pkg
https://github.com/saltstack/salt/tree/3006.x/pkg

Is the drop of alpine support by design or this is an unexpected regression?

Thanks!

**Comment by dmurphy18** [comment]
@marccardinal Can you retry this with the latest stable release (2024-07-18), noting that 3006 and up is supported by that script. Noting that Salt doesn't support Python 3.11 or 3.12 yet

**Comment by dmurphy18** [comment]
@marccardinal Closing this due to unresponsive, please feel free to reopen if more information is provided.
