### ISSUE TITLE
Cannot install on Alma Linux 9 on aarch64 (AWS m6g)

### ISSUE THREAD

**Issue by driskell** [saltstack/salt-bootstrap#1976]
### Description of Issue/Question

```
    amazon-ebs.xxx:  *  INFO: System Information:
    amazon-ebs.xxx:  *  INFO:   CPU:
    amazon-ebs.xxx:  *  INFO:   CPU Arch:     aarch64
    amazon-ebs.xxx:  *  INFO:   OS Name:      Linux
    amazon-ebs.xxx:  *  INFO:   OS Version:   5.14.0-284.18.1.el9_2.aarch64
    amazon-ebs.xxx:  *  INFO:   Distribution: AlmaLinux 9.3
```

This should result in arm64 RedHat 9 but results in aarch64 passing through and it hits a 404 on the key.

```
* ERROR: https://repo.saltproject.io/salt/py3/redhat/9/aarch64/minor/3006.4/SALT-PROJECT-GPG-PUBKEY-2023.pub failed to download to /tmp/salt-gpg-5wMh4Y2a.pub
```

### Setup

N/A

### Steps to Reproduce Issue

Launch Alma Linux 9 on Amazon Linux m6g instance, which reports `aarch64` when you call `uname -m`

```
*  INFO: Command line: '/srv/salt/bootstrap-salt.sh -x python3 stable 3006.4'
```

### Versions and Systems

```
*  INFO: Running version: 2023.11.07
```

**Comment by driskell** [comment]
Looks like it uses `$basearch` and the repositories only have `arm64` but even `$basearch` is aarch64 so it looks like some missing support here?

**Comment by kalramani** [comment]
May i know which hardware architecture was imported well on AWS for Alma Linux 9

**Comment by dmurphy18** [comment]
@driskell Suggest you try Salt 3006.5 at a minimum, if not the most recent 3006.8, https://repo.saltproject.io/salt/py3/redhat/9/aarch64/minor, no support for 3006.4

If this addresses your issue, please consider closing this issue.

**Comment by dmurphy18** [comment]
@driskell Can you try with the latest bootstrap script, which was recently updated with PR https://github.com/saltstack/salt-bootstrap/pull/1987, and released today, 2024-07-12.  If this resolves the issue, please close this issue.

**Comment by dmurphy18** [comment]
Problem may be fixed with this PR https://github.com/saltstack/salt-bootstrap/pull/2005, which was merged today

**Comment by driskell** [comment]
I will close this as I do think a newer version was fine - I don’t think related to any of the changes recently and just a case of the older versions of Salt didn’t have aarch64 folders, only arm64 folders.

I have been successfully using in last few months on latest Alma Linux 9 the latest versions of 3006 and simply forgot about this. Will close it
