### ISSUE TITLE
Bootstrap fails to install properly on RHEL systems if optional repo is not enabled.

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt-bootstrap#198]
Currently when trying to run the bootstrap script (without additional options) on a rhel 6 64 bit machine salt as well as Jinja2 fail to install because the only package available in EPEL is [jinja2-26](http://dl.fedoraproject.org/pub/epel/6/x86_64/repoview/python-jinja2-26.html). This was previously brought up as a failure for the salt master to install [here](https://groups.google.com/forum/#!msg/salt-users/ZyatYnb95QY/ADngjIjVF8cJ), and [bug 844710](https://bugzilla.redhat.com/show_bug.cgi?id=844710) was filed, but not considered to be an actual problem as the optional channel for RHEL can be enabled. 

If we're unable to address this issue in the packages themselves (and really that should NOT need to be done, the RPM available in EPEL should be corrected), then the RHEL function could be updated to run the following command <code>rhn-chanel --add --channel=rhel-$ARCH-server-optional-$DISTRO_VERSION</code>, so for x86_64, on rhel6 it would look like <code>rhn-chanel --add --channel=rhel-x86_64-server-optional-6</code>.

**Comment by s0undt3ch** [comment]
Thanks @gravyboat !

**Comment by s0undt3ch** [comment]
@herlo can you please tell us what you think should be done regarding this issue?

**Comment by herlo** [comment]
There are two problems with this suggestion. First, if I recall correctly, putting the package in as a Requires for salt would mean we'd be using the wrong jinja2 package. Secondly, enabling the repository seems like a good idea, except for the fact that some subscriptions do not include the optional repository. 

I think the second one is more problematic. Maybe salt-bootstrap could have a distro/OS specific set of flags which can be passed to enable things such as this?

herlo

**Comment by gravyboat** [comment]
@herlo Yes I agree that putting the package in as a requires is a bad idea. The optional repo is also problematic, since then individuals who don't have an optional repo subscription are completely out of luck when it comes to installing salt via the bootstrap unless they decide to pull from git. Is there no way we can contact Thomas Moschny and request that he fix the package in EPEL? His email is freely available with a quick Google search (thomas.moschny@gmx.de) , and I don't believe the bugzilla was closed with a response that took the situation you provided into account.

Just because the package IS available from optional, doesn't mean that it's acceptable to have an improperly named package floating around in EPEL. If there is a case for the splitting of versions thanks to this naming scheme (2.2.1 provided via centos/rhel, versus 2.6.2 provided by EPEL), that's fine, but it doesn't mean that the original and correctly name packaged should be excluded from the repo. I'd be interested to see a record of which RPMs actually require this oddly named jinja2-26 package, as opposed to simply jinja2 if such a database exists.

**Comment by herlo** [comment]
I don't think the one is the same as the other, the jinja2-26 package is
the same as the jinja2 package. For one, the former is actually for EPEL5
only, since it supports python2.6 which EL5 doesn't have except in EPEL. I
think that's been the issue from the very beginning.

I'm pretty sure nothing in EL6 needs jinja2-26, though I'd have to look
again to tell you why.

Cheers,

herlo

**Comment by gravyboat** [comment]
@herlo So I guess we didn't really come to a conclusion here, what sort of action should be taken regarding this issue?

**Comment by herlo** [comment]
My conclusion hasn't really changed. The jinja2-26 package is not needed.
It's impossible to expect someone to turn on the optional repository (or
pay to subscribe to it), but it's also not going to be something we
package. The only real option I can see we have is to deal with the issues
as they come in.

**Comment by gravyboat** [comment]
@herlo Maybe I'm misunderstanding you or am confused in some fashion, but you're stating that the jinja2-26 package is not needed in the EPEL repository right? If so, is the best course of action to now contact Thomas Moschny and request he re-package jinja2 with the correct name in EPEL?

**Comment by herlo** [comment]
Not quite what I'm saying. That package is for el5 only iirc. I don't
include it because epel isn't supposed to conflict with rhel. Thus, there
should not be any conflict. I'm still not clear how there is a conflict
with that package.

**Comment by gravyboat** [comment]
The issue is not that there is a conflict, it's that you can't install from the bootstrap script on RHEL 6 because EPEL has the wrong jinja2 package (which is provided by optionals for RHEL).

The [jinja2-26](http://dl.fedoraproject.org/pub/epel/6/x86_64/repoview/python-jinja2-26.html) package from EPEL is for RHEL 6, 64 bit. There is no jinja2 package available other than that one. How is it acceptable for EPEL not to conflict with RHEL if the only way to get that correct (jinja2) RPM is the optional repo, which some users might not have? This means you'd either have to build your own repo, pay for the optional repo, or manually perform a local installation every time you want to run the bootstrap script. It's not really friendly for new users. Does that make more sense?

**Comment by herlo** [comment]
Hi Forrest,

On Fri, Aug 9, 2013 at 2:53 PM, Forrest notifications@github.com wrote:

> The issue is not that there is a conflict, it's that you can't install
> from the bootstrap script on RHEL 6 because EPEL has the wrong jinja2
> package (which is provided by optionals for RHEL).
> 
> jinja2-26 is not the same as jinja2. We do not have requires in salt for
> jinja2-26. Whoever had the idea of using jinja2-26 instead of jinja2 is
> incorrect.
> I think you misunderstood my point. I did the research before and it's not
> the same. I think the person who packaged it had a different idea in mind
> for it.
> 
> The jinja2-26http://dl.fedoraproject.org/pub/epel/6/x86_64/repoview/python-jinja2-26.htmlpackage from EPEL is for RHEL 6, 64 bit. There is no jinja2 package
> available other than that one. How is it acceptable for EPEL not to
> conflict with RHEL if the only way to get that correct (jinja2) RPM is the
> optional repo, which some users might not have? This means you'd either
> have to build your own repo, pay for the optional repo, or manually perform
> a local installation every time you want to run the bootstrap script. It's
> not really friendly for new users. Does that make more sense?
> 
> The point I'm making is that EPEL WILL NOT package something if it exists
> anywhere in RHEL. This has been policy for a while. Thus, the fact that
> jinja2 is in the optional repo on rhel (and CentOS just puts it in the
> general repo) means that this will not show up in EPEL. The jinja2-26
> package should not EVER be brought in to any package or to bootstrap. If it
> is, this is wrong.

I agree that it's a bit annoying, but it's the way it is. If you are using
RHEL, you should be paying for optional to use salt. Either that, or salt
should package it and put it in its own repositories. I'm not really for
that idea, however, since there's already a maintainer.

I hope that clears things up.

herlo

**Comment by gravyboat** [comment]
Yea I'm agreeing with you that jinja2-26 should NEVER be part of any requires, package, bootstrap, etc. It is worthless. 

Your answer clears things up, I don't like it, but that's not your fault, it's Red Hat's fault for deciding that package should live in optional.

I am still in favor of adding logic for trying to determine whether the optional repo is available in the bootstrap, and if so it will enable it so the user doesn't have to do some gimmicky work around, and if it isn't available, it can at least error out with a half decent error message for RHEL users so they aren't wasting time trying to figure out what isn't working.

**Comment by gravyboat** [comment]
Yep we're in agreement here then! 

@s0undt3ch , I'l try to work on the RHEL portion of the bootstrap when I get some time, we just need to basically make a copy of the fedora/centos one with the rhn-channel content I posted earlier (and better logic for checking if it is available obviously), as well as a decent error message.

Thanks for the input Herlo.

**Comment by s0undt3ch** [comment]
I'm glad we're in sync. Thanks @herlo!

@gravyboat I'll be waiting for your pull request ;)

**Comment by s0undt3ch** [comment]
RHEL 6 users are now warned about this issue. Closing as fixed.
