### ISSUE TITLE
Rocky Linux 8 Container is missing find command

### ISSUE THREAD

**Issue by blu-base** [saltstack/salt-bootstrap#1991]
### Description of Issue/Question

For bootstraps from version 3006.0 there seems to be a scriptlet which is expecting the `find`command.
However, in the container for Rocky Linux 8 apparently is no `find` command available.

The ubiquitous `findutils` is preinstalled in all RHEL-based Distro (-containers), but Rocky Linux 8... 

https://github.com/saltstack/salt-bootstrap/actions/runs/7628876701/job/20781257386
```
        *  INFO: Running install_rocky_linux_onedir()
       Last metadata expiration check: 0:00:02 ago on Tue Jan 23 16:45:34 2024.
       Dependencies resolved.
       ================================================================================
        Package             Architecture Version                 Repository       Size
       ================================================================================
       Installing:
        salt-master         x86_64       3006.5-0                saltstack       3.4 M
        salt-minion         x86_64       3006.5-0                saltstack       235 k
       Installing dependencies:
        dmidecode           x86_64       1:3.3-5.el8             baseos           91 k
        hwdata              noarch       0.314-8.19.el8          baseos          1.8 M
        openssl             x86_64       1:1.1.1k-9.el8_7        baseos          709 k
        pciutils            x86_64       3.7.0-3.el8             baseos          104 k
        pciutils-libs       x86_64       3.7.0-3.el8             baseos           53 k
        salt                x86_64       3006.5-0                saltstack        57 M
       
       Transaction Summary
       ================================================================================
       Install  8 Packages
       
       Total download size: 64 M
       Installed size: 183 M
       Downloading Packages:
       (1/8): dmidecode-3.3-5.el8.x86_64.rpm           195 kB/s |  91 kB     00:00    
       (2/8): pciutils-3.7.0-3.el8.x86_64.rpm          880 kB/s | 104 kB     00:00    
       (3/8): pciutils-libs-3.7.0-3.el8.x86_64.rpm     449 kB/s |  53 kB     00:00    
       (4/8): hwdata-0.314-8.19.el8.noarch.rpm         1.7 MB/s | 1.8 MB     00:01    
       (5/8): openssl-1.1.1k-9.el8_7.x86_64.rpm        601 kB/s | 709 kB     00:01    
       (6/8): salt-3006.5-0.x86_64.rpm                  88 MB/s |  57 MB     00:00    
       (7/8): salt-master-3006.5-0.x86_64.rpm           10 MB/s | 3.4 MB     00:00    
       (8/8): salt-minion-3006.5-0.x86_64.rpm          866 kB/s | 235 kB     00:00    
       --------------------------------------------------------------------------------
       Total                                            43 MB/s |  64 MB     00:01     
       Running transaction check
       Transaction check succeeded.
       Running transaction test
       Transaction test succeeded.
       Running transaction
         Preparing        :                                                        1/1 
         Installing       : pciutils-libs-3.7.0-3.el8.x86_64                       1/8 
         Running scriptlet: pciutils-libs-3.7.0-3.el8.x86_64                       1/8 
         Installing       : openssl-1:1.1.1k-9.el8_7.x86_64                        2/8 
         Installing       : hwdata-0.314-8.19.el8.noarch                           3/8 
         Installing       : pciutils-3.7.0-3.el8.x86_64                            4/8 
         Installing       : dmidecode-1:3.3-5.el8.x86_64                           5/8 
         Running scriptlet: salt-3006.5-0.x86_64                                   6/8 
         Installing       : salt-3006.5-0.x86_64                                   6/8 
         Running scriptlet: salt-3006.5-0.x86_64                                   6/8 
         Running scriptlet: salt-master-3006.5-0.x86_64                            7/8 
       /var/tmp/rpm-tmp.7pYvQP: line 3: find: command not found
       error: %prein(salt-master-3006.5-0.x86_64) scriptlet failed, exit status 127
       
       Error in PREIN scriptlet in rpm package salt-master
         Installing       : salt-minion-3006.5-0.x86_64                            8/8 
       error: salt-master-3006.5-0.x86_64: install failed
       
         Running scriptlet: salt-minion-3006.5-0.x86_64                            8/8 
         Verifying        : dmidecode-1:3.3-5.el8.x86_64                           1/8 
         Verifying        : hwdata-0.314-8.19.el8.noarch                           2/8 
         Verifying        : openssl-1:1.1.1k-9.el8_7.x86_64                        3/8 
         Verifying        : pciutils-3.7.0-3.el8.x86_64                            4/8 
         Verifying        : pciutils-libs-3.7.0-3.el8.x86_64                       5/8 
         Verifying        : salt-3006.5-0.x86_64                                   6/8 
         Verifying        : salt-master-3006.5-0.x86_64                            7/8 
         Verifying        : salt-minion-3006.5-0.x86_64                            8/8Error: Transaction failed
        
       
       Installed:
         dmidecode-1:3.3-5.el8.x86_64             hwdata-0.314-8.19.el8.noarch        
         openssl-1:1.1.1k-9.el8_7.x86_64          pciutils-3.7.0-3.el8.x86_64         
         pciutils-libs-3.7.0-3.el8.x86_64         salt-3006.5-0.x86_64                
         salt-minion-3006.5-0.x86_64             
       Failed:
         salt-master-3006.5-0.x86_64                                                   
       
        * ERROR: Failed to run install_rocky_linux_onedir()!!!
       You asked for bootstrap install and you have got 3006.5, hope thats ok!
       Downloading files from <onedir-3006-rockylinux-8>
       Finished converging <onedir-3006-rockylinux-8> (0m25.93s).
```

### Setup
(Please provide relevant configs (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible, `bootstrap-salt.sh -D`.)

Run the workflow for commit https://github.com/saltstack/salt-bootstrap/commit/e05d70558f7aa1bc4b3ecce530e1ad60f4bab7ac

### Versions and Systems
(`salt --versions-report`, `bootstrap-salt.sh -v`, system type and version,
cloud/VM provider as appropriate.)

**Comment by dmurphy18** [comment]
@blu-base Wondering why this is an issue for Salt , and not for the Rocky 8 container, given that the find command is basically part of every Linux OS shipped.

I remember RHEL 6.2 minimal shipped with no ssh, funny how 6.3 minimal added it back in, might have been 6.1 and 6.2, long time ago, but point is, why is this not a problem for the container ?

**Comment by blu-base** [comment]
Regarding ssh, the base images of rhel-based distros likey haven't have ssh included for a long time. For an appliance image it doesn't even make sense to include all conventional tooling. I guess it would be better to test on the UBI container for the rhel derivatives. This is much closer to a conventional system managed by a salt-minion.

_But why is this relevant for the salt project?_

EL8 is going to stay around for another 5 years. The RL8 part of the CI hasn't been running for at least the last 6 month.  An in small parts broken CI likely is not helping with the other refactoring you guys are currently doing.

My reasoning why having find installed during bootstrapping is because, currently, it's an implicit dependency, but a dependency non the less. 

Let's ask us the same question about `procps` , why is it getting installed in the same section of the bootstrap script. The command `ps` is also installed on almost every conventionally managed system.
https://github.com/saltstack/salt-bootstrap/blob/e05d70558f7aa1bc4b3ecce530e1ad60f4bab7ac/bootstrap-salt.sh#L4811

I think we could project the (assumed) intent of installing `procps` at boostrap (to make sure `ps` (or `sysctl`) are surely available) to the `findutils` package, too. Though, i can understand the wish to not add debt to the script.

**Comment by dmurphy18** [comment]
@blu-base Yes, ssh is coming with openssh-clients-xxxxxx, but for all practical purposes, Linux OS in their default ship with ssh installed, except that minimal RHEL 6.x version :) .

Salt is designed for a regular version  of a Linux OS, e.g. desktop etc, rather than some minimal version, and containers are designed for minimizing what is needed for the app to function etc.

That said, if using it in the spec file, then need to ensure that it is installed too, and will look at adding to the bootstrap script.  However the bootstrap script is going through a major overhaul at the moment, see https://github.com/saltstack/salt-bootstrap/issues/1940 and https://github.com/saltstack/salt-bootstrap/pull/1987

Will approve the PR but expect major changes coming to the bootstrap script.

**Comment by blu-base** [comment]
I understand. The undergoing work has been mentioned in the community hours. Feel free to close the respective PR if it adds unnecessary noise. This is just "getting my feet wet" with this sub project and looking for opportunities to contribute

**Comment by dmurphy18** [comment]
@blu-base Closing this since resolved by PR https://github.com/saltstack/salt-bootstrap/pull/1987 and now available in current stable release (2024-07-12).
