### ISSUE TITLE
unbound variable on Gentoo

### ISSUE THREAD

**Issue by tmessi** [saltstack/salt-bootstrap#201]
bootstrapping fails with the following error:

<pre>
/tmp/bootstrap_salt.sh: line 2712: __gentoo_use_binhost: unbound variable
</pre>

**Comment by s0undt3ch** [comment]
Thanks for the report, we'll fix this asap.

**Comment by s0undt3ch** [comment]
what version of the script is this?

**Comment by s0undt3ch** [comment]
I'm unable to reproduce.
Are you using the latest available script?
The full output with `-D` would also help a lot.

**Comment by tmessi** [comment]
I pulled the latest from develop today and got the error above. I'll get output with `-D` for you as soon as I can.

**Comment by tmessi** [comment]
Here is the output after runing the following:

<pre>
curl -L https://raw.github.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh | sudo sh -s -- -D git develop
</pre>

(I trimmed out the long emerge --sync output)

<pre>
*  INFO: PIPED THROUGH sh -- Version 1.5.7
*  WARN: Running the unstable version of bootstrap-salt.sh
*  INFO: System Information:
*  INFO:   CPU:          GenuineIntel
*  INFO:   CPU Arch:     x86_64
*  INFO:   OS Name:      Linux
*  INFO:   OS Version:   3.6.11-gentoo
*  INFO:   Distribution: Gentoo 2.1
*  INFO: Installing minion
* DEBUG: install_gentoo_2_git_deps not found....
* DEBUG: install_gentoo_2_1_git_deps not found....
* DEBUG: install_gentoo_2_deps not found....
* DEBUG: install_gentoo_2_1_deps not found....
*  INFO: Found function install_gentoo_git_deps
* DEBUG: DEPS_INSTALL_FUNC=install_gentoo_git_deps
* DEBUG: CONFIG_SALT_FUNC=null
* DEBUG: PRESEED_MASTER_FUNC=null
* DEBUG: install_gentoo_2_git not found....
* DEBUG: install_gentoo_2_1_git not found....
*  INFO: Found function install_gentoo_git
* DEBUG: INSTALL_FUNC=install_gentoo_git
* DEBUG: install_gentoo_2_git_post not found....
* DEBUG: install_gentoo_2_1_git_post not found....
* DEBUG: install_gentoo_2_post not found....
* DEBUG: install_gentoo_2_1_post not found....
* DEBUG: install_gentoo_git_post not found....
*  INFO: Found function install_gentoo_post
* DEBUG: POST_INSTALL_FUNC=install_gentoo_post
* DEBUG: install_gentoo_2_git_restart_daemons not found....
* DEBUG: install_gentoo_2_1_git_restart_daemons not found....
* DEBUG: install_gentoo_2_restart_daemons not found....
* DEBUG: install_gentoo_2_1_restart_daemons not found....
* DEBUG: install_gentoo_git_restart_daemons not found....
*  INFO: Found function install_gentoo_restart_daemons
* DEBUG: STARTDAEMONS_INSTALL_FUNC=install_gentoo_restart_daemons
* DEBUG: daemons_running_gentoo_2_git not found....
* DEBUG: daemons_running_gentoo_2_1_git not found....
* DEBUG: daemons_running_gentoo_2 not found....
* DEBUG: daemons_running_gentoo_2_1 not found....
* DEBUG: daemons_running_gentoo_git not found....
* DEBUG: daemons_running_gentoo not found....
*  INFO: Found function daemons_running
* DEBUG: DAEMONS_RUNNING_FUNC=daemons_running
*  INFO: Running install_gentoo_git_deps()
!!! Your current profile is deprecated and not supported anymore.
!!! Use eselect profile to update your profile.
!!! Please upgrade to the following profile if possible:
        default/linux/amd64/13.0
Calculating dependencies  
 * IMPORTANT: 2 news items need reading for repository 'gentoo'.
 * Use eselect news to read news items.
... done!
>>> Verifying ebuild manifests
>>> Jobs: 0 of 1 complete, 1 running                Load avg: 0.04, 0.87, 0.78
>>> Emerging (1 of 1) dev-vcs/git-1.8.1.5
>>> Jobs: 0 of 1 complete, 1 running                Load avg: 0.04, 0.87, 0.78
>>> Installing (1 of 1) dev-vcs/git-1.8.1.5
>>> Jobs: 0 of 1 complete, 1 running                Load avg: 1.41, 1.13, 0.87
>>> Jobs: 0 of 1 complete                           Load avg: 1.41, 1.13, 0.87
>>> Jobs: 1 of 1 complete                           Load avg: 1.37, 1.13, 0.87
 * Messages for package dev-vcs/git-1.8.1.5:
 * These additional scripts need some dependencies:
 *   git-quiltimport  : dev-util/quilt
 *   git-instaweb     : || ( www-servers/lighttpd www-servers/apache )
>>> Auto-cleaning packages...
>>> No outdated packages were found on your system.
 * GNU info directory index is up-to-date.
 * IMPORTANT: 2 news items need reading for repository 'gentoo'.
 * Use eselect news to read news items.
!!! Your current profile is deprecated and not supported anymore.
!!! Use eselect profile to update your profile.
!!! Please upgrade to the following profile if possible:
        default/linux/amd64/13.0
Welcome to boobie.gentoo.org / rsync.gentoo.org
Server Address : 91.186.30.235
Contact Name   : mirror-admin@gentoo.org
Hardware       : 2 x Intel(R) Xeon(R) CPU 3050 @ 2.13GHz, 3958MB RAM
Sponsor        : EUKhost, Maidenhead, England
Please note: common gentoo-netiquette says you should not sync more
than once a day.  Users who abuse the rsync.gentoo.org rotation
may be added to a temporary ban list.
MOTD autogenerated by update-rsync-motd on Sun Apr  1 01:05:34 UTC 2012
receiving incremental file list
timestamp.chk
Number of files: 1
Number of files transferred: 1
Total file size: 32 bytes
Total transferred file size: 32 bytes
Literal data: 32 bytes
Matched data: 0 bytes
File list size: 27
File list generation time: 0.001 seconds
File list transfer time: 0.000 seconds
Total bytes sent: 98
Total bytes received: 620
sent 98 bytes  received 620 bytes  478.67 bytes/sec
total size is 32  speedup is 0.04
Welcome to boobie.gentoo.org / rsync.gentoo.org
Server Address : 91.186.30.235
Contact Name   : mirror-admin@gentoo.org
Hardware       : 2 x Intel(R) Xeon(R) CPU 3050 @ 2.13GHz, 3958MB RAM
Sponsor        : EUKhost, Maidenhead, England
Please note: common gentoo-netiquette says you should not sync more
than once a day.  Users who abuse the rsync.gentoo.org rotation
may be added to a temporary ban list.
MOTD autogenerated by update-rsync-motd on Sun Apr  1 01:05:34 UTC 2012
receiving incremental file list
*** trimed sync output ***
Number of files: 169878
Number of files transferred: 17
Total file size: 297.97M bytes
Total transferred file size: 604.60K bytes
Literal data: 604.60K bytes
Matched data: 0 bytes
File list size: 4.03M
File list generation time: 0.001 seconds
File list transfer time: 0.000 seconds
Total bytes sent: 41.95K
Total bytes received: 4.76M
sent 41.95K bytes  received 4.76M bytes  147.64K bytes/sec
total size is 297.97M  speedup is 62.10
>>> Starting rsync with rsync://91.186.30.235/gentoo-portage...
>>> Checking server timestamp ...
 * An update to portage is available. It is _highly_ recommended
 * that you update portage now, before any other packages are updated.
 * To update portage, run 'emerge portage' now.
 * IMPORTANT: 2 news items need reading for repository 'gentoo'.
 * Use eselect news to read news items.
sh: line 2712: __gentoo_use_binhost: unbound variable
 * DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe
 * DEBUG: Killing logging pipe tee's with pid(s): 11362
</pre>

**Comment by s0undt3ch** [comment]
Hmm. Thanks! I'll spin up a VM as soon as I can and debug this issue.

**Comment by tmessi** [comment]
Looks like the issue is with calling a function as a variable. A quick script shows this doesn't seem to work.

For example the following:

<pre>
#!/bin/sh -
__foo(){
    return "bar"
}
echo ${__foo}
</pre>

Does not actually echo `"bar"`, it just prints a new line.

and if you add `set - o nounset` like so:

<pre>
#!/bin/sh -
set -o nounset
__foo(){
    return "bar"
}
echo ${__foo}
</pre>

You get the same error as the bootstrap script

<pre>
./foo.sh:  line 9: __foo: unbound variable
</pre>

**Comment by s0undt3ch** [comment]
How did that work in the first place :)

**Comment by s0undt3ch** [comment]
Could you please run:

```
curl -L https://raw.github.com/s0undt3ch/salt-bootstrap/issues/201/bootstrap-salt.sh | sudo sh -s -- -D git develop
```

Does this solve the issue?

**Comment by tmessi** [comment]
seems to have done the trick. thanks

**Comment by s0undt3ch** [comment]
Nice!
