### ISSUE TITLE
[Feature Request] salt-api not installed in onedir

### ISSUE THREAD

**Issue by Foorack** [saltstack/salt-bootstrap#2012]
### Description of Issue/Question

There is no way to tell bootstrap to install `salt-api` when using the `onedir` method.

This is effectively a breakout of https://github.com/saltstack/salt-bootstrap/issues/609#issuecomment-250011006 to be able to track it.

> There isn't a flag currently in the bootstrap script that handles installing the salt-api package. This needs to be added for all distros that split out the salt-api package, which I believe is most (if not all) of the distros packaged and hosted on repo.saltstack.com.

### Steps to Reproduce Issue

```
curl -L https://bootstrap.saltstack.com -o install_salt.sh
sh install_salt.sh -d -M -X onedir 3007.1
salt-api      # COMMAND DOES NOT EXIST
```

**Comment by amalaguti** [comment]
Just had the same issue with 3006.8

**Comment by dmurphy18** [comment]
@Foorack Wow, quoting an issue from 2015, bootstrap appear not to have this functionality, so treating this as a Feature Request. Need to pick an option flag to install salt_api and ensure salt-master is installed if selected, same for syndic

Note, the salt-api won't be enabled at boot, given the amount of times this comment appears
```
Skip salt-api since the service should be opt-in and not necessarily started on boot
```
