### ISSUE TITLE
https://bootstrap.saltproject.io/sha256 gives 404

### ISSUE THREAD

**Issue by hvt** [saltstack/salt-bootstrap#2025]
### Description of Issue/Question

```
$ wget https://bootstrap.saltproject.io/sha256
--2024-10-28 10:54:37--  https://bootstrap.saltproject.io/sha256
Resolving bootstrap.saltproject.io (bootstrap.saltproject.io)... 185.199.108.153, 185.199.109.153, 185.199.110.153, ...
Connecting to bootstrap.saltproject.io (bootstrap.saltproject.io)|185.199.108.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-10-28 10:54:37 ERROR 404: Not Found.
```

The regular `https://bootstrap.saltproject.io` artifact seems to work just fine.

**Comment by hvt** [comment]
Mmm, I just read https://saltproject.io/blog/salt-bootstrap-breakage/ and that seems to be the issue.

I am using the Vagrant Salt plugin and that uses the old-style GitHub Pages links (see https://github.com/hashicorp/vagrant/blob/71150ee3d8c59c2e27acd8278ae0cad99d12f212/plugins/provisioners/salt/bootstrap_downloader.rb).

Luckily @max-arnold already created a PR to update the Vagrant plugin (see https://github.com/hashicorp/vagrant/pull/13517).

**Comment by tazaki** [comment]
Also having an issue with vagrant. Seems as though the https://github.com/saltstack/salt-bootstrap/releases/latest/download/bootstrap-salt.sh still points to repos at https://repo.saltproject.io/salt ?

**Comment by dmurphy18** [comment]
Closing this since https://github.com/saltstack/salt-bootstrap/issues/2027 is handling all issues related to the recent infrastructure changes, issues and fixes will be tracked there
