### ISSUE TITLE
Unable install salt master and minions using ./bootstrap-salt.sh -M

### ISSUE THREAD

**Issue by NaveenKummetha** [saltstack/salt-bootstrap#2026]
### Setup
Just download ubuntu 20.4 and jump into ubuntu 20.4 

### Steps to Reproduce Issue
Just download ubuntu 20.4 and jump into ubuntu 20.4 
Follow below page:
 https://docs.saltproject.io/salt/install-guide/en/latest/topics/bootstrap.html#commonly-used-bootstrap-script-options

Followed "Install using the bootstrap script" section from above page.
getting below error.

<img width="931" alt="Screenshot 2024-10-29 at 12 28 09 PM" src="https://github.com/user-attachments/assets/00123ea3-57f9-49d7-aa1f-09e56128dcde">

Logs:
`root@ff9a632b3e45:/# ./bootstrap-salt.sh -D
./bootstrap-salt.sh: line 1: syntax error near unexpected token `newline'
./bootstrap-salt.sh: line 1: `<meta http-equiv="refresh" content="0; url=./bootstrap-salt.sh" />'`

### Versions and Systems
Getting below log for version check also
`root@ff9a632b3e45:/# ./bootstrap-salt.sh -v
./bootstrap-salt.sh: line 1: syntax error near unexpected token `newline'
./bootstrap-salt.sh: line 1: `<meta http-equiv="refresh" content="0; url=./bootstrap-salt.sh" />'`
(`salt --versions-report`, `bootstrap-salt.sh -v`, system type and version,
cloud/VM provider as appropriate.)

**Comment by Devorkin** [comment]
@NaveenKummetha I just experienced the same issue as you.
Found those 2 blog posts
Part #1: https://saltproject.io/blog/salt-bootstrap-breakage/
Part #2 https://saltproject.io/blog/salt-bootstrap-breakage-part-2/

In short, you can and should download the bootstrap script from [here](https://github.com/saltstack/salt-bootstrap/releases/latest/download/bootstrap-salt.sh), on-going forward.

**Comment by NaveenKummetha** [comment]
Thank you very much Devorkin. Let me check this.
