### ISSUE TITLE
salt-bootstrap scripts broken: Need a new release to work with packages.broadcom.com repos

### ISSUE THREAD

**Issue by ScriptAutomate** [saltstack/salt-bootstrap#2027]
### Description of Issue/Question

`salt-bootstrap` needs updating to work with the new `packages.broadcom.com` repo hosting, layout, and package management layer of version pinning (apt, dnf), the removal of all Salt versions before Salt 3006 LTS, etc. since the migration (Salt Project Blog post: [Salt Project Package Repository (repo.saltproject.io) Migration and Guidance](https://saltproject.io/blog/salt-project-package-repo-migration-and-guidance/) and [Salt Install Guide Overhaul and salt-bootstrap updates](https://saltproject.io/blog/salt-install-guide-overhaul/)).

The Salt Install Guide has been updated to show how people can install on target systems without `salt-bootstrap` at the moment, and can be used as a reference point for updating `salt-bootstrap` logic:

- https://docs.saltproject.io/salt/install-guide/en/latest/

### Follow-up steps

This also means, upon completion, that documentation in both this repo and the https://github.com/saltstack/salt-install-guide will need updates based on changes in the script behavior.

- https://github.com/saltstack/salt-install-guide/issues/3

**Comment by ipaqmaster** [comment]
Same here. This has been handled no less than horribly. 783 servers failed to provision today due to failing to make a connection with repo.saltproject.io. All it needed was a 302 redirect but not even that could be achieved with Broadcom.

This is a mess and good reason to migrate states to Ansible.

**Comment by sanket925** [comment]
Ridiculous and completely unprofessional change from Broadcom unless this is a security issue. The infrastructure to support new repo is not updated before the closure of existing repositories.  This has impacted our production deployments resulting in  SEV-A situations in a holiday week.

**Comment by ghost** [comment]
I spent half an hour trying to figure out why all my machines' DNS are blowing up and can't resolve `repo.saltproject.io`, turns out it's because Broadcom intentionally broke it. 💀

FFS, add a fucking 302 redirection.

**Comment by aholyoake-bc** [comment]
A 302 wouldn't work by the looks - the deb repo structure is completely different.
Absolute shambles :rage4:

**Comment by tjyang** [comment]
Waiting for a newer  bootstrap-salt.sh that use broadcom URL.

```
root@ubuntu22t01:~# bash bootstrap-salt.sh -v
bootstrap-salt.sh -- Version 2024.09.24
root@ubuntu22t01:~# egrep "saltproject\.io"  bootstrap-salt.sh
#  ORGANIZATION: SaltStack (saltproject.io)
_REPO_URL="repo.saltproject.io"
                           for packages available at repo.saltproject.io
                           packages available at repo.saltproject.io
                           onedir packages available at repo.saltproject.io
                           onedir RC packages available at repo.saltproject.io
        repo.saltproject.io. The option passed with -R replaces the
        "repo.saltproject.io". If -R is passed, -r is also set. Currently only
# Set the _REPO_URL value based on if -R was passed or not. Defaults to repo.saltproject.io.
url = "https://repo.saltproject.io/salt/py3/macos/repo.json"
root@ubuntu22t01:~#
```

**Comment by mconnley** [comment]
When was the deprecation of repo.saltproject.io first announced? The earliest I see any mention of it is [here](https://saltproject.io/blog/upcoming-salt-project-docs-and-repo-migration/) on 10/23. That's 8 days ago.

Surely it must have been announced longer ago than that.

**Comment by cxdy** [comment]
@mconnley Nope, that's when it was announced 🙃

**Comment by mconnley** [comment]
@cxdy If that's accurate and there aren't any truly, truly compelling extenuating circumstances... I really don't even know what to say about that.

**Comment by ZsBT** [comment]
huh it also breaks salt-cloud deployments which is a vein cut in cloud environments. I've found the RHEL repos are at https://packages.broadcom.com/artifactory/saltproject-rpm/ but the bootstrap script works more complicated than we could replace the URL somewhere.

For a temporary workaroud, I've made a very ugly hotfix to make the RHEL bootstrap script work.
Based on the original material: https://github.com/saltstack/salt-bootstrap/releases/latest/download/bootstrap-salt.sh

```
--- orig-bootstrap-salt.sh     2024-09-24 23:42:30.000000000 +0200
+++ bootstrap-salt.sh   2024-11-01 20:11:58.481604547 +0100
@@ -4066,18 +4066,22 @@
 
     repo_file="/etc/yum.repos.d/salt.repo"
 
+# UGLY hack - yuck!!
+base_url="https://packages.broadcom.com/artifactory/saltproject-rpm/"
+
     if [ ! -s "$repo_file" ] || [ "$_FORCE_OVERWRITE" -eq $BS_TRUE ]; then
         cat <<_eof > "$repo_file"
 [saltstack]
 name=SaltStack ${repo_rev} Release Channel for RHEL/CentOS \$releasever
 baseurl=${base_url}
 skip_if_unavailable=True
-gpgcheck=1
-gpgkey=${gpg_key_urls}
+gpgcheck=0
 enabled=1
 enabled_metadata=1
 _eof
 
+return 0
+
         fetch_url="${HTTP_VAL}://${_REPO_URL}/${_ONEDIR_DIR}/${__PY_VERSION_REPO}/redhat/${DISTRO_MAJOR_VERSION}/${CPU_ARCH_L}/${ONEDIR_REV}/"
         if [ "${ONEDIR_REV}" = "nightly" ] ; then
             fetch_url="${HTTP_VAL}://${_REPO_URL}/${_ONEDIR_NIGHTLY_DIR}/${__PY_VERSION_REPO}/redhat/${DISTRO_MAJOR_VERSION}/${CPU_ARCH_L}/"
```

**Comment by dmurphy18** [comment]
@twangboy working on Windows script 
@dmurphy18 working on shell script

**Comment by skob** [comment]
any news here?..
maybe some workaround?..

**Comment by aholyoake-bc** [comment]
After going through the script it turns out for a debian onedir install it's just doing an 
```
apt-get install salt-common salt-minion
``` 

In broadcom's jFrog repo there seems to be no choice which version of debian you can install for, so all but about 5 lines out of 8000+ are irrelevant in our case.

We've moved the currently available debs to a private google `apt` artifact repository and removed salt-bootstrap entirely from our stack overnight. We'll stay on 3006.7 while we aggressively migrate away from salt.

Two breakages (first was a move in where the bootstrap script was hosted) in a week and we've had enough after 9 years.

Thanks Broadcom /s

**Comment by ftrueck** [comment]
> After going through the script it turns out for a debian onedir install it's just doing an
> 
> ```
> apt-get install salt-common salt-minion
> ```

Not if you used the bootstrap script before, because it added a salt.list to /etc/apt/sources.list.d
In that there is the old repo url which breaks the whole thing. I have no clue on how to change the package line in it because I have no clue how the new folder structure is working. It would be easy if someone could just do a public comment what the new deb line should be.

> In broadcom's jFrog repo there seems to be no choice which version of debian you can install for, so all but about 5 lines out of 8000+ are irrelevant in our case.
> 
> We've moved the currently available debs to a private google `apt` artifact repository and removed salt-bootstrap entirely from our stack overnight. We'll stay on 3006.7 while we aggressively migrate away from salt.
> 
> Two breakages (first was a move in where the bootstrap script was hosted) in a week and we've had enough after 9 years.
> 
> Thanks Broadcom /s

Yeah, its a shame how this was pulled off. Makes one think there is not a lot of interest in this project anymore...

**Comment by cxdy** [comment]
I mean, you can just remove the file. Or modify the workaround script to remove the file if it exists.

**Comment by ftrueck** [comment]
That's the first thing I tried, but the bootstrap script and the sources.list file in the project are not updated yet. The result is the old repo gets added again. There is a pull request fixing "something" but it is not yet merged since there is a conflict that prevents the merge.

**Comment by mconnley** [comment]
@ftrueck 
> It would be easy if someone could just do a public comment what the new deb line should be.

This? 
`deb https://packages.broadcom.com/artifactory/saltproject-deb/ stable main`

**Comment by ftrueck** [comment]
Wow, yes!!! Thanks :-) Sorry for being a noob there. I never took the time to fully understand the way apt folder structures work ;-)

**Comment by ghost** [comment]
Workaround to replace salt repo URL:

`salt '*' cmd.run "sed -i 's#https://repo.saltproject.io/salt/py3/ubuntu/24.04/amd64/latest noble main#https://packages.broadcom.com/artifactory/saltproject-deb stable main#' /etc/apt/sources.list.d/salt.list"`

Replace the distro & arch as needed.

**Comment by tjyang** [comment]
> https://packages.broadcom.com/artifactory/saltproject-deb

@AutisticShark , Do you know how can I set the broadcom repo URL to get stable 3006.9 version ?  not sure why "stable" is pointing to STS 3007.x version.

We can see 3006.x  .deb pkgs are under https://packages.broadcom.com/artifactory/saltproject-deb/pool/

```
root@ubuntu24t01:~# more  /etc/apt/sources.list.d/salt.list
deb [signed-by=/usr/share/keyrings/salt-archive-keyring.gpg] https://packages.broadcom.com/artifactory/saltproject-deb stable main
root@ubuntu24t01:~# apt install salt-minion
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  salt-common
The following NEW packages will be installed:
  salt-common salt-minion
0 upgraded, 2 newly installed, 0 to remove and 244 not upgraded.
Need to get 36.6 MB of archives.
After this operation, 169 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:2 https://packages.broadcom.com/artifactory/saltproject-deb stable/main amd64 salt-minion amd64 3007.1 [92.7 kB]
Get:1 https://packages.broadcom.com/artifactory/saltproject-deb stable/main amd64 salt-common amd64 3007.1 [36.6 MB]
Fetched 36.6 MB in 15s (2,381 kB/s)
Selecting previously unselected package salt-common.
(Reading database ... 349899 files and directories currently installed.)
Preparing to unpack .../salt-common_3007.1_amd64.deb ...
Adding group salt....done
Adding system user salt....done
Unpacking salt-common (3007.1) ...
Selecting previously unselected package salt-minion.
Preparing to unpack .../salt-minion_3007.1_amd64.deb ...
Unpacking salt-minion (3007.1) ...
Setting up salt-common (3007.1) ...
Setting up salt-minion (3007.1) ...
Processing triggers for man-db (2.12.0-4build2) ...
Processing triggers for libc-bin (2.39-0ubuntu8.3) ...
/sbin/ldconfig.real: /lib/x86_64-linux-gnu/libssl.so.1.1 is not a symbolic link

root@ubuntu24t01:~#

```

**Comment by ScriptAutomate** [comment]
@tjyang 
> > https://packages.broadcom.com/artifactory/saltproject-deb
> 
> Do you know how can I set the broadcom repo URL to get stable 3006.9 version ? not sure why "stable" is pointing to STS 3007.x version.
> 
> We can see 3006.x .deb pkgs are under https://packages.broadcom.com/artifactory/saltproject-deb/pool/
>

Can take a look here - users can pin to a specific major version via `preferences.d` configs:

- [Salt Install Guide: Linux (DEB)](https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/linux-deb.html)

> Populate `/etc/apt/preferences.d/salt-pin-1001` in order to restrict upgrades to Salt 3006.x LTS:
>
> ```bash
> echo 'Package: salt-*
> Pin: version 3006.*
> Pin-Priority: 1001' | sudo tee /etc/apt/preferences.d/salt-pin-1001
> ```

**Comment by tjyang** [comment]
> @tjyang
> 
> > > https://packages.broadcom.com/artifactory/saltproject-deb
> > 
> > 
> > Do you know how can I set the broadcom repo URL to get stable 3006.9 version ? not sure why "stable" is pointing to STS 3007.x version.
> > We can see 3006.x .deb pkgs are under https://packages.broadcom.com/artifactory/saltproject-deb/pool/
> 
> Can take a look here - users can pin to a specific major version via `preferences.d` configs:
> 
> * [Salt Install Guide: Linux (DEB)](https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/linux-deb.html)
> 
> > Populate `/etc/apt/preferences.d/salt-pin-1001` in order to restrict upgrades to Salt 3006.x LTS:
> > ```shell
> > echo 'Package: salt-*
> > Pin: version 3006.*
> > Pin-Priority: 1001' | sudo tee /etc/apt/preferences.d/salt-pin-1001
> > ```
Thanks for this help, with salt-pin-1001 added file, I am now able to use my formula to update source.list across my ubuntu LTS minions.

**Comment by ketzacoatl** [comment]
This broke my AMI builds as well :(
I spent part of last week wondering what I did wrong and/or looking at what changed in the bootstrap script here.
I'm appreciative for this issue to understand the details, thanks.

**Comment by rcmoutinho** [comment]
Although I'm waiting for a fix via bootstrap script, I was able to install via RPM using the following config:

```
sudo bash -c 'cat <<EOF > /etc/yum.repos.d/saltproject.repo
[saltproject]
name=SaltProject Repository
baseurl=https://packages.broadcom.com/artifactory/saltproject-rpm/
enabled=1
gpgcheck=1
gpgkey=https://somewhere/you/might/have/the/SALT-PROJECT-GPG-PUBKEY-2023.gpg
EOF'

sudo yum install -y salt-minion-3006.9

# other packages like master, api, etc are also available under:
# https://packages.broadcom.com/artifactory/saltproject-rpm/
```

I was lucky to have the GPG key somewhere, but currently, I can't see `SALT-PROJECT-GPG-PUBKEY-2023.gpg` under Broadcom Artifactory. I guess once we have it there, it might manage the installation, or at least with some workarounds until the final fix.

You can still set `gpgcheck=0` to skip the verification, but that's not ideal at all!

All public references that I have for `SALT-PROJECT-GPG-PUBKEY-2023.gpg` are targeting `repo.saltproject.io` 😞 

Note that using this approach means you are losing all the easy ways we would have via the Bootstrap script. So you will also need to create your minimum minion reference and restart the service:

```
sudo bash -c 'cat <<EOF > /etc/salt/minion
master: your-salt-master-name
id: your-salt-minion-name
EOF'

sudo systemctl start salt-minion
```

This should give you minimal control of the target so you can run all your automation.

**Comment by ScriptAutomate** [comment]
@rcmoutinho 
> I was lucky to have the GPG key somewhere, but currently, I can't see `SALT-PROJECT-GPG-PUBKEY-2023.gpg` under Broadcom Artifactory. I guess once we have it there, it might manage the installation, or at least with some workarounds until the final fix.
> 
> You can still set `gpgcheck=0` to skip the verification, but that's not ideal at all!
> 
> All public references that I have for `SALT-PROJECT-GPG-PUBKEY-2023.gpg` are targeting `repo.saltproject.io` 😞

With Artifactory as the new backend, public keys are provided differently.

- New endpoint: https://packages.broadcom.com/artifactory/api/security/keypair/SaltProjectKey/public

In the new updates to the Salt Install Guide, `Linux (RPM)` includes the download of an updated `salt.repo` configuration which includes a reference to the new pub key on the users behalf:

- [Salt Install Guide: Linux (RPM)](https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/linux-rpm.html): Details how to use the new `salt.repo` file, etc.
  - [Permanent download location of `salt.repo`](https://github.com/saltstack/salt-install-guide/releases/latest/download/salt.repo)
  - [Source of the `salt.repo` file](https://github.com/saltstack/salt-install-guide/blob/main/salt.repo)

**Comment by kristoffertt** [comment]
Hey. 
TurtleTraction (www.turtletraction.com) has mirrored saltproject repos. These mirrors are now available to help you smooth the process. 

https://repo.saltproject.io.turtletraction.com/ 
https://archive.repo.saltproject.io.turtletraction.com/ 

Please handle with care and avoid pointing a large number of Salt Minions to it. 
As always, if you have any issues teach out to us on support@turtletraction.com or directly to me here.
Please, share the word in order to avoid interruption of others.

**Comment by rcmoutinho** [comment]
@ScriptAutomate thanks for the reference!

**Comment by tjyang** [comment]
@dmurphy18 

I grabbed  latest commit (11/04), The script is still not fixed for RH based distro.
- /bootstrap-salt.sh.11.01: line 4191: REPO_FILE: unbound variable
```bash
root@rocky8t03# ./bootstrap-salt.sh.11.01 stable
 *  INFO: Running version: 2024.11.01
 *  INFO: Executed by: shell pipe
 <snipped>
 *  INFO: Found function install_rocky_linux_onedir
 *  INFO: Found function install_rocky_linux_onedir_post
 *  INFO: Found function install_rocky_linux_restart_daemons
 *  INFO: Found function daemons_running_onedir
 *  INFO: Found function install_rocky_linux_check_services
 *  INFO: Running install_rocky_linux_onedir_deps()
./bootstrap-salt.sh.11.01: line 4191: REPO_FILE: unbound variable
root@rocky8t03# cksum bootstrap-salt.sh.11.01
805362595 300009 bootstrap-salt.sh.11.01
root@rocky8t03#
```
- work around  solution for now is like following, when new salt.repo got installed.
```
 REPO_FILE="/etc/yum.repos.d/salt.repo" ./bootstrap-salt.sh.11.01 onedir 3006
```
- When all salt stuff got removed.
```bash
root@rocky8t03# REPO_FILE="/etc/yum.repos.d/salt.repo" ./bootstrap-salt.sh.11.01 onedir 3006
 *  INFO: Running version: 2024.11.01
 *  INFO: Executed by: shell pipe
 *  INFO: Command line: './bootstrap-salt.sh.11.01 onedir 3006'
 <snipped>
 *  INFO: Running install_rocky_linux_onedir_deps()
 * ERROR: https://github.com/saltstack/salt-install-guide/releases/latest/download/salt.repo.repo failed to download to /etc/yum.repos.d/salt.repo
Error: No matching repo to modify: salt-repo-*.
Error: No matching repo to modify: salt-repo-latest.
Cache was expired
0 files removed
<snipped>
Dependencies resolved.
Nothing to do.
Complete!
 *  INFO: Running install_rocky_linux_onedir()
Last metadata expiration check: 0:00:01 ago on Tue Nov  5 09:51:13 2024.
No match for argument: salt-minion
Error: Unable to find a match: salt-minion
 * ERROR: Failed to run install_rocky_linux_onedir()!!!
root@rocky8t03#

```

**Comment by chrisnew** [comment]
We followed the instruction from the blog post (using https://github.com/saltstack/salt-bootstrap/releases/latest/download/bootstrap-salt.sh to bootstrap), but we ran into the same issue on Debian 12 again:

```
 * ERROR: https://repo.saltproject.io/salt/py3/debian/12/amd64/latest/SALT-PROJECT-GPG-PUBKEY-2023.gpg failed to download to /tmp/salt-gpg-KarB42Hb.pub
 ```

**Comment by kquinsland** [comment]
> @rcmoutinho
> 
> > I was lucky to have the GPG key somewhere, but currently, I can't see `SALT-PROJECT-GPG-PUBKEY-2023.gpg` under Broadcom Artifactory. I guess once we have it there, it might manage the installation, or at least with some workarounds until the final fix.
> > You can still set `gpgcheck=0` to skip the verification, but that's not ideal at all!
> > All public references that I have for `SALT-PROJECT-GPG-PUBKEY-2023.gpg` are targeting `repo.saltproject.io` 😞
> 
> With Artifactory as the new backend, public keys are provided differently.
> 
>     * New endpoint: https://packages.broadcom.com/artifactory/api/security/keypair/SaltProjectKey/public


-----


I drafted this yesterday, forgot to hit "submmit". This is a snip from the hacked-up script I'm using internally to keep our CI/CD pipe running:

```shell
# Previously:
# __apt_key_fetch "$SALTSTACK_UBUNTU_URL/SALT-PROJECT-GPG-PUBKEY-2023.gpg" || return 1

# A working host that has the key:
__apt_key_fetch "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x64cbbc8173d76b3f" || return 1
```

**Comment by kquinsland** [comment]
> I drafted this yesterday, forgot to hit "submmit", but this is a snip from the hacked-up script I'm using internally to keep our CI/CD pipe running:
> 
> ```shell
> # Previously:
> # __apt_key_fetch "$SALTSTACK_UBUNTU_URL/SALT-PROJECT-GPG-PUBKEY-2023.gpg" || return 1
> 
> # A working host that has the key:
> __apt_key_fetch "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x64cbbc8173d76b3f" || return 1
> ```


---

For completeness, this is the other "brute force" approach that we are using.

We are a debian shop so YMMV for other hosts, but just before the bootstrap script runs, we have this small hook:

```shell
sudo apt install -y gnupg
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 64CBBC8173D76B3F
```

Which then allows for a simpler `apt` setup:

```shell
# Previously: 
# echo "$__REPO_ARCH_DEB $SALTSTACK_UBUNTU_URL $UBUNTU_CODENAME main" >/etc/apt/sources.list.d/salt.list
# Crude, but works. Also assumes that the gpg key is in the apt-key store and not set to explicit `keyrings/salt-archive-keyring.gpg` location
echo "deb https://packages.broadcom.com/artifactory/saltproject-deb/ stable main" >/etc/apt/sources.list.d/salt.list

```

**Comment by ssoto2** [comment]
Experiencing the same issue as @chrisnew 

```
 *  INFO: Running version: 2024.09.24
 *  INFO: Executed by: sh
 *  INFO: Command line: 'bootstrap-salt.sh -X -P onedir'

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   4.18.0-553.22.1.el8_10.x86_64
 *  INFO:   Distribution: Rocky Linux 8.10

 *  INFO: Installing minion
 *  INFO: Daemons will not be started
 *  INFO: Found function install_rocky_linux_onedir_deps
 *  INFO: Found function config_salt
 *  INFO: Found function preseed_master
 *  INFO: Found function install_rocky_linux_onedir
 *  INFO: Found function install_rocky_linux_onedir_post
 *  INFO: Found function install_rocky_linux_restart_daemons
 *  INFO: Found function daemons_running_onedir
 *  INFO: Found function install_rocky_linux_check_services
 *  INFO: Running install_rocky_linux_onedir_deps()
 * ERROR: https://repo.saltproject.io/salt/py3/redhat/8/x86_64/latest/SALT-PROJECT-GPG-PUBKEY-2023.pub failed to download to /tmp/salt-gpg-41jEoMzr.pub
 * ERROR: Failed to run install_rocky_linux_onedir_deps()!!!

```

**Comment by jeffdyke** [comment]
> ```shell
> sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 64CBBC8173D76B3F
> ```

This was the nice final key, and i stored my bootstrap-init-hack.sh in s3 with the following differences, i didn't need to update the `debian` sections, but wanted to get rid of all of the `SALT-PROJECT-GPG-PUBKEY-2023.pub`
The above `sudo apt-key adv` command should be run before the bootstrap script. 
```
diff bootstrap-salt.sh bootstrap-salt-hack.sh
2925,2926c2925,2927
<     echo "$__REPO_ARCH_DEB $SALTSTACK_UBUNTU_URL $UBUNTU_CODENAME main" > /etc/apt/sources.list.d/salt.list
<     __apt_key_fetch "$SALTSTACK_UBUNTU_URL/SALT-PROJECT-GPG-PUBKEY-2023.gpg" || return 1
---
>     #echo "$__REPO_ARCH_DEB $SALTSTACK_UBUNTU_URL $UBUNTU_CODENAME main" > /etc/apt/sources.list.d/saltstack.list
>     echo "deb https://packages.broadcom.com/artifactory/saltproject-deb/ stable main" > /etc/apt/sources.list.d/saltstack.list
>     __apt_key_fetch "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x64cbbc8173d76b3f" || return 1
2970,2972c2971,2973
<     echo "$__REPO_ARCH_DEB $SALTSTACK_UBUNTU_URL $UBUNTU_CODENAME main" > /etc/apt/sources.list.d/salt.list
<
<     __apt_key_fetch "${SALTSTACK_UBUNTU_URL}SALT-PROJECT-GPG-PUBKEY-2023.gpg" || return 1
---
>     #echo "$__REPO_ARCH_DEB $SALTSTACK_UBUNTU_URL $UBUNTU_CODENAME main" > /etc/apt/sources.list.d/saltstack.list
>     echo "deb https://packages.broadcom.com/artifactory/saltproject-deb/ stable main" >/etc/apt/sources.list.d/saltstack.list
>     __apt_key_fetch "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x64cbbc8173d76b3f" || return 1
3418c3419,3420
<     echo "$__REPO_ARCH_DEB $SALTSTACK_DEBIAN_URL $DEBIAN_CODENAME main" > "/etc/apt/sources.list.d/salt.list"
---
>     # echo "$__REPO_ARCH_DEB $SALTSTACK_DEBIAN_URL $DEBIAN_CODENAME main" > "/etc/apt/sources.list.d/saltstack.list"
>     echo "deb https://packages.broadcom.com/artifactory/saltproject-deb/ stable main" >/etc/apt/sources.list.d/saltstack.list
3420c3422
<     __apt_key_fetch "$SALTSTACK_DEBIAN_URL/SALT-PROJECT-GPG-PUBKEY-2023.gpg" || return 1
---
>     __apt_key_fetch "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x64cbbc8173d76b3f" || return 1
3457c3459,3460
<     echo "$__REPO_ARCH_DEB $SALTSTACK_DEBIAN_URL $DEBIAN_CODENAME main" > "/etc/apt/sources.list.d/salt.list"
---
>     #echo "$__REPO_ARCH_DEB $SALTSTACK_DEBIAN_URL $DEBIAN_CODENAME main" > "/etc/apt/sources.list.d/saltstack.list"
>     echo "deb https://packages.broadcom.com/artifactory/saltproject-deb/ stable main" >/etc/apt/sources.list.d/saltstack.list
3459c3462
<     __apt_key_fetch "${SALTSTACK_DEBIAN_URL}/SALT-PROJECT-GPG-PUBKEY-2023.gpg" || return 1
---
>     __apt_key_fetch "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x64cbbc8173d76b3f" || return 1
```

Thanks @kquinsland and CC: @ssoto2 and @chrisnew

**Comment by tjyang** [comment]
> Experiencing the same issue as @chrisnew
> 
> ```
>  *  INFO: Running version: 2024.09.24
>  *  INFO: Executed by: sh
>  *  INFO: Command line: 'bootstrap-salt.sh -X -P onedir'
> 
>  *  INFO: System Information:
>  *  INFO:   CPU:          GenuineIntel
>  *  INFO:   CPU Arch:     x86_64
>  *  INFO:   OS Name:      Linux
>  *  INFO:   OS Version:   4.18.0-553.22.1.el8_10.x86_64
>  *  INFO:   Distribution: Rocky Linux 8.10
> 
>  *  INFO: Installing minion
>  *  INFO: Daemons will not be started
>  *  INFO: Found function install_rocky_linux_onedir_deps
>  *  INFO: Found function config_salt
>  *  INFO: Found function preseed_master
>  *  INFO: Found function install_rocky_linux_onedir
>  *  INFO: Found function install_rocky_linux_onedir_post
>  *  INFO: Found function install_rocky_linux_restart_daemons
>  *  INFO: Found function daemons_running_onedir
>  *  INFO: Found function install_rocky_linux_check_services
>  *  INFO: Running install_rocky_linux_onedir_deps()
>  * ERROR: https://repo.saltproject.io/salt/py3/redhat/8/x86_64/latest/SALT-PROJECT-GPG-PUBKEY-2023.pub failed to download to /tmp/salt-gpg-41jEoMzr.pub
>  * ERROR: Failed to run install_rocky_linux_onedir_deps()!!!
> ```

Wait on the bootstrap-salt.sh to be released. See my test on dev one above at https://github.com/saltstack/salt-bootstrap/issues/2027#issuecomment-2457310779

**Comment by jeffdyke** [comment]
> > Experiencing the same issue as @chrisnew
> > ```
> >  *  INFO: Running version: 2024.09.24
> >  *  INFO: Executed by: sh
> >  *  INFO: Command line: 'bootstrap-salt.sh -X -P onedir'
> > 
> >  *  INFO: System Information:
> >  *  INFO:   CPU:          GenuineIntel
> >  *  INFO:   CPU Arch:     x86_64
> >  *  INFO:   OS Name:      Linux
> >  *  INFO:   OS Version:   4.18.0-553.22.1.el8_10.x86_64
> >  *  INFO:   Distribution: Rocky Linux 8.10
> > 
> >  *  INFO: Installing minion
> >  *  INFO: Daemons will not be started
> >  *  INFO: Found function install_rocky_linux_onedir_deps
> >  *  INFO: Found function config_salt
> >  *  INFO: Found function preseed_master
> >  *  INFO: Found function install_rocky_linux_onedir
> >  *  INFO: Found function install_rocky_linux_onedir_post
> >  *  INFO: Found function install_rocky_linux_restart_daemons
> >  *  INFO: Found function daemons_running_onedir
> >  *  INFO: Found function install_rocky_linux_check_services
> >  *  INFO: Running install_rocky_linux_onedir_deps()
> >  * ERROR: https://repo.saltproject.io/salt/py3/redhat/8/x86_64/latest/SALT-PROJECT-GPG-PUBKEY-2023.pub failed to download to /tmp/salt-gpg-41jEoMzr.pub
> >  * ERROR: Failed to run install_rocky_linux_onedir_deps()!!!
> > ```
> 
> Wait on the bootstrap-salt.sh to be released. See my test on dev one above at [#2027 (comment)](https://github.com/saltstack/salt-bootstrap/issues/2027#issuecomment-2457310779)

This is not always possible, and a fix ended up being about 10 lines for `ubuntu`.  I was blocked by this.

**Comment by tjyang** [comment]
@dmurphy18 , Thanks for this [fix candidate in your repo](https://github.com/dmurphy18/salt-bootstrap/commit/6050a0b21731347b694d0f12eab8f82a067d4e50).
- I was able to install minion on RL9 with **onedir 3006** arguments, it can now populate /etc/yum.repos.d/salt.repo but ended up with "salt-repo-latest" enabled by default. Thus 3007.1 minion got installed.
```bas
[me@rocky9t01a ~]$ ./11.06.bootstrap-salt.sh -v
./11.06.bootstrap-salt.sh -- Version 2024.11.05
[me@rocky9t01a ~]$ ./11.06.bootstrap-salt.sh onedir 3006
<snipped>
[me@rocky9t01a ~]$ rpm -qa |grep salt
salt-3007.1-0.x86_64
salt-minion-3007.1-0.x86_64
[me@rocky9t01a ~]$

```
Let me know if you need /tmp/bootstrap-salt.log

**Comment by IanMann-CVET** [comment]
I've updated the URLs but its installing 3006.9 when I'm specifying 3006.1. After it installs and I do a salt --version I'm getting 3006.9 (Sulfur). 

sudo rpm --import https://packages.broadcom.com/artifactory/api/security/keypair/SaltProjectKey/public
curl -fsSL https://github.com/saltstack/salt-install-guide/releases/latest/download/salt.repo | sudo tee /etc/yum.repos.d/salt.repo
sudo yum clean expire-cache
sudo yum -y install salt-minion-3006.1

**Comment by dmurphy18** [comment]
FYI everyone on this issue, just released https://github.com/saltstack/salt-bootstrap/releases/latest/download/bootstrap-salt.sh v2024.11.07 which now works with packaging.broadcom.com, but look at the release note for tag v2024.11.06 which has the details.  Had some work to do on GitHub Actions release.yml to get it out.

- Support for Broadcom packaging infrastructure, packaging.broadcom.com
- Photon OS support only for latest Salt, that is, Salt 3007.1 (problem with Photon support for repo file exclude parameter)
- Linux platforms only support latest major branch versions (similar to Salt Install Guide),  for example: 3006.9, 3007.1
- Windows and MacOS support minor branch versions, for example: 3006.8
- Future fixes for Linux minor versions of Salt will be forth-coming

**Comment by chrisnew** [comment]
Good news, appreciate the update! @dmurphy18 

Are there plans to keep the bootstrap script in that new place or to fix the old one? Also saltstack/salt#67051 is relevant for us.

**Comment by dmurphy18** [comment]
@chrisnew The old place is gone forever, the new place is where to find the bootstrap script. As for https://github.com/saltstack/salt/issues/67051 that is a Broadcom corporate issue and beyond control of the Salt team, however we have raised it as an issue up the food chain.

Also note https://github.com/saltstack/salt-bootstrap/issues/2038, further work on the scripts

**Comment by jeffdyke** [comment]
> @chrisnew The old place is gone forever, the new place is where to find the bootstrap script. As for saltstack/salt#67051 that is a Broadcom corporate issue and beyond control of the Salt team, however we have raised it as an issue up the food chain.
> 
> Also note saltstack/salt-bootstrap#2038, further work on the scripts

Where exactly is the `new place`?  I'm thinking that `github/latest` is not it.  Thanks for the work on the issue.

**Comment by dmurphy18** [comment]
@jeffdyke https://saltproject.io/blog/new-salt-bootstrap-release-2024-11-07, can check Discord for Salt Community Announcements or saltproject.io Blog of Media drop-down in the future for such information

**Comment by jeffdyke** [comment]
I appreciate it, the reason I asked here is I'm sure not to be the only one
to read that "new place" and wonder.  Plus this was notified on said pages
and implemented in 7 days, thus pain was incurred, hopefully next time will
be a bit better.

Thanks again
