### ISSUE TITLE
Expired certificate on repo.saltproject.io

### ISSUE THREAD

**Issue by sbaczkow** [saltstack/salt-bootstrap#2030]
### Description of Issue/Question
Please renew expired certificate for repo.saltproject.io

![image](https://github.com/user-attachments/assets/bc24c47c-a6cb-4df1-9454-078678dc64f8)

**Comment by PCouaillierM** [comment]
See: https://saltproject.io/blog/salt-install-guide-overhaul/

```
Upon migration, Salt Project will be deprecating repo.saltproject.io, which will mean a breaking change in scripts and installation automation expecting to pull from or install packages from repo.saltproject.io in your infrastructure.
```

**Comment by ScriptAutomate** [comment]
> See: https://saltproject.io/blog/salt-install-guide-overhaul/
> 
> ```
> Upon migration, Salt Project will be deprecating repo.saltproject.io, which will mean a breaking change in scripts and installation automation expecting to pull from or install packages from repo.saltproject.io in your infrastructure.
> ```

@sbaczkow see above ^^

Closing.
