### ISSUE TITLE
bootstrap.saltproject.io/bootstrap-salt.sh points to v2024.09.24 instead of to the newest release (v2024.11.07).

### ISSUE THREAD

**Issue by P4rcev4l** [saltstack/salt-bootstrap#2042]
### Description of Issue/Question
https://bootstrap.saltproject.io/bootstrap-salt.sh points to v2024.09.24 instead of to the newest release (v2024.11.07). 

### Setup
N/A

### Steps to Reproduce Issue
`curl -o bootstrap-salt.sh -L https://bootstrap.saltproject.io/bootstrap-salt.sh`
try executing `bootstrap-salt.sh` errors out, because https://repo.saltproject.io does not exist anymore.

### Versions and Systems
N/A

### Fix
`curl -o bootstrap-salt.sh -L https://github.com/saltstack/salt-bootstrap/releases/latest/download/bootstrap-salt.sh`

**Comment by ScriptAutomate** [comment]
The script there should now be updated.

Going forward, make sure to use the GitHub Releases download endpoints instead.

The `bootstrap.saltproject.io` and `winbootstrap.saltproject.io` hosted endpoints for the scripts will be taken down at the end of **November 2024**. See here for more info:

- https://saltproject.io/blog/salt-bootstrap-breakage-part-2/
- https://saltproject.io/blog/new-salt-bootstrap-release-2024-11-07

**Comment by P4rcev4l** [comment]
> The script there should now be updated.
> 
> Going forward, make sure to use the GitHub Releases download endpoints instead.
> 
> The `bootstrap.saltproject.io` and `winbootstrap.saltproject.io` hosted endpoints for the scripts will be taken down at the end of **November 2024**. See here for more info:
> 
> - https://saltproject.io/blog/salt-bootstrap-breakage-part-2/
> - https://saltproject.io/blog/new-salt-bootstrap-release-2024-11-07

Good to know, thank you
