### ISSUE TITLE
Update certifi to version >= 2024.7.4

### ISSUE THREAD

**Issue by MakZer0** [saltstack/salt-bootstrap#2046]
Hi,

Salt-Bootstrap uses certifi v2023.7.22 as a dependency.
Due to multiple Issues with versions prior to 2024.7.4 we're getting a lot of hits on vulnerability scanners in our environment.
Mainly due to untrusted certificates.
https://github.com/certifi/python-certifi/security/advisories/GHSA-248v-346w-9cwc

Are there any plans to update this dependency?

**Comment by dmurphy18** [comment]
@MakZer0 Can you please provide more information about your system, for example: OS, ca-certificates on the system etc.

The bootstrap script leverages the ```ca-certificates``` that come with the system, and does not explicitly come with it's own ca-certificate.  I suggest you examine your system for the ca-certificates used, for example: RedHat family
```
__yum_install_noinput ca-certificates || return 1
```

The script is using that which is on the system.

**Comment by dmurphy18** [comment]
Closing this since answer given and related to user's version of OS and what is installed on it, independent of bootstrap script.
