### ISSUE TITLE
* ERROR: Failed to run install_ubuntu_git_deps()!!!

### ISSUE THREAD

**Issue by qqchose** [saltstack/salt-bootstrap#222]
Hi,

I tried to excute this line

curl --insecure -L http://bootstrap.saltstack.org | sudo sh -s -- git develop

and after I tried

curl -L https://raw.github.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh |     sudo sh -s -- git develop

But I always have this result:

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 \*  INFO: PIPED THROUGH sh -- Version 1.5.7
-  WARN: Running the unstable version of bootstrap-salt.sh
-  INFO: System Information:
-  INFO:   CPU:          GenuineIntel
-  INFO:   CPU Arch:     i686
-  INFO:   OS Name:      Linux
-  INFO:   OS Version:   3.2.0-24-generic-pae
-  INFO:   Distribution: Ubuntu 12.04
-  INFO: Installing minion
  100  112k  100  112k    0     0  83194      0  0:00:01  0:00:01 --:--:-- 85627
-  INFO: Found function install_ubuntu_git_deps
-  INFO: Found function install_ubuntu_git
-  INFO: Found function install_ubuntu_git_post
-  INFO: Found function install_ubuntu_restart_daemons
-  INFO: Found function daemons_running
-  INFO: Running install_ubuntu_git_deps()
  Ign http://ppa.launchpad.net precise InRelease
  Ign http://security.ubuntu.com precise-security InRelease
  Ign http://extras.ubuntu.com precise InRelease
  Ign http://it.archive.ubuntu.com precise InRelease
  Hit http://security.ubuntu.com precise-security Release.gpg
  Hit http://extras.ubuntu.com precise Release.gpg
  Get:1 http://ppa.launchpad.net precise Release.gpg [316 B]
  Ign http://it.archive.ubuntu.com precise-updates InRelease
  Hit http://security.ubuntu.com precise-security Release
  Hit http://extras.ubuntu.com precise Release
  Ign http://it.archive.ubuntu.com precise-backports InRelease
  Hit http://ppa.launchpad.net precise Release
  Ign http://ppa.launchpad.net precise Release
  Hit http://security.ubuntu.com precise-security/main Sources
  Hit http://it.archive.ubuntu.com precise Release.gpg
  Hit http://extras.ubuntu.com precise/main Sources
  Ign http://ppa.launchpad.net precise/main Sources/DiffIndex
  Hit http://security.ubuntu.com precise-security/restricted Sources
  Hit http://extras.ubuntu.com precise/main i386 Packages
  Ign http://ppa.launchpad.net precise/main i386 Packages/DiffIndex
  Hit http://security.ubuntu.com precise-security/universe Sources
  Ign http://extras.ubuntu.com precise/main TranslationIndex
  Hit http://it.archive.ubuntu.com precise-updates Release.gpg
  Hit http://security.ubuntu.com precise-security/multiverse Sources
  Ign http://ppa.launchpad.net precise/main TranslationIndex
  Hit http://it.archive.ubuntu.com precise-backports Release.gpg
  Hit http://ppa.launchpad.net precise/main Sources
  Hit http://security.ubuntu.com precise-security/main i386 Packages
  Hit http://ppa.launchpad.net precise/main i386 Packages
  Hit http://security.ubuntu.com precise-security/restricted i386 Packages
  Hit http://it.archive.ubuntu.com precise Release
  Hit http://security.ubuntu.com precise-security/universe i386 Packages
  Hit http://it.archive.ubuntu.com precise-updates Release
  Hit http://security.ubuntu.com precise-security/multiverse i386 Packages
  Hit http://security.ubuntu.com precise-security/main TranslationIndex
  Hit http://it.archive.ubuntu.com precise-backports Release
  Hit http://security.ubuntu.com precise-security/multiverse TranslationIndex
  Hit http://it.archive.ubuntu.com precise/main Sources
  Hit http://security.ubuntu.com precise-security/restricted TranslationIndex
  Hit http://security.ubuntu.com precise-security/universe TranslationIndex
  Hit http://it.archive.ubuntu.com precise/restricted Sources
  Ign http://extras.ubuntu.com precise/main Translation-en_US
  Hit http://security.ubuntu.com precise-security/main Translation-en
  Ign http://extras.ubuntu.com precise/main Translation-en
  Hit http://it.archive.ubuntu.com precise/universe Sources
  Hit http://security.ubuntu.com precise-security/multiverse Translation-en
  Hit http://security.ubuntu.com precise-security/restricted Translation-en
  Hit http://it.archive.ubuntu.com precise/multiverse Sources
  Ign http://ppa.launchpad.net precise/main Translation-en_US
  Hit http://security.ubuntu.com precise-security/universe Translation-en
  Ign http://ppa.launchpad.net precise/main Translation-en
  Hit http://it.archive.ubuntu.com precise/main i386 Packages
  Hit http://it.archive.ubuntu.com precise/restricted i386 Packages
  Hit http://it.archive.ubuntu.com precise/universe i386 Packages
  Hit http://it.archive.ubuntu.com precise/multiverse i386 Packages
  Hit http://it.archive.ubuntu.com precise/main TranslationIndex
  Hit http://it.archive.ubuntu.com precise/multiverse TranslationIndex
  Hit http://it.archive.ubuntu.com precise/restricted TranslationIndex
  Hit http://it.archive.ubuntu.com precise/universe TranslationIndex
  Hit http://it.archive.ubuntu.com precise-updates/main Sources
  Hit http://it.archive.ubuntu.com precise-updates/restricted Sources
  Get:2 http://it.archive.ubuntu.com precise-updates/universe Sources [95.3 kB]
  Hit http://it.archive.ubuntu.com precise-updates/multiverse Sources
  Hit http://it.archive.ubuntu.com precise-updates/main i386 Packages
  Hit http://it.archive.ubuntu.com precise-updates/restricted i386 Packages
  Hit http://it.archive.ubuntu.com precise-updates/universe i386 Packages
  Hit http://it.archive.ubuntu.com precise-updates/multiverse i386 Packages
  Hit http://it.archive.ubuntu.com precise-updates/main TranslationIndex
  Hit http://it.archive.ubuntu.com precise-updates/multiverse TranslationIndex
  Hit http://it.archive.ubuntu.com precise-updates/restricted TranslationIndex
  Hit http://it.archive.ubuntu.com precise-updates/universe TranslationIndex
  Hit http://it.archive.ubuntu.com precise-backports/main Sources
  Hit http://it.archive.ubuntu.com precise-backports/restricted Sources
  Hit http://it.archive.ubuntu.com precise-backports/universe Sources
  Hit http://it.archive.ubuntu.com precise-backports/multiverse Sources
  Hit http://it.archive.ubuntu.com precise-backports/main i386 Packages
  Hit http://it.archive.ubuntu.com precise-backports/restricted i386 Packages
  Hit http://it.archive.ubuntu.com precise-backports/universe i386 Packages
  Hit http://it.archive.ubuntu.com precise-backports/multiverse i386 Packages
  Hit http://it.archive.ubuntu.com precise-backports/main TranslationIndex
  Hit http://it.archive.ubuntu.com precise-backports/multiverse TranslationIndex
  Hit http://it.archive.ubuntu.com precise-backports/restricted TranslationIndex
  Hit http://it.archive.ubuntu.com precise-backports/universe TranslationIndex
  Hit http://it.archive.ubuntu.com precise/main Translation-en
  Hit http://it.archive.ubuntu.com precise/multiverse Translation-en
  Hit http://it.archive.ubuntu.com precise/restricted Translation-en
  Hit http://it.archive.ubuntu.com precise/universe Translation-en
  Hit http://it.archive.ubuntu.com precise-updates/main Translation-en
  Hit http://it.archive.ubuntu.com precise-updates/multiverse Translation-en
  Hit http://it.archive.ubuntu.com precise-updates/restricted Translation-en
  Hit http://it.archive.ubuntu.com precise-updates/universe Translation-en
  Hit http://it.archive.ubuntu.com precise-backports/main Translation-en
  Hit http://it.archive.ubuntu.com precise-backports/multiverse Translation-en
  Hit http://it.archive.ubuntu.com precise-backports/restricted Translation-en
  Hit http://it.archive.ubuntu.com precise-backports/universe Translation-en
  Fetched 317 B in 15s (20 B/s)
  W: GPG error: http://ppa.launchpad.net precise Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4759FA960E27C0A6
  W: Failed to fetch bzip2:/var/lib/apt/lists/partial/it.archive.ubuntu.com_ubuntu_dists_precise-updates_universe_source_Sources  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
python-software-properties is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 611 not upgraded.
Error reading /saltstack/salt/ubuntu: couldn't connect to host
Ign http://security.ubuntu.com precise-security InRelease
Ign http://ppa.launchpad.net precise InRelease
Ign http://extras.ubuntu.com precise InRelease
Ign http://it.archive.ubuntu.com precise InRelease
Get:1 http://security.ubuntu.com precise-security Release.gpg [198 B]
Hit http://extras.ubuntu.com precise Release.gpg
Get:2 http://ppa.launchpad.net precise Release.gpg [316 B]
Ign http://it.archive.ubuntu.com precise-updates InRelease
Get:3 http://security.ubuntu.com precise-security Release [49.6 kB]
Hit http://extras.ubuntu.com precise Release
Ign http://it.archive.ubuntu.com precise-backports InRelease
Hit http://ppa.launchpad.net precise Release
Ign http://ppa.launchpad.net precise Release
Hit http://extras.ubuntu.com precise/main Sources
Ign http://ppa.launchpad.net precise/main Sources/DiffIndex
Get:4 http://security.ubuntu.com precise-security/main Sources [84.9 kB]
Hit http://extras.ubuntu.com precise/main i386 Packages
Ign http://ppa.launchpad.net precise/main i386 Packages/DiffIndex
Hit http://it.archive.ubuntu.com precise Release.gpg
Ign http://ppa.launchpad.net precise/main TranslationIndex
Ign http://extras.ubuntu.com precise/main TranslationIndex
Hit http://ppa.launchpad.net precise/main Sources
Hit http://it.archive.ubuntu.com precise-updates Release.gpg
Get:5 http://security.ubuntu.com precise-security/restricted Sources [2,494 B]
Hit http://ppa.launchpad.net precise/main i386 Packages
Get:6 http://security.ubuntu.com precise-security/universe Sources [28.0 kB]
Hit http://it.archive.ubuntu.com precise-backports Release.gpg
Hit http://it.archive.ubuntu.com precise Release
Get:7 http://security.ubuntu.com precise-security/multiverse Sources [1,803 B]
Get:8 http://security.ubuntu.com precise-security/main i386 Packages [331 kB]
Hit http://it.archive.ubuntu.com precise-updates Release
Hit http://it.archive.ubuntu.com precise-backports Release
Hit http://it.archive.ubuntu.com precise/main Sources
Hit http://it.archive.ubuntu.com precise/restricted Sources
Ign http://extras.ubuntu.com precise/main Translation-en_US
Hit http://it.archive.ubuntu.com precise/universe Sources
Ign http://ppa.launchpad.net precise/main Translation-en_US
Ign http://extras.ubuntu.com precise/main Translation-en
Ign http://ppa.launchpad.net precise/main Translation-en
Hit http://it.archive.ubuntu.com precise/multiverse Sources
Hit http://it.archive.ubuntu.com precise/main i386 Packages
Get:9 http://security.ubuntu.com precise-security/restricted i386 Packages [4,620 B]
Get:10 http://security.ubuntu.com precise-security/universe i386 Packages [84.5 kB]
Hit http://it.archive.ubuntu.com precise/restricted i386 Packages
Hit http://it.archive.ubuntu.com precise/universe i386 Packages
Get:11 http://security.ubuntu.com precise-security/multiverse i386 Packages [2,633 B]
Hit http://it.archive.ubuntu.com precise/multiverse i386 Packages
Hit http://security.ubuntu.com precise-security/main TranslationIndex
Hit http://security.ubuntu.com precise-security/multiverse TranslationIndex
Hit http://it.archive.ubuntu.com precise/main TranslationIndex
Hit http://security.ubuntu.com precise-security/restricted TranslationIndex
Hit http://security.ubuntu.com precise-security/universe TranslationIndex
Hit http://it.archive.ubuntu.com precise/multiverse TranslationIndex
Hit http://security.ubuntu.com precise-security/main Translation-en
Hit http://it.archive.ubuntu.com precise/restricted TranslationIndex
Hit http://security.ubuntu.com precise-security/multiverse Translation-en
Hit http://it.archive.ubuntu.com precise/universe TranslationIndex
Hit http://security.ubuntu.com precise-security/restricted Translation-en
Hit http://security.ubuntu.com precise-security/universe Translation-en
Hit http://it.archive.ubuntu.com precise-updates/main Sources
Hit http://it.archive.ubuntu.com precise-updates/restricted Sources
Get:12 http://it.archive.ubuntu.com precise-updates/universe Sources [95.3 kB]
Hit http://it.archive.ubuntu.com precise-updates/multiverse Sources
Hit http://it.archive.ubuntu.com precise-updates/main i386 Packages
Hit http://it.archive.ubuntu.com precise-updates/restricted i386 Packages
Hit http://it.archive.ubuntu.com precise-updates/universe i386 Packages
Hit http://it.archive.ubuntu.com precise-updates/multiverse i386 Packages
Hit http://it.archive.ubuntu.com precise-updates/main TranslationIndex
Hit http://it.archive.ubuntu.com precise-updates/multiverse TranslationIndex
Hit http://it.archive.ubuntu.com precise-updates/restricted TranslationIndex
Hit http://it.archive.ubuntu.com precise-updates/universe TranslationIndex
Hit http://it.archive.ubuntu.com precise-backports/main Sources
Hit http://it.archive.ubuntu.com precise-backports/restricted Sources
Hit http://it.archive.ubuntu.com precise-backports/universe Sources
Hit http://it.archive.ubuntu.com precise-backports/multiverse Sources
Hit http://it.archive.ubuntu.com precise-backports/main i386 Packages
Hit http://it.archive.ubuntu.com precise-backports/restricted i386 Packages
Hit http://it.archive.ubuntu.com precise-backports/universe i386 Packages
Hit http://it.archive.ubuntu.com precise-backports/multiverse i386 Packages
Hit http://it.archive.ubuntu.com precise-backports/main TranslationIndex
Hit http://it.archive.ubuntu.com precise-backports/multiverse TranslationIndex
Hit http://it.archive.ubuntu.com precise-backports/restricted TranslationIndex
Hit http://it.archive.ubuntu.com precise-backports/universe TranslationIndex
Hit http://it.archive.ubuntu.com precise/main Translation-en
Hit http://it.archive.ubuntu.com precise/multiverse Translation-en
Hit http://it.archive.ubuntu.com precise/restricted Translation-en
Hit http://it.archive.ubuntu.com precise/universe Translation-en
Hit http://it.archive.ubuntu.com precise-updates/main Translation-en
Hit http://it.archive.ubuntu.com precise-updates/multiverse Translation-en
Hit http://it.archive.ubuntu.com precise-updates/restricted Translation-en
Hit http://it.archive.ubuntu.com precise-updates/universe Translation-en
Hit http://it.archive.ubuntu.com precise-backports/main Translation-en
Hit http://it.archive.ubuntu.com precise-backports/multiverse Translation-en
Hit http://it.archive.ubuntu.com precise-backports/restricted Translation-en
Hit http://it.archive.ubuntu.com precise-backports/universe Translation-en
Fetched 590 kB in 21s (27.3 kB/s)
W: GPG error: http://ppa.launchpad.net precise Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4759FA960E27C0A6
W: Failed to fetch bzip2:/var/lib/apt/lists/partial/it.archive.ubuntu.com_ubuntu_dists_precise-updates_universe_source_Sources  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  git git-man liberror-perl libyaml-0-2 patch python-support
Suggested packages:
  git-daemon-run git-daemon-sysvinit git-doc git-el git-arch git-cvs git-svn
  git-email git-gui gitk gitweb diffutils-doc python-crypto-dbg
  python-crypto-doc python-jinja2-doc
The following NEW packages will be installed:
  git git-core git-man liberror-perl libyaml-0-2 msgpack-python patch
  python-jinja2 python-m2crypto python-support python-yaml python-zmq
The following packages will be upgraded:
  python-crypto
1 upgraded, 12 newly installed, 0 to remove and 610 not upgraded.
Need to get 7,877 kB of archives.
After this operation, 19.4 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  python-zmq
E: There are problems and -y was used without --force-yes
- ERROR: Failed to run install_ubuntu_git_deps()!!!

I'm using ubuntu and I'm begginer user.

**Comment by gravyboat** [comment]
Maybe your keyring isn't getting updated? Try running <code>apt-key update</code> and then <code>apt-get update</code> as the root user. That seems more like an issue with where you're pulling the package from as opposed to a problem with the bootstrap script, but I'll spin up a VM and see if I can duplicate it later tonight if updating the keyring doesn't work for you.

**Comment by qqchose** [comment]
Thanks, I did not try apt-key update. But I succeed to install following http://docs.saltstack.com/topics/installation/ubuntu.html

Then it's fine. Thanks

**Comment by gravyboat** [comment]
The version from that repository won't get you the latest development release, it will be the latest stable release. If you're trying to use something from the development branch you need either pull it from github, or use the bootstrap. Let me know if you try the bootstrap again with the updated keyring command and it fails.
