### ISSUE TITLE
Ubuntu 11.04 bootstrap fails when adding repository.

### ISSUE THREAD

**Issue by sdelmas** [saltstack/salt-bootstrap#225]
The -y option for add-apt-repository isn't supported (at least not on my 11.04). I have a patch attempt attached. What's the best way to get that to you? I also added fixed the help text for the -U option, and added a -K option to set _KEEP_TEMP_FILES from the commandline.

**Comment by s0undt3ch** [comment]
The keep temp files setting was not added as a cli option on purpose, there is no support for long options so we can only has many options as the alphabet.

Is there any particular reason why you can't use the environment variable setting?

Regarding the -y option to apt, I though only apt from 10.x would not accept that option... Need to recheck.

As for the contribution, you can fork our repository, update it and the submit a pull request.

## 

Pedro Algarvio @ phone

----- Reply message -----
De: "Sven Delmas" notifications@github.com
Para: "saltstack/salt-bootstrap" salt-bootstrap@noreply.github.com
Assunto: [salt-bootstrap] Debian 11.04 bootstrap fails when adding repository. (#225)
Data: qui, Set 12, 2013 21:48
The -y option for add-apt-repository isn't supported (at least not on my 11.04). I have a patch attempt attached. What's the best way to get that to you? I also added fixed the help text for the -U option, and added a -K option to set _KEEP_TEMP_FILES from the commandline. 

&mdash;

**Comment by sdelmas** [comment]
Sorry for the delayed response... didn't see your response. 

Well, same reason why one would have a -U option, or any other commandline option I presume :-). I am running the bootstrap through ssh on a remote machine, so to set environment variables becomes tricky. Your call of course, but you currently have 7 capital letters used (plus around the same number of lower case letters), so it would seem that there is room before you run out :-).

As for -y, let me know if you need help. Happens for me every time... could it be that the difference is a fully patched 11.04 (mine is the original unpatched version).

I will create a pull request then.

Thanks,
Sven

**Comment by sdelmas** [comment]
Hm, I tried the bootstrap on my Ubuntu 11.04 test machine, and that fails now due to the recently added http://archive.ubuntu.com dependency I believe. natty is not available from there as far as I can tell. I am getting my packages from:

deb http://old-releases.ubuntu.com/ubuntu/ natty main restricted universe multiverse
deb http://old-releases.ubuntu.com/ubuntu/ natty-updates main restricted universe multiverse
deb http://old-releases.ubuntu.com/ubuntu/ natty-security main restricted universe multiverse

However, when I get past that it would seem to me that the natty repo at:
  http://ppa.launchpad.net/saltstack/salt/ubuntu/dists/natty/main/binary-amd64/Packages 
is empty. I am pretty sure that used to be there (I installed from there). Did that change recently?

Two additional questions:

1) I noticed that the install_ubuntu_daily_deps function is actually not adding the universe (is that intentional?)
2) You are setting __IS_UNIVERSE_ENABLED... but never seem to use it. I changed the login in my pull request to what I suspect is the intention (adding the universe if it's not already present). I didn't change the repo location you add there though... maybe I am missing something, so I don't want to mess things up.

I know... all that pain for a distribution that shouldn't really be used anymore :-).

Thanks,
Sven

**Comment by s0undt3ch** [comment]
I'll try not to forget having a look at this repo location and daily issues.

**Comment by quinnypig** [comment]
Launchpad won't keep packages or PPAs for EOL'd releases, unfortunately.

**Comment by s0undt3ch** [comment]
The only solution is to install the desired salt version from git.

**Comment by s0undt3ch** [comment]
Ok, in order not to make the script unmaintainable in the future, all EOL distributions will not be supported.

**Comment by sdelmas** [comment]
Ouch... Interesting. I guess 11.04 is rather old.

**Comment by s0undt3ch** [comment]
You always have the manual installation route,or you can upgrade to an LTS?

**Comment by sdelmas** [comment]
Yeah... but bootstrap is sooooo nice :-).

**Comment by s0undt3ch** [comment]
Thanks! :smile:
