### ISSUE TITLE
RHEL does not install the latest salt

### ISSUE THREAD

**Issue by ranl** [saltstack/salt-bootstrap#232]
Hi

I've installed salt with the bootstrap script today and I've noticed that it installed salt 0.16.3 instead of 0.16.4.
I saw that 0.16.4 is in epel-testing so I've installed it manually after

RHEL 6.4 64bit

Thanks

**Comment by s0undt3ch** [comment]
This is not a bootstrap issue, it's just how peel works...

Still, if you want to install from testing, there's a way, please read the script's help message, and be sure to use the develop branch of the script... Sorry I'm on my phone which prevents me from giving you the specific information. I think that passing "testing" to the script might do it...

**Comment by s0undt3ch** [comment]
Please read epel on the above peel...

**Comment by ranl** [comment]
I figured its not a bug just wanted to make sure
Thanks for clarifying this :-)
