### ISSUE TITLE
one liner installs are broken in current git

### ISSUE THREAD

**Issue by s0undt3ch** [saltstack/salt-bootstrap#25]
one liner installs are broken in current git

It works until https://github.com/saltstack/salt-bootstrap/commit/61cf5d4e813f09f36b4276f7ae670e371743111f

**Comment by s0undt3ch** [comment]
For now, I reverted last bashism.

**Comment by s0undt3ch** [comment]
This is now fixed

**Comment by thatch45** [comment]
I am deeply impressed!

**Comment by s0undt3ch** [comment]
@thatch45 We **no longer** have any bash'isms on our script, and it even works on FreeBSD ;)
