### ISSUE TITLE
fails on ubuntu 12.04 LTS

### ISSUE THREAD

**Issue by pille** [saltstack/salt-bootstrap#250]
<pre>
wget -O - http://bootstrap.saltstack.org | sudo sh

*  INFO: PIPED THROUGH sh -- Version 1.5.8

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.8.0-31-generic
 *  INFO:   Distribution: Ubuntu 12.04

 *  INFO: Installing minion
100%[=============================================================================================================================================================================================================================================>] 119,312     --.-K/s   in 0.1s    

2013-10-16 11:20:48 (795 KB/s) - written to stdout [119312/119312]

 *  INFO: Found function install_ubuntu_deps
 *  INFO: Found function install_ubuntu_stable
 *  INFO: Found function install_ubuntu_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Running install_ubuntu_deps()

...

Reading package lists...
sh: 1254: [: missing ]
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  python-pycurl unattended-upgrades
Suggested packages:
  libcurl4-gnutls-dev python-pycurl-dbg bsd-mailx
The following NEW packages will be installed:
  python-pycurl python-software-properties unattended-upgrades
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 96.1 kB of archives.
After this operation, 645 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  python-pycurl
E: There are problems and -y was used without --force-yes
 * ERROR: Failed to run install_ubuntu_deps()!!!

</pre>

**Comment by pille** [comment]
just FYI with debugging enabled.
turns out, that when i wanted to fix this, it already was in 7e1522863ec907f3ed53a3636e1be2ae87daf2e0 six days ago. please merge that into stable branch...

it also turned out that we see two different bugs here, where the second one is found in our hosters infrastructure:
they provide a non-signed mirror by default.

<pre>
Reading package lists...
+ [ 12 -gt 12 ]
+ [ 12 -eq 12
bootstrap-salt.sh: 1254: [: missing ]
+ __apt_get_install_noinput python-software-properties
+ apt-get install -y -o DPkg::Options::=--force-confold python-software-properties
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  python-pycurl unattended-upgrades
Suggested packages:
  libcurl4-gnutls-dev python-pycurl-dbg bsd-mailx
The following NEW packages will be installed:
  python-pycurl python-software-properties unattended-upgrades
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 96.1 kB of archives.
After this operation, 645 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  python-pycurl
E: There are problems and -y was used without --force-yes
+ return 100
+ return 1
+ [ 1 -ne 0 ]
+ echoerror Failed to run install_ubuntu_deps()!!!
+ printf \033[1;31m * ERROR\033[0m: Failed to run install_ubuntu_deps()!!!\n
 * ERROR: Failed to run install_ubuntu_deps()!!!
+ exit 1
+ __exit_cleanup
+ EXIT_CODE=1
+ echodebug Removing the logging pipe /tmp/bootstrap-salt.logpipe
+ [ 0 -eq 1 ]
+ rm -f /tmp/bootstrap-salt.logpipe
+ ps ax
+ + grep /tmp/bootstrap-salt.log
+ awk {print $1}
grep tee
+ TEE_PID=5416
+ [ x5416 = x ]
+ echodebug Killing logging pipe tee's with pid(s): 5416
+ [ 0 -eq 1 ]
+ trap __trap_errors INT QUIT ABRT KILL QUIT TERM
</pre>

**Comment by s0undt3ch** [comment]
The stable branch get's merges from develop from time to time. If it's stable, and if enough fixes, or a major fix was made in develop.

It's just a matter of [running from the develop branch](https://github.com/saltstack/salt-bootstrap#i-found-a-bug) or wait a little longer for the stable merge.

Can we close the issue? Or you want it open for other reason?

**Comment by pille** [comment]
ignore the second one, since it's tied to my infrastructure.

OT: i'm not sure if this is the best way to deal with bugs, since most people will probably report them against stable release. if you sit on a fix for over a week, why don't release it?
issue should be closed, when resolved in branch filed against.

**Comment by s0undt3ch** [comment]
This should be fixed in current stable.
