### ISSUE TITLE
Installation fails in docker Ubuntu 12.04 Guest with Ubuntu 13.04 Host

### ISSUE THREAD

**Issue by Caustic** [saltstack/salt-bootstrap#251]
When running the script inside a docker guest installation fails with a package not found error.  I isolated the problem to [here](https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L1231) and worked around it by removing the logic in that function in exchange for just `add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe"`.

The script was using old-releases and was hitting 404s when archive works fine.

I'll get some debugging output up later when I have time.

**Comment by Caustic** [comment]
This may have been a goof by me.  Doing the installation manually I found that the universe repository isn't a part of the base docker image.

Adding the universe repository then installing saltstack through `add-apt-repository ppa:saltstack/salt` worked fine.

Closing for now.

**Comment by s0undt3ch** [comment]
Thank you for the update.
