### ISSUE TITLE
Files removed from the repo are not removed with bootstrapping a new version from git over an old version

### ISSUE THREAD

**Issue by peterlandry** [saltstack/salt-bootstrap#252]
I was running `v0.17.0` from the git tag. There was a regression that broke the creation of virtualenvs, which was fixed for 0.17.1 (https://github.com/saltstack/salt/commit/bd002f97da2d0819f732d8468f984b2b23740ee9). I updated to `v0.17.1` by running another bootstrap. This issue was caused by `salt/modules/virtualenv.py`, which was removed in `v0.17.1`. After bootstrapping `virtualenv.py` was not removed, so the module was still broken. Manually deleting that file to match the repo fixed the problem.

I think most users would expect the bootstrap to leave the repo in a state that matches the git tag they passed.

**Comment by s0undt3ch** [comment]
Honestly, the script just installs salt, if it was already installed or not, the script should not handle that, there are too many possibilities for the script to properly handle un-installations which is somewhat what you're after.

I'll leave the ticket open for a while for further discussion but I'm tagging it as _wontfix_.

**Comment by techhat** [comment]
I'm going to agree with @s0undt3ch on this one. It's for bootstrapping, not maintaining a salt install.

**Comment by s0undt3ch** [comment]
No further discussion happened. Closing.
