### ISSUE TITLE
[FreeBSD] Repository "salt" not always available

### ISSUE THREAD

**Issue by wunki** [saltstack/salt-bootstrap#255]
In `install_freebsd_9_stable_deps` you are trying to install `swig` from the salt repository. See [line 2360](https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L2360).

But that repository is only setup when your box doesn't have pkg already installed. See [line 2343](https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L2343).

I'm running on a vagrant box which already has pkgng setup and I do have `swig` in my repository, but not in a special "salt" repository, thus receiving an error `pkg: Unknown repository: salt`.

Maybe a check to only add `-r salt` if the repository is added by the script. Otherwise fetch it from the repository which is already setup?

**Comment by mortn** [comment]
Thank you! That did the trick on FreeBSD 9.1 i386

**Comment by s0undt3ch** [comment]
Closing as the fix is now part of the script.
