### ISSUE TITLE
checking debian install steps

### ISSUE THREAD

**Issue by joehealy** [saltstack/salt-bootstrap#260]
Hi,

I've just had a quick look at the debian install process and it looks a little outdated. I'm not entirely sure what it is doing (it may be doing more than I think for good reasons).

but I don't think we need to add the unstable repo (around https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L1449 and the same at around https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L1520) anymore. Maybe it is in there for reasons I don't understand though...

cheers and thanks,

Joe

**Comment by s0undt3ch** [comment]
Can assure those steps are no longer necessary?

**Comment by jsplink** [comment]
`# We NEED to install the unstable dpkg or mime-support WILL fail to install`
is this the case anymore?

**Comment by joehealy** [comment]
I don't think the following is needed (ie mime-support):

```
    __apt_get_install_noinput -t unstable dpkg liblzma5 python mime-support || return 1
```

Not sure what it is needed for at all.

**Comment by jfindlay** [comment]
Now that debian.saltstack.com is superseded by repo.saltstack.com, I'm going to close this issue.  Installing from the latter repo uses different code.
