### ISSUE TITLE
-X doesn't work on ubuntu

### ISSUE THREAD

**Issue by pwaller** [saltstack/salt-bootstrap#266]
I passed `-X` to the bootstrap because I was installing into a docker container (where upstart is unable to run), so I needed the master to not be started. However, apt still attempted to start it and failed, preventing the installation from succeeding.

```
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
start: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
invoke-rc.d: initscript salt-master, action "start" failed.
dpkg: error processing salt-master (--configure):
 subprocess installed post-installation script returned error exit status 1
```

cc @holmboe

**Comment by s0undt3ch** [comment]
This was installing Salt using packages? not git, right?

**Comment by pwaller** [comment]
Well, this is what I did:

```
curl -o bootstrap-salt.sh https://github.com/saltstack/salt-bootstrap/blob/b5d203115069f758bc947ccdd3b9cc0414e64997/bootstrap-salt.sh
bash boostrap-salt.sh -X -M -N
```

I was hoping that this wouldn't start the daemon, but it seems it is trying to (and failing).

**Comment by holmboe** [comment]
I will have a look at this tomorrow.
Den 16 nov 2013 21:59 skrev "Peter Waller" notifications@github.com:

**Comment by s0undt3ch** [comment]
Aren't deb's supposed to start daemons at install time? Can we override that with apt?

## 

Pedro Algarvio @ phone

----- Reply message -----
De: "Henrik Holmboe" notifications@github.com
Para: "saltstack/salt-bootstrap" salt-bootstrap@noreply.github.com
Cc: "Pedro Algarvio" pedro@algarvio.me
Assunto: [salt-bootstrap] -X doesn&apos;t work on ubuntu (#266)
Data: dom, Nov 17, 2013 07:43
I will have a look at this tomorrow.

Den 16 nov 2013 21:59 skrev "Peter Waller" notifications@github.com:

> Well, this is what I did:
> 
> curl -o bootstrap-salt.sh https://github.com/saltstack/salt-bootstrap/blob/b5d203115069f758bc947ccdd3b9cc0414e64997/bootstrap-salt.sh
> 
> bash boostrap-salt.sh -X -M -N
> 
> I was hoping that this wouldn't start the daemon, but it seems it is
> 
> trying to (and failing).
> 
> —
> 
> Reply to this email directly or view it on GitHubhttps://github.com/saltstack/salt-bootstrap/issues/266#issuecomment-28635666
> 
> .

&mdash;

**Comment by holmboe** [comment]
@pwaller could you test the patch in holmboe/salt-bootstrap@a98664b0ca88a9a5dbc01863fab778652ca9b3c9?

Just so you know, I have not been able to test it myself yet (no access to Debian or Ubuntu at the moment) so feel free to review the changes before running it.

**Comment by holmboe** [comment]
@s0undt3ch apparently policy-rc.d is the way to go in Debian and derivatives.

**Comment by holmboe** [comment]
Note to self: If this does not work we can resort to installing `policyrcd-script-zg2` and creating a specific policy file. See http://lists.debian.org/debian-devel/2012/06/msg00046.html for more information.

**Comment by s0undt3ch** [comment]
Awesome findings!!!

**Comment by pwaller** [comment]
@holmboe it still seems to have tried to start it:

```
Setting up salt-minion (0.17.2-2quantal1) ...
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
start: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
invoke-rc.d: initscript salt-minion, action "start" failed.
dpkg: error processing salt-minion (--configure):
```

Here is a Dockerfile to reproduce with docker:

```
from base

run apt-get install -yy wget ca-certificates

run wget https://raw.github.com/holmboe/salt-bootstrap/a98664b0ca88a9a5dbc01863fab778652ca9b3c9/bootstrap-salt.sh
run bash bootstrap-salt.sh
```

**Comment by s0undt3ch** [comment]
We don't have any news with regards to this, right?

If that's the case I can just make the script tell the user that this is not possible for debian based distributions?

**Comment by pwaller** [comment]
So far as I know it is still broken so I haven't tried again.

**Comment by holmboe** [comment]
I haven't had the chance to look more into this. If there is any informative message that the script can output until this is completely closed, then go ahead and add it. 

Sorry for my limited time.

**Comment by s0undt3ch** [comment]
@holmboe No need to be sorry! I'll add the note.

**Comment by pwaller** [comment]
I'm garbage collecting old issues for the new year. I think I cared about this for running salt inside docker, and the docker images these days have a policy file which prevents any services from starting.
