### ISSUE TITLE
Change bootstrap.saltstack.org to use salt-bootstrap.sh

### ISSUE THREAD

**Issue by holmboe** [saltstack/salt-bootstrap#267]
I assume here that `salt-bootstrap.sh` is the prefered name because of the reasoning in #73.

In order to remove legacy filenames of the bootstrap script the `Location` header at http://bootstrap.saltstack.org needs to be updated.

``` bash
$ curl --insecure -D - http://bootstrap.saltstack.org
HTTP/1.1 302 Found
Date: Wed, 20 Nov 2013 22:16:20 GMT
Server: Apache
Location: https://raw.github.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh
Content-Length: 256
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://raw.github.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh">here</a>.</p>
</body></html>
```

**Comment by s0undt3ch** [comment]
Nope :)

`salt-bootstrap` is the project name, `bootstrap-salt` is the script name :smile:

**Comment by holmboe** [comment]
Ok so if it is intentional then please close this issue. :)

I just found it odd to have three similarly named files and two of them being a symlink.

**Comment by s0undt3ch** [comment]
Yes, it is in fact odd. The symlinks exist in order to support the assumptions you just had...

The one that is not a symlink is the real deal :smile:
