### ISSUE TITLE
Enable SSL for bootstrap.saltstack.org

### ISSUE THREAD

**Issue by jasonkeene** [saltstack/salt-bootstrap#269]
I'm not quite sure where to post this.  The documentation on [docs.saltstack.com](http://docs.saltstack.com/topics/installation/index.html) currently has the user piping the bootstrap script into a root privileged shell over an insecure connection.  Obviously those that are concerned about such things have alternative ways of getting the script.  However, it would be nice if SSL was enabled for this domain and the documentation fixed to point to the SSL version just so new users aren't put at risk of getting their systems owned.  You could leave the insecure HTTP redirect in place in case people rely on it.

I recalled reading this last month: http://blog.existentialize.com/dont-pipe-to-your-shell.html  I forgot that they called Salt out directly but was just reading your install guide and saw this myself I thought I should bring it to someone's attention.

**Comment by thatch45** [comment]
I agree, we are looking into getting the download behind a https connection and providing a checksum for verification

**Comment by ryan-lane** [comment]
Also, the shell script itself uses  wget --no-check-certificate and curl --insecure. It pulls a number of resources that should additionally be signed and the signature should be checked when downloaded.

**Comment by s0undt3ch** [comment]
@ryan-lane I've fixed the issue internally by defaulting to not ignoring security and additionally added a flag which allows insecure connections just how it was previously(for those who might need it)

**Comment by ryan-lane** [comment]
I don't actually use the script, but this is a major problem for me pointing people to check out salt. It's like nerd kryptonite. Salt does remote execution and people are wary about that from a security perspective. When they see that as the install instructions their initial reaction is that salt itself is likely incredibly insecure. It's a very bad first impression.

**Comment by pwaller** [comment]
The SSL certificate for https://bootstrap.saltstack.com is bad and the instructions for using the bootstrap script are failing.

```
$ curl -L https://bootstrap.saltstack.org
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
```

![image](https://f.cloud.github.com/assets/438648/2125190/dc3d0b1c-924c-11e3-80f3-1f8d12280513.png)

**Comment by s0undt3ch** [comment]
![warning](https://f.cloud.github.com/assets/300048/2125323/69e93efc-924f-11e3-9d85-84c166ca735e.png)

As seen on the [`README.rst`](https://github.com/saltstack/salt-bootstrap/blob/develop/README.rst) file, the short URL is provided as a shortcut and is not supposed to work unless you ignore any arising certificate issues.

**Comment by pwaller** [comment]
Sorry, I did find that later. Why not just remove that and suggest the github URL instead? Why advise users to ignore certificate issues for software which runs as root? :(

**Comment by s0undt3ch** [comment]
We advise the opposite right on the top, on the message I showed you, the short URL is, as said, a helpful shortcut

**Comment by jasonkeene** [comment]
Helpful insecure defaults are not helpful.

**Comment by pwaller** [comment]
I agree with @jasonkeene and also I just went straight to the helpful relevant example I was after, and stopped looking upon seeing what I needed, so having some other text above is unhelpful, even if it does say "Attention!" (not in bold). I found `In case you found a bug, please read I found a bug first before submitting a new issue.` long before I saw `to complain about certificate issues. If this worries you, you should not use this URL. Use instead:`.

Not being concerned about getting certificates correct does not inspire confidence..

**Comment by s0undt3ch** [comment]
We how properly support SSL

stable: https://bootstrap.saltstack.com
develop: https://bootstrap.saltstack.com/develop

Closing as fixed.
