### ISSUE TITLE
Race condition on deb based debian install

### ISSUE THREAD

**Issue by jbeda** [saltstack/salt-bootstrap#270]
I've seen this intermittently when running on Debian 7 Wheezy.

When running `wget -O - http://bootstrap.saltstack.org | sudo sh -s` I see buggy behavior.  Sometimes there are errors where the master sees duplicate keys from the minion.  Other times I'll see 2 minions running with confusing results.

Here is what I think is happening:
- The bootstrap script installs the deb.  This automatically starts the minion running.
- It immediately calls stop/start on the init.d script.
- Sometimes the stop/start gets called before the original invocation created its pid file.
- This can result in multiple minions running with the same config racing themselves with nondeterministic behavior.  Sometimes both error out and exit.

I was able to work around this with the `-X` flag that causes the stop/start to be skipped.

Also note that the check to see if the daemons are running (`daemons_running`) didn't catch this as it executes while they are in the process of failing.  I'm not sure how to deal with this beyond perhaps having the daemons write out a 'healty' file into /var/run (next to the pid containing the same pid?) once they've completed their initialization.  Or perhaps just waiting a few seconds and then checking to see if they are running.

**Comment by s0undt3ch** [comment]
I've added some sleeps just before restarting daemons and just before checking if they are running. Hopefully it will take care of this. Please re-open if it does not.
