### ISSUE TITLE
Changing version does not work 

### ISSUE THREAD

**Issue by tomasfejfar** [saltstack/salt-bootstrap#281]
Bootstrap script fetches only one branch into `/tmp/git/salt`. It does not cleanup after itself nor does it check if the branch is there. So if I bootstrap again with different version it fails. It needs to either:
- do `git fetch origin $version:$version` on the repo
- remove `/tmp/git/salt` after successful install

**Comment by s0undt3ch** [comment]
The bootstrap process is supposed to be a one time action, though, code was added to handle these kind of issues.

However, I'm inclined to start deleting the cloned repository afterwards.

Pedro Algarvio @ Phone

----- Reply message -----

**Comment by tomasfejfar** [comment]
I installed develop version of saltmaster to test the `manage.bootstrap` and I failed to notice that it installs the dev version of minions too. So I needed to force the version parameter. And it broke because the repo was existing and it had only `develop` branch. I managed to fix it by deleting the folder using salt-ssh ;)
