### ISSUE TITLE
Recommended upgrade strategy

### ISSUE THREAD

**Issue by ruimarinho** [saltstack/salt-bootstrap#288]
I've been executing a simple command re-run when I want to update salt to the latest git develop update. I've noticed that recent salt-bootstrap version make sure the git clone temporary dir is cleared out before attempting to do so again, but the question remains - what is the recommended way to upgrade the salt (master and/or minion) versions when using the git develop argument?

Thanks for the input!

**Comment by vutny** [comment]
@ruimarinho Now salt bootstrap (`develop` branch) is not purging temporary Git checkout directory, but make an attempt to fetch, `reset --hard` and `pull --rebase` if necessary. So there is no special upgrade strategy for Git-based installations.

I hope that helps. Please could you be so kind to close this issue?

**Comment by ruimarinho** [comment]
Sounds good to me! Thanks!
