### ISSUE TITLE
__check_config_dir: not found

### ISSUE THREAD

**Issue by scjudd** [saltstack/salt-bootstrap#289]
I'm getting the following error when I try to provision Vagrant VMs with Salt:

```
% vagrant provision
[default] Running provisioner: salt...
Copying salt minion config to vm.
Checking if salt-minion is installed
salt-minion was not found.
Checking if salt-call is installed
salt-call was not found.
Bootstrapping Salt... (this may take a while)
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/tmp/bootstrap_salt.sh  -c /tmp

Stdout from the command:



Stderr from the command:

stdin: is not a tty
sh: 206: __check_config_dir: not found
 * ERROR: The configuration directory  does not exist.
 Traceback (most recent call last):
   File "<string>", line 1, in <module>
   IOError: [Errno 32] Broken pipe
```

I originally filed an issue at mitchellh/vagrant#2894, thinking it was a problem with Vagrant, but @mitchellh said this was an issue with Salt itself. Here is a [github repo](https://github.com/scjudd/salt-test) with the Vagrantfile and Salt root. Any help is greatly appreciated!

**Comment by s0undt3ch** [comment]
This issue is now fixed in the latest salt-boostrap script, v1.5.11, which is now included into salt's repository, both in the develop and 2014.1 branches.
Sorry for the breakage.
