### ISSUE TITLE
FreeBSD 10.0 - fetch fails due to SSL

### ISSUE THREAD

**Issue by m87carlson** [saltstack/salt-bootstrap#290]
FreeBSD 10.0's fetch utility has changed from 9.x, it now defaults to check the ssl certificate, so this command fails:

```
root@fbsd-qa:~ # fetch -o - http://bootstrap.saltstack.org
Certificate verification failed for /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert High Assurance CA-3
34380826280:error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed:/usr/src/secure/lib/libssl/../../../crypto/openssl/ssl/s3_clnt.c:1168:
fetch: http://bootstrap.saltstack.org: Authentication error
```

Fetch can either have this flag passed:

```
fetch --no-verify-peer -o - http://bootstrap.saltstack.org | sh
```

Or, you can set the environment variable SSL_NO_VERIFY_PEER=1

**Comment by s0undt3ch** [comment]
Ah! Yes! This makes sense.

**Comment by s0undt3ch** [comment]
@m87carlson Think I can ask you to edit the bootstrap script locally, rename all of `_freebsd_9` occurrences to `_freebsd_10` and run the script to see if the minion get's installed?

If's it's all good, let me know, or, you could also create a pull request which could have the `*_freebsd_10*` just call the `*_freebsd_9*` functions? This way the credit goes to you, as it should.

**Comment by m87carlson** [comment]
You bet, I've tested that out and it seems to work just fine (created new
freebsd_10 functions that just call freebsd_9)

I'll create a pull request

**Comment by s0undt3ch** [comment]
Awesome!

**Comment by amontalban** [comment]
Documentation should be updated as well, for example this line:

fetch -o install_salt.sh https://bootstrap.saltstack.com
sudo sh install_salt.sh

Should be:

fetch --no-verify-peer -o install_salt.sh https://bootstrap.saltstack.com
sudo sh install_salt.sh

Thanks!

**Comment by deeprave** [comment]
Actually a better (and permanent) solution to this is to:

$ pkg install ca_root_nss

then, ln or cp the combined root certificates to /etc/ssl/cert.pem
e.g.
$ ln -s /usr/local/share/certs/ca-root-nss.crt /etc/ssl/cert.pem

which installs the nss root certificates in a place where fetch(1) can find them.

Bypassing security is rarely a good solution.

**Comment by ghost** [comment]
Many thanks deeprave !

**Comment by s0undt3ch** [comment]
Thanks! I'll update the docs with this info.

**Comment by s0undt3ch** [comment]
This information is now on the readme file. Thanks!
