### ISSUE TITLE
Configuration files are being deleted

### ISSUE THREAD

**Issue by ConsoleCatzirl** [saltstack/salt-bootstrap#294]
The usage says that files in `/etc/salt` should only be affected if the script is passed a `-F` and that you can pass a `-c /path` to use config files in `/path`.

However, on Ubuntu LTS, running (as root)

```
mkdir ~/salt
cp -r /etc/salt/* ~/salt
curl -L  http://bootstrap.saltstack.org | sh -s -- -c ~/salt git v0.17.5
```

results in `/etc/salt` being deleted, the example config file put in place, and new pki keys being generated.

**Comment by s0undt3ch** [comment]
I have verified this.
