### ISSUE TITLE
Install multiple minions in one machine

### ISSUE THREAD

**Issue by pedropaulovc** [saltstack/salt-bootstrap#305]
I'm trying to install and run multiple minions independently in one machine. My goal is to have `/etc/salt` and `/etc/salt-2` config folders and and one daemon running for each configuration. 
## Steps attempted

After the first minion is installed:

``` sh
export BS_SALT_ETC_DIR=/etc/salt-2
wget -O install_salt.sh http://bootstrap.saltstack.org
sudo sh install_salt.sh
```

No `/etc/salt-2` folder is created. Only one daemon is running using the `/etc/salt` configs. 

``` sh
export BS_SALT_ETC_DIR=/etc/salt-2
wget -O install_salt.sh http://bootstrap.saltstack.org
sudo sh install_salt.sh -c ./config
```

No `/etc/salt-2` folder is created. Only one daemon is running using the `/etc/salt` configs taken from the `./config` folder.

**Comment by s0undt3ch** [comment]
I've updated the script in order not to ignore that environment variable. It was just being used for FreeBSD.

However, even with the updated script, what you want will only be achieved to some point.

For git based installations, and a recent enough version of salt( >= 2014.1.0rc3 ), when installing salt, the value of `BS_SALT_ETC_DIR` will be used as the default configuration directory, but the `init.d` or `upstart` or `systemd` scripts, used to start the minion, will only work for one of them(unless you copy and adapt accordingly).

So, while we _kind_ of support what you want, this was never the intended, nor the expected, behavior for the bootstrap script.

You'll have to do some scripting work of your own if you wish to automate this process.

I hope I've helped, at least to some point.

Closing. Please re-open if need be.
