### ISSUE TITLE
Config files are not copied from /tmp to /etc/salt

### ISSUE THREAD

**Issue by ajw0100** [saltstack/salt-bootstrap#316]
Running into this on `develop`. Reverting to `v1.5.11` avoids the issue. Master and minion config are both empty in `/etc/salt`.

```
$ cat /tmp/master 
user: ubuntu

fileserver_backend:
  - git

gitfs_remotes:
  - file:///vagrant
  - https://github.com/ajw0100/salt-states.git

ext_pillar:
  - git: master file:///pillar
  - git: dev file:///pillar
  - git: qa file:///pillar
  - git: prod file:///pillar

$ cat /tmp/minion
master: localhost
id: epicsampler-master-qa

$ cat /etc/salt/master 
$ cat /etc/salt/minion
$ 
```

Seed keys on the other hand are copied over correctly.

Server info:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.4 LTS
Release:    12.04
Codename:   precise

$ uname -a
Linux 3.2.0-58-virtual #88-Ubuntu SMP Tue Dec 3 17:58:13 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by s0undt3ch** [comment]
Does that system already has `/etc/salt/master` and/or `/etc/salt/minion` when bootstrapping?
Can you please include the full output of your bootstrap by passing an additional flag, `-D`?

**Comment by ajw0100** [comment]
Ok I see the issue. I am trying to run `salt-master` as `ubuntu` not `root`. In order to do this I've been running a short bash script before `bootstrap-salt.sh` that sets up some common salt directories/files and then `chown`s them so they can be read from and written to by `ubuntu`.

```
mkdir -p /etc/salt/pki /var/cache/salt /var/log/salt
touch /etc/salt/master /etc/salt/minion
chown -R ubuntu:ubuntu /etc/salt /var/cache/salt /var/log/salt
```

I `touch` the configs because I'm using salt's wheel module in one of my projects to programmatically edit the config files so I need to ensure they can be written to by `ubuntu`.

The above works on `v1.5.11` but I guess I could run `bootstrap-salt.sh` with `-X` and then run the following after `bootstrap-salt.sh` but before starting the daemons and calling highstate:

```
chown -R ubuntu:ubuntu /etc/salt /var/cache/salt /var/log/salt
```

Is there a way to tell `bootstrap-salt.sh` which user to create salt's config, cache, and log dirs/files as so `salt-master` can be run easily as a non-root after a fresh install?

Thanks!

**Comment by s0undt3ch** [comment]
I you're bootstrapping on Ubuntu, `-X` won't have any effect, the daemons, **will** start(see #266).

If you're touching the configuration files, previously they were being overridden by default, which was a bug, now you'll have to pass, `-F`.

About a specific user, nope, you can't define a user to execute the script as...

Anyway, `-F` should get you back on track to what you were doin' with v1.5.11

**Comment by s0undt3ch** [comment]
If you with to have the daemons run under a specific user, see [this](http://docs.saltstack.com/topics/nonroot.html)

**Comment by ajw0100** [comment]
I'm installing from git develop not apt so `-X` seems to work fine.

`-F` is what I need. Thanks.

**Comment by s0undt3ch** [comment]
Awesome!

Pedro Algarvio @ Phone

----- Reply message -----

**Comment by s0undt3ch** [comment]
Closing as fixed. Please reopen if need be.
