### ISSUE TITLE
Support for debian jessie

### ISSUE THREAD

**Issue by Lothiraldan** [saltstack/salt-bootstrap#327]
Hi,

I tried yesterday to run a debian jessie VM using vagrant and a salt provisionner. It uses this script to install salt-minion and restart salt-minion but unfortunately debian jessie seems not supported.

I take a quick look at the script and I noticed a difference between wheezy VM and jessie VM, the /etc/os-release file.

In wheezy VM:

```
PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
NAME="Debian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="http://bugs.debian.org/
```

In jessie VM:

```
NAME="Debian GNU/Linux"
ID=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="http://bugs.debian.org/"
```

And for /etc/debian_version, in wheezy VM:

```
 7.2
```

In the jessie VM:

```
 jessie/sid
```

We could add a workaround like this one : https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L727 for detecting jessie and add corresponding functions.

**Comment by s0undt3ch** [comment]
If you change the check for [`wheezy/sid`](https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L727) for `jessie/sid` does that system get bootstrapped properly?

**Comment by Lothiraldan** [comment]
Yep it looks like it's works, but we already installed salt-minion by hand on this VM. I tried to remove salt-common, salt-minions and all dependencies with purge option and run the script again, it seems to works.

I will retry with a fresh jessie install.

**Comment by s0undt3ch** [comment]
Thank you. If it works, I'll add some function aliases for it.

**Comment by Lothiraldan** [comment]
I just tried on a fresh VM, it works great. I tried to install salt minion the first time and salt-master + salt-minion the second time.

Saltstack seems to not have an official jessie repo right now, so we could use the debian one.

**Comment by s0undt3ch** [comment]
Thanks for your investigation work @Lothiraldan !

**Comment by benallard** [comment]
jessie is not being recognized for me ...
