### ISSUE TITLE
CentOS and proxy settings

### ISSUE THREAD

**Issue by ginglass** [saltstack/salt-bootstrap#328]
rpm can't import thought a authenticated proxy server. So could be better wget that EPEL repo file (line 2011) and import from local...
Great project!

**Comment by s0undt3ch** [comment]
We do accept PR's :)

Anyway, we'll look into this and ask you for more details if necessary...

**Comment by s0undt3ch** [comment]
Since we now support passing a proxy server, `-H`, closing as fixed.
