### ISSUE TITLE
Centos 6.5 install salt as service

### ISSUE THREAD

**Issue by matdrapeau** [saltstack/salt-bootstrap#329]
Seems that salt-minion is not installed as a service, it is not started at boot time on centos 6.5 (upstart support).
The file `/etc/init/salt-minion.conf` has been created.

**Comment by matdrapeau** [comment]
please see:
https://github.com/saltstack/salt/issues/10740

**Comment by matdrapeau** [comment]
Line 2229:
`copyfile ${SALT_GIT_CHECKOUT_DIR}/pkg/salt-$fname.upstart /etc/init/salt-$fname.conf`
should use the `.upstart.rhel6` script instead for centos?

**Comment by diegows** [comment]
Redhat/Centos packages doesn't have upstart config files, so I think that we should check that. I'll send a pull request soon.

**Comment by diegows** [comment]
Please, have a look at pull request #336 

Tested on CentOS with Upstart installed but with SysV script available only.

**Comment by s0undt3ch** [comment]
Fixed in the upcoming salt bootstrap release.
