### ISSUE TITLE
Allow No Install

### ISSUE THREAD

**Issue by akoumjian** [saltstack/salt-bootstrap#33]
In some rare circumstances, we may not want to install any binaries but simply run the config() option. Option one involves silently accepting not installing anything, or if we are configuring but not installing anything. Option number two would be an additional flag of some kind.

The case in point is that not salty-vagrant uses bootstrap to copy config files over. However, we currently only run bootstrap is salt is not already on the machine. If salt is pre-installed, the configs don't get copied over. Instead of duplicating this functionality, it would be ideal to just run bootstrap anything, but with the options to not install and `-c` to config.

**Comment by techhat** [comment]
I like this, but not as much as I like the idea of images with Salt already being installed being the norm...

**Comment by akoumjian** [comment]
@techhat Amen!

**Comment by s0undt3ch** [comment]
I'll chew on this for a moment, all ideas will be taken into consideration ;)

**Comment by s0undt3ch** [comment]
@akoumjian We should restart the daemons correct? Or at this stage the daemons are not running?

**Comment by akoumjian** [comment]
It was my impression that daemons are not running, but I suppose they could be. Can we do it without complains if the service is not installed?

**Comment by s0undt3ch** [comment]
I think I should make the start daemons function aware if they should start or restart the daemons to avoid future problems.

**Comment by s0undt3ch** [comment]
@akoumjian please report any issues you encounter.
