### ISSUE TITLE
Salt-Bootstrap now broken on CentOS 6.5 for vagrant deployment

### ISSUE THREAD

**Issue by jberkus** [saltstack/salt-bootstrap#332]
As of the 27th, one can no longer deploy vagrant CentOS 6.5 images with Salt.  

Complete!
-  INFO: Running install_centos_stable_post()
-  INFO: Running install_centos_check_services()
- ERROR: Failed to run install_centos_check_services()!!!

This commit seems to be at fault:
https://github.com/saltstack/salt-bootstrap/commit/355c0e44b0186e17f3fe7fb32caa25b29bfb92a0

Here's another report of the same issue:
https://groups.google.com/forum/#!msg/salt-users/78jMXyHxi9g/CmPf50PFCYoJ

Please revert the commit or fix, thanks!

**Comment by s0undt3ch** [comment]
I'll have a look at this as soon as possible.

**Comment by d1gital42** [comment]
I am experiencing the same issue, CentOS 6.5 on Vagrant.

Linux localhost.localdomain 2.6.32-431.3.1.el6.i686 #1 SMP Fri Jan 3 18:53:30 UTC 2014 i686 i686 i386 GNU/Linux
- ERROR: Failed to run install_centos_check_services()!!!

**Comment by jillr** [comment]
Also on official Centos 6.5 AMI on EC2, 2.6.32-431.5.1.el6.x86_64.  Alternative in previously linked Google group post worked.  Debian 7 images working normally.

# salt-minion --version

salt-minion 2014.1.0
-  INFO: Running install_centos_stable_post()
-  INFO: Running install_centos_check_services()
- ERROR: Failed to run install_centos_check_services()!!!

**Comment by Abukamel** [comment]
Please fix this as fast as possible, i confirm same problem.

**Comment by scjudd** [comment]
Experiencing the same thing on DigitalOcean's CentOS 6.5 x64 images. Curling an older salt-bootstrap, per [this salt-users message](https://groups.google.com/d/msg/salt-users/78jMXyHxi9g/CmPf50PFCYoJ), seems to work.

**Comment by s0undt3ch** [comment]
This is fixed in the upcoming bootstrap release. Closing. Please reopen if need be.

**Comment by jberkus** [comment]
Verified fixed.  Thanks for the quick fix!

**Comment by s0undt3ch** [comment]
Well it should have been quicker but this week was not easy....

Anyway... Awesome!
