### ISSUE TITLE
Oracle Linux 5x not supported

### ISSUE THREAD

**Issue by briffle** [saltstack/salt-bootstrap#335]
CentOS 5.x works fine, but Oracle Enterprise Linux 5.x does not seem to.  Looking at Issue #302 it appears this is the output you need:

wget --no-check-certificate -O - http://bootstrap.saltstack.org | sudo sh -s -- -D -P git v0.17.5 

Saving to: `STDOUT'

 0% [                                                                               ] 0           --.-K/s               
-  INFO: PIPED THROUGH sh -- Version 2014.02.27
  55% [==========================================>                                    ] 81,920       330K/s              
  -  INFO: System Information:
  -  INFO:   CPU:          GenuineIntel
  -  INFO:   CPU Arch:     x86_64
  -  INFO:   OS Name:      Linux
  -  INFO:   OS Version:   2.6.18-274.el5
  -  INFO:   Distribution: EnterpriseEnterpriseServer 5.7
  -  INFO: Installing minion
    100%[==============================================================================>] 148,246      319K/s   in 0.5s    

2014-03-05 09:58:01 (319 KB/s) - `-' saved [148246/148246]
- DEBUG: install_enterpriseenterpriseserver_5_git_deps not found....
- DEBUG: install_enterpriseenterpriseserver_5_7_git_deps not found....
- DEBUG: install_enterpriseenterpriseserver_5_deps not found....
- DEBUG: install_enterpriseenterpriseserver_5_7_deps not found....
- DEBUG: install_enterpriseenterpriseserver_git_deps not found....
- DEBUG: install_enterpriseenterpriseserver_deps not found....
- DEBUG: DEPS_INSTALL_FUNC=null
- DEBUG: CONFIG_SALT_FUNC=null
- DEBUG: PRESEED_MASTER_FUNC=null
- DEBUG: install_enterpriseenterpriseserver_5_git not found....
- DEBUG: install_enterpriseenterpriseserver_5_7_git not found....
- DEBUG: install_enterpriseenterpriseserver_git not found....
- DEBUG: INSTALL_FUNC=null
- DEBUG: install_enterpriseenterpriseserver_5_git_post not found....
  - DEBUG: install_enterpriseenterpriseserver_5_7_git_post not found....
- DEBUG: install_enterpriseenterpriseserver_5_post not found....
- DEBUG: install_enterpriseenterpriseserver_5_7_post not found....
- DEBUG: install_enterpriseenterpriseserver_git_post not found....
- DEBUG: install_enterpriseenterpriseserver_post not found....
- DEBUG: POST_INSTALL_FUNC=null
- DEBUG: install_enterpriseenterpriseserver_5_git_restart_daemons not found....
- DEBUG: install_enterpriseenterpriseserver_5_7_git_restart_daemons not found....
- DEBUG: install_enterpriseenterpriseserver_5_restart_daemons not found....
- DEBUG: install_enterpriseenterpriseserver_5_7_restart_daemons not found....
- DEBUG: install_enterpriseenterpriseserver_git_restart_daemons not found....
- DEBUG: install_enterpriseenterpriseserver_restart_daemons not found....
- DEBUG: STARTDAEMONS_INSTALL_FUNC=null
- DEBUG: daemons_running_enterpriseenterpriseserver_5_git not found....
- DEBUG: daemons_running_enterpriseenterpriseserver_5_7_git not found....
- DEBUG: daemons_running_enterpriseenterpriseserver_5 not found....
- DEBUG: daemons_running_enterpriseenterpriseserver_5_7 not found....
- DEBUG: daemons_running_enterpriseenterpriseserver_git not found....
- DEBUG: daemons_running_enterpriseenterpriseserver not found....
-  INFO: Found function daemons_running
- DEBUG: Waiting 3 seconds for processes to settle before checking for them
- DEBUG: DAEMONS_RUNNING_FUNC=daemons_running
- DEBUG: install_enterpriseenterpriseserver_5_git_check_services not found....
- DEBUG: install_enterpriseenterpriseserver_5_7_git_check_services not found....
- DEBUG: install_enterpriseenterpriseserver_5_check_services not found....
- DEBUG: install_enterpriseenterpriseserver_5_7_check_services not found....
- DEBUG: install_enterpriseenterpriseserver_git_check_services not found....
- DEBUG: install_enterpriseenterpriseserver_check_services not found....
- DEBUG: CHECK_SERVICES_FUNC=null
- ERROR: No dependencies installation function found. Exiting...
- DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe
- DEBUG: Killing logging pipe tee's with pid(s): 18159

Is there an easy way to alias all these RHEL derivatives? (Ie, Oracle Linux, ClearOS, Scientific Linux, etc?)

**Comment by s0undt3ch** [comment]
I need more info:

Can you please show me the output of:

``` bash
sudo find /etc/ -name '*-release' -print -exec cat {} \;
```

and also:

``` bash
which lsb_release && lsb_release -a
```

**Comment by briffle** [comment]
sudo find /etc/ -name '*-release' -print -exec cat {} \;

```
/etc/oracle-release
Oracle Linux Server release 5.8
/etc/redhat-release 
Red Hat Enterprise Linux Server release 5.8 (Tikanga)
/etc/enterprise-release 
Enterprise Linux Enterprise Linux Server release 5.8 (Carthage)
```

which lsb_release && lsb_release -a

```
/usr/bin/lsb_release
LSB Version:    :core-4.0-amd64:core-4.0-ia32:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-ia32:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-ia32:printing-4.0-noarch
Distributor ID: EnterpriseEnterpriseServer
Description:    Enterprise Linux Enterprise Linux Server release 5.8 (Carthage)
Release:        5.8
Codename:       Carthage
```

I also created a pull request of the changes I made to the script, that allow it to work on my OEL servers..

**Comment by s0undt3ch** [comment]
Can you please test https://raw.github.com/s0undt3ch/salt-bootstrap/develop/bootstrap-salt.sh and see if it all goes well?
