### ISSUE TITLE
bootstrap/deploy.sh fails to run on CentOS minions after upgrade to latest 2014.1.0

### ISSUE THREAD

**Issue by gadams999** [saltstack/salt-bootstrap#337]
Hi,

On my test master, I upgraded salt to latest 2014.1 release and stop/started the master.

``` sh
curl -L http://bootstrap.saltstack.org | sudo sh -s -- -M -N git 2014.1
```

All installed well, this is the master:

``` shell
# salt --versions-report
           Salt: 2014.1.0-31-g7dac680
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
         PyYAML: 3.10
          PyZMQ: 2.2.0.1
            ZMQ: 3.2.4
```

When I deploy a CentOS 6 minion via salt-cloud, everything completes properly to this point (output from master):

```
================================================================================
 Package            Arch          Version                  Repository      Size
================================================================================
Installing:
 salt-minion        noarch        2014.1.0-1.el6           epel            21 k
```

followed by:

```
Complete!
 *  INFO: Running install_centos_stable_post()
 *  INFO: Running install_centos_check_services()
 * ERROR: Failed to run install_centos_check_services()!!!
[ERROR   ] Failed to deploy 'ars_coin1'. Error: Executing the command '/tmp/.saltcloud/deploy.sh -c /tmp/.saltcloud' failed
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1620, in run_map
    profile, local_master=master_name is None
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 854, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/openstack.py", line 738, in create
    deployed = salt.utils.cloud.deploy_script(**deploy_kwargs)
  File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 753, in deploy_script
    deploy_command
SaltCloudSystemExit: Executing the command '/tmp/.saltcloud/deploy.sh -c /tmp/.saltcloud' failed
[INFO    ] Complete
```

When I connect to the VM and run the deploy script I see this:

```
# /tmp/.saltcloud/deploy.sh 
 *  INFO: /bin/sh /tmp/.saltcloud/deploy.sh -- Version 2014.02.27

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   2.6.32-358.el6.x86_64
 *  INFO:   Distribution: CentOS 6.4

 *  INFO: Installing minion
 *  INFO: Found function install_centos_stable_deps
 *  INFO: Found function install_centos_stable
 *  INFO: Found function install_centos_stable_post
 *  INFO: Found function install_centos_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Found function install_centos_check_services
 *  INFO: Running install_centos_stable_deps()
Retrieving http://mirrors.kernel.org/fedora-epel/6/x86_64/epel-release-6-8.noarch.rpm
Preparing...                ##################################################
epel-release                ##################################################
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: linux.mirrors.es.net
 * epel: mirrors.kernel.org
 * extras: mirror.nwresd.org
 * updates: mirrors.sonic.net
Setting up Install Process
Package PyYAML-3.10-3.el6.x86_64 already installed and latest version
Package m2crypto-0.20.2-9.el6.x86_64 already installed and latest version
Package python-crypto-2.0.1-22.el6.x86_64 already installed and latest version
Package python-msgpack-0.1.13-3.el6.x86_64 already installed and latest version
Package python-zmq-2.2.0.1-1.el6.x86_64 already installed and latest version
Package python-jinja2-2.2.1-1.el6.x86_64 already installed and latest version
Nothing to do
 *  INFO: Running install_centos_stable()
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: linux.mirrors.es.net
 * epel: mirrors.kernel.org
 * extras: mirror.nwresd.org
 * updates: mirrors.sonic.net
Setting up Install Process
Package salt-minion-2014.1.0-1.el6.noarch already installed and latest version
Nothing to do
 *  INFO: Running install_centos_stable_post()
 *  INFO: Running install_centos_check_services()
 * ERROR: Failed to run install_centos_check_services()!!!
```

Hope this is the right area to bring this up!

**Comment by s0undt3ch** [comment]
You know that

```
curl -L http://bootstrap.saltstack.org | sudo sh -s -- -M -N git 2014.1
```

will install salt from the `2014.1` branch right? not the `v2014.1.0` release.

I believe this is related to the recent `systemd` checks added

**Comment by s0undt3ch** [comment]
This is fixed in the upcoming bootstrap release. Closing. Please reopen if need be.

**Comment by gadams999** [comment]
EDIT: commented before seeing s0undt3ch's closed comment Reverting to develop branch.

I didn't know about the differences in the 2014.1 branch vs. actual release v2014.1.0 release, thanks. Still new to the nuances of git.

Even with v2014.1.0 same issue. Is there some dependency not being picked up by the RPM or just a work-in-progress?

Is there an interim solution to use a previous known, working, version of salt-minion that works with the release?

**Comment by s0undt3ch** [comment]
I just released the v2014.03.10 version of the script where this problem should be fixed. Please try it and reopen the ticket if it still fails.

**Comment by disylee** [comment]
I also met this problem.I try this command wget -O - https://bootstrap.saltstack.com | sudo sh -x
but returns 

Error getting repository data for epel, repository not found
- return 1
- '[' 1 -ne 0 ']'
- echoerror 'Failed to run install_centos_stable_deps()!!!'
- printf '\033[1;31m \* ERROR\033[0m: %s\n' 'Failed to run install_centos_stable_deps()!!!'
  - ERROR: Failed to run install_centos_stable_deps()!!!
- exit 1
- __exit_cleanup
- EXIT_CODE=1
- '[' stable = git ']'
- echodebug 'Removing the logging pipe /tmp/bootstrap-salt.logpipe'
- '[' 0 -eq 1 ']'
- rm -f /tmp/bootstrap-salt.logpipe
  ++ awk '{print $1}'
  ++ grep /tmp/bootstrap-salt.log
  ++ grep tee
  ++ ps ax

Is my repository didn't include the right epel?
look here 
[root@localhost src]# rpm -ql epel-release-6-8.noarch
/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
/etc/rpm/macros.ghc-srpm
/etc/yum.repos.d/epel-testing.repo
/etc/yum.repos.d/epel.repo
/usr/share/doc/epel-release-6
/usr/share/doc/epel-release-6/GPL

my release 

[root@localhost src]# cat /etc/redhat-release
CentOS release 6.6 (Final)

Could U please help me?

**Comment by s0undt3ch** [comment]
@disylee please paste the full output of `wget -O - https://bootstrap.saltstack.com | sudo sh -s -- -D`

**Comment by disylee** [comment]
too long to paste that

**Comment by s0undt3ch** [comment]
Put it in gist or a pastebin. Can't do much without all of that info...
