### ISSUE TITLE
While installing via salt-bootstrap, older version of salt minion breaks things but latest does not

### ISSUE THREAD

**Issue by ksalman** [saltstack/salt-bootstrap#341]
Installing latest Salt works fine when I install using the bootsctrap script

```
wget --no-check-certificate -O - http://bootstrap.saltstack.org | sh -s
```

But when I try to install an older version, 0.17.2..

```
wget --no-check-certificate -O - http://bootstrap.saltstack.org | sh -s -- -P git v0.17.2
```

.. it breaks a lot of things by installing things from Debian Unstable 

```
 * WARN: PyZMQ will be installed from PyPI in order to compile it against ZMQ3
* WARN: This is required for long term stable minion connections to the master.
* WARN: YOU WILL END UP WITH QUITE A FEW PACKAGES FROM DEBIAN UNSTABLE
* WARN: Sleeping for 3 seconds so you can cancel...
```

I am using Debian Wheezy and previously when 0,17.2 was the latest version it did not need to install anything from Debian unstable, so I am curious why it needs to do that now? What I find odd is that the Salt 2014.1.0 does NOT need to install anything from unstable and does not break things.

My Salt master is 0.17.2 so I need to install 0.17.2 Salt minion

**Comment by s0undt3ch** [comment]
By passing `-P` you're telling the script to use pip pacakges and the unstable repo.

If you just want to install `v0.17.2` you can omit that `-P`...

```
wget --no-check-certificate -O - http://bootstrap.saltstack.org | sh -s -- git v0.17.2
```

**Comment by s0undt3ch** [comment]
No more information was given.
Closing. Please reopen if need be.
