### ISSUE TITLE
rhel optional repo check fails

### ISSUE THREAD

**Issue by akimyonoglu** [saltstack/salt-bootstrap#350]
$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.4 (Santiago)

$ sudo sh -x /tmp/bootstrap-salt.sh

```
++rhn-channel -l
+ '[' Xrhel-x86_64-server-optional-6.4.z '!=' Xrhel-x86_64-server-optional-6 ']'
+ echoerror 'Failed to find RHN optional repo, please enable it using the GUI or rhn-channel command.'
+ printf '\033[1;31m * ERROR\033[0m: Failed to find RHN optional repo, please enable it using the GUI or rhn-channel command.\n'
 * ERROR: Failed to find RHN optional repo, please enable it using the GUI or rhn-channel command.
```

**Comment by s0undt3ch** [comment]
Is this from a cloud image so I can test?
Because the Vms I have access to only use the major part of the version, and yours, include the minor and z?

**Comment by akimyonoglu** [comment]
yes this one is running on KVM host which is RedHat 6.3, 
here is the subscription information of the VM from RHN:

```
System Info
Virtualization: Fully Virtualized
Kernel:  2.6.32-358.32.3.el6.x86_64
Description:    Initial Registration Parameters:
OS: redhat-release-server
Release: 6Server
CPU Arch: x86_64
Subscribed Channels (Alter Channel Subscriptions)
RHEL EUS Server (v. 6.4.z for 64-bit x86_64)
RHEL EUS Server Optional (v. 6.4.z 64-bit x86_64)
```

one of these should be fine for testing http://www.filewatcher.com/m/rhel-server-6.4-x86_64-dvd.iso.3720347648-0.html

I was thinking patching this one myself, didn't have time tho.
