### ISSUE TITLE
ERROR: You need to allow pip based installations

### ISSUE THREAD

**Issue by pwaller** [saltstack/salt-bootstrap#370]
It used to be that one could just run `sudo sh bootstrap-salt.sh stable`, but that seems to have changed. Now this happens:

```
Reading package lists...
Building dependency tree...
Reading state information...
python-requests is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 36 not upgraded.
 * ERROR: You need to allow pip based installations(-P) in order to install the python 'requests' package
```

I don't really want to allow a pip installation, so what's happening?

**Comment by s0undt3ch** [comment]
A pip installation is installing a package from python's package library. This happens because such package is not available as a system package on your distribution.

Using your command above, all you need to do now is pass `-P`:

``` bash
sudo sh bootstrap-salt.sh -P stable
```

**Comment by s0undt3ch** [comment]
What script are you using?
current develop?
Which is your distribution?

**Comment by pwaller** [comment]
I'm using the current stable. My distribution is Ubuntu 13.10.

I don't want to contaminate my system with software installed outside of apt, so I don't want to do a system-wide pip install.

**Comment by s0undt3ch** [comment]
Can you please try the following script?

https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh

**Comment by pwaller** [comment]
The instructions here (essentially) use that, and that's what I used before reporting this bug.

https://github.com/saltstack/salt-bootstrap/blob/develop/README.rst

I've also tried `/stable/` and I had to go to `/v2014.02.27/` to find one that worked.

**Comment by s0undt3ch** [comment]
The instructions use the sable versions, not the develop one. There's only a single reference to the develop version which should be followed in cases of errors.

**Comment by s0undt3ch** [comment]
Dam! We do have the references to develop there!!! Fixing :smile:

**Comment by s0undt3ch** [comment]
URL reference fixed.

I'll take a look why that pip warning is showing up in 13.10

**Comment by benallard** [comment]
Related to that issue, `python-requests` is available under debian jessie, would be good not to requests pip, when it can be downloaded, or, even worst, when it is already installed !

**Comment by benallard** [comment]
Didn't saw the issue was closed, going to open a new one.

**Comment by bogdanr** [comment]
Because of this salt-cloud can't automatically install it's minion: https://github.com/saltstack/salt-bootstrap/issues/604
