### ISSUE TITLE
Feature: Easily support alternative renderers

### ISSUE THREAD

**Issue by cachedout** [saltstack/salt-bootstrap#373]
As mentioned in Salt issue #11882, it would be handy if the bootstrap script could accept a `--renderers` flag and use the results to install deps for alternatives renderers, such as Mako.

**Comment by cachedout** [comment]
cc: @masterkorp

**Comment by s0undt3ch** [comment]
Double dashes are not a POSIX compliant way of passing arguments to a shell script, so, we're stuck with single letters, however:

```
$ sh bootstrap-salt.sh -h

  Usage :  bootstrap-salt.sh [options] <install-type> <install-type-args>

[ ..... ]

  -p  Extra-package to install while installing salt dependencies. One package
      per -p flag. You're responsible for providing the proper package name.
```

So, this is already supported. Do note that _"You're responsible for providing the proper package name"_.
