### ISSUE TITLE
Centos5 bootstrap fails

### ISSUE THREAD

**Issue by c-nixon** [saltstack/salt-bootstrap#375]
When Installing centos5 i386 I ran into 2 issues:
- Missing dependencies:
  - chkconfig
  - python26-requests
- Could not find chkconfig
  - chkconfig is installed to /sbin and isn't on the system path

Once I manually corrected these problems everything worked as expected.

In case it's relevant I installed centos5 with desktop configuration

**Comment by s0undt3ch** [comment]
For the python requests issue, please try the unreleased script to see if that works:
- https://raw.github.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh

About `chkconfig` not being in path, is this when installing from an official ISO? Is this a cloud image?

**Comment by c-nixon** [comment]
Looks like that fixes the missing requests dependency, thanks.

I installed using the official centos5 netinstall iso, which is presumably quite minimal.
