### ISSUE TITLE
seed_master uses wrong file names

### ISSUE THREAD

**Issue by claytondaley** [saltstack/salt-bootstrap#379]
Chased [this issue](https://github.com/saltstack/salty-vagrant/issues/102) back through the built-in Vagrant Salt provisioner.  [Thought that script was broken](https://github.com/mitchellh/vagrant/issues/3492) until I figured out that the `-k` option should be moving the keys into the correct location.

Adding some debug code to salt-bootstrap, I found the actual root cause:
- _TEMP_KEYS_DIR is /tmp/minion-seed-keys
- SEED_DEST is /etc/salt/pki/master/minions
- src_keyfile is /tmp/minion-seed-keys//tmp/minion-seed-keys/minion
- dst_keyfile is /etc/salt/pki/master/minions//tmp/minion-seed-keys/minion

Obviously, the keyfiles are wrong so the movefile fails (technically is never reached).  My less than stellar bash research suggests that this can be solved using basename (around line 4009):

```
        src_keyfile="${_TEMP_KEYS_DIR}/$(basename ${keyfile})"
        dst_keyfile="${SEED_DEST}/$(basename ${keyfile})"
```

**Comment by s0undt3ch** [comment]
Fixed in #380
