### ISSUE TITLE
Vagrant provisioning idempotency issues

### ISSUE THREAD

**Issue by bmcorser** [saltstack/salt-bootstrap#383]
The first provisioning run of a **master-only** box works beautifully, but when I try to run `vagrant provision` again to effect a change in my config, I get a permissions failure; the `vagrant` user does have perms for where the bootstrap script wants to copy keys?

Ok, I don't need to copy minion or master keys across in this provisioning run, so despite the tremendous inconvenience, I can just comment out a few lines from my `Vagrantfile` for now and try again.

This time, things look more serious. There is a lot of red text, which reads:

```
 *  INFO: Running install_ubuntu_restart_daemons()
start: Unknown job: salt-minion
 * ERROR: No init.d support for salt-minion was found
 * ERROR: Failed to run install_ubuntu_restart_daemons()!!!
```

Holy bacon!!! Why do we care about the minion daemon? This is a **master-only** box!

I can pass `-N` through `bootstrap_options` in my `Vagrantfile`, but this feels redundant because I am already setting `no_minion` to `true`.

**Comment by s0undt3ch** [comment]
So, first things first.
- I'm not a vagrant user and the last time I used vagrant with salt, vagrant didn't yet supported salt :smile: 
- The bootstrap script is coded to install salt in a machine that does not have it. It's not supposed to maintain or upgrade a salt setup. If multiple executions work, AWESOME!

Now, the problems you report seem only related to how the salt vagrant provider is passing options to the script.
Could this be best reported on the vagrant issue tracker?

**Comment by bmcorser** [comment]
You're probably right. I actually realised that this was really an issue in the flags being passed to the bootstrap script, but the last issue I reported for provisioner/bootstrap I posted on the Vagrant issue tracker, so I thought I might share the load :wink:

I'll copy pasta over to them.

**Comment by s0undt3ch** [comment]
No worries.

Pedro Algarvio @ Phone

----- Reply message -----
