### ISSUE TITLE
getting the bootstrap sometimes gives me code 400 instead of 302

### ISSUE THREAD

**Issue by rasschaert** [saltstack/salt-bootstrap#385]
`$ curl -L http://bootstrap.saltstack.org`

gives a 302 redirect to `https://raw.github.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh`

Very often, github refuses to serve up the bootstrap script and serves up this error instead:

``` html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>
```

Github is probably rate-limiting or taking some other measure to avoid people using them as a CDN (which is basically what you are doing).

`https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh` seems to work every time though.

Shoutout to @kalmanolah for helping me troubleshoot this.

**Comment by unicolet** [comment]
I noticed that too, see #384 and #386

**Comment by rasschaert** [comment]
Meanwhile [Vagrant](https://github.com/mitchellh/vagrant) has started using the raw.githubusercontent.com url: https://github.com/mitchellh/vagrant/commit/f80fdfa32acacee024458844a27d0b9269a141c4.

**Comment by s0undt3ch** [comment]
The new bootstrap URLs
- stable: https://bootstrap.saltstack.com
- develop: https://bootstrap.saltstack.com/develop

Should now properly work without hitting this issue.

Closing. Please reopen if need be.
