### ISSUE TITLE
option to only install salt-call (salt-common)

### ISSUE THREAD

**Issue by wuxxin** [saltstack/salt-bootstrap#389]
**Rationale:** In a master-less setup, it should not be required to have a full salt-minion installed (which tries to connect to a master).
**Requested Feature:** The Bootstrap Script should support a "salt-call" only configuration.

salt-call (which is in salt-common on debian like systems), is enough to provide a masterless setup.

If you have to install the minion package at minimum, the minion install defaults to try to connect to whatever answers at "salt[.fqdn]", which is not what is usually wanted in a master-less setup.

As a workaround, i install "salt-common python-msgpack python-zmq" from the ppa for debian/ubuntu with a self written bootstrap script, but i think this could be an interesting feature in salt-bootstrap for any platform.

**Comment by s0undt3ch** [comment]
On 6 de Maio de 2014 16:25:35 WEST, wuxxin notifications@github.com wrote:

> Rationale: In a master-less setup, it should not be required to have a
> full salt-minion installed. The Bootstrap Script should support this
> configuration.
> 
> salt-call (which is in salt-common (debian like systems)), is enough to
> provide a masterless setup.
> 
> If you have to install the minion package at minimum, the minion tries
> to connect to whatever answers at "salt[.fqdn]", which is not what is
> usually wanted in a master-less setup.
> 
> As a workaround i currently install "salt-common python-msgpack
> python-zmq" from the ppa to make this working, but i think this could
> be an interesting feature for salt-bootstrap.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/saltstack/salt-bootstrap/issues/389#issuecomment-42317044

So this is Debian specific...

There is a flag which tells the script not to install a minion... But it will fail since you don't install a master or a syndic...
Pedro Algarvio @ Phone

**Comment by s0undt3ch** [comment]
On 6 de Maio de 2014 16:14:06 WEST, wuxxin notifications@github.com wrote:

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/saltstack/salt-bootstrap/issues/389

We can only pass single character options to the script. On top of that, splitting packages is a distribution specific choice (not all supported distributions split their packages).

So, at first glance I'm going to say no, but, what's the reason behind this request?
Pedro Algarvio @ Phone

**Comment by wuxxin** [comment]
In my opinion: this is not a distribution related ticket.
The functionality needed is: bootstrap installs (if requested to do so) only the files needed to run "salt-call" as a minimum, because salt-minion tries to connect to a master, which is not needed and wanted in a masterless setup.

use case:
- sally wants to setup a physical machine using some salt scripts.
- she downloads a set of salt-states in a zip file, and the salt-bootstrap script.
- she executes salt-bootstrap with the "--no-minion --no-master" option
- salt boot-strap only installs salt-common, which is enough to run salt script masterless
- she does not want to install a salt-minion bootstrap package, because this package tries to connect to whatever answers at "master.fqdn"

**Comment by s0undt3ch** [comment]
@wuxxin I must disagree, and, as an example, on Arch, salt is packaged as as a whole, on Fedora it's packaged as salt-master and salt-minion.

The script needs to support multiple distributions and your request is closely tied to debian based systems. How would we solve this problem for all distributions?

**Comment by wuxxin** [comment]
@s0undt3ch thanks for clarifying, 
i agree, splitting salt into salt- master, syndic, minion, common is specific to debian/ubuntu.
splitting it into master& minion  is specific to debian, ubuntu, fedora, centos, opensuse.

there is a option "-X" (do not start daemons), which has a distribution specific bug, daemons are always started in debian/ubuntu, if you install the corresponding package (eg. salt-minion, salt-master).

My reason for this is, if you want a masterless setup, you do not want a machine trying to connect to a master at any time, so it would help to have a switch that prevent running (and optional installing) the minion as a daemon on all platforms in case of a masterless install.

**Comment by s0undt3ch** [comment]
On 18 de Maio de 2014 16:31:02 WEST, wuxxin notifications@github.com wrote:

> @s0undt3ch thanks for clarifying, 
> i agree, splitting salt into salt- master, syndic, minion, common is
> specific to debian/ubuntu.
> splitting it into master& minion  is specific to debian, ubuntu,
> fedora, centos, opensuse.
> 
> there is a option "-X" (do not start daemons), which has a distribution
> specific bug, daemons are always started in debian/ubuntu, if you
> install the corresponding package (eg. salt-minion, salt-master).
> 
> My reason for this is, if you want a masterless setup, you do not want
> a machine trying to connect to a master at any time, so it would help
> to have a switch that prevent running (and optional installing) the
> minion as a daemon on all platforms in case of a masterless install.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/saltstack/salt-bootstrap/issues/389#issuecomment-43442727

I'm not saying your reason is not valid. I'm just saying that it's too specific for a generic script, and, as you pointed out, we're unable to not start daemons on Debian based distributions, so, I really can't see a way to solve this without specifically addressing Debian based systems.
Pedro Algarvio @ Phone

**Comment by s0undt3ch** [comment]
Closing as won't fix since this only target's ubuntu. We need to keep the script as generic as possible.
