### ISSUE TITLE
Start Daemons

### ISSUE THREAD

**Issue by s0undt3ch** [saltstack/salt-bootstrap#39]
I think we should have either an additional flag, or a function to start the installed daemons.

Some distributions start the daemons on their own, for example, Ubuntu. Others do not start their daemons, for example, RHEL/CentOS/Amazon Linux.

I'm in favor for having an optional function.

**Comment by s0undt3ch** [comment]
A function which is only called, if defined(of course), and if any of master, minion or syndic are to be installed.(#33)

**Comment by s0undt3ch** [comment]
Support for this is now in-place.

**Comment by ghost** [comment]
Hey, could you please add a special case for Ubuntu 10.04? The package system there tries to launch salt before everything is done and it terminates right away on a completely unbootstrapped (Lucid) system.  `lsb_release` can tell you the Ubuntu name, e.g.:

```
if [ `lsb_release -sc` = "Lucid" ]
    do foo ...
```

**Comment by s0undt3ch** [comment]
@seanchannel a new ticket please?
