### ISSUE TITLE
Allow *.conf files to work with -F

### ISSUE THREAD

**Issue by JasonSwindle** [saltstack/salt-bootstrap#392]
Howdy,

It would be really great if -F could understand *.conf files, and then place them in the correct master.d / minion.d dir. :)
- Jason Swindle

**Comment by s0undt3ch** [comment]
And with all the `.d` and `.conf` that salt supports, how do you suggest we support them all?
My only thought is to lay them in the temporary directory under the desired directory basenames.

Ie, `/tmp/.saltconf/minion.d/foo`, `/tmp/.saltconf/master.d/bar`...

Would this do it?

**Comment by JasonSwindle** [comment]
I would think that would work great......
