### ISSUE TITLE
salt-bootstrap fails on Solaris 10

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt-bootstrap#393]
Unable to install salt on Solaris 10 server using salt-bootstrap. Here's the output from my bootstrap run:

```
[nmadhok@csodev1:~]> curl --insecure -L http://bootstrap.saltstack.org -o install_salt.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  154k  100  154k    0     0    99k      0  0:00:01  0:00:01 --:--:--   99k
[nmadhok@csodev1:~]> sudo sh install_salt.sh git v2014.1.4
install_salt.sh: -o: bad option(s)
[nmadhok@csodev1:~]> 
```

```
[nmadhok@csodev1:~]> sudo bash install_salt.sh git v2014.1.4
eDir Password: 
 *  INFO: bash install_salt.sh -- Version 2014.04.16
sed: illegal option -- r

 *  INFO: System Information:
 *  INFO:   CPU:          
 *  INFO:   CPU Arch:     sun4u
 *  INFO:   OS Name:      SunOS
 *  INFO:   OS Version:   5.10
 *  INFO:   Distribution: Oracle Solaris 

 *  INFO: Installing minion
sed: illegal option -- r
awk: syntax error near line 1
awk: bailing out near line 1
awk: syntax error near line 1
awk: bailing out near line 1
awk: syntax error near line 1
awk: bailing out near line 1
awk: syntax error near line 1
awk: bailing out near line 1
awk: syntax error near line 1
awk: bailing out near line 1
awk: syntax error near line 1
awk: bailing out near line 1
 * ERROR: No dependencies installation function found. Exiting...
usage: ps [ -aAdeflcjLPyZ ] [ -o format ] [ -t termlist ]
        [ -u userlist ] [ -U userlist ] [ -G grouplist ]
        [ -p proclist ] [ -g pgrplist ] [ -s sidlist ] [ -z zonelist ]
  'format' is one or more of:
        user ruser group rgroup uid ruid gid rgid pid ppid pgid sid taskid ctid
        pri opri pcpu pmem vsz rss osz nice class time etime stime zone zoneid
        f s c lwp nlwp psr tty addr wchan fname comm args projid project pset
[nmadhok@csodev1:~]> 

```

By the way, my OS version is not 5.10 

```
[nmadhok@csodev1:~]> cat /etc/release 
                   Oracle Solaris 10 8/11 s10s_u10wos_17b SPARC
  Copyright (c) 1983, 2011, Oracle and/or its affiliates. All rights reserved.
                            Assembled 23 August 2011
```

**Comment by scentoni** [comment]
Solaris 10 corresponds to SunOS 5.10, actually; see the table at [http://en.wikipedia.org/wiki/Solaris_%28operating_system%29]. You're using update 10 (aka 8/11), while most of the servers I'm working on are update 9 (9/10):

```
$ cat /etc/release
                    Oracle Solaris 10 9/10 s10x_u9wos_14a X86
     Copyright (c) 2010, Oracle and/or its affiliates. All rights reserved.
                            Assembled 11 August 2010
```

**Comment by nmadhok** [comment]
@scentoni You are right. Thanks for pointing that out to me.

**Comment by scentoni** [comment]
No problem. I'm hopeful that with this ticket and https://github.com/saltstack/salt/issues/12323, we can help the devs make current versions of Salt able to install on Solaris in an easy way soon, whether from OpenCSW packages (preferably) or pip or the bootstrap script.

**Comment by nmadhok** [comment]
@scentoni I hope so too.

**Comment by nmadhok** [comment]
@basepi Has no one been assigned to this issue yet?

**Comment by s0undt3ch** [comment]
On 18 de Maio de 2014 21:20:14 WEST, Nitin Madhok notifications@github.com wrote:

> Has no one been assigned to this issue yet? What's the progress so far?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/saltstack/salt-bootstrap/issues/393#issuecomment-43450415

No one assigned and if no patch comes in, I'll eventually work on it... (which might mean today or somewhere in the future).
Pedro Algarvio @ Phone

**Comment by nmadhok** [comment]
Any progress on this @s0undt3ch ?

**Comment by nmadhok** [comment]
ping @s0undt3ch

**Comment by s0undt3ch** [comment]
Still haven't had the time to get to this issue, sorry.

**Comment by mikepietruszka** [comment]
Hello, has anyone had a chance to look at this issue?

**Comment by tjyang** [comment]
For my understanding Solaris SVR4 pkg is supported in Salt Enterprise version. 
Anyone here know open source and SVR4 packaging willing to create and maintain open source version of salt-minion for Solaris 9/10/11 ?

**Comment by davep75** [comment]
Has anyone successfully installed a Solaris 10 minion and got it working in the open source version of salt ?

**Comment by mikepietruszka** [comment]
I did but it kept dying due to old zeromq version (2.2). I had to install it via PIP. You will need to install OpenCSW and these packages via OpenCSW's pkgutil.

``` bash
python27
py_pi
py_pyzmq
py_crypto
py_m2crypto
```

This should let you install salt with PIP. From there, you will need to create manifest files for SMF (if you choose so).

**Comment by tjyang** [comment]
@marccardinal , thanks for the pointer. Here is my exact CSW pkgutil and pip command. This is on a solars 10 x86.

```
pkgutil -i gcc5g++ python27_dev  libzmq1_dev python27 py_pip py_pyzmq py_crypto py_m2crypto
pip install salt --upgrade
```

@marccardinal , what version of salt-minion you compile successfully using pip ? Right Now, pip is pulling down 6.3.2 which require ZMQ > 3.2 while csw solaris 10 x86 only has zmq 2.2

See error log below

```
   /opt/csw/bin/gcc-5.2 -m32 build/temp.solaris-2.10-i86pc.32bit-2.7/scratch/vers.o -lzmq -o build/temp.solaris-2.10-i86pc.32bit-2.7/scratch/vers
        ZMQ version detected: 2.2.0

    Bad libzmq version: Detected ZMQ version: 2.2.0, but require ZMQ >= 3.2
        Explicitly allow legacy zmq by specifying `--zmq=/zmq/prefix`

    Failed with default libzmq, trying again with /usr/local
    {'libraries': ['zmq'], 'extra_link_args': ['-m32'], 'runtime_library_dirs': [], 'library_dirs': ['/usr/local/lib'], 'include_dirs': ['/usr/local/i                nclude']}
    ************************************************
    Configure: Autodetecting ZMQ settings...
        Custom ZMQ dir:       /usr/local
    /opt/csw/bin/gcc-5.2 -O2 -pipe -m32 -march=pentiumpro -std=gnu89 -fno-strict-aliasing -O2 -pipe -m32 -march=pentiumpro -std=gnu89 -DNDEBUG -g -fwr                apv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -Izmq/utils -Izmq/backend/cython -Izmq/devices -c build/temp.solaris-2.10-i86pc.32bit-2.7                /scratch/vers.c -o build/temp.solaris-2.10-i86pc.32bit-2.7/scratch/vers.o
    /opt/csw/bin/gcc-5.2 -m32 build/temp.solaris-2.10-i86pc.32bit-2.7/scratch/vers.o -L/usr/local/lib -Wl,-R/usr/local/lib -lzmq -o build/temp.solaris                -2.10-i86pc.32bit-2.7/scratch/vers
        ZMQ version detected: 2.2.0


```

**Comment by The-Loeki** [comment]
We're deploying recent versions of `salt` on Solaris 10 using the following scripty:

```
pkgadd -d http://get.opencsw.org/now
/opt/csw/bin/pkgutil -i -y python27 py_pip libssl1_0_0 libsodium13 gcc5core python27_dev libgcc_s1 gcc5g++ gcc5objc libgccpp1 cacertificates openldap_dev sasl_dev sasl
ln -s /opt/csw/lib/libcrypto.so.1.0.0 /lib/libcrypto.so

#export V=99
export CC=gcc
export PATH=$PATH:/opt/csw/bin
/opt/csw/bin/pip -vvv install pyzmq --global-option="fetch_libzmq" --install-option="--zmq=bundled" || exit 1
/opt/csw/bin/pip -vvv install --global-option=build_ext --global-option="-I/opt/csw/include" python-ldap
/opt/csw/bin/pip install --upgrade salt raet || exit 1
```

**Comment by mikepietruszka** [comment]
@The-Loeki what version of ZeroMQ does that come with?

**Comment by The-Loeki** [comment]
2.2.0 (?): https://www.opencsw.org/get-it/packages/

But IIRC those options I specified were specifically meant to download, compile & use ZMQ from source rather than the packaged one.

**Comment by eradman** [comment]
At this point Solaris 11 was release 7 years ago... I don't think anyone is installing Solaris 10 any more. Okay to close?

**Comment by mikepietruszka** [comment]
@eradman At this point I don't touch anything Solaris related and SaltStack offers installation packages for Enterprise customers. Judging by how quiet this issue is, it seems like this affects very little amount of folks. I would say that it's OK to close this.

**Comment by The-Loeki** [comment]
While we actually still run Solaris 10 in some production (this is an 'enterprise' OS, folks ;) ) I consider my posted 'workaround' or salt-ssh good enough as-is.
Just make sure it's closed as 'rejected' or sumtin'

**Comment by rallytime** [comment]
Yes, I am going to close this as it is not something we will be adding to bootstrap. Thank you for posting the work-around @The-Loeki and for answering those questions. :)
