### ISSUE TITLE
salt-bootstrap does not support Windows guests

### ISSUE THREAD

**Issue by marnovdm** [saltstack/salt-bootstrap#395]
Now that Vagrant supports Windows guests I've been testing the Salt minion on Windows. I've created the following pull request for the Vagrant project which includes a very basic Salt bootstrap script in Powershell: https://github.com/mitchellh/vagrant/pull/3825/files

Is this something the salt-bootstrap project would like to include (and probably greatly improve on) or is salt-bootstrap only meant for Linux deployments?

**Comment by s0undt3ch** [comment]
Sorry @marnovdm for the slow response.

It would be very cool to additionally host a windows powershell script which automated the installation process!!!

Would you be able to maintain it? I can try to take care of small issues that we find in the future but I've never powershell'ed before :smile:

**Comment by techhat** [comment]
+1 on this, @marnovdm! I would love to see this get into Salt Cloud too, in (or instead of) `salt.utils.cloud.deploy_windows()`.

**Comment by marnovdm** [comment]
@s0undt3ch no problem, I've been busy with other things as well. To be honest I'm not really a Windows/Powershell guy either, this is my first Powershell script, was hoping other people could improve it :) Just wanted to get this working so I don't have to manually deploy Windows VMs anymore. 

I've just started playing with salt-cloud as well, once the vSphere provider is supported (Helium I believe) in salt-cloud I could try to integrate this in salt cloud and create a pull reqeust, however I feel like someone more experienced with Powershell would probably do a much better job. Thoughts?

**Comment by s0undt3ch** [comment]
Well, if it's in a working condition, make a PR against the bootstrap script repo, others might pick up on it and develop it even further, hopefully :smile:

**Comment by marnovdm** [comment]
It's definitely in working condition with Vagrant and has been merged, will be released in 1.6.3. I would prepare a pull request for salt-bootstrap as well but don't have a provider supporting Windows in salt-cloud untill the vSphere provider is released for it.

**Comment by s0undt3ch** [comment]
On 27 de Maio de 2014 16:06:20 WEST, Marno notifications@github.com wrote:

> It's definitely in working condition with Vagrant and has been merged,
> will be released in 1.6.3. I would prepare a pull request for
> salt-bootstrap as well but don't have a provider supporting Windows in
> salt-cloud untill the vSphere providers is released for it.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/saltstack/salt-bootstrap/issues/395#issuecomment-44288685

Let's leave this open until fulfilled.
Pedro Algarvio @ Phone

**Comment by UtahDave** [comment]
@marnovdm this is great!

@s0undt3ch, my first thought is that we should host this as a separate file. Maybe at winbootstrap.saltstack.org

Unless you have an idea on how to integrate this windows deploy with the *nix bootstrap shell script, I think there are just too many differences to easily combine the two.

What do you think?

**Comment by s0undt3ch** [comment]
@UtahDave it needs to be a separate file, I can't see it happening any other way.

**Comment by s0undt3ch** [comment]
Upon conversation with @UtahDave we agreed that a new repository for this windows bootstrap script is the best choice.
We'll leave this open until you say your ready and we'll create a repository for the script.

How does this sound to you?

**Comment by marnovdm** [comment]
That sounds great, I'll get back to you when I can test this with salt-cloud & start preparing a PR!

**Comment by s0undt3ch** [comment]
On 28 de Maio de 2014 7:28:41 WEST, Marno notifications@github.com wrote:

> That sounds great, I'll get back to you when I can test this with
> salt-cloud & start preparing a PR!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/saltstack/salt-bootstrap/issues/395#issuecomment-44370116

Awesome!
Pedro Algarvio @ Phone

**Comment by radiumx3** [comment]
@marnovdm @s0undt3ch   Any ETA ?

**Comment by marnovdm** [comment]
@radiumx3 I think some of my colleagues are still using the salt bootstrap support for Windows which got merged some time ago, but we haven't developed it any further because we currently only deploy *nix servers (yay!). I don't use Windows in my spare time either so this has kind of lost my attention... sorry for not giving you guys an update on this!

**Comment by PatOShea** [comment]
Does this new windows repo exist now @s0undt3ch @UtahDave?  It seems salt-windows-bootstrap is more for a development environment. Is that accurate?  I've updated the windows salt bootstrap script for vagrant and I thought updating some more would enable it to be used independently. I'd like to see the windows bootstrapper script in a salt repo that vagrant can reference. It's already done like that for the linux side. Thoughts?

**Comment by UtahDave** [comment]
closed by https://github.com/saltstack/salt-bootstrap/pull/618 

We might consider a url like we do for the *nix bootstrap script.
