### ISSUE TITLE
Add support for http proxy

### ISSUE THREAD

**Issue by ghost** [saltstack/salt-bootstrap#397]
When bootstrapping an instance in a private aws VPC, the script fails running the first apt-get update, because the instance has no public IP and it is not behind NAT.
It would be nice to have an option to set an http/ftp proxy to the package manager configuration.

**Comment by s0undt3ch** [comment]
And you can't set that as an environment variable prior to running the script?

**Comment by ghost** [comment]
salt-bootstrap is triggered by salt-cloud, after the VM is created.
The only available way to access one of those VMs is SSH with the private key used by salt-cloud during provisioning, which is kind of a manual process - that's why it would be nice for salt-bootstrap to do that. If setting the apt proxy is too distro-specific, even just exporting the right environment variable should be fine - but IMHO this should be handled.

**Comment by giannello** [comment]
("ghost" is my other, obsolete, account)
