### ISSUE TITLE
curl not getting the bootstrap script from http://bootstrap.saltstack.org

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt-bootstrap#398]
After reading from https://github.com/saltstack/salt-bootstrap#examples I tried to install Salt by doing the following:

```
curl -L http://bootstrap.saltstack.org -o install_salt.sh
sudo sh install_salt.sh git develop
```

I get an error as follows:

```
[root@salt-mom ~]# curl -L http://bootstrap.saltstack.org -o install_salt.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
113   226  113   226    0     0    516      0 --:--:-- --:--:-- --:--:--   516
[root@salt-mom ~]# sudo sh install_salt.sh git develop
install_salt.sh: line 1: syntax error near unexpected token `newline'
install_salt.sh: line 1: `<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">'
[root@salt-mom ~]# 
```

Here's how the file `install_salt.sh` looks like:

```
[root@salt-mom ~]# cat install_salt.sh
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>
```

I next opened `http://bootstrap.saltstack.org` which i use in my curl command and it redirected me to `https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh` so i used `https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh` instead to curl and it was successful.

Here's what works:

```
curl -L https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh -o install_salt.sh
sudo sh install_salt.sh git develop
```

For some reason, curl isn't getting the redirected page and hence failing the installation. Please look into it.

**Comment by s0undt3ch** [comment]
Thank you for the report.

This is a known issue and we've been "deprecating" the http(s)://bootstrap.saltstack.org url usage. In fact, I though I had removed all the references to it(I'll be removing them right after).

**Comment by nmadhok** [comment]
No problem @s0undt3ch! Just wanted to report the issue so that users don't face any problems when using the bootstrap installation :)

**Comment by s0undt3ch** [comment]
There! Doc fixed.

Again, Thanks @nmadhok!

**Comment by nmadhok** [comment]
Perfect! Glad to help! :+1:
