### ISSUE TITLE
Duplicate import warning

### ISSUE THREAD

**Issue by dlip** [saltstack/salt-bootstrap#400]
Installed on CentOS 6.5 with command:

```
curl -L https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh | sudo sh -s -- git develop
```

Running salt-minion or salt command gives the following warning:

```
# salt --versions-report
/usr/lib64/python2.6/site-packages/jinja2/__init__.py:31: UserWarning: Module backports was already imported from /usr/lib64/python2.6/site-packages/backports/__init__.pyc, but /usr/lib/python2.6/site-packages is being added to sys.path
  __version__ = __import__('pkg_resources') \
           Salt: 2014.1.0-7279-g8ff91a9
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
         PyYAML: 3.10
          PyZMQ: 2.2.0.1
            ZMQ: 3.2.4
```

**Comment by RickieL** [comment]
I guess you used two method to install jinja2 or salt.  both system method and python method.

my suggestion is to uninstall jinja2 and salt  with the both method.
yum remove python-jinja2 salt salt-master salt-minion
pip uninstall Jinja
pip uninstall salt

then
yum install salt salt-master salt-minion

**Comment by s0undt3ch** [comment]
This is unrelated to the bootstrap script. Closing.
Please reopen if you have any more information.
