### ISSUE TITLE
Add support for RHEL7

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt-bootstrap#403]
Found this:

```
install_red_hat_enterprise_linux_7_stable_deps() {
    echoerror "Stable version is not available on RHEL 7 Beta/RC. Please set installation type to git."
    return 1
}
```

See this: https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L2562
Packages are at: http://dl.fedoraproject.org/pub/epel/beta/7/x86_64/

**Comment by dmick** [comment]
Is anyone in-progress on this?   I need it, so can work on it if no one else is.

**Comment by s0undt3ch** [comment]
On 6 de Julho de 2014 2:24:15 WEST, Dan Mick notifications@github.com wrote:

> Is anyone in-progress on this?   I need it, so can work on it if no one
> else is.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/saltstack/salt-bootstrap/issues/403#issuecomment-48100539

Have you tried?
What failed?
Pass -D to the script for extra logging.
Pedro Algarvio @ Phone

**Comment by dmick** [comment]
Yes, I've tried, and gotten the response that is mentioned above; I assumed it was fixed and went back to asking for "stable", but got the message again, so assumed stable had not yet received the fix.  Do you need me to investigate further, or wasn't it clear that I meant "in stable"?

**Comment by s0undt3ch** [comment]
We need tsflags which, apparently, is not available for CentOS7/RHEL7

**Comment by s0undt3ch** [comment]
This should now be supported. Of course, up to the point where you have your optionals repository subscription setup.

Try the script from develop `https://bootstrap.saltstack.com/develop`

Please reopen if it's still not possible to bootstrap RHEL 7

**Comment by dmick** [comment]
develop had been working when I first commented (or apparently working, at least...) it was stable that hadn't been working.  I did not investigate details as to why.  What fixed this?

**Comment by s0undt3ch** [comment]
@dmick I'm doin' what `tsflags` was supposed to do. Test for proper package installations, ie, a dry run. This way we can detect if jinja2, which is in the optionals repository, is available or not.
