### ISSUE TITLE
Add flag for raet support

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt-bootstrap#411]
This is a stub, I am going to try and do this when I have time.

But with raet supposed to be in beta/stablized for 2014.7rc1, we should have a flag to include installing raet at least via pip.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
anyone had a chance to look at this?

Thanks!

**Comment by gtmanfred** [comment]
Any possibility of getting any movement on this?

Thanks!

**Comment by cinterloper** [comment]
+1

**Comment by adubkov** [comment]
:+1:

**Comment by lsh-0** [comment]
+1
