### ISSUE TITLE
Sleep before and after restart daemons

### ISSUE THREAD

**Issue by zeezooz** [saltstack/salt-bootstrap#413]
I use vagrant to install master and minion together on Ubuntu 14.04 x64 and have 2 issues:
1. When salt bootstrapped with [sleep before restart](https://github.com/saltstack/salt-bootstrap/blob/stable/bootstrap-salt.sh#L4437), salt command (e.g. `salt salt test.ping`) often fails with `Failed to authenticate, is this user permitted to execute commands?` (or `Failed to authenticate!  This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error ocurred (check disk/inode usage).` in latest git version). Removing sleep helps, but this may be salt issue because version 2014.1.3 seems not affected. Also I have to start services in install_ubuntu_git_post() to test this with git install because git install start services only once in install_*_restart_daemons and so doesn't affected.
2. It seems that [3 seconds](https://github.com/saltstack/salt-bootstrap/blob/stable/bootstrap-salt.sh#L4449) isn't enough to start master. When I try to append grain immediately after bootstrap, first call fails with

```
[ERROR   ] The master failed to decrypt the random minion token
[CRITICAL] The Salt Master server's public key did not authenticate!
The master may need to be updated if it is a version of Salt lower than 2014.1.0-8541-g25c1174, or
If you are confident that you are connecting to a valid Salt Master, then remove the master public key and restart the Salt Minion.
The master public key can be found at:
/etc/salt/pki/minion/minion_master.pub
```

but next calls succeed. Waiting at least 12 seconds eliminates error.

Vagrantfile:

```
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "trusty"
  config.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box"
  config.vm.hostname = "salt"
  config.vm.provision :salt do |salt|
    salt.verbose = true
    salt.install_master = true
    salt.master_key = "salt/key/master.pem"
    salt.master_pub = "salt/key/master.pub"
    salt.minion_key = "salt/key/salt.pem"
    salt.minion_pub = "salt/key/salt.pub"
    salt.seed_master = {
      "salt" => "salt/key/salt.pub",
    }
  end
  config.vm.provision :shell, inline: "
    salt-call grains.append roles test1
    salt-call grains.append roles test2
  "
end
```

**Comment by s0undt3ch** [comment]
Could this be a vagrant issue? We spin quite a few ubuntu vms and never got hit by this....

Would a configurable sleep variable help here?
I really don't want to keep every other distro waiting because of ubuntu on vagrant...

**Comment by zeezooz** [comment]
It's not vagrant issue. I get same errors with just virtualbox and ubuntu (though not always).
I tried some other variants and it seems that troubles with upstart. When I change bootstrap script to use init instead of upstart, these errors are eliminated (but stopping of master service fails sometimes).

> We spin quite a few ubuntu vms and never got hit by this....

Do you use packages or git install? Git install only starts services (no restart) and so not affected by first issue. Maybe you run other commands after bootstrapping which give master time to start and don't encounter second issue. I added `salt salt test.ping` before `salt-call grains.append roles test1` and it gives enough time to append grains correctly.

Did you try to reproduce errors with the provided vagrantfile?

**Comment by zeezooz** [comment]
> Would a configurable sleep variable help here?
> I really don't want to keep every other distro waiting because of ubuntu on vagrant...

The second issue actually can be handled outside bootstrap.
What about delay before `install_*_restart_daemons`? Is it necessary? Could you remove it or move inside each function except for ubuntu?
