### ISSUE TITLE
add option for installing salt-api daemon scripts (new in helium)

### ISSUE THREAD

**Issue by dstokes** [saltstack/salt-bootstrap#415]
the `develop` branch in saltstack exposes a new `salt-api` service for accessing salt via a rest api. the init scripts for this service should be installable either by default when the `-M` flag is passed, or as an optional service. /cc @whiteinge

**Comment by s0undt3ch** [comment]
@whiteinge optional? or include them in master installations by default?

**Comment by whiteinge** [comment]
@s0undt3ch install on master by default.

**Comment by s0undt3ch** [comment]
Thanks. Will update script as soon as possible.
