### ISSUE TITLE
Take python-requests from jessie, or check if it is already installed

### ISSUE THREAD

**Issue by benallard** [saltstack/salt-bootstrap#424]
The bootstrap script is asking me to allow pip (-P), whereas it could simply install python-requests from debian jessie (my current distribution).

Even after having installed in manually, it still ask that I enable pip ... That's quite annoying ...

**Comment by s0undt3ch** [comment]
On 3 de Julho de 2014 15:35:20 WEST, "Benoît Allard" notifications@github.com wrote:

> The bootstrap script is asking me to allow pip (-P), whereas it could
> simply install python-requests from debian jessie (my current
> distribution).
> 
> Even after having installed in manually, it still ask that I enable pip
> ... That's quite annoying ...
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/saltstack/salt-bootstrap/issues/424

Thank you. We'll get this fixed.
Pedro Algarvio @ Phone
