### ISSUE TITLE
Old bootstrap for chosen for CentOS 7 cloud deployment

### ISSUE THREAD

**Issue by jeteokeeffe** [saltstack/salt-bootstrap#425]
I'm using CentOS 7 master to deploy a new CentOS 7 cloud instance to digital ocean. Unfortunately, it seems to choosing an older version of the bootstrap to kick off the installation of the salt minion. 

Old version its using

```
__ScriptVersion="2014.04.16"
__ScriptName="bootstrap-salt.sh"
```

When I need to be using this version

```
__ScriptVersion="2014.06.30"
__ScriptName="bootstrap-salt.sh"
```

How does salt choose what bootstrap to use? Does it fetch it from salt's site or is this supplied by the salt package (scp'd or something like that)?

**Comment by gtmanfred** [comment]
To grab the newest one, salt-cloud -u

**Comment by jeteokeeffe** [comment]
Thanks, that got me one step further and installed the salt minion.

Now its erroring on starting the minion.

```
Complete!
 *  INFO: Running install_centos_stable_post()
 *  INFO: Running install_centos_check_services()
 *  INFO: Running install_centos_restart_daemons()
 *  INFO: Running daemons_running()
 * ERROR: salt-minion was not found running
 * ERROR: Failed to run daemons_running()!!!
 * ERROR: salt-minion was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
```

**Comment by jeteokeeffe** [comment]
seems the problem is centos 7 is using init instead of systemd (like fedora).

**Comment by s0undt3ch** [comment]
@jeteokeeffe it's the other way around. Cent 7 **defaults** to systemd

**Comment by s0undt3ch** [comment]
Will be fixed in develop shortly and will be released on the stable in a few days

**Comment by jeteokeeffe** [comment]
@s0undt3ch I was talking about salt bootstrap (using init for the CentOS functions). I also provided a commit for centos restart and service check functions that safely check and use systemd. I might of missed a few other functions but its allowing me to kick off successful cloud instances for digitial ocean (centos 6 and 7).

**Comment by s0undt3ch** [comment]
Ah! Then yes!

And yes, you just missed one step which I've taken care of. Thanks!
