### ISSUE TITLE
Bootstrap on Amazon Linux fails on dependencie rpmlib

### ISSUE THREAD

**Issue by jacksoncage** [saltstack/salt-bootstrap#426]
Bootstrap on Amazon Linux fails on dependencie rpmlib.

```
[root@ip-10-0-0-77 ~]# curl -L https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh -o install_salt.sh; sh install_salt.sh -A salt.bloglovin.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  163k  100  163k    0     0   654k      0 --:--:-- --:--:-- --:--:-- 2065k
 *  INFO: PIPED THROUGH install_salt.sh -- Version 2014.06.30

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     i686
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   2.6.34.7-56.40.amzn1.i686
 *  INFO:   Distribution: Amazon Linux AMI 2010.11

 *  INFO: Installing minion
 *  INFO: Found function install_amazon_linux_ami_deps
 *  INFO: Found function install_amazon_linux_ami_stable
 *  INFO: Found function install_amazon_linux_ami_stable_post
 *  INFO: Found function install_amazon_linux_ami_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Running install_amazon_linux_ami_deps()
warning: /var/tmp/rpm-tmp.01w7lf: Header V3 RSA/SHA256 Signature, key ID 0608b895: NOKEY
error: Failed dependencies:
    rpmlib(PayloadIsXz) <= 5.2-1 is needed by epel-release-6-8.noarch
Retrieving http://mirrors.kernel.org/fedora-epel/6/i386/epel-release-6-8.noarch.rpm
 * ERROR: Failed to run install_amazon_linux_ami_deps()!!!
```

**Comment by s0undt3ch** [comment]
On July 14, 2014 12:10:48 PM GMT+01:00, Love Nyberg notifications@github.com wrote:

> Bootstrap on Amazon Linux fails on dependencie rpmlib.
> 
> ```
> [root@ip-10-0-0-77 ~]# curl -L
> https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh
> -o install_salt.sh; sh install_salt.sh -A salt.bloglovin.com
> % Total    % Received % Xferd  Average Speed   Time    Time     Time 
> Current
>                           Dload  Upload   Total   Spent    Left  Speed
> 100  163k  100  163k    0     0   654k      0 --:--:-- --:--:--
> --:--:-- 2065k
> *  INFO: PIPED THROUGH install_salt.sh -- Version 2014.06.30
> 
> *  INFO: System Information:
> *  INFO:   CPU:          GenuineIntel
> *  INFO:   CPU Arch:     i686
> *  INFO:   OS Name:      Linux
> *  INFO:   OS Version:   2.6.34.7-56.40.amzn1.i686
> *  INFO:   Distribution: Amazon Linux AMI 2010.11
> 
> *  INFO: Installing minion
> *  INFO: Found function install_amazon_linux_ami_deps
> *  INFO: Found function install_amazon_linux_ami_stable
> *  INFO: Found function install_amazon_linux_ami_stable_post
> *  INFO: Found function install_amazon_linux_ami_restart_daemons
> *  INFO: Found function daemons_running
> *  INFO: Running install_amazon_linux_ami_deps()
> warning: /var/tmp/rpm-tmp.01w7lf: Header V3 RSA/SHA256 Signature, key
> ID 0608b895: NOKEY
> error: Failed dependencies:
>   rpmlib(PayloadIsXz) <= 5.2-1 is needed by epel-release-6-8.noarch
> Retrieving
> http://mirrors.kernel.org/fedora-epel/6/i386/epel-release-6-8.noarch.rpm
> * ERROR: Failed to run install_amazon_linux_ami_deps()!!!
> ```
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/saltstack/salt-bootstrap/issues/426

Got the AMI if the VM which failed to help us reproduce this?

Thanks for reporting, we'll look into this.
Pedro Algarvio @ Phone

**Comment by jacksoncage** [comment]
Sure, it's the default NAT ami: ami-vpc-nat-1.0.0-beta.i386-ebs (ami-095b6c7d)

**Comment by s0undt3ch** [comment]
The problem here is that this image is too old, Amazon Linux AMI 2010.xx, and not supported.

We will now show a better error message telling to try a more recent image.

For example:
- amzn-ami-vpc-nat-pv-2013.03.1.x86_64-ebs (ami-ed352799)
-  amzn-ami-vpc-nat-pv-2013.09.1.x86_64-ebs (ami-f3e30084)

**Comment by jacksoncage** [comment]
Thanks @s0undt3ch! Great to have it exit with a better error code. Worked when I switched to newer image.

The bad thing is that `ami-vpc-nat-1.0.0-beta.i386-ebs` is still AWS standard image for NAT in a VPC in eu-west region.

**Comment by s0undt3ch** [comment]
eu-east is Ireland(on the web UI) right?

hmmm, a more recent image showed up in the search results when I had Ireland selected. Maybe we get results from other areas too?

Anyway. That image is way too old. Maybe a request to amazon to update that default image?

**Comment by jacksoncage** [comment]
Yep, when creating via the wizard in EC2 UI. I've added a [forum issue](https://forums.aws.amazon.com/thread.jspa?threadID=156946) to AWS.
