### ISSUE TITLE
Error installing on OpenSuse 12.2

### ISSUE THREAD

**Issue by annabzz** [saltstack/salt-bootstrap#430]
Hi, I'm trying to install Salt on OpenSuse 12.2 with bootstrap and I get the following error:

wget -O install_salt.sh https://bootstrap.saltstack.com
sudo sh install_salt.sh
-  INFO: sh install_salt.sh -- Version 2014.06.30
-  INFO: System Information:
-  INFO:   CPU:          AuthenticAMD
-  INFO:   CPU Arch:     x86_64
-  INFO:   OS Name:      Linux
-  INFO:   OS Version:   3.4.33-2.24-desktop
-  INFO:   Distribution: suse 12.2
-  INFO: Installing minion
-  INFO: Found function daemons_running
-  INFO: Found function install_suse_check_services
- ERROR: No dependencies installation function found. Exiting...

**Comment by s0undt3ch** [comment]
@annabzz Is this openSUSE? not SuSE?

Is this system from a cloud provider? An ISO?

**Comment by s0undt3ch** [comment]
Also, what's the output of the following commands:

```
sudo find /etc/ -name '*-release' -print -exec cat {} \;
```

```
which lsb_release && lsb_release -a
```

**Comment by annabzz** [comment]
The output of the commands you requested is:

sudo find /etc/ -name '*-release' -print -exec cat {} \;
/etc/java/jpackage-release
JPackage release 1.7 (openSUSE 12.2) for %{buildarch}
/etc/SuSE-release
openSUSE 12.2 (x86_64)
VERSION = 12.2
CODENAME = Mantis
/etc/os-release
NAME=openSUSE
VERSION="12.2 (Mantis)"
VERSION_ID="12.2"
PRETTY_NAME="openSUSE 12.2 (Mantis) (x86_64)"
ID=opensuse
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:opensuse:12.2"

which lsb_release && lsb_release -a
/usr/bin/lsb_release
LSB Version:    n/a
Distributor ID: SUSE LINUX
Description:    openSUSE 12.2 (x86_64)
Release:        12.2
Codename:       Mantis

I hope this helps! Just ask if you need something else.

**Comment by s0undt3ch** [comment]
Since we're at it :smile: 

```
sh -x bootstrap-script-sh -D
```

You can use https://gist.github.com/ since that content is way longer.

Thanks!

**Comment by annabzz** [comment]
I don't know if I did the right way, but this is what I got:
https://gist.github.com/annabzz/dfc4bcf88704bdd6c24c

**Comment by s0undt3ch** [comment]
On July 22, 2014 10:22:34 AM GMT+01:00, Anna notifications@github.com wrote:

> I don't know if I did the right way, but this is what I got:
> https://gist.github.com/annabzz/dfc4bcf88704bdd6c24c
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/saltstack/salt-bootstrap/issues/430#issuecomment-49716162

Yep! That's exactly what I was after.

Thanks! It will now be much simpler to get this fixed.
Pedro Algarvio @ Phone

**Comment by annabzz** [comment]
You're welcome!
But not so fast, it may be our system's fault. Sorry if that's the case. :)

**Comment by s0undt3ch** [comment]
The issue is that lsb_release says this system is SUSE and not openSUSE. we must add some additional checks to separate both of them.

If lsb_release was not available, the system would be properly detected.
