### ISSUE TITLE
Bootstrapping SLES 11 SP3

### ISSUE THREAD

**Issue by dakleine** [saltstack/salt-bootstrap#431]
Please support SLES 11 SP3. Just say a word if can help you with testing or sending you logs. I ran the following commands for additional information for you:

find /etc/ -name '*-release' -print -exec cat {} \;

/etc/SuSE-release
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 3

which lsb_release && lsb_release -a

which: no lsb_release in (/home/dakleine/bin:/usr/local/bin:/usr/bin:/bin:/usr/X11R6/bin:/usr/games:/usr/lib/mit/bin:/usr/lib/mit/sbin)

**Comment by s0undt3ch** [comment]
What does not work?

What's the output of:

```
sh bootstrap-salt.sh -P -D
```

**Comment by dakleine** [comment]
After
`curl -L https://bootstrap.saltstack.com | sudo sh -s -- git develop`
i got

```
Reading installed packages...
''python-M2Crypto>=0.21'' not found in package names. Trying capabilities.
No provider of ''python-M2Crypto >= 0.21'' found.
'python-pycrypto' is already installed.
No update candidate for 'python-pycrypto-2.6.1-35.1.x86_64'. The highest available version is already     installed.
'libzmq3' is already installed.
No update candidate for 'libzmq3-4.0.4-36.1.x86_64'. The highest available version is already installed.
 * ERROR: Failed to run install_suse_11_git_deps()!!!
```

I have python-M2Crypto Version 0.22.3 and it is already installed.

**Comment by s0undt3ch** [comment]
Try the develop version instead which should be fixed...

```
curl -L https://bootstrap.saltstack.com/develop | sudo sh -s -- git develop
```
