### ISSUE TITLE
Limit depth and breadth of git clones

### ISSUE THREAD

**Issue by cachedout** [saltstack/salt-bootstrap#435]
In some cases, specifically in VMs used for testing, it often takes a long time (5-10 minutes) to simply clone the Salt repo. It may be possible to significantly reduce the amount of time needed to clone a specific version of Salt, especially when the user doesn't need access to previous commits.

As of (at least) git 1.7.12.4 we should have access to the following flags, which could be combined to target a particular salt revision and limit the clone to only the a single point in time without any past history:

`--depth 1`
`--branch <salt_version>`

cc: @whiteinge for comments.

**Comment by whiteinge** [comment]
The above looks like a good implementation (with fallback). I don't know how far back those flags are supported offhand.

Question though: if we don't need the history could we just grab the tarball for that SHA instead? That would be even less overhead.

**Comment by s0undt3ch** [comment]
We need a gitt version higher than 1.7.10

**Comment by whiteinge** [comment]
Also tested successfully on 1.7.1 (Cent 6.)

**Comment by whiteinge** [comment]
The GitHub-supplied tarball approach in my question won't have the `git describe` information we need to do the install. I don't see a way to get that from GitHub. This shallow clone approach has the same problem.

**Comment by s0undt3ch** [comment]
@whiteinge we fetch tags afterwards. Still a problem?

**Comment by whiteinge** [comment]
Hm. Actually, that may work. Having an incomplete history will mess with `git describe` unless you get all the requisite history for wherever you run it from. Might take a little experimenting to get right.
