### ISSUE TITLE
bootstrap fails at attempt to restart salt-api

### ISSUE THREAD

**Issue by thenewwazoo** [saltstack/salt-bootstrap#450]
The following bootstrap...

```
 *  INFO:  sh -- Version 2014.07.29

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.8.0-44-generic
 *  INFO:   Distribution: Ubuntu 12.04
```

Fails with the following error:

```
(lots and lots of copying and compilation elided)
running install_egg_info
Writing /usr/lib/python2.7/dist-packages/salt-2014.7.0_n_a_ed2b459.egg-info
 *  INFO: Running install_ubuntu_git_post()
 *  WARN: Upstart does not appear to know about salt-minion
 *  WARN: Upstart does not appear to know about salt-master
 *  WARN: Upstart does not appear to know about salt-api
 *  INFO: Running install_ubuntu_check_services()
 *  INFO: Running install_ubuntu_restart_daemons()
salt-minion start/running, process 4479
salt-master start/running, process 4484
salt-api start/running, process 4491
 *  INFO: Running daemons_running()
 * ERROR: salt-api was not found running
 * ERROR: Failed to run daemons_running()!!!
 * ERROR: salt-minion was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
 * ERROR: salt-master was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
 * ERROR: salt-api was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
```

**Comment by thenewwazoo** [comment]
This installation is using the vagrant salt provisioner with install_type="git" and install_args="v2014.7.0rc1".

**Comment by thenewwazoo** [comment]
Vagrant's salt-provisioner passes the following arguments to the salt-bootstrap.sh script:

```
-F -c /tmp -k /tmp/minion-seed-keys -M git v2014.7.0rc1
```

The failure can be reproduced by running:

```
curl -L https://bootstrap.saltstack.com/develop | sudo sh -s -- -F -c /tmp -M git v2014.7.0rc1
```

or

```
curl -L https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh | sudo sh -s -- -F -c /tmp -M git v2014.7.0rc1
```

**Comment by audreyfeldroy** [comment]
I'm getting the same error with this bootstrap:
-  INFO: sh install_salt.sh -- Version 2014.08.23
-  WARN: Running the unstable version of bootstrap-salt.sh
-  INFO: System Information:
-  INFO:   CPU:          GenuineIntel
-  INFO:   CPU Arch:     i686
-  INFO:   OS Name:      Linux
-  INFO:   OS Version:   3.13.0-32-generic
-  INFO:   Distribution: Ubuntu 14.04

And with this one too:
-  INFO: sh install_salt.sh -- Version 2014.08.23
-  INFO: System Information:
-  INFO:   CPU:          GenuineIntel
-  INFO:   CPU Arch:     x86_64
-  INFO:   OS Name:      Linux
-  INFO:   OS Version:   3.13.0-32-generic
-  INFO:   Distribution: Ubuntu 12.04

**Comment by s0undt3ch** [comment]
Can you please try with the latest develop version?

**Comment by audreyfeldroy** [comment]
I just tried again and got the same error.

The commands I used to attempt to set up a salt-master:

```
curl -o install_salt.sh -L https://bootstrap.saltstack.com
sudo sh install_salt.sh -M -N git develop
```

This was on a fresh DigitalOcean droplet:
-  INFO: sh install_salt.sh -- Version 2014.08.30
-  INFO: System Information:
-  INFO:   CPU:          GenuineIntel
-  INFO:   CPU Arch:     x86_64
-  INFO:   OS Name:      Linux
-  INFO:   OS Version:   3.13.0-32-generic
-  INFO:   Distribution: Ubuntu 12.04

If you need me to try anything else, I'm happy to help however I can.

**Comment by mattmb** [comment]
@s0undt3ch this was still failing my deployment as it was running daemons_running (maybe because i'm deploying a git tag)? See PR ^

**Comment by s0undt3ch** [comment]
@mattmb I've completed the salt-api checks skipping on the develop version of the script.

**Comment by tuminoid** [comment]
Got hit by this one too when bootstrapping Vagrant box with Salt:

```
Bootstrapping Salt... (this may take a while)
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/tmp/bootstrap_salt.sh  -F -c /tmp

Stdout from the command:

 *  INFO:  sh -- Version 2015.01.12

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.16.3-031603-lowlatency
 *  INFO:   Distribution: Ubuntu 14.04
```

==>

```
salt-minion start/running, process 3173
 *  INFO: Running daemons_running()
 * ERROR: salt-minion was not found running
 * ERROR: Failed to run daemons_running()!!!
 * ERROR: salt-minion was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
```
