### ISSUE TITLE
Allow pip install regardless of distro

### ISSUE THREAD

**Issue by jcockhren** [saltstack/salt-bootstrap#451]
For some scenarios, it's easier to manage salt upgrades via pip. This approach obvious clashes on distros like fedora and ubuntu where there exists salt packages in their mainstream repos which usually contain much older versions. 

See: https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L1688-L1696

Even though the `-P` option is set, for ubuntu the option isn't respected.

**Comment by s0undt3ch** [comment]
The `-P` flag was never intended to do totally `pip` based installation. It's intended use is to provide packages which are not available on some distros, or, to use a more recent version of said packages. Never all the packages.

**Comment by mayuroks** [comment]
I agree pip would be more suitable than apt-get or yum or pacman. I have a Centos 6 server with python 2.6 on it. I manually installed python2.7 and pip2.7 but as soon as I ran bootstrap minion script, it installed python2.6 packages

**Comment by jfindlay** [comment]
Support for this was added for ubuntu with #666, which also added a base mechanism that other distros could use for pip (and virtualenv) installs.
