### ISSUE TITLE
Current salt-bootstrap won't install salt on arch?

### ISSUE THREAD

**Issue by cro** [saltstack/salt-bootstrap#457]
Greetings all,
See below--am I missing something?

```
curl https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh > bootsalt.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  177k  100  177k    0     0   519k      0 --:--:-- --:--:-- --:--:--  520k
[root@vultarch ~]# sh bootsalt.sh git develop
 *  INFO: sh bootsalt.sh -- Version 2014.08.30

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.16.1-1-ARCH
 *  INFO:   Distribution:

 *  INFO: Installing minion
 *  INFO: Found function daemons_running
 * ERROR: No dependencies installation function found. Exiting...
```

**Comment by s0undt3ch** [comment]
Hmm... This IS the latest version if the script and this issue should have been solved. Where is this Arch from? Rackspace?

**Comment by cro** [comment]
Excerpts from Pedro Algarvio's message of 2014-09-02 01:13:33 -0600:

> Hmm... This IS the latest version if the script and this issue should have been solved. Where is this Arch from? Rackspace?

It's an install direct from the Arch ISO.  I've been experimenting with the
VPSs at Vultr.com and they let you create a custom image from an ISO.

--cro

**Comment by s0undt3ch** [comment]
On the readme of the bootstrap scrip there's 2 bash lines which discover the available system information from where we detect the distro. Can you run those and paste the output please?

Or, if the system is already online I can get you my pub key to debug this later today.

**Comment by cro** [comment]
Excerpts from Pedro Algarvio's message of 2014-09-02 08:03:12 -0600:

> On the readme of the bootstrap scrip there's 2 bash lines which discover the available system information from where we detect the distro. Can you run those and paste the output please?

```
[cro@vultarch ~]$ sudo find /etc/ -name '*-release' -print -exec cat {} \;
[sudo] password for cro:
/etc/arch-release
/etc/os-release
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```

## 

C. R. Oldham, Platform Engineer  | cr@saltstack.com 
SaltStack, Inc.                  | http://saltstack.com

**Comment by s0undt3ch** [comment]
On September 2, 2014 3:32:35 PM GMT+01:00, "C. R. Oldham" notifications@github.com wrote:

> Excerpts from Pedro Algarvio's message of 2014-09-02 08:03:12 -0600:
> 
> > On the readme of the bootstrap scrip there's 2 bash lines which
> > discover the available system information from where we detect the
> > distro. Can you run those and paste the output please?
> 
> ```
> [cro@vultarch ~]$ sudo find /etc/ -name '*-release' -print -exec cat {}
> \;
> [sudo] password for cro:
> /etc/arch-release
> /etc/os-release
> NAME="Arch Linux"
> ID=arch
> PRETTY_NAME="Arch Linux"
> ANSI_COLOR="0;36"
> HOME_URL="https://www.archlinux.org/"
> SUPPORT_URL="https://bbs.archlinux.org/"
> BUG_REPORT_URL="https://bugs.archlinux.org/"
> ```
> 
> ## 
> 
> C. R. Oldham, Platform Engineer  | cr@saltstack.com 
> SaltStack, Inc.                  | http://saltstack.com
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/saltstack/salt-bootstrap/issues/457#issuecomment-54160041

And that system does not have a lsb_release binary?
Pedro Algarvio @ Phone

**Comment by cro** [comment]
Excerpts from Pedro Algarvio's message of 2014-09-02 09:50:49 -0600:

> On September 2, 2014 3:32:35 PM GMT+01:00, "C. R. Oldham" notifications@github.com wrote:
> 
> > Excerpts from Pedro Algarvio's message of 2014-09-02 08:03:12 -0600:
> > And that system does not have a lsb_release binary?

Not by default--you have to install it with

pacman -S lsb-release

and after installation it returns

```
[root@vultarch ~]# lsb_release
LSB Version:    1.4
```

--cro

**Comment by cro** [comment]
Excerpts from C. R. Oldham's message of 2014-09-02 10:22:10 -0600:

> Excerpts from Pedro Algarvio's message of 2014-09-02 09:50:49 -0600:
> 
> > On September 2, 2014 3:32:35 PM GMT+01:00, "C. R. Oldham" notifications@github.com wrote:
> > 
> > > Excerpts from Pedro Algarvio's message of 2014-09-02 08:03:12 -0600:
> > > And that system does not have a lsb_release binary?
> 
> Not by default--you have to install it with
> 
> pacman -S lsb-release

And just FYI I confirmed that I can install the 2014.7 release candidate with
the bootstrap script IF if first install the lsb-release package.

--cro

**Comment by bricewge** [comment]
Same issue here, inside VirtualBox. As @cro said, after installing `lsb-release` the bootstrap script run fine.

**Comment by s0undt3ch** [comment]
My problem here is that, we previously did not support lsb detection(which was recently added), so, your systems should have been properly detected. Need to dig into this issue...
