### ISSUE TITLE
Incorrect warning when supplying version

### ISSUE THREAD

**Issue by rbjorklin** [saltstack/salt-bootstrap#464]
When running: ./bootstrap-salt.sh git v2014.7

I incorrectly get this:
-  WARN: The git revision being installed does not match a Salt version tag. Shallow cloning disabled

My initial analysis is that the regexp match in function __check_unparsed_options is incorrect.

If nobody beats me too it I will try to fix this later this week.

**Comment by s0undt3ch** [comment]
Thanks for reporting this. It's now fixed in the develop version of the script.
