### ISSUE TITLE
error bootstrapping to RHEL on EC2 via salt-cloud

### ISSUE THREAD

**Issue by mike-ainsworth** [saltstack/salt-bootstrap#466]
when using salt-cloud with default salt-bootstrap on RHEL on AWS EC2 it throws the following error directly after the "INFO: Running install_red_hat_enterprise_git_deps"

"Unable to locate system id file"

"ERROR: Failed to find RHN optional repo, please enable it using the GUI or rhn-channel command."
"ERROR: Failed to run install_red_hat_enterprise_git_deps"

RHEL 6.  This may be a duplicate of issue 420, but re-opening because it is not fixed.

**Comment by polliard** [comment]
This is when using the Enterprise Master/Minion. Using the epel salt-minion/master works without issue.

**Comment by vutny** [comment]
@mike-ainsworth This looks outdated. I had no problems bootstrapping RHEL systems in EC2 with recent `develop` version.

**Comment by vutny** [comment]
@jfindlay I thinks this could be closed too and reopened if necessary.
