### ISSUE TITLE
error bootstraping centos7

### ISSUE THREAD

**Issue by Basti-W** [saltstack/salt-bootstrap#467]
i get the following error if i try to start a new Minion for saltstack
yesterday all was working perfect, but today it will not install git dependencies

curl: (22) The requested URL returned error: 404 Not Found\
error: skipping http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-1.noarch.rpm - transfer failed\
Retrieving http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-1.noarch.rpm\
- ERROR: Failed to run install_centos_git_deps()!!!\

it looks, that the problem is the update from epel-release-7.1 to 7.2

**Comment by s0undt3ch** [comment]
Thanks! I'll get this fixed today.

**Comment by s0undt3ch** [comment]
Fixed in today's stable release
