### ISSUE TITLE
Broken on the Amazon AMI

### ISSUE THREAD

**Issue by 303jim** [saltstack/salt-bootstrap#468]
Maybe a recent change to the AMI, around 9/24/2014:

NAME="Amazon Linux AMI"
VERSION="2014.09"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2014.09"
PRETTY_NAME="Amazon Linux AMI 2014.09"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2014.09:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

specifically: ID="amzn"

...doesn't seem friendly with the install script.
My shell scripting is phenomenally weak, but I was able to hack around it by adding:

amzn )
    n=“Amazon Linux AMI”
    v=$rv
    ;;

around line 777.

I'm not confident that the workaround is completely correct, but it worked in my case to bootstrap a minion. Looks like there's other ways to solve it too.

**Comment by s0undt3ch** [comment]
Thanks for the info! I'll get this fixed.

/cc @whiteinge

**Comment by whiteinge** [comment]
Thank you, sir.

**Comment by whiteinge** [comment]
TYVM!
