### ISSUE TITLE
bootstrap_salt.sh requires '-p python-gnupg' argument when using GPG renderer

### ISSUE THREAD

**Issue by blbradley** [saltstack/salt-bootstrap#470]
Since the GPG renderer is part of the salt codebase now, this package is required.

It's currently defined in [saltstack/salt/opt_requirements.txt](https://github.com/saltstack/salt/blob/7c3a1375c140988004988b4294d03da869d75a01/opt_requirements.txt) which suggest that it is an optional requirement. Is that the case?

**Comment by s0undt3ch** [comment]
It is an optional requirement, one which can be installed once salt is bootstrapped, ie, it's not a hard dependency, which is why the bootstrap script does not install it.

**Comment by blbradley** [comment]
Would it be a bad idea to update the bootstrap script so if the optional features are used (in an existing config supplied before bootstrapping) the corresponding package is installed?
