### ISSUE TITLE
Latest development version salt-minion does not seem to connect on CentOS5 x64

### ISSUE THREAD

**Issue by githubcdr** [saltstack/salt-bootstrap#471]
[DEBUG   ] Attempting to authenticate with the Salt Master at <<<>>>
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[INFO    ] SaltReqTimeoutError: after 60 seconds. (Try 1 of 7)
[INFO    ] SaltReqTimeoutError: after 60 seconds. (Try 2 of 7)

Using "tcpdump port 4505 or port 4506" shows no connections at all, a working client shows connections.

**Comment by s0undt3ch** [comment]
Se have our Jenkins tests server bootrapping CentOS 5 machines everyday so I'm kind of lost to the problem here.

Have you opened up your firewall for Salt's ports?

Can you also paste the output of salt-minion --versions-report?

I assume the bootstrapping process finished without issues right?

**Comment by githubcdr** [comment]
I will investigate further, but firewalling was not the issue since other minions could connect. The bootstrap script finished without issues. What worries me is that no connection at all was made, I even removed the key from the master to see if it would appear, but nope.

**Comment by s0undt3ch** [comment]
Are the other systems Aldo CentOS5?

**Comment by s0undt3ch** [comment]
*also

... Dam Phone...

**Comment by githubcdr** [comment]
Both systems are CentOS, the master is 6.5 client is 5.10.

salt-master;

[root@salt tmp ]# salt --versions-report
           Salt: 2014.7.0rc2-2589-g188fd6c
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed

salt-minion;

This is on CentOS 5.10 x64

[root@ldap tmp ]# salt --versions-report
           Salt: 2014.7.0-n/a-188fd6c
         Python: 2.6.8 (unknown, Nov  7 2012, 14:47:45)
         Jinja2: 2.5.5
       M2Crypto: 0.21.1
 msgpack-python: 0.1.12
   msgpack-pure: Not Installed
       pycrypto: 2.3
        libnacl: Not Installed
         PyYAML: 3.08
          ioflo: Not Installed
          PyZMQ: 13.1.0
           RAET: Not Installed
            ZMQ: 3.2.2
           Mako: Not Installed

[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[INFO    ] SaltReqTimeoutError: after 60 seconds. (Try 1 of 7)

**Comment by s0undt3ch** [comment]
Do you have the necessary ports open?

**Comment by githubcdr** [comment]
Yes, but newer builds are working correctly again so this issue is apperently solved.

**Comment by s0undt3ch** [comment]
Ok. Please reopen if this issue reappears.
