### ISSUE TITLE
salt-minion not found running when deploying minion with salt-cloud

### ISSUE THREAD

**Issue by SVQTQ** [saltstack/salt-bootstrap#472]
I get the following error trying to deploy a minion with the command salt-cloud -p profile id
I use digital ocean as provider
I had this error before, but now it keeps coming... I cannot deploy a minion anymore

```
 ERROR: salt-minion was not found running
 ERROR: Failed to run daemons_running()!!!
 ERROR: salt-minion was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
Error: There was a profile error: Executing the command '/tmp/.saltcloud-0e1a07ba-c91a-4fbc-9f8f-e96b8e90a41b/deploy.sh -c /tmp/.saltcloud-0e1a07ba-c91a-4fbc-9f8f-e96b8e90a41b' failed

```

Salt-version:

```
Salt: 2014.1.10
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6
         PyYAML: 3.10
          PyZMQ: 13.1.0
            ZMQ: 3.2.3

```

**Comment by s0undt3ch** [comment]
Is there a chance to get me the bootstrap output? What distro was this minion deployed in? Does it only happen for that distro?

**Comment by SVQTQ** [comment]
this can be closed, the problem now and then comes up again, but running --keep-tmp makes sure it succeeds. The distro was debian 7.6, my master is running this and my minions as well
