### ISSUE TITLE
lack of metalink for epel repo causes install_centos_[git|stable]_deps() to fail

### ISSUE THREAD

**Issue by storysj** [saltstack/salt-bootstrap#474]
centos 6.3
x86_64

fails with both the stable bootstrap and the development version.

```
[root@ip-172-31-24-160 ~]# wget -O - http://bootstrap.saltstack.org | sudo sh -s git v2014.1.7 
--2014-10-15 11:07:24--  http://bootstrap.saltstack.org/
Resolving bootstrap.saltstack.org... 74.208.29.198
Connecting to bootstrap.saltstack.org|74.208.29.198|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.github.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh [following]
--2014-10-15 11:07:24--  https://raw.github.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh
Resolving raw.github.com... 199.27.79.133
Connecting to raw.github.com|199.27.79.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh [following]
--2014-10-15 11:07:25--  https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh
Resolving raw.githubusercontent.com... 199.27.79.133
Connecting to raw.githubusercontent.com|199.27.79.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 185227 (181K) [text/plain]
Saving to: “STDOUT”

 0% [                                                                                     ] 0           --.-K/s               *  INFO: PIPED THROUGH sh -- Version 2014.10.14
57% [===============================================>                                     ] 106,496      441K/s              
 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   2.6.32-279.22.1.el6.x86_64
 *  INFO:   Distribution: CentOS 6.3

 *  INFO: Installing minion
100%[====================================================================================>] 185,227      468K/s   in 0.4s    

2014-10-15 11:07:25 (468 KB/s) - written to stdout [185227/185227]

 *  INFO: Found function install_centos_git_deps
 *  INFO: Found function install_centos_git
 *  INFO: Found function install_centos_git_post
 *  INFO: Found function install_centos_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Found function install_centos_check_services
 *  INFO: Running install_centos_git_deps()
Loaded plugins: fastestmirror, security
Loading mirror speeds from cached hostfile


Cannot retrieve metalink for repository: epel. Please verify its path and try again
 * ERROR: Failed to run install_centos_git_deps()!!!
[root@ip-172-31-24-160 ~]#
```

**Comment by storysj** [comment]
found the issue. The files at /etc/yum.repos.d/epel.repo and /etc/yum.repos.d/epel-testing.repo contain lines that match

```
mirrorlist=https://.*
```

but if they are changed to be

```
mirrorlist=http://.*
```

the bootstrapping script runs fine.

**Comment by s0undt3ch** [comment]
So the issue might be with switching to https for the mirror list?

Was that file modified by you? Or is it the default?

**Comment by storysj** [comment]
When the bootstrap script runs 

``` bash
rpm -Uvh --force http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
```

(line 2523 right now) the /etc/yum.repo.d/epel*.repo files are created by default having

```
mirrorlist=https://.*
```

So when I tried once to run the bootstrap, those files were generated but the bootstrap failed. I then manually modified those files, ran the bootstrapping script again, and this time it succeeded.

**Comment by s0undt3ch** [comment]
Hmm, so the epel rmp is creating those files with the wrong protocol!?

Bummer...

**Comment by mieciu** [comment]
I've got the same situation with centOS 6.4. 
When sed'ing https to http everything starts working

**Comment by s0undt3ch** [comment]
I think this might be a problem with the upstream epel package but I'll see how we can cleanly work around that.

**Comment by s0undt3ch** [comment]
@terminalmage, think this is an issue we should file against the epel package upstream?

**Comment by mieciu** [comment]
Right now I patched it by

```
sed -i 's/https/http/g' /etc/yum.repos.d/epel.repo
```

before any `yum update`.
It's definitely that EPEL package fault, which creates the `epel.repo` file with wrong URLs..

**Comment by s0undt3ch** [comment]
Are any of you behind a firewall?

See [this](https://www.centos.org/forums/viewtopic.php?t=1420) ...

**Comment by mieciu** [comment]
Already seen this :smile: 
It's also not an issue of the firewall, definitely. CentOS 6.6 can access https repos.
I think it might be an SSL issue on a previous version.

**Comment by s0undt3ch** [comment]
Bummer. I'm not that keen on disabling HTTPS...

**Comment by jeremyfelt** [comment]
I ran into this as well today. Per [this HP article](https://community.hpcloud.com/article/centos-63-instance-giving-cannot-retrieve-metalink-repository-epel-error), it's an issue of the EPEL repos using SSL 3.0.

**Comment by mieciu** [comment]
So I was right then :smile: 
I'll write on EPEL devel list about this

**Comment by avijc** [comment]
Do not change https to http in the URL. The proper fix is:

yum update --disablerepo=epel\*

and then run your install script again.

**Comment by s0undt3ch** [comment]
The script does need EPEL enabled....

**Comment by avijc** [comment]
The install script will work after running that yum update command. That was the point.

**Comment by vutny** [comment]
@storysj Looks like it was resolved some time ago. I haven't experienced any EPEL issues while bootstrapping recently. I think this could be closed.

**Comment by storysj** [comment]
works for me

**Comment by vutny** [comment]
@storysj That's great! Please could you be so kind to close the issue?
