### ISSUE TITLE
Use the https url for cloning the repo

### ISSUE THREAD

**Issue by dkubb** [saltstack/salt-bootstrap#475]
The `_SALTSTACK_REPO_URL` on https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L183 should probably be the `https://` url rather than the `git://` url since it is less likely to be blocked by firewalls.

**Comment by mochrul** [comment]
The git port is blocked in our firewall too.
And what it makes worst there are the -g option which set the url for some part of the code but not in others.  So in practice the -g option is useless.

**Comment by s0undt3ch** [comment]
Where in the code is -g not being respected?

**Comment by mochrul** [comment]
There are two variable using to set the original repository for the saltstack.
_SALTSTACK_REPO_URL and _SALT_REPO_URL. Only the latter is changed by the -g option.

184:**_SALTSTACK_REPO_URL**="git://github.com/saltstack/salt.git"
185:_SALT_REPO_URL=${_SALTSTACK_REPO_URL}
302:    g ) _SALT_REPO_URL=$OPTARG                          ;;
1147:        if [ "$(git remote -v | grep $_SALTSTACK_REPO_URL)" != "" ]; then
1152:            git remote add upstream "**$_SALTSTACK_REPO_URL**"
1179:                echoinfo "Attempting to shallow clone $GIT_REV from Salt's repository ${_SALT_REPO_URL}"
1180:                git clone --depth 1 --branch "$GIT_REV" "$_SALT_REPO_URL" "$__SALT_CHECKOUT_REPONAME"
1188:                    git clone "$_SALT_REPO_URL" "$__SALT_CHECKOUT_REPONAME" || return 1
1193:                git clone "$_SALT_REPO_URL" "$__SALT_CHECKOUT_REPONAME" || return 1
1198:            git clone "$_SALT_REPO_URL" "$__SALT_CHECKOUT_REPONAME" || return 1
1202:        if [ "$(echo "$_SALT_REPO_URL" | sed 's/^((git|https):\/\/github.com\/saltstack\/salt.git|git@github.com:saltstack\/salt.git)$/MATCH/')" != "MATCH" ]; then
1205:            git remote add upstream "**$_SALTSTACK_REPO_URL**" || return 1

**Comment by mochrul** [comment]
Sorry I was too compact. :(

So the proble is that in some places the _SALTSTACK_REPO_URL is used to set the/a remote. And because of it the git fetch will hang even when I set the -g option to change the repo url. I bold the places where the _SALTSTACK_REPO_URL is used to set the remote repository.

**Comment by rbjorklin** [comment]
Running Ubuntu 12.04 and this seems to be working: sudo ./salt-bootstrap.sh -g https://github.com/saltstack/salt.git git v2014.7.0rc6

Until this is resolved you could use the following one-liner for install: 
curl -s -L https://bootstrap.saltstack.com | sed 's/git:\/\//https:\/\//g' | sudo sh -s -- git v2014.7.0rc6
