### ISSUE TITLE
Checking Debian services fails when chrooted from a systemd system

### ISSUE THREAD

**Issue by angel333** [saltstack/salt-bootstrap#479]
[Line 1547](https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L1547) uses `runlevel` command to determine whether it is enabled in the current runlevel. However, when chrooted from a systemd OS (ArchLinux in my case) the utility just doesn't work:

```
# runlevel
unknown
```

Wouldn't it be more sensible to check whether the services are enabled in the usual runlevels 2345?

[Here](https://gist.github.com/angel333/927d11a7ad96b9662f46) is whole output.

**Comment by gdm85** [comment]
Found same issue today. Problem was addressed but only for Docker containers in #394.

For me this issue comes as a surprise because I am using `-X` and I'd expect that if I don't want daemons running, then services are not checked as well.

**Comment by s0undt3ch** [comment]
The develop version of the script allows check services to be skipped now.
