### ISSUE TITLE
installing bootstrap breaks apt-get in BeagleBone

### ISSUE THREAD

**Issue by shynis** [saltstack/salt-bootstrap#482]
Hi,

I am running an armhf port of debian7.6 on BeagleBone black
$uname -a
Linux beaglebone 3.8.13-bone64 #1 SMP Thu Aug 21 21:24:58 UTC 2014 armv7l GNU/Linux

When I run the salt-bootstrap script, it fails with the following error:
- ERROR: Failed to run install_debian_7_git_deps()!!!

After this "apt-get update" fails because of Hash Sum mismatch, and I an unable to install any new packages. The develop version of the script was used as suggested. 
apt-get update was succeeding earlier on the beaglebone, and works with the same mirrors in other beaglebones where the script has not been run.

Regards,
Shyni

The complete output of the script is pasted below:
root@beaglebone:/tmp# sudo sh install_salt.sh git develop
-  INFO: sh install_salt.sh -- Version 2014.10.14
-  WARN: Running the unstable version of bootstrap-salt.sh
-  INFO: System Information:
-  INFO:   CPU:          :
-  INFO:   CPU Arch:     armv7l
-  INFO:   OS Name:      Linux
-  INFO:   OS Version:   3.8.13-bone64
-  INFO:   Distribution: Debian 7.6
-  INFO: Installing minion
-  INFO: Found function install_debian_7_git_deps
-  INFO: Found function install_debian_7_git
-  INFO: Found function install_debian_git_post
-  INFO: Found function install_debian_restart_daemons
-  INFO: Found function daemons_running
-  INFO: Found function install_debian_check_services
-  INFO: Running install_debian_7_git_deps()
  Hit http://repos.rcn-ee.net wheezy InRelease
  Hit http://security.debian.org wheezy/updates InRelease
  Ign http://ftp.us.debian.org wheezy InRelease
  Hit http://debian.beagleboard.org wheezy-bbb InRelease
  Hit http://debian.saltstack.com wheezy-saltstack InRelease
  Get:1 http://repos.rcn-ee.net wheezy/main armhf Packages [40.8 kB]
  Hit http://ftp.us.debian.org wheezy-updates InRelease
  Hit http://ftp.us.debian.org wheezy Release.gpg
  Get:2 http://ftp.us.debian.org wheezy-updates/main armhf Packages [20 B]
  Get:3 http://security.debian.org wheezy/updates/main armhf Packages [261 kB]
  Get:4 http://debian.beagleboard.org wheezy-bbb/main armhf Packages [18.8 kB]
  Get:5 http://debian.saltstack.com wheezy-saltstack/main armhf Packages [3414 B]
  Get:6 http://ftp.us.debian.org wheezy-updates/contrib armhf Packages [20 B]
  Get:7 http://ftp.us.debian.org wheezy-updates/non-free armhf Packages [20 B]
  Get:8 http://ftp.us.debian.org wheezy-updates/contrib Translation-en [14 B]
  Ign http://repos.rcn-ee.net wheezy/main Translation-en
  Get:9 http://ftp.us.debian.org wheezy-updates/non-free Translation-en [14 B]
  Ign http://debian.saltstack.com wheezy-saltstack/main Translation-en
  Ign http://debian.beagleboard.org wheezy-bbb/main Translation-en
  Hit http://ftp.us.debian.org wheezy Release
  Get:10 http://ftp.us.debian.org wheezy-updates/main Translation-en [14 B]
  Get:11 http://security.debian.org wheezy/updates/contrib armhf Packages [20 B]
  Get:12 http://ftp.us.debian.org wheezy/main armhf Packages [7431 kB]
  Get:13 http://security.debian.org wheezy/updates/non-free armhf Packages [20 B]
  Get:14 http://security.debian.org wheezy/updates/contrib Translation-en [14 B]
  Get:15 http://security.debian.org wheezy/updates/main Translation-en [123 kB]
  Get:16 http://security.debian.org wheezy/updates/non-free Translation-en [14 B]
  Get:17 http://ftp.us.debian.org wheezy/contrib armhf Packages [39.3 kB]
  Get:18 http://ftp.us.debian.org wheezy/non-free armhf Packages [67.7 kB]
  Get:19 http://ftp.us.debian.org wheezy/contrib Translation-en [34.8 kB]
  Get:20 http://ftp.us.debian.org wheezy/main Translation-en [3846 kB]
  Get:21 http://ftp.us.debian.org wheezy/non-free Translation-en [66.1 kB]
  Fetched 7862 kB in 20s (377 kB/s)
  W: Failed to fetch http://security.debian.org/dists/wheezy/updates/contrib/i18n/Translation-en  Hash Sum mismatch

W: Failed to fetch http://security.debian.org/dists/wheezy/updates/main/i18n/Translation-en  Hash Sum mismatch

W: Failed to fetch http://security.debian.org/dists/wheezy/updates/non-free/i18n/Translation-en  Hash Sum mismatch

W: Failed to fetch http://ftp.us.debian.org/debian/dists/wheezy-updates/contrib/i18n/Translation-en  Hash Sum mismatch

W: Failed to fetch http://ftp.us.debian.org/debian/dists/wheezy-updates/main/i18n/Translation-en  Hash Sum mismatch

W: Failed to fetch http://ftp.us.debian.org/debian/dists/wheezy-updates/non-free/i18n/Translation-en  Hash Sum mismatch

W: Failed to fetch http://ftp.us.debian.org/debian/dists/wheezy/contrib/i18n/Translation-en  Hash Sum mismatch

W: Failed to fetch http://ftp.us.debian.org/debian/dists/wheezy/main/i18n/Translation-en  Hash Sum mismatch

W: Failed to fetch http://ftp.us.debian.org/debian/dists/wheezy/non-free/i18n/Translation-en  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
debian-archive-keyring is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 54 not upgraded.
Hit http://repos.rcn-ee.net wheezy InRelease
Hit http://security.debian.org wheezy/updates InRelease
Hit http://debian.saltstack.com wheezy-saltstack InRelease
Hit http://debian.beagleboard.org wheezy-bbb InRelease
Ign http://ftp.us.debian.org wheezy InRelease
Get:1 http://repos.rcn-ee.net wheezy/main armhf Packages [40.8 kB]
Hit http://ftp.us.debian.org wheezy-updates InRelease
Get:2 http://security.debian.org wheezy/updates/main armhf Packages [261 kB]
Get:3 http://debian.beagleboard.org wheezy-bbb/main armhf Packages [18.8 kB]
Get:4 http://debian.saltstack.com wheezy-saltstack/main armhf Packages [3414 B]
Hit http://ftp.us.debian.org wheezy Release.gpg
Get:5 http://ftp.us.debian.org wheezy-updates/main armhf Packages [20 B]
Get:6 http://ftp.us.debian.org wheezy-updates/contrib armhf Packages [20 B]
Get:7 http://ftp.us.debian.org wheezy-updates/non-free armhf Packages [20 B]
Ign http://repos.rcn-ee.net wheezy/main Translation-en
Get:8 http://security.debian.org wheezy/updates/contrib armhf Packages [20 B]
Get:9 http://ftp.us.debian.org wheezy-updates/contrib Translation-en [14 B]
Get:10 http://security.debian.org wheezy/updates/non-free armhf Packages [20 B]
Ign http://debian.saltstack.com wheezy-saltstack/main Translation-en
Get:11 http://security.debian.org wheezy/updates/contrib Translation-en [14 B]
Get:12 http://security.debian.org wheezy/updates/main Translation-en [123 kB]
Get:13 http://ftp.us.debian.org wheezy-updates/non-free Translation-en [14 B]
Ign http://debian.beagleboard.org wheezy-bbb/main Translation-en
Get:14 http://security.debian.org wheezy/updates/non-free Translation-en [14 B]
Hit http://ftp.us.debian.org wheezy Release
Get:15 http://ftp.us.debian.org wheezy-updates/main Translation-en [14 B]
Get:16 http://ftp.us.debian.org wheezy/main armhf Packages [7431 kB]
Get:17 http://ftp.us.debian.org wheezy/contrib armhf Packages [39.3 kB]
Get:18 http://ftp.us.debian.org wheezy/non-free armhf Packages [67.7 kB]
Get:19 http://ftp.us.debian.org wheezy/contrib Translation-en [34.8 kB]
Get:20 http://ftp.us.debian.org wheezy/main Translation-en [3846 kB]
Get:21 http://ftp.us.debian.org wheezy/non-free Translation-en [66.1 kB]
Fetched 7862 kB in 21s (366 kB/s)
W: Failed to fetch http://security.debian.org/dists/wheezy/updates/contrib/i18n/Translation-en  Hash Sum mismatch

W: Failed to fetch http://security.debian.org/dists/wheezy/updates/main/i18n/Translation-en  Hash Sum mismatch

W: Failed to fetch http://security.debian.org/dists/wheezy/updates/non-free/i18n/Translation-en  Hash Sum mismatch

W: Failed to fetch http://ftp.us.debian.org/debian/dists/wheezy-updates/contrib/i18n/Translation-en  Hash Sum mismatch

W: Failed to fetch http://ftp.us.debian.org/debian/dists/wheezy-updates/main/i18n/Translation-en  Hash Sum mismatch

W: Failed to fetch http://ftp.us.debian.org/debian/dists/wheezy-updates/non-free/i18n/Translation-en  Hash Sum mismatch

W: Failed to fetch http://ftp.us.debian.org/debian/dists/wheezy/contrib/i18n/Translation-en  Hash Sum mismatch

W: Failed to fetch http://ftp.us.debian.org/debian/dists/wheezy/main/i18n/Translation-en  Hash Sum mismatch

W: Failed to fetch http://ftp.us.debian.org/debian/dists/wheezy/non-free/i18n/Translation-en  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
OK
Hit http://repos.rcn-ee.net wheezy InRelease
Ign http://ftp.us.debian.org wheezy InRelease
Hit http://debian.saltstack.com wheezy-saltstack InRelease
Get:1 http://repos.rcn-ee.net wheezy/main armhf Packages [40.8 kB]
Hit http://security.debian.org wheezy/updates InRelease
Hit http://ftp.us.debian.org wheezy-updates InRelease
Hit http://debian.beagleboard.org wheezy-bbb InRelease
Get:2 http://debian.saltstack.com wheezy-saltstack/main armhf Packages [3414 B]
Hit http://ftp.us.debian.org wheezy Release.gpg
Hit http://ftp.us.debian.org wheezy Release
Get:3 http://security.debian.org wheezy/updates/main armhf Packages [261 kB]
Get:4 http://ftp.us.debian.org wheezy-updates/main armhf Packages [20 B]
Get:5 http://debian.beagleboard.org wheezy-bbb/main armhf Packages [18.8 kB]
Get:6 http://ftp.us.debian.org wheezy-updates/contrib armhf Packages [20 B]
Get:7 http://ftp.us.debian.org wheezy-updates/non-free armhf Packages [20 B]
Ign http://repos.rcn-ee.net wheezy/main Translation-en
Get:8 http://ftp.us.debian.org wheezy-updates/contrib Translation-en [14 B]
Ign http://debian.saltstack.com wheezy-saltstack/main Translation-en
Get:9 http://ftp.us.debian.org wheezy-updates/non-free Translation-en [14 B]
Get:10 http://ftp.us.debian.org wheezy/main armhf Packages [7431 kB]
Ign http://debian.beagleboard.org wheezy-bbb/main Translation-en
Get:11 http://security.debian.org wheezy/updates/contrib armhf Packages [20 B]
Get:12 http://security.debian.org wheezy/updates/non-free armhf Packages [20 B]
Get:13 http://security.debian.org wheezy/updates/contrib Translation-en [14 B]
Get:14 http://security.debian.org wheezy/updates/main Translation-en [123 kB]
Get:15 http://security.debian.org wheezy/updates/non-free Translation-en [14 B]
Get:16 http://ftp.us.debian.org wheezy/contrib armhf Packages [39.3 kB]
Get:17 http://ftp.us.debian.org wheezy/non-free armhf Packages [67.7 kB]
Get:18 http://ftp.us.debian.org wheezy/contrib Translation-en [34.8 kB]
Get:19 http://ftp.us.debian.org wheezy/main Translation-en [3846 kB]
Get:20 http://ftp.us.debian.org wheezy/non-free Translation-en [66.1 kB]
Get:21 http://ftp.us.debian.org wheezy-updates/main Translation-en [14 B]
Fetched 7862 kB in 19s (413 kB/s)
W: Failed to fetch http://security.debian.org/dists/wheezy/updates/contrib/i18n/Translation-en  Hash Sum mismatch

W: Failed to fetch http://security.debian.org/dists/wheezy/updates/main/i18n/Translation-en  Hash Sum mismatch

W: Failed to fetch http://security.debian.org/dists/wheezy/updates/non-free/i18n/Translation-en  Hash Sum mismatch

W: Failed to fetch http://ftp.us.debian.org/debian/dists/wheezy-updates/contrib/i18n/Translation-en  Hash Sum mismatch

W: Failed to fetch http://ftp.us.debian.org/debian/dists/wheezy-updates/main/i18n/Translation-en  Hash Sum mismatch

W: Failed to fetch http://ftp.us.debian.org/debian/dists/wheezy-updates/non-free/i18n/Translation-en  Hash Sum mismatch

W: Failed to fetch http://ftp.us.debian.org/debian/dists/wheezy/contrib/i18n/Translation-en  Hash Sum mismatch

W: Failed to fetch http://ftp.us.debian.org/debian/dists/wheezy/main/i18n/Translation-en  Hash Sum mismatch

W: Failed to fetch http://ftp.us.debian.org/debian/dists/wheezy/non-free/i18n/Translation-en  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
- ERROR: Failed to run install_debian_7_git_deps()!!!

**Comment by tkrajca** [comment]
This seem to be fixed in the latest mater b9c6090caeab64550cee0710dc46c6b6f4cd2f16. I have successfully bootstrapped new salt on Shyni's BeagleBone (I am her work colleague:).

**Comment by tkrajca** [comment]
Actually, I am not sure whether it was fixed but if I just run sudo sh install_salt.sh (without any options), it works.

**Comment by wolfpackmars2** [comment]
Can probably be closed if no new information

**Comment by vutny** [comment]
Yeah, looks outdated. Ping @jfindlay
