### ISSUE TITLE
minion Bootstrap fails on RHEL Server 6.6

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt-bootstrap#483]
[root@32dhcp176231 boot]# wget -O - http://bootstrap.saltstack.org | sh
--2014-10-21 12:20:40--  http://bootstrap.saltstack.org/
Resolving bootstrap.saltstack.org... 74.208.29.198
Connecting to bootstrap.saltstack.org|74.208.29.198|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.github.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh [following]
--2014-10-21 12:20:40--  https://raw.github.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh
Resolving raw.github.com... 199.27.76.133
Connecting to raw.github.com|199.27.76.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh [following]
--2014-10-21 12:20:40--  https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh
Resolving raw.githubusercontent.com... 199.27.76.133
Connecting to raw.githubusercontent.com|199.27.76.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 185227 (181K) [text/plain]
Saving to: “STDOUT”

 0% [                                                           ] 0           --.-K/s               \*  INFO: PIPED THROUGH sh -- Version 2014.10.14
-  INFO: System Information:
-  INFO:   CPU:          GenuineIntel
-  INFO:   CPU Arch:     x86_64
-  INFO:   OS Name:      Linux
-  INFO:   OS Version:   2.6.32-504.el6.x86_64
-  INFO:   Distribution: Red Hat Enterprise Server 6.6
-  INFO: Installing minion
  100%[==========================================================>] 185,227     --.-K/s   in 0.1s

2014-10-21 12:20:40 (1.33 MB/s) - written to stdout [185227/185227]
-  INFO: Found function install_red_hat_enterprise_server_stable_deps
-  INFO: Found function install_red_hat_enterprise_server_stable
-  INFO: Found function install_red_hat_enterprise_server_stable_post
-  INFO: Found function install_red_hat_enterprise_server_restart_daemons
-  INFO: Found function daemons_running
-  INFO: Running install_red_hat_enterprise_server_stable_deps()
-  INFO: Testing if packages usually on the optionals repository are available:
-  INFO:   - python-jinja2
- ERROR: Failed to find an installable 'python-jinja2' package. The optional repository or its subscription might be missing.
-  INFO: Sleeping 10 seconds while waiting for the optional repository subscription to be externally configured
-  INFO: Testing if packages usually on the optionals repository are available:
-  INFO:   - python-jinja2
- ERROR: Failed to find an installable 'python-jinja2' package. The optional repository or its subscription might be missing.

**Comment by s0undt3ch** [comment]
You need to have the optional subscription properly configured. The script can't do that for you.

**Comment by s0undt3ch** [comment]
*optionals

**Comment by tjyang** [comment]
Thanks for the pointer,bootstrap scripts works now. following is check point. rhel-6-server-optional-rpms need to be enabled in  /etc/yum.repos.d/redhat.repo.

[root@32dhcp176231 boot]# yum repolist |grep optional-rpms
rhel-6-server-optional-rpms          Red Hat Enterprise Linux 6 Server -   8,040
[root@dhcp176231 boot]#
