### ISSUE TITLE
Salt install fails after running "deborphan"

### ISSUE THREAD

**Issue by howardroark** [saltstack/salt-bootstrap#484]
I'm building Ubuntu Vagrant VMs with Salt preinstalled using a project which sums things up by running deborphan as a way to minimize image size.  It ends up removing some core python packages...

```
    virtualbox-iso: Removing linux-server (3.13.0.32.38) ...
    virtualbox-iso: Removing python-crypto (2.6.1-4build1) ...
    virtualbox-iso: Removing python-jinja2 (2.7.2-2) ...
    virtualbox-iso: Removing python-m2crypto (0.21.1-3ubuntu5) ...
    virtualbox-iso: Removing python-msgpack (0.3.0-1ubuntu3) ...
    virtualbox-iso: Removing python-yaml (3.10-4build4) ...
    virtualbox-iso: Removing python-zmq (14.0.1-1build2) ...
```

https://github.com/box-cutter/ubuntu-vm/blob/master/script/minimize.sh#L40

I'm wondering if you feel this is an issue with this script in use (which is fine with me)... Or if maybe the bootstrap could do something different to avoid having core packages removed by deborphan.

**Comment by s0undt3ch** [comment]
Well, the script does not remove any packages, so, I think this issue should be handled by the minimize script.

**Comment by howardroark** [comment]
Could it be any concern to Salt that [deborphan](http://packages.ubuntu.com/trusty/deborphan) labels required packages as "unused" after the bootstrap installation?

```
root@hostname:/vagrant# deborphan --guess-all
python-yaml
python-dev
python-m2crypto
python-msgpack
libxft-dev
linux-headers-server
python-jinja2
software-properties-common
libssl-dev
python-crypto
python-zmq
python-virtualenv
linux-server
```

**Comment by s0undt3ch** [comment]
I have no idea how that script works, so, I would be just guessing... Can't you specify packages that shouldn't be removed?

**Comment by howardroark** [comment]
I guess the tool is not very common... I'll just close this up. Thanks for your time!

**Comment by s0undt3ch** [comment]
Sorry I couldn't be of more help.
