### ISSUE TITLE
-g option does not work

### ISSUE THREAD

**Issue by mochrul** [saltstack/salt-bootstrap#488]
Hi,

As I mentioned in a previous issue, the -g option is useless in this form, because it has no influence the upstream repo setting.

ie.:
# sh -x ./install_salt.sh -g http://github.com/saltstack/salt.git -P git v2014.7rc6 2>&1 | tee /tmp/nez2.txt
+ set -o nounset
+ __ScriptVersion=2014.10.30
+ __ScriptName=bootstrap-salt.sh
+ BS_TRUE=1
+ BS_FALSE=0
+ __DEFAULT_SLEEP=3
+ __DEFAULT_SLEEP_ORIGINAL=3
[...]
+ printf \033[1;32m \*  INFO\033[0m: %s\n Adding SaltStack's Salt repository as a remote
 *  INFO: Adding SaltStack's Salt repository as a remote
+ **git remote add upstream git://github.com/saltstack/salt.git**
+ echodebug Fetching upstream(SaltStack's Salt repository) git tags
+ [ 0 -eq 1 ]
+ git fetch --tags upstream
fatal: unable to connect to github.com:
github.com[0: 192.30.252.130]: errno=Connection timed out

\+ return 1

This is because there are two variable for the remote repositories:
_SALTSTACK_REPO_URL and _SALT_REPO_URL

The second is defaulted to the first, but could be changed by the -g option. But not the first.
And in two places in the code (when the remote is set) it uses the first one and not the second.

**Comment by s0undt3ch** [comment]
On November 3, 2014 1:44:20 PM GMT, Attila Szalay notifications@github.com wrote:

> Hi,
> 
> As I mentioned in a previous issue, the -g option is useless in this
> form, because it has no influence the upstream repo setting.
> 
> ie.:
> # sh -x ./install_salt.sh -g http://github.com/saltstack/salt.git -P
> git v2014.7rc6 2>&1 | tee /tmp/nez2.txt
> + set -o nounset
> + __ScriptVersion=2014.10.30
> + __ScriptName=bootstrap-salt.sh
> + BS_TRUE=1
> + BS_FALSE=0
> + __DEFAULT_SLEEP=3
> + __DEFAULT_SLEEP_ORIGINAL=3
> [...]
> + printf \033[1;32m \*  INFO\033[0m: %s\n Adding SaltStack's Salt
> repository as a remote
> *  INFO: Adding SaltStack's Salt repository as a remote
> + **git remote add upstream git://github.com/saltstack/salt.git**
> + echodebug Fetching upstream(SaltStack's Salt repository) git tags
> + [ 0 -eq 1 ]
> + git fetch --tags upstream
> fatal: unable to connect to github.com:
> github.com[0: 192.30.252.130]: errno=Connection timed out
> 
> \+ return 1
> 
> This is because there are two variable for the remote repositories:
> _SALTSTACK_REPO_URL and _SALT_REPO_URL
> 
> The second is defaulted to the first, but could be changed by the -g
> option. But not the first.
> And in two places in the code (when the remote is set) it uses the
> first one and not the second.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/saltstack/salt-bootstrap/issues/488

What you're after is probably -G not -g <repo>
Pedro Algarvio @ Phone

**Comment by mochrul** [comment]
Thanks to answer.

Yes, I know that there are the -G option, I just want to say that the -g is not needed any more/not used /could not be used.

I happily use the -G option anyway.

**Comment by s0undt3ch** [comment]
Well, `-g` is still necessary because the initial idea of it wasn't to use it to switch from `git://` to `https://`, ie, the idea was to be able to pass a custom repository URL.
`-G` however, was added to overcome the firewall issue that you mention.

Closing. Please reopen if need be.
