### ISSUE TITLE
six.with_metaclass given 3 args (expects 2) in setup.py

### ISSUE THREAD

**Issue by jsalva** [saltstack/salt-bootstrap#495]
Traceback (most recent call last):
  File "setup.py", line 117, in <module>
    exec(compile(open(SALT_VERSION).read(), SALT_VERSION, 'exec'))
  File "/tmp/git/salt/salt/version.py", line 491, in <module>
    **saltstack_version** = **get_version(__saltstack_version**)
  File "/tmp/git/salt/salt/version.py", line 421, in **get_version
    from salt._version import __saltstack_version**  # pylint: disable=E0611,F0401
  File "/tmp/git/salt/salt/**init**.py", line 38, in <module>
    import salt.log.setup
  File "/tmp/git/salt/salt/log/**init**.py", line 16, in <module>
    from salt.log.setup import (
  File "/tmp/git/salt/salt/log/setup.py", line 99, in <module>
    class SaltLoggingClass(six.with_metaclass(LoggingMixInMeta, LOGGING_LOGGER_CLASS, NewStyleClassMixIn)):
TypeError: with_metaclass() takes at most 2 arguments (3 given)
- ERROR: Failed to run install_amazon_linux_ami_git()!!!

**Comment by s0undt3ch** [comment]
You need a more recent six library, a known issue with salt's develop branch.

Keeping it open until a good solution is found.

**Comment by jsalva** [comment]
I just installed w/ pip which worked fine, though I had to manually create startup scripts

**Comment by s0undt3ch** [comment]
From pip you install a stable version, not expected to fail. Above you tried to install from Salt's develop branch, right?

**Comment by jsalva** [comment]
Yea, i used the one-liner which pulls from develop. 

```
curl -L https://bootstrap.saltstack.com | sudo sh -s -- git develop
```

**Comment by s0undt3ch** [comment]
Ok. Salt now ships with six bundled, though, develop is not currently proper for bootstrap.

**Comment by s0undt3ch** [comment]
Since https://github.com/saltstack/salt/issues/17943 was merged, I'm closing this as fixed. Please reopen if not.
