### ISSUE TITLE
Bootstrap relies on Debian Wheezy python-requests package which is seriously outdated

### ISSUE THREAD

**Issue by ross-p** [saltstack/salt-bootstrap#497]
Salt v2014.7 requires a minimum version for the Python requests module that is greater than what wheezy provides in ports.

``` bash
$ pip freeze | grep requests
requests==0.12.1
```

salt-bootstrap relies on Debian ports to install the requests module, even when PIP mode is enabled.

This causes 2014.7.0rc7 to be completely broken.

Upgrading via pip works:

``` bash
$ pip install -U 'requests>=2.4.3'
$ pip freeze | grep requests
requests=2.4.3
```

**Comment by speedlight** [comment]
Install from the oficial repo still the same:

The following packages have unmet dependencies:
 salt-minion : Depends: salt-common (= 2014.7.2+ds-1~bpo70+1) but it is not going to be installed
               Depends: python-zmq (>= 13.1.0) but 2.2.0-1 is to be installed

The following packages have unmet dependencies:
 salt-common : Depends: python-requests (>= 1.0.0) but 0.12.1-1+deb7u1 is to be installed

**Comment by speedlight** [comment]
Solved in my Wheezy box upgrading python-requests and python-zmq to the versions that saltstack repo have, apt install the versions of the debian repos.

An apt-cache policy python-requests show:

apt-cache policy python-requests 
python-requests:
  Installed: 2.0.0-1~bpo70+1
  Candidate: 2.0.0-1~bpo70+1
  Version table:
 **\* 2.0.0-1~bpo70+1 0
        500 http://debian.saltstack.com/debian/ wheezy-saltstack/main amd64 Packages
        100 /var/lib/dpkg/status
     0.12.1-1+deb7u1 0
        990 http://security.debian.org/ wheezy/updates/main amd64 Packages
     0.12.1-1 0
        990 http://ftp.us.debian.org/debian/ wheezy/main amd64 Packages

Minimal wheezy sources.list and no apt preferences configured.. anyway.. I did:

apt-get install -t wheezy-saltstack python-requests python-zmq

And that installed the versions from salt repo, then 
apt-get install salt-\* (master, minion, whatever) works whitout a problem.

**Comment by ebayer** [comment]
Why are you enforcing to install pip version? Both wheezy backports and saltstack repos have 2.0.0-1 and release notes or installation documents do not mention a specific version?

**Comment by s0undt3ch** [comment]
If you install that request package, does salt run properly?

**Comment by s0undt3ch** [comment]
Hmm.. I'll take care of that, seems that 2.0 is fine...

**Comment by ebayer** [comment]
Well, we were using 2.0 version before this commit and minions were working fine AFAIK.

**Comment by s0undt3ch** [comment]
The next stable release will fix this.
