### ISSUE TITLE
[docker ubuntu 14.04] Cannot install Master only

### ISSUE THREAD

**Issue by chrisduong** [saltstack/salt-bootstrap#506]
Hi,

My Dockerfile is 
# Dockerfile for SaltStack  Master

FROM ubuntu:14.04
MAINTAINER Chris Duong chris.duong83@gmail.com
# Install dependencies

RUN apt-get update -qq && \
    apt-get install -y curl
RUN curl -L https://bootstrap.saltstack.com | sh -s -- -M -N -X git v2014.7.0

CMD ["bash"]

However, it ends up with both SALT master, minion installed and other stuff

```
root@1156833ef8ab:/# salt
salt         salt-api     salt-call    salt-cloud   salt-cp      salt-key     salt-master  salt-minion  salt-run     salt-ssh     salt-syndic  salt-unity
root@1156833ef8ab:/# salt-minion
```

**Comment by s0undt3ch** [comment]
If you're installing from git, then everything is installed. If you installed from stable packages, then the proper separation would occur.

**Comment by chrisduong** [comment]
Thanks for your answer. :)
