### ISSUE TITLE
Bootstrap python package dependency problems for docker.

### ISSUE THREAD

**Issue by mooperd** [saltstack/salt-bootstrap#510]
Hi,

I want to provision docker hypervisors using salt-cloud, salt-bootstrap and then use the salt dockerio module to bring up my dockers.

docker_py 0.5.0 requires six 1.8.0 however the default for Centos 7 is Version: 1.3.0 which breaks a urllib dependancy.

Can I somehow get cloud-provider to upgrade python six with pip or somehow pass an arbitrary command to the bootstrap. I guess I can pass some option with script_args: in the /etc/salt/cloud.profile somehow.

Cheers,

Andrew

**Comment by s0undt3ch** [comment]
Are you still having troubles with this?

**Comment by mooperd** [comment]
No. We dumped docker a while ago.

**Comment by s0undt3ch** [comment]
Ok. Thanks!
