### ISSUE TITLE
Bootstrap breaks for releases of CentOS that aren't using systemd

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt-bootstrap#515]
Looks like https://github.com/saltstack/salt-bootstrap/commit/d24410bee9eb7194cdd7ffb6b0a4540c80e27633 broke centos if you aren't using systemd:

```
 * INFO: Running install_centos_git_post()
cp: cannot create regular file `/usr/lib/systemd/system/': No such file or directory
sh: line 2738: /bin/systemctl: No such file or directory
sh: line 2766: /bin/systemctl: No such file or directory
* ERROR: Failed to run install_centos_git_post()!!! 
```

I'm getting that during a setup where it's pulling down from GitHub.

**Comment by egarbi** [comment]
Same for me when I run:
./bootstrap-salt.sh -G git 'v2014.1.13'

**Comment by jeff-minard-ck** [comment]
I've got reports of this coming in from my team as well. The base image is a CentOS 6.5 box

**Comment by s0undt3ch** [comment]
I'll have a look at this today or tomorrow.

**Comment by gravyboat** [comment]
@s0undt3ch Sounds good, if you don't have time to look at it you can always just revert that commit I linked and that should fix it up for the time being.

**Comment by s0undt3ch** [comment]
I prefer not loose systemd support for cent 7. Should be just a simple logic fix.

**Comment by gravyboat** [comment]
Sounds good!

**Comment by csakoda** [comment]
Any update on this?  Should we expect a patch in the near future or be investigating alternative bootstrap pathways?

**Comment by s0undt3ch** [comment]
Sorry I haven't taken care of this yet. Near future.

**Comment by jeff-minard-ck** [comment]
Personally, I've just had us hard code to an older version for the time being.

**Comment by csakoda** [comment]
Unfortunately we're seeing intermittent failure on 2014.10.30 as well -- issue #519

**Comment by s0undt3ch** [comment]
Latest develop version should have this fixed.

**Comment by gravyboat** [comment]
Good fix, thanks for getting this merged in @s0undt3ch.

**Comment by s0undt3ch** [comment]
Sorry it took so long.

**Comment by csakoda** [comment]
Thanks for the fix @s0undt3ch, looks to be working in our systems!

**Comment by s0undt3ch** [comment]
Awesome#

**Comment by s0undt3ch** [comment]
!
