### ISSUE TITLE
Bootstrap fails on CentOS7 due to EPEL RPM's release change

### ISSUE THREAD

**Issue by escapenguin** [saltstack/salt-bootstrap#516]
# cat /etc/redhat-release

CentOS Linux release 7.0.1406 (Core)
-  INFO: Running install_centos_stable_deps()
  curl: (22) The requested URL returned error: 404 Not Found
  error: skipping http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-2.noarch.rpm - transfer failed
  Retrieving http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-2.noarch.rpm

New rpm is epel-release-7-5.noarch.rpm

**Comment by cro** [comment]
Closing as duplicate, see #513 for original ticket.  Please reopen if we didn't fix it.
