### ISSUE TITLE
python-gnupg should be considerer to be added as a dependency

### ISSUE THREAD

**Issue by tjuberg** [saltstack/salt-bootstrap#517]
With the release of 2014.7 the gpg renderer was added.
This depends on the python-gnupg package to be installed for Debian and CentOS (have not checked package names for others)

After bootstrapping minions I currently have to remember to manually install this package as the initial highstate will not run on the minion given the use of encrypted data.

With the gpg renderer being a part of salt itself, I feel this package should be included as a dependency.

**Comment by s0undt3ch** [comment]
This is out of the scope of the bootstrap script.

Please see https://github.com/saltstack/salt-bootstrap/pull/507 for additional background on why.
Closing. Please reopen if need be.
