### ISSUE TITLE
ERROR: The master failed to decrypt the random minion token

### ISSUE THREAD

**Issue by MarkuzK** [saltstack/salt-bootstrap#52]
There seems to be an issue with salt's bootstrapping process on Amazon Linux 64bit (tested with Amazon Linux AMI release 2012.09; Linux 3.2.30-49.59.amzn1.x86_64) with Script version 1.4.

I'm bootstrapping various salt master & minions automatically with AWS CloudFormation & salt-bootstrap. I noticed that the bootstrapping fails since the script version was upgraded from 1.3 to 1.4. I verified this by starting up two new and identical AWS deployments; only difference being the salt-bootstrap script version I've been using.

salt-bootstrap v1.3: master and minions come up cleanly and work fine

salt-bootstrap v1.4: only the master comes up fine; all minions terminate with an error:

Running 'salt-minion -l debug' shows the following output:

[INFO    ] Loaded configuration file: /etc/salt/minion
[WARNING ] Setting up the Salt Minion "ip-10-1-67-200"
[DEBUG   ] loading grain in ['/var/cache/salt/minion/extmods/grains', '/usr/lib/python2.6/site-packages/salt/grains']
[DEBUG   ] Skipping /var/cache/salt/minion/extmods/grains, it is not a directory
[DEBUG   ] Attempting to authenticate with the Salt Master at 10.1.33.141
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[ERROR   ] The master failed to decrypt the random minion token
[CRITICAL] The Salt Master server's public key did not authenticate!
The master may need to be updated if it is a version of Salt lower than 0.12.1, or
If you are confident that you are connecting to a valid Salt Master, then remove the master public key and restart the Salt Minion.
The master public key can be found at:
/etc/salt/pki/minion/minion_master.pub

Running 'salt-master --version' shows: salt-master 0.12.1
Running 'salt-minion --version' shows: salt-minion 0.12.1

Cheers,

```
  Markus
```

**Comment by s0undt3ch** [comment]
Well this does seem more related to salt than salt-bootstrap, though, if you say that with 2 identical machines, only the one using the 1.4 version of the script fails, then this throws me a little off guard.

There were some significant changes lately, namely to support salt-master and salt-syndic installations, daemons reloading when only configuring daemons and some other minor stuff.

So, in order for us to better understand, can you answer the following questions for now:
1. can you try with the latest bootstrap script?
2. these machines never had salt installed?

**Comment by MarkuzK** [comment]
Yes, I also suspected salt at first. However, after verifying this with two clean installs, the only difference was the version of salt-bootstrap.

Re q1: I've used salt-bootstrap v1.3 that I downloaded about 10 days ago; as for salt-bootstrap v1.4, my deployment scripts automatically download the latest stable script version from the git repo.

Re q2: No, I started new machines, applied all updates and then ran salt-bootstrap; I used clean environments to verify this issue.

**Comment by s0undt3ch** [comment]
Ok. Thank You for the information. I will try to reproduce this erratic behavior.

One more question. You are passing a configuration directory which contains the master and minion config files correct? Also passing any keys around?

## 

Pedro Algarvio

----- Reply message -----
De: "Markus" notifications@github.com
Para: "saltstack/salt-bootstrap" salt-bootstrap@noreply.github.com
Cc: "Pedro Algarvio" pedro@algarvio.me
Assunto: [salt-bootstrap] ERROR: The master failed to decrypt the random minion token (#52)
Data: qui, Fev 14, 2013 14:22
Yes, I also suspected salt at first. However, after verifying this with two clean installs, the only difference was the version of salt-bootstrap. 

Re q1: I've used salt-bootstrap v1.3 that I downloaded about 10 days ago; as for salt-bootstrap v1.4, my deployment scripts automatically download the latest stable script version from the git repo. 

Re q2: No, I started new machines, applied all updates and then ran salt-bootstrap; I used clean environments to verify this issue. 

&mdash;

**Comment by MarkuzK** [comment]
I'm setting configs on the master and minion; I checked those as well. The master is set to accept all keys as I run this in a non-public / protected environment.

I created a simplified CloudFormation script that reproduces the erratic behaviour:

> more saltStackInstallTest.json

``` json
{
  "AWSTemplateFormatVersion" : "2010-09-09",

  "Description" : "Salt Stack Master - Minion Test Setup $Rev: 001$",

  "Parameters" : {
    "KeyPairName" : {
      "Description" : "EC2 Key Pair Name for SSH Access",
      "Type" : "String"
    }
  },

  "Mappings" : {
    "AWSRegionAMIs" : {
      "us-east-1" : {
        "amazlinux" : "ami-1624987f"
      },
      "us-west-1" : {
        "amazlinux" : "ami-1bf9de5e"
      },
      "us-west-2" : {
        "amazlinux" : "ami-2a31bf1a"
      },
      "eu-west-1" : {
        "amazlinux" : "ami-c37474b7"
      },
      "sa-east-1" : {
        "amazlinux" : "ami-1e08d103"
      },
      "ap-southeast-1" : {
        "amazlinuz" : "ami-a6a7e7f4"
      },
      "ap-southeast-2" : {
        "amazlinux" : "ami-bd990e87"
      },
      "ap-northeast-1" : {
        "amazlinuz" : "ami-4e6cd34f"
      }
    }
  },

  "Resources" : {
    "SaltStackSecurityGroup" : {
      "Type" : "AWS::EC2::SecurityGroup",
      "Properties" : {
        "GroupDescription" : "Enable Salt n SSH Access from ALL",
        "SecurityGroupIngress" : [
          { "IpProtocol" : "tcp", "FromPort" : "22", "ToPort" : "22", "CidrIp" : "0.0.0.0/0" },
          { "IpProtocol" : "tcp", "FromPort" : "4505", "ToPort" : "4506", "CidrIp" : "0.0.0.0/0" }
        ]
      }
    },

    "SaltStackMasterServer" : {
      "Type" : "AWS::EC2::Instance",
      "Properties" : {
        "ImageId" : { "Fn::FindInMap" : [ "AWSRegionAMIs", { "Ref" : "AWS::Region" }, "amazlinux" ] },
        "InstanceType" : "t1.micro",
        "SecurityGroups" : [ { "Ref" : "SaltStackSecurityGroup" } ],
        "KeyName" : { "Ref" : "KeyPairName" },
        "DisableApiTermination" : "false",
        "UserData" : {
          "Fn::Base64" : {
            "Fn::Join" : [ "", [
              "#!/bin/bash\n",
              "\n",
              "yum -y update --security\n",
              "\n",
              "sed -i -e \"s/#PermitEmptyPasswords no/PermitEmptyPasswords no/\"",
              " -e \"s/PermitRootLogin forced-commands-only/PermitRootLogin yes/\"",
              " -e \"s/PasswordAuthentication no/PasswordAuthentication yes/\"",
              " /etc/ssh/sshd_config\n",
              "/etc/init.d/sshd restart\n",
              "install -m640 /home/ec2-user/.ssh/authorized_keys /root/.ssh\n",
              "\n",
              "mkdir -p /etc/salt/\n",
              "touch /etc/salt/master\n",
              "cat <<EOF > /etc/salt/master\n",
              "# Enable auto_accept (automatically accept all incoming public keys from the minions).\n",
              "auto_accept: True\n",
              "\n",
              "# File Server settings\n",
              "file_roots:\n",
              "  base:\n",
              "    - /srv/salt\n",
              "\n",
              "# The level of messages to send to the console.\n",
              "log_level: debug\n",
              "EOF\n",
              "\n",
              "mkdir -p /srv/salt\n",
              "cat <<EOF > /srv/salt/top.sls\n",
              "base:\n",
              "  'roles:minionTest':\n",
              "    - match: grain\n",
              "    - minionTest\n",
              "EOF\n",
              "\n",
              "mkdir -p /srv/salt/minionTest\n",
              "touch /srv/salt/minionTest/init.sls\n",
              "cat <<EOF > /srv/salt/minionTest/init.sls\n",
              "mc:\n",
              "  pkg:\n",
              "    - installed\n",
              "EOF\n",
              "\n",
              "cd /root/\n",
              "wget -O bootstrap-salt.sh http://bootstrap.saltstack.org\n",
              "sh ./bootstrap-salt.sh -M -N\n",
              "# Start Salt Master automatically at boot time.\n",
              "chkconfig salt-master on\n",
              "# Start the Salt Master now.\n",
              "service salt-master start\n" ] ]
          }
        }
      }
    },

    "SaltStackMasterEIP" : {
      "Type" : "AWS::EC2::EIP",
      "Properties" : {
        "InstanceId" : { "Ref" : "SaltStackMasterServer" }
      }
    },

    "SaltStackMinionServer" : {
      "Type" : "AWS::EC2::Instance",
      "Properties" : {
        "ImageId" : { "Fn::FindInMap" : [ "AWSRegionAMIs", { "Ref" : "AWS::Region" }, "amazlinux" ] },
        "InstanceType" : "t1.micro",
        "SecurityGroups" : [ { "Ref" : "SaltStackSecurityGroup" } ],
        "KeyName" : { "Ref" : "KeyPairName" },
        "DisableApiTermination" : "false",
        "UserData" : {
          "Fn::Base64" : {
            "Fn::Join" : [ "", [
              "#!/bin/bash\n",
              "\n",
              "yum -y update --security\n",
              "\n",
              "sed -i -e \"s/#PermitEmptyPasswords no/PermitEmptyPasswords no/\"",
              " -e \"s/PermitRootLogin forced-commands-only/PermitRootLogin yes/\"",
              " -e \"s/PasswordAuthentication no/PasswordAuthentication yes/\"",
              " /etc/ssh/sshd_config\n",
              "/etc/init.d/sshd restart\n",
              "install -m640 /home/ec2-user/.ssh/authorized_keys /root/.ssh\n",
              "\n",
              "mkdir -p /etc/salt/\n",
              "touch /etc/salt/minion\n",
              "cat <<EOF > /etc/salt/minion\n",
              "# IP of the salt master server.\n",
              "master: ", { "Ref" : "SaltStackMasterEIP" }, "\n",
              "\n",
              "# Custom grains for this minion.\n",
              "grains:\n",
              "  roles:\n",
              "    - minionTest\n",
              "  aws_region: ", { "Ref" : "AWS::Region" } , "\n",
              "\n",
              "# The level of messages to send to the console.\n",
              "log_level: debug\n",
              "EOF\n",
              "\n",
              "wget -O - http://bootstrap.saltstack.org | sh\n",
              "\n",
              "# Start the Salt Minion automatically at boot time.\n",
              "chkconfig salt-minion on\n",
              "# Start the Salt Minion now.\n",
              "service salt-minion start\n",
              "\n",
              "TIMEOUT=90\n",
              "COUNT=0\n",
              "while [ ! -f /etc/salt/pki/minion/minion_master.pub ]; do\n",
              "  echo 'Waiting for salt install.'\n",
              "  if [ \"$COUNT\" -ge \"$TIMEOUT\" ]; then\n",
              "    echo 'minion_master.pub not detected by timeout'\n",
              "    exit 1\n",
              "  fi\n",
              "  sleep 5s\n",
              "  COUNT=$((COUNT+5))\n",
              "done\n",
              "\n",
              "salt-call state.highstate -l debug\n" ] ]
          }
        }
      }
    }
  }
}
```

You can run the scripts via AWS CloudFormation Command Line tools (http://aws.amazon.com/developertools/AWS-CloudFormation/2555753788650372):

```
cfn-create-stack SaltStackInstallTest --template-file saltStackInstallTest.json --region us-west-2 --parameters "KeyPairName=<YOUR_KEY_NAME_GOES_HERE>"
```

This script uses the latest salt-bootstrap script; when I replace both occurrences of 'http://bootstrap.saltstack.org' with a URI pointing to v1.3 of the salt-bootstrap script master and minion are working fine. When I run the above as is, I get the error I reported earlier ...

Hope that helps.

I simplified the script and also tried to utilise only AWS resources for which you are not being charged ...

**Comment by s0undt3ch** [comment]
Thanks for this additional information.

Just by reading it, I can give you some usage more pointers.
I've created a [gist](https://gist.github.com/s0undt3ch/4960167) with your json data so I can give you line numbers.

On line [108 and 109](https://gist.github.com/s0undt3ch/4960167#file-gistfile1-json-L108), you can substitute:

```
"wget -O bootstrap-salt.sh http://bootstrap.saltstack.org\n",
"sh ./bootstrap-salt.sh -M -N\n",
```

With:

```
"wget -O - http://bootstrap.saltstack.org\n | sh -s -- -M -N\n",
```

What you do on line [111](https://gist.github.com/s0undt3ch/4960167#file-gistfile1-json-L111), the script already does for you on [line 1198](https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L1198), which is an alias for the call on [line 1000](https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L1000). If it doesn't, it's a bug.

What you do on [line 113](https://gist.github.com/s0undt3ch/4960167#file-gistfile1-json-L113), the scrip also does that for you on [line 1202](https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L1202) which is an alias for [line 1066](https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L1066), if it doesn't, it's a bug.

Regarding the configuration that you do from [lines 77-89](https://gist.github.com/s0undt3ch/4960167#file-gistfile1-json-L77-L89) and [lines 149-162](https://gist.github.com/s0undt3ch/4960167#file-gistfile1-json-L149-L162) you could do that in a temporary directory and pass that directory to the script using `-c`.
If that directory contains a `master` and a `minion` file, those files will be placed in the proper directory when bootstrapping.
If that directory also contains a `minion.pem`, `minion.pub`, `master.pem` and `master.pub`, those key files will also be copied to the proper PKI directories with the correct permissions.

Regarding what you for state files and the highstate call, I guess those are ok.

With this said, and your additional information, I will try to reproduce this issue.

**Comment by MarkuzK** [comment]
Thanks for the pointers. Based on your comments and my tests, there seem to be another issue with your bootstrap script:

re: service salt-master start / service salt-minion start

I have to call those explicitly as there are no salt-related processes active after executing the bootstrap script on either master nor minion.

However, 'chkconfig salt-master on' and 'chkconfig salt-minion on' are not required to be called explicitly as this is done by your script (but I never tested it before). That is, when I reboot my test machines, the master & minions are running.

Do note, I tested this with version 1.3 of the salt-bootstrap script.

**Comment by s0undt3ch** [comment]
Well, services (re)start were recently added, so, if using latest bootstrap script, you still need to add those calls, then it's a bug.

**Comment by MarkuzK** [comment]
salt-bootstrap script version 1.5 (bootstrapping salt stack v.0.13.1) doesn't exhibit the reported error any more.

**Comment by s0undt3ch** [comment]
Awesome!
