### ISSUE TITLE
New feature: upload a .sls for post-bootstrap execution

### ISSUE THREAD

**Issue by ketzacoatl** [saltstack/salt-bootstrap#522]
It is nice that we can control the arguments passed to the bootstrap script, but if you want to do some shell/etc after bootstrap completes.. you need to edit/customize the bootstrap script. It is silly to need to edit a 4k+ line script for 2 lines to run git clone and salt-call. @whiteinge suggested a feature which would upload a .sls to be executed after the bootstrap script completes. This would be _awesome_ for masterless setups.

**Comment by whiteinge** [comment]
@ketzacoatl I learned today that a bit of undocumented functionality was added to salt-cloud in 2014.7 that could help with this. The addition is saltstack/salt#16886. That makes it possible to transfer sls files (or whatever) via salt-cloud in the current Salt release. We'd just need a way to run that with masterless mode.

@s0undt3ch how would you feel about adding an arg to bootstrap that would perform a `salt-call --local state.sls <sls>` (or `state.highstate`) at the end of the run? With `file_map` in place people could easily seed the new minion with any files or states needed.

**Comment by s0undt3ch** [comment]
This all sounds like salt-cloud's work.

Salt cloud can upload files and Salt cloud can also be told to run highstate at the end. I think it can even run a specific SLS.

The part that I really don't know is if it currently supports using/passing `--local` to salt-call. But again this all sounds like salt-cloud's work.

Do note that I'm not opposing to changes to the script, I just think its something that salt-cloud already does(if it doesn't it could do)

**Comment by whiteinge** [comment]
@s0undt3ch yeah, that makes a lot of sense. Since salt-cloud is kicking off bootstrap, it should be able to kick off another proc as well. Thanks for the feedback.

@ketzacoatl I vote we close this out and reopen on the Salt repo.

**Comment by s0undt3ch** [comment]
Yep, the functionality already exists [here](https://github.com/saltstack/salt/blob/develop/salt/utils/cloud.py#L1326-L1349)...

**Comment by whiteinge** [comment]
Whelp. That fully resolves this. Sheesh, I missed that one. Thanks, @s0undt3ch!

@ketzacoatl looks like we have all the pieces we need for this already. Not exactly pretty but after putting the files in place with the `file_map` above the setting to kick off an initial run would look like this:

```
start_action: '--local state.sls <some-sls>'
```

or

```
start_action: '--local cmd.script salt://path/to/script.sh'
```

http://docs.saltstack.com/en/latest/topics/cloud/deploy.html#post-deploy-commands

**Comment by whiteinge** [comment]
@ketzacoatl I'm going to close this issue then. If there's anything still missing, feel free to open a new issue on the Salt repo.

**Comment by ketzacoatl** [comment]
Thank you @whiteinge for your assistance on this and to @s0undt3ch for the info. I think I can make this work for my needs!
