### ISSUE TITLE
EPEL5 retired python26-distribute which is a requirement for python26-jinja2

### ISSUE THREAD

**Issue by ngolnik** [saltstack/salt-bootstrap#533]
One of the requirements for RHEL5 has been removed from EPEL. 
salt.noarch requires python26-jinja2 which requires python26-distribute.  python26-distribute has been retired and removed from epel, so this will fail.

**Comment by s0undt3ch** [comment]
@ngolnik and what happened to python26-jinja2?

@terminalmage have any idea on how we should go about this?

**Comment by ngolnik** [comment]
@s0undt3ch:  python26-jinja2 rpm is still there, but since it requires python26-distribute it will not install.

I opened up a bug with Red Hat/Fedora, the bug was closed with the response: afaict, the whole python26 stack will be retired... and was closed with a wont fix.

**Comment by s0undt3ch** [comment]
How professional. Is RHEL5 support in its EOL?

**Comment by ngolnik** [comment]
RHEL5 is supported until 2017 I think but python26 is an EPEL package which is community supported.  My guess is the maintainer no longer wants to deal with it.

**Comment by gtmanfred** [comment]
That is exactly what happened.  http://osdir.com/ml/scm-fedora-commits/2015-01/msg13626.html

The maintainer dropped it so it was removed after no one else picked it up.  From everyone I have heard from, if you still have to be on RHEL5, you are doing everything wrong and they don't want to support it anymore.

I ran into this problem with an internal project for rackspace, so I just grabbed the old .rpm from koji and am hosting it on my internal server.  That is really the only option unless someone picks the package back up, which it doesn't look like they will.

**Comment by s0undt3ch** [comment]
The solution here is to require Jinja2 to be installed with `pip`.

**Comment by gtmanfred** [comment]
I am not sure that is going to fix it, cause to install with pip, it is going to need to use setuptools/distribute to install it.

https://github.com/mitsuhiko/jinja2/blob/master/setup.py#L40

**Comment by jasee** [comment]
I manually installed python26-distribute to workaround.

``` sh
yum install python26
wget ftp5.gwdg.de/pub/opensuse/repositories/home:/matejv:/epel/RedHat_RHEL-5/noarch/python26-distribute-0.6.10-5.3.noarch.rpm
rpm -Uvh python26-distribute-0.6.10-5.3.noarch.rpm
```

**Comment by gtmanfred** [comment]
If yall do that, it should be stored somewhere on saltstack.com cause that could be removed at some point in the future.  Also, it should be grabbed from epel's koji link.

**Comment by s0undt3ch** [comment]
While `python26-setuptools` is still available, [we can use `pip`](https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L2566-L2569).

**Comment by terminalmage** [comment]
I think that the way we're going to have to go moving forward is dropping Salt from EPEL5 and maintaining it (along with things like python26-distribute, etc.) on [COPR](http://copr.fedoraproject.org/).

**Comment by s0undt3ch** [comment]
I'd be cool with that.

**Comment by gtmanfred** [comment]
setuptools is not actually there either.

python26-distribute provided it -setuptools as well.

https://dl.fedoraproject.org/pub/epel/5/x86_64/repoview/python26-setuptools.html

using copr is probably the best path.

**Comment by cournape** [comment]
I encountered the same issue. As I needed a quick fix, I uploaded the required rpms https://github.com/enthought/enthought-rpms

Those were quickly hacked together, and I did not even try to make them work in parallel to other salt packages in EPEL, so use at your own peril.

**Comment by terminalmage** [comment]
I have created a repo on COPR, please feel free to test and let me know if I have left out any dependencies.

https://copr.fedoraproject.org/coprs/saltstack/salt-el5/

**Comment by alanivey** [comment]
If anyone needs this RPM for old CentOS 5 servers and finds this thread... the suggested download link of http://ftp5.gwdg.de/pub/opensuse/repositories/home:/matejv:/epel/RedHat_RHEL-5/noarch/python26-distribute-0.6.10-5.3.noarch.rpm is for an un-signed package, and it's not the latest version. 

Going through http://www.filewatcher.com/m/python26-distribute-0.6.10-4.el5.noarch.rpm.522342-3.html, I found that [ftp://ftp.rhd.ru/pub/epel/5/x86_64/python26-distribute-0.6.10-4.el5.noarch.rpm](http://ftp.rhd.ru/pub/epel/5/x86_64/python26-distribute-0.6.10-4.el5.noarch.rpm) is an EPEL-signed and still (2015-March) available file to download.

**Comment by terminalmage** [comment]
There shouldn't be any need for that, since python26-distribute is available in the COPR repo I referenced in my earlier comment.
