### ISSUE TITLE
bootstrap fails to recognize debian - 

### ISSUE THREAD

**Issue by sivann** [saltstack/salt-bootstrap#55]
Commit edd743070ea44c4db6fc08f4869ca14a508f3a93 broke debian 6 detection. Bootstrap script ends with " \* ERROR: No dependencies installation function found. Exiting..."

This also happens in all recent commits.

Please consider calling  lsb_release on linux instead of grepping various files to determine distro. It works in debian,ubuntu and redhat and maybe others.

```
DISTRO_NAME=`lsb_release -si`
DISTRO_VERSION=`lsb_release -sr`
DISTRO_MAJOR_VERSION=`lsb_release -sr|cut -d. -f1`
DISTRO_MINOR_VERSION=`lsb_release -sr|cut -d. -f2`
```

I could provide a patch if needed.

**Comment by s0undt3ch** [comment]
I did notice I had broken the distro's detection, I just did not realize it was **that** broken ;)
I'm already on the issue.

**Comment by s0undt3ch** [comment]
Regarding using `lsb_release`, that needs to be installed, and it ain't necessarily, and what it does, is parse files, which is what we do. :smile:

**Comment by s0undt3ch** [comment]
You suggestion was not thrown in a bag though, see b66bc75d5f159c379f9e98b68626a4594232bb94.

**Comment by sivann** [comment]
great! Thanks for the immediate response!

**Comment by s0undt3ch** [comment]
No problem. Still not fixed though... One can always revert back, but ....

**Comment by sivann** [comment]
It is fixed, I just tested it. Should I close it?

**Comment by s0undt3ch** [comment]
Well, it's fixed if your system has `lsb-release` installed.
Not all Debian systems, even latest 6.0.6 does not install that package by default, if you have AWS access, check `ami-c4259aad`.

What I did was use the lsb_release` binary if found, which, in your case, solves the problem.

Let's leave it open.

**Comment by s0undt3ch** [comment]
:smile: if only it was that simple....
- How do you know which distro is running before you try to install?
- Do all distros have a apt-get binary available? No.
- Does the lsb-release package exists for all distros?
- And the distros that do have that package, what's the exact name of the package?
- You cannot use `echo -e`, there are some `sh` implementation which don't support `-e`...

Don't think that I'm not appreciating your effort on solving this, because I am...
... It's just that the script needs to be generic...

**Comment by sivann** [comment]
You're right amazon images are strange beasts! I have an ami-a2ded2d6  which is a debian 6.0.6 with a redhat kernel (cat /proc/platform) (!)

I suggest
1. try with lsb-release binary
2. try with python: python -c 'import platform;print platform.dist();'
3. try with guesswork. Some hints here: http://www.novell.com/coolsolutions/feature/11251.html (detects ubuntu as debian though)
for debian,ubuntu,fedora,redhat,centos:

```
command -v apt-get >/dev/null 2>&1 && LSBINSTCMD="apt-get install lsb-release" || { LSBINSTCMD="yum install redhat-lsb";}
command -v lsb_release >/dev/null 2>&1 || { echo -e >&2 "*Installing lsb-release"; $LSBINSTCMD ; }
```

**Comment by sivann** [comment]
Unfortunately it seems to also fail for RHEL 6.3  with "No dependencies installation function found".
FYI: lsb_release -a reports:
LSB Version:    :core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 6.3 (Santiago)
Release:    6.3
Codename:   Santiago

```
# lsb_release -si
RedHatEnterpriseServer
```

and thus it searches for : 

```
install_redhatenterpriseserver_6_stable_restart_daemons
install_redhatenterpriseserver_6_3_stable_restart_daemons
install_redhatenterpriseserver_6_restart_daemons
install_redhatenterpriseserver_6_3_restart_daemons
install_redhatenterpriseserver_stable_restart_daemons
install_redhatenterpriseserver_restart_daemons
```
