### ISSUE TITLE
Bootstrapping FreeBSD puts config files in wrong location

### ISSUE THREAD

**Issue by The-Loeki** [saltstack/salt-bootstrap#552]
Given 

`bootstrap.sh -D -G -Z git upstream/2014.7`

Most config files (not the minion_id) are put in `/etc/salt`, but for FreeBSD these belong in `/usr/local/etc/salt`, or they won't be picked up.

**Comment by s0undt3ch** [comment]
Did the bootstrap script detected the system as FreeBSD?

Hmm.... 2014.7.... I think we don't have the salt syspaths options to setup.py for this branch...

Anyway, Thanks! I'll investigate this...

**Comment by The-Loeki** [comment]
I'm guessing yes considering the fact that all of it worked except for this :)
