### ISSUE TITLE
Git based installation with using a fork doesn't work

### ISSUE THREAD

**Issue by arnisoph** [saltstack/salt-bootstrap#553]
how can I bootstrap a salt minion using a git fork? 

```
./bootstrap-salt.sh -M -K -g https://github.com/bechtoldt/salt.git git 2014.7-arbe
```

I think the script creates a new branch 2014.7-arbe instead of using the existing branch of my fork.

**Comment by s0undt3ch** [comment]
Can you please paste the full debug, `-D`, output?

**Comment by arnisoph** [comment]
=> https://np.adm.sx/view/3af587f2

**Comment by arnisoph** [comment]
_push_

Can someone please verify this issue?

**Comment by arnisoph** [comment]
bug can't be reproduced (anymore)

**Comment by s0undt3ch** [comment]
Glad to see it sorted out.
