### ISSUE TITLE
Allow for Multi-Master-PKI on Minions

### ISSUE THREAD

**Issue by freimer** [saltstack/salt-bootstrap#554]
Copy master_sign.pub file from temp to minion PKI directory if found.  This could be extended to look for alternate files for the master_sign public key, but master_sign.pub is the default.

**Comment by jfindlay** [comment]
@freimer, I'm confused about what you mean.  In a normal multimaster setup, the redundant masters [share the same key](https://docs.saltstack.com/en/latest/topics/tutorials/multimaster.html#summary-of-steps).

**Comment by rallytime** [comment]
Closing for lack of response. Though I think this is also getting at the same idea as the feature request in #600, so I'll close this one as a duplicate.
