### ISSUE TITLE
libzmq3 packages for debian 6

### ISSUE THREAD

**Issue by sivann** [saltstack/salt-bootstrap#57]
Debian 6 (and 7) comes with libzmq1, not libzmq3. This version doesn't support keepalive and is thus pretty worthless (we loose half our minions in a day). Ubuntu doesn't have this problem since it comes with libzmq3.

I have created 2 debian 6 packages:
libzmq3_3.2.2_amd64.deb
python-zmq_2.2.0.1_amd64.deb

After installing those, I run the bootstrap and the minion is successfully installed using libzmq3. 
Who should I send those (or a howto for making them) ?

**Comment by s0undt3ch** [comment]
According to the [0MQ website](http://www.zeromq.org/distro:debian), one can find those packages in the [experimental repository](http://packages.debian.org/source/experimental/zeromq3).

We'll add support to the bootstrap script to install ZMQ from the experimental repository.

Opinions?

**Comment by s0undt3ch** [comment]
Dam, we do not have python-zmq3 in debian's experimental...

**Comment by s0undt3ch** [comment]
@sivann We currently do not have any way to store and serve your packages. Also, your packages are only for AMD64, we would need to build against other arch'es too.

The solution being considered right now is shown on #59.

**Comment by s0undt3ch** [comment]
Closing this for now. Please re-open if need be.
