### ISSUE TITLE
Boot strapping with latest docker official docker image fails.

### ISSUE THREAD

**Issue by loque1** [saltstack/salt-bootstrap#572]
When trying to bootstrap a centos7 image using the official docker centos image the bootstraping process fails reffering to conflicts

systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64

There is a containerised systemd installation which causes the default systemd package not to be installed and also therefore causes salt not to be installed. 

We use this dockerised setup along with docker-compose to create environments that we can test our saltstates on before we merge in to our master branch. A bit like CI for local states.

Is there a way aroud this to be able to bootstarp salt using the script to overcome these conflicts.

**Comment by s0undt3ch** [comment]
I think you'd have to resolve that conflict on your Dockerfile, we don't install systemd, we only make use of it if available.
