### ISSUE TITLE
Debian have changed wheezy-backports repository

### ISSUE THREAD

**Issue by dave-dave** [saltstack/salt-bootstrap#575]
This no longer works:
deb http://http.debian.net/debian wheezy-backports main

This does:
deb http://ftp.debian.net/debian wheezy-backports main

The debian backports wiki doesn't report this, but testing confirms.

Patch coming shortly.

**Comment by dave-dave** [comment]
```
diff --git a/bootstrap-salt.sh b/bootstrap-salt.sh
index 4e2da55..cecf4ce 100755
--- a/bootstrap-salt.sh
+++ b/bootstrap-salt.sh
@@ -2117,7 +2117,7 @@ install_debian_7_deps() {

     # Debian Backports
     if [ "$(grep -R 'wheezy-backports' /etc/apt | grep -v "^#")" = "" ]; then
-        echo "deb http://http.debian.net/debian wheezy-backports main" >> \
+        echo "deb http://ftp.debian.net/debian wheezy-backports main" >> \
             /etc/apt/sources.list.d/backports.list
     fi
```

**Comment by s0undt3ch** [comment]
My concern here is, if the http repo is gone, will the ftp also disappear?

**Comment by dave-dave** [comment]
I was about to put in a pull request, but I agree that a little more clarity from Debian would be a better answer. Could take a little while.

**Comment by s0undt3ch** [comment]
I'm good with switching it to ftp, but my concern remains...

**Comment by dave-dave** [comment]
turned out to be a localised issue. http.debian.net is functioning again. Best as I can figure out, we were being redirected to a dead mirror. It is working again.

**Comment by s0undt3ch** [comment]
OK. Thanks for getting back with that information.
