### ISSUE TITLE
Installing Salt Master with bootstrap from git develop doesn't install init scripts

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt-bootstrap#58]
Running CentOS 6.3.

Following the documentation, I attempted to install a salt-master from git develop using the following command:

```
curl -L http://bootstrap.saltstack.org | sudo sh -s -- -M -N git develop
```

Everything seemed to work fine, except that `service salt-master start` failed.

salt-master is indeed installed, but there is no salt-master init script in /etc/init.d/

Looking back at the install output I did notice one error:

```
 *  INFO: Running install_centos_git_post()
error reading information on service salt-master: No such file or directory
```

I think it's looking at the wrong source location for the init scripts.

**Comment by UtahDave** [comment]
I manually ran the steps here: https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L1096

and salt then runs fine.

**Comment by s0undt3ch** [comment]
@UtahDave Thanks! I'll investigate this in a few hours.

**Comment by UtahDave** [comment]
This same thing happens when installing the minion on CentOS 6.3 from git develop
