### ISSUE TITLE
git v2015.2 is using old commit dc778a8e from Dec 23, 2014

### ISSUE THREAD

**Issue by steverweber** [saltstack/salt-bootstrap#581]
`sudo curl -L http://bootstrap.saltstack.com | sudo sh -s -- git v2015.2`

```
 *  INFO: Attempting to shallow clone v2015.2 from Salt's repository git://github.com/saltstack/salt.git
Cloning into 'salt'...
Note: checking out 'dc778a8e5e1c6786e08df6fb6b9948a7b894ca6c'.

You are in 'detached HEAD' state. You can look around, make experimental ...

 *  INFO: Cloning Salt's git repository succeeded
 *  INFO: Running config_salt()
 *  INFO: Running install_ubuntu_git()
2015.2.0
```

This 'dc778a8' is a old commit in . Dec 23, 2014.... not the latest v2015.2 commit!

https://github.com/saltstack/salt/commits/dc778a8e5e1c6786e08df6fb6b9948a7b894ca6c

Should be cloning from a commit like:

https://github.com/saltstack/salt/commits/921a0e9da7f601c476bbbf2afa08c57b6c516e5d

Thanks!

**Comment by s0undt3ch** [comment]
To clone the branch remove the initial `v`. The v2015.2 tag is from when that branch was created.

**Comment by steverweber** [comment]
ah, no one should be using that :P
perhaps to reduce stupid people like me the README should have a more up todate example.

`sudo curl -L http://bootstrap.saltstack.com | sudo sh -s -- git 2015.2`
Thanks.

**Comment by s0undt3ch** [comment]
I should probably error out in these cases...
