### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by maguec** [saltstack/salt-bootstrap#582]
https://www.sslshopper.com/ssl-checker.html#hostname=bootstrap.saltstack.com

Common name: *.saltstack.com
SANs: *.saltstack.com, saltstack.com
Valid from April 16, 2014 to April 17, 2015

Note this is not the case on the main website

Common name: *.saltstack.com
SANs: *.saltstack.com, saltstack.com
Valid from April 5, 2015 to April 27, 2016
Serial Number: a528a9cb54790d7223d7b8044059a07d

**Comment by grahamgreen** [comment]
:+1:

**Comment by TronPaul** [comment]
:+1: was confused why my bootstrap didn't install salt-call.

**Comment by s0undt3ch** [comment]
Certificate updated. Thanks for reporting it.
