### ISSUE TITLE
please support https - https://bootstrap.saltstack.org

### ISSUE THREAD

**Issue by steverweber** [saltstack/salt-bootstrap#586]
please support https - https://bootstrap.saltstack.org
only http://bootstrap.saltstack.org is working..

**Comment by cro** [comment]
Hi @steverweber -- You can use https://bootstrap.saltstack.com -- it has the right certificate attached and everything and goes to the same place that the .org does.

I'm going to close this but reply if I didn't cover your issue.

**Comment by steverweber** [comment]
thanks!
