### ISSUE TITLE
salt-cloud bootstrap RHEL6 fails due to missing python-jinja2 - catch22

### ISSUE THREAD

**Issue by bradthurber** [saltstack/salt-bootstrap#587]
I'm using salt-cloud to spin up an EC2 RHEL 6. salt-cloud calls salt bootstrap which tries to install python-jinja2 and fails due to not being subscribed to "RHEL Server Optional Channel"; however, at this point, the machine has not yet registered a license with the Red Hat Subscription Manager so we can't subscribe to this channel.

RHEL 7 doesn't have this problem. RHEL 6 does have `python-jinja2-26` in `epel`. (version 2.6.3.el6). Would this be sufficient for Salt or do we need 27?

**Comment by s0undt3ch** [comment]
I believe this has been fixed in the develop version of the scrip soon to be pushed as stable. Please comment and I'll re-open the issue if not.
