### ISSUE TITLE
ubuntu lucid packages at launchpad are broken

### ISSUE THREAD

**Issue by joehealy** [saltstack/salt-bootstrap#594]
Unfortunately, the final (ie now we are post EOL and launchpad no longer accepts new packages) packages in launchpad for ubuntu lucid are broken.
I have copied everything across to debian.saltstack.com, so for lucid, it will be similar to adding a wheezy system:

deb http://debian.saltstack.com/debian lucid-saltstack main

added to an apt config file.

**Comment by joehealy** [comment]
Also, not sure how we want to deal with this as lucid is now EOL...

**Comment by s0undt3ch** [comment]
My guess is to keep it as long as we package for it and then also turn it in a eol support in the bootstrap script...

**Comment by ryanwalder** [comment]
12.04.5 EOL isn't until 2017

| Version | Code name | Docs | Release date | End of life date |
| --- | --- | --- | --- | --- |
| Ubuntu 12.04.5 LTS | Precise Pangolin | Rel | August 7, 2014 | April 2017 |

https://wiki.ubuntu.com/Releases

**Comment by s0undt3ch** [comment]
We were talking about lucid, not precise.

**Comment by ryanwalder** [comment]
Whoops my bad! Its been a long day, apologies.

**Comment by s0undt3ch** [comment]
No worries @ryanwalder :)

**Comment by s0undt3ch** [comment]
We have dropped support for Ubuntu EOL versions. All Ubuntu version before 12.04.
