### ISSUE TITLE
Stable-branch bootstrap returns "need to allow pip installations" on debian/wheezy

### ISSUE THREAD

**Issue by thenewwazoo** [saltstack/salt-bootstrap#597]
As illustrated in gist https://gist.github.com/thenewwazoo/ef96e4a4cc5212586bd8, running the bootstrap script on

``` bash
master:/etc/salt$ uname -a
Linux master 3.2.0-4-amd64 #1 SMP Debian 3.2.46-1 x86_64 GNU/Linux
master:/etc/salt$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.4 (wheezy)
Release:    7.4
Codename:   wheezy
```

Returns the following error:
`* ERROR: You need to allow pip based installations (-P) in order to install requests`
when invoked as

``` bash
master:/etc/salt$ curl -n -L https://bootstrap.saltstack.com > bootstrap-salt.sh
master:/etc/salt$ chmod +x bootstrap-salt.sh 
master:/etc/salt$ sudo ./bootstrap-salt.sh -M stable
```

Executing the current develop version (from https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh) installs cleanly.

**Comment by s0undt3ch** [comment]
You hit a time frame where the develop branch was not yet merged as stable and released.

Please try stable again as this issue should be solved now. Closing. Please reopen if this is not the case.
