### ISSUE TITLE
Installation fails on Debian 7 due to missing easy_install

### ISSUE THREAD

**Issue by wwentland** [saltstack/salt-bootstrap#598]
The bootstrap script currently runs into the following error when installing salt on Debian 7 in Vagrant:

This happens when passing `-P` to enable pip installs, which was necessary to be able to install a, yet unpacked, python-requests version. It is, apparently, not really necessary to install that particular version (cf. 7fc5adfb9f326a5604a1ff522c665bd1d08ddfb2) which was introduced earlier in 1d09eaeb5d75d9ec2d268cd0968da73c3f3662ba to "Make sure that a recent enough requests package is installed in Debian/Ubuntu".

```
[…]
Setting up python-yaml (3.10-4+deb7u1) ...
Setting up rsync (3.0.9-4) ...
update-rc.d: using dependency based boot sequencing
Setting up salt-common (2014.7.5+ds-1~bpo70+1) ...
Setting up salt-master (2014.7.5+ds-1~bpo70+1) ...

Configuration file `/etc/salt/master'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
 ==> Using current old file as you requested.
Starting salt master control daemon: salt-master.
Setting up salt-minion (2014.7.5+ds-1~bpo70+1) ...

Configuration file `/etc/salt/minion'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
 ==> Using current old file as you requested.
Starting salt minion control daemon: salt-minion.
Processing triggers for python-support ...
sh: 2443: easy_install: not found
 * ERROR: Failed to run install_debian_7_stable()!!!


Stderr from the command:

```

Luckily one doesn't actually have to pass `-P` these days anymore, so that an installation is still possible. I'd recommend fixing the script in such a way that python-setuptools is installed _before_ one tries to use `easy_install`. That being said: Just because pip doesn't work as expected on Squeeze, doesn't necessarily mean that one should continue using `easy_install` on Wheezy, Jessie or later releases.

**Comment by s0undt3ch** [comment]
Thanks for reporting this.

**Comment by wwentland** [comment]
@s0undt3ch Thanks for fixing it and your ongoing work in general.

**Comment by s0undt3ch** [comment]
Anytime!
