### ISSUE TITLE
running bootstrap may break apt sources on Debian 6.0

### ISSUE THREAD

**Issue by sivann** [saltstack/salt-bootstrap#60]
```
install_debian_6_0_deps() {
    echo "deb http://backports.debian.org/debian-backports squeeze-backports main" >> \
        /etc/apt/sources.list.d/backports.list
```

The above adds multiple times the same source if it already exists or if running the bootstrap more than once. This has the side-effect of breaking apt-get update on some debian 6 systems. I haven't found out how. Removing the duplication fixes the problem.

**Comment by arnisoph** [comment]
I can confirm, that the repository will be added without a check against its existence in the sources list(s). "apt-get update" displays an error message (but doesn't abort).

The bootstrap file adds backports.file, but the source exists already in /etc/apt/sources.list (on my systems).

**Comment by s0undt3ch** [comment]
Yes, you are correct. Will be fixed.
