### ISSUE TITLE
Support setting multiple masters via -A

### ISSUE THREAD

**Issue by hubez** [saltstack/salt-bootstrap#600]
Can it gain support to allow specifying multiple masters? It is to handle high-availability cases when we'd like to spawn more EC2 instances (such as via an EC2 Autoscaler) when a salt-master is offline.

I propose being able to specify -A multiple times. For example:

```
salt-bootstrap.sh -A mymaster1 -A mymaster2
```

Results in:
/etc/salt/minion.d/99-master-address.conf

```
master:
  - mymaster1
  - mymaster2
```

**Comment by rallytime** [comment]
@hubez The `-j` option should be able to handle this nicely for you. The `-j` option allows you to pass in a custom minion configuration file as a json dict, which you can use to pass the the two masters in:
```
sh install_salt.sh -j '{"master": ["mymaster1", "mymaster2"], "id": "my-minion-id"}'
```

See #841 for the change. Note that the option will write over your existing minion config (but makes a reasonable attempt to create a .bak file).

**Comment by hubez** [comment]
@rallytime: That is perfect! I never noticed the -j before. 

Solved. And Thank you.

**Comment by rallytime** [comment]
@hubez Awesome!

That is a new-ish feature, that definitely went in since you filed this. :) Glad it works for you!
