### ISSUE TITLE
Ubuntu 12.04 needs newer PyZMQ and ZMQ versions installed

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-bootstrap#603]
When bootstrapping a new Ubuntu 12.04 machine, the latest stable version of the bootstrap script isn't pulling in newer versions of PyZMQ and ZMQ. It is defaulting to old versions.

Bootstrap version:

```
# sh salt.sh -v
salt.sh -- Version 2015.05.07
```

Salt Version that is installed by the bootstrap script:

```
# salt --versions
           Salt: 2015.5.0-591-g429adfe
         Python: 2.7.3 (default, Feb 27 2014, 19:58:35)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.4.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 2.1.11
           RAET: Not Installed
            ZMQ: 2.1.11
           Mako: Not Installed
```

I ran across this because my minions, after being provisioned via salt-cloud were not receiving events from the master after the initial installation, even though the minion process was running. ZMQ 2.x is too old.

ping @s0undt3ch

**Comment by rallytime** [comment]
Looks like the regression has happened since bootstrap stable version `2015.03.15`. That version of the bootstrap script installs ZMQ and PyZMQ newer versions correctly. (Here's the versions report of a minion setup with the older script:

```
# salt --versions
                         Salt: 2015.5.0
                    Python: 2.7.3 (default, Feb 27 2014, 19:58:35)
                    Jinja2: 2.6
                  M2Crypto: 0.21.1
            msgpack-python: 0.1.10
              msgpack-pure: Not Installed
                  pycrypto: 2.4.1
                   libnacl: Not Installed
                    PyYAML: 3.10
                     ioflo: Not Installed
                     PyZMQ: 14.0.1
                      RAET: Not Installed
                       ZMQ: 4.0.4
                      Mako: Not Installed
     Debian source package: 2015.5.0+ds-1precise1
```

**Comment by s0undt3ch** [comment]
I believe this might be fixed with the latest stable release of the script:

```
root@pedro-test-ubuntu-12:~# sh bs.sh -v
bs.sh -- Version 2015.07.17
root@pedro-test-ubuntu-12:~# salt --versions-report
Salt Version:
           Salt: 2015.8.0rc1-387-g5c94fe3

Dependency Versions:
         Jinja2: 2.6
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.3 (default, Jun 22 2015, 19:33:41)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.1.10
       pycrypto: 2.4.1

System Versions:
           dist: Ubuntu 12.04 precise
        machine: x86_64
        release: 3.2.0-86-generic
         system: Ubuntu 12.04 precise

root@pedro-test-ubuntu-12:~# 
```

**Comment by s0undt3ch** [comment]
@rallytime please reopen if you still see this happening.

**Comment by s0undt3ch** [comment]
Ok, you're not getting the newer versions because for stable installations you also need to pass `-Z`

```
  -Z  Enable external software source for newer ZeroMQ(Only available for RHEL/CentOS/Fedora/Ubuntu based distributions)
```

**Comment by rallytime** [comment]
@s0undt3ch We didn't need to pass `-Z` before...why do we need to pass that in now? Is there no way to go back to the previous behavior?

It works if you pass in the `-Z`, but does not work without it.

**Comment by s0undt3ch** [comment]
I only enforce -Z because its an external repo. Once we host our dep chain, we won't need that flag anymore.

**Comment by rallytime** [comment]
OK sounds good. I wondered if we could just do what we were doing before, but that makes sense. Hopefully that will be soon. :)

**Comment by s0undt3ch** [comment]
Though, we do use other external repos without requiring a flag...

**Comment by rallytime** [comment]
Yeah...
