### ISSUE TITLE
salt-cloud bootstrap error on Debian 7.8

### ISSUE THREAD

**Issue by bogdanr** [saltstack/salt-bootstrap#604]
Hello,

Using salt-cloud 2015.5.0, while trying to spawn some instances on AWS I get the following error:

```
You need to allow pip based installations (-P) in order to install requests
```

The complete error is this: http://hastebin.com/tihocabiwo

I was able to spawn many instances a few months ago with an older salt-cloud version and it work flawlessly.

**Comment by pierluca** [comment]
I experinece the same problem on a different IaaS provider, same salt-cloud version.

**Comment by s0undt3ch** [comment]
Recent versions of Salt require a recent version of tornado, that's why you get that error message. You need to pass that flag.

**Comment by bogdanr** [comment]
@s0undt3ch how do you pass the flag from salt-cloud?

**Comment by s0undt3ch** [comment]
On your profile configuration add:

``` yaml
<your_cloud_profile_name>:
  script_args: -P
```
