### ISSUE TITLE
SSL Certificate Error

### ISSUE THREAD

**Issue by dgn** [saltstack/salt-bootstrap#605]
When starting minions via salt-cloud, while bootstrapping I get an error message saying that the SSL certificate I get when querying "bootstrap.saltstack.com" is for "wpengine.com". Looks like a man-in-the-middle attack, full error is here: https://gist.github.com/dgn/e1d5ef98f4acf559807f

Note that bootstrapping seems to work still (?!)

**Comment by jfindlay** [comment]
@dgn, thanks for the report.  This problem should have been fixed a while ago.  Can you confirm?

**Comment by dgn** [comment]
nope, abandoned salt-cloud. you can close if you like
