### ISSUE TITLE
SmartOS doesn't detect missing git, fails install

### ISSUE THREAD

**Issue by BretFisher** [saltstack/salt-bootstrap#611]
On a fresh SmartOS machine, install fails due to not having `git` installed, but script thinks it is.

In `bootstrap-salt.sh` on SmartOS, the `which` binary doesn't work as it does on Linux and returns a string rather then `null`. This trips the script into thinking `git` is installed, even though it isn't. Current bootstrap-salt.sh:

``` bash
install_smartos_git_deps() {
    install_smartos_deps || return 1
    if [ "$(which git)" = "" ]; then
        pkgin -y install scmgit || return 1
    fi
```

https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L4172

I'm not sure how to fix it using the return string compare as used throughout the script. Here's what SmartOS `which` returns:

`which git`
`no git in /usr/local/sbin /usr/local/bin /opt/local/sbin /opt/local/bin /usr/sbin /usr/bin /sbin`

And here are alternatives to using `which` to determine if a binary exists.
http://stackoverflow.com/questions/592620/check-if-a-program-exists-from-a-bash-script

I'm happy to submit patch but first what to see which way team is leaning on the solution. This is a working replacement in my testing:

``` bash
command -v git >/dev/null 2>&1 || { pkgin -y install git; }
```

**Comment by jfindlay** [comment]
Shouldn't it be `if [ "$(which git)" == "" ]; then`?  Linux has a similar return statement to what you've posted when it cannot find the executable on the path, which means that `which` will never return an empty string, so I don't understand what this code is expecting.  I am in favor of using a builtin if it is guaranteed to be available in that platform's 'posix' shell offering.

**Comment by BretFisher** [comment]
How would compare look if we just looked for "no git" in the return string?

**Comment by jfindlay** [comment]
@BretFisher, I'm willing to accept that solution, although after closer inspection, it seems, at least on linux, that `which` returns the `... no git in ...` string to stderr rather than stdout, which makes sense.

**Comment by s0undt3ch** [comment]
I can't remember right now but `commmand -v` might not be portable, I'd have to check.

How about passing `--version` or `-v` to `git` while redirecting errors to `/dev/null`?

An empty string would mean a missing git binary, right?

**Comment by BretFisher** [comment]
Right, I know we're striving for consistency but this would be a smartos-only solution under `install_smartos_git_deps() {` I'm thinking.

**Comment by s0undt3ch** [comment]
If this is remains a smartos only solution, I have no problems with it. Can you please submit a pull request with your fix?

**Comment by BretFisher** [comment]
Yes, sorry, should have some time this month to submit PR for this and a few other SmartOS fixes.

**Comment by johngrasty** [comment]
Couldn't you just test on exit codes? `which` on illumos distributions  returns `0` when it successfully finds something. It exits `1` when it doesn't. So…

```
    if [ 'which git' ]; then
        pkgin -y install git || return 1
    fi
```

I'm an amateur, so don't feel bad correcting me, but that seems simple and reliable.

**Comment by s0undt3ch** [comment]
The correct sh would be something like:

``` sh
    if [ $(which git) -eq 1 ]; then
        pkgin -y install git || return 1
    fi
```

And I'm cool with it if it also works for SmartOS...

**Comment by johngrasty** [comment]
@s0undt3ch I don't think so. (Though I am not saying that mine is correct either :-) )

 With `if [ $(which git) -eq 1 ]`, `-eq` is going to be expecting an integer and will fail with the string output of `$(which git)`.

**Comment by s0undt3ch** [comment]
hmm, forgot to redirect output

**Comment by s0undt3ch** [comment]
``` sh
GIT=$(which git)
if [ $? -eq 1 ]; then
    ....
fi
```

**Comment by johngrasty** [comment]
Now that works! Thanks. 

I've just spent some time reading some man pages. To get a working version of my test would be:

```
if which git; then
    true;
    else 
        pkgin -y install git || return 1
fi
```

Thanks for excuse to spend some time learning new stuff!
