### ISSUE TITLE
Cleanup when switching between salt versions with bootstrap

### ISSUE THREAD

**Issue by bradthurber** [saltstack/salt-bootstrap#614]
Does bootstrap cleanup properly when switching between salt versions? If I go from v2015.5.2 to develop then back to v2015.5.2 via bootstrap for example is that a safe operation, or are manual cleanup steps necessary (deleting /var/cache/salt for example)?

If manual steps are necessary, can they be added to bootstrap?

**Comment by s0undt3ch** [comment]
The intention of the script is to bootstrap a system. Switching versions is out of the scope of the script, however its usually a safe process to switch versions and no manual clean up routines should be necessary(but I might be wrong).
