### ISSUE TITLE
SmartOS base-64 15.1.1    /etc/salt should be /opt/local/etc/salt

### ISSUE THREAD

**Issue by fractaluniverse** [saltstack/salt-bootstrap#615]
#### SMF manifest installed by salt-bootstrap specifies correct directory

```
# svccfg export salt-minion | grep name=\'config_dir\'
      <propval name='config_dir' type='astring' value='/opt/local/etc/salt'/>
```
#### Salt configuration at /etc/salt but not /opt/local/etc/salt

```
# ls -ld /etc/salt /opt/local/etc/salt
ls: cannot access /opt/local/etc/salt: No such file or directory
drwxr-xr-x 3 root root 5 Jun 26 08:36 /etc/salt
```
#### temporary work-around

```
ln -s /etc/salt /opt/local/etc/salt
```

**Comment by BretFisher** [comment]
@fractaluniverse This looks to be same as https://github.com/saltstack/salt/issues/22634 which was fixed  in PR https://github.com/saltstack/salt/pull/22635 and avail in v2015.2 it looks like.

**Comment by johngrasty** [comment]
Hmmm.… @BretFisher I see that your fix made into v.2015.5.2, but I just spun up a new zone to test the `which git` that I suggested, and I still ran into this. The config directory was at `/etc/salt`

**Comment by BretFisher** [comment]
Are you on wrong issue @johngrasty? the git issue is still unresolved: https://github.com/saltstack/salt-bootstrap/issues/611. This issue was about wrong etc path.

**Comment by johngrasty** [comment]
@BretFisher I was actually working on three different ones. Once I realized that you installed v2015.5.2 via git and the bootstrap script, I intended to do that to check on the file.managed issue saltstack/salt#20687. You were correct that the file.managed bug was resolved.

In installing though, I ran into two different issues with the bootstrap script. This one (the path issue) and the git issue: #611. Though I see your fix committed for v.2015.5.2 (or .3, I can't remember which), I still had the same path issue with a fresh install of salt with a fresh base zone. 

Regarding the git issue, I think that I may have a simplified fix for that in [this comment](https://github.com/saltstack/salt-bootstrap/issues/611#issuecomment-120308099).

Thanks for your help!

**Comment by BretFisher** [comment]
Right, so if you're a SaltStack user on SmartOS, and to a certain extent, Joyent Public Cloud, I'm tracking these issues:

### Open
- https://github.com/saltstack/salt-bootstrap/issues/611 - always thinks git is installed
- https://github.com/saltstack/salt-bootstrap/issues/613 - /tmp/git/salt isn't removed
- https://github.com/saltstack/salt-bootstrap/issues/473 - list of issues from others
- https://github.com/saltstack/salt/issues/22518 - JPC support for RBAC auth
- https://github.com/saltstack/salt/issues/10959 - Broken Cron? also broke passed -N

### Recently Fixed
- https://github.com/saltstack/salt/issues/22634 - wrong config dir
- https://github.com/saltstack/salt-bootstrap/pull/612 - install libcloud
- https://github.com/saltstack/salt/pull/24918 - SMF xml for proper start

### New, not posted yet
- add user to group doesn't work with salt
- turning off password auth for user doesn't have a salt state (see 10959 above)
- Try out how JPC lx would work with salt
