### ISSUE TITLE
Salt build for ubuntu is broken (TypeError: any() takes exactly one argument)

### ISSUE THREAD

**Issue by amitlicht** [saltstack/salt-bootstrap#617]
Latest ubuntu build from July 2 (2015.5.2) contains a bug:
An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1563, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/rabbitmq_vhost.py", line 84, in present
                  if any(user, owner, conf, write, read):
              TypeError: any() takes exactly one argument (5 given)

This is due to a bug in /usr/lib/python2.7/dist-packages/salt/states/rabbitmq_vhost.py which has already been fixed, but the deployment was created on a broken version (v2015.0.2).

**Comment by s0undt3ch** [comment]
So this isn't actually a bug in the bootstrap script right? Or better, what's the behaviour of the bootstrap script that you were expecting?

**Comment by amitlicht** [comment]
Perhaps your right. However there isn't really a "salt-ubuntu"\"salt-linux" project to which this bug is directly relevant, so maybe you can help with advising which part of the project this relates to.

**Comment by s0undt3ch** [comment]
This issue is now being tracked in https://github.com/saltstack/salt/issues/25287
