### ISSUE TITLE
README cleanup / confusion: "install specific version" mentioned twice, but only once with '-P'

### ISSUE THREAD

**Issue by jf** [saltstack/salt-bootstrap#620]
As per subject:

Under `Examples`, the example of installing a specific version from git is first mentioned using wget:

Install a specific version from git using `wget`:

```
wget -O install_salt.sh https://bootstrap.saltstack.com
sudo sh install_salt.sh -P git v0.16.4
```

Notice how `-P` is passed to the install script. If you scroll down some more, the example of installing a specific version from git is mentioned again, only this time, with different instructions; **and** the install script is now called without `-P`:

If you want to install a specific release version (based on the git tags):

```
curl -o install_salt.sh -L https://bootstrap.saltstack.com
sudo sh install_salt.sh git v0.16.4
```

**Comment by s0undt3ch** [comment]
`-P` as seen when passing `-h` to the script to display it's help message, is used to allow pip based installations to be done in case they are needed, so, it's just an example usage, but yeah, I guess we should probably comment on why `-P` was used in that example.

**Comment by jf** [comment]
hm. Does this mean that you're planning to keep the 2 different sets of instructions for installing a specific version from git?
