### ISSUE TITLE
python-requests : Depends: python-urllib3 (>= 1.7.1) but it is not installable

### ISSUE THREAD

**Issue by JulianGindi** [saltstack/salt-bootstrap#632]
I am currently bootstrapping salt via the following command:

`wget -O - http://bootstrap.saltstack.org | sudo sh -s -- -P git develop`

and am running into the aforementioned error...

`python-requests : Depends: python-urllib3 (>= 1.7.1) but it is not installable`

I see some similar issues being discussed, but am unable to fix the issue I'm having by implementing the proposed solutions. Any advice on how to move forwards would be greatly appreciated.

**Comment by s0undt3ch** [comment]
Could you please test the latest development version to confirm the fix?

**Comment by b4hand** [comment]
What's the URL for the latest development version of the bootstrap script?

**Comment by b4hand** [comment]
Found the URL in the README: https://bootstrap.saltstack.com/develop

**Comment by s0undt3ch** [comment]
Yep, that's the one.

**Comment by b4hand** [comment]
So, yes, I was able to confirm this worked for me. Although, I think for my purposes, I'm going to pin our download to a known good prior sha for the bootstrap script to avoid future breakages.

**Comment by Moulde** [comment]
I get the above error when i try to provision the "django-salted" repo. (https://github.com/wunki/django-salted/).
I'm not sure how i use the above solution to fix the issues i have when vagrant attempts to provision the precise64 box.

Thanks in advance

**Comment by s0undt3ch** [comment]
I believe you must update your vagrant file to include `bootstrap_options: "-P"`

**Comment by b4hand** [comment]
@s0undt3ch: Actually, I think the Vagrant salt provisioner hard codes the URL for the salt bootstrap script to be the stable version:

https://github.com/mitchellh/vagrant/blob/master/plugins/provisioners/salt/bootstrap-salt.sh#L5

**Comment by Moulde** [comment]
I downloaded the develop bootstrap-salt script and configured vagrant to use the downloaded script instead of downloading the stable one.

The changes i made to the vagrantfile:

```
salt.bootstrap_script = "bootstrap-salt.sh"
salt.bootstrap_options = "-P"
```

This seems to fix the issue for me.

**Comment by Phlip** [comment]
here to confirm @Moulde 's workaround, on Vivid Vervet on amd64

**Comment by jpic** [comment]
For some reason that doesn't work on travis: https://travis-ci.org/saltstack-formulas/jenkins-formula/jobs/74122862

Any idea ?

saltstack-formulas/jenkins-formula#26

**Comment by s0undt3ch** [comment]
The next travis build, as long as it pulls the latest stable, should run(make sure to pass `-P` to the bootstrap script.
