### ISSUE TITLE
salt-bootstrap fails with latest salt develop branch on RHEL 6.6

### ISSUE THREAD

**Issue by bradthurber** [saltstack/salt-bootstrap#639]
I had to install the develop branch of salt on RHEL 6.6 to test a PR. After install I received the following error:

```
  File "/usr/lib/python2.6/site-packages/salt/transport/mixins/auth.py", line 22, in <module>                    
    from Crypto.Cipher import PKCS1_OAEP                                                                         
ImportError: cannot import name PKCS1_OAEP    
```

It took quite a bit of remove/install work to get the minion to startup on latest develop. Listing what I did here in case it is helpful to someone:

```
 yum remove python-crypto
 yum install python-pip
 yum install python2-devel
 yum install gmp-devel
 yum install libsodium
 salt-bootstrap git develop
 pip install pycrypto --upgrade
```

**Comment by vutny** [comment]
@bradthurber  `python-crypto` packages for RHEL systems were updated recently on SaltStack main repo: https://repo.saltstack.com/yum/. Looks like that workaround is no longer required, so issue can be closed.

**Comment by vutny** [comment]
Ping @jfindlay

**Comment by bradthurber** [comment]
@vutny I'm using latest "develop" version of salt-bootstrap without issue on RHEL 6.7 systems. Agree this can be closed.
