### ISSUE TITLE
Salt bootstrap documentation is out of date

### ISSUE THREAD

**Issue by VynceMontgomery** [saltstack/salt-bootstrap#641]
running the bootstrap script with no argument fails for me on ubuntu 14.04, saying i must specify -P. In addition, something is unclear here: 

```
$ bootstrap_salt.sh stable 2014.7
<...>
$ salt-minion --version
salt-minion 2015.5.2 (Lithium)
```

**Comment by s0undt3ch** [comment]
The documentation states some scenarios, and when required versions are not available as system packages, the -P is used to allow installation of packages from PyPi which should be explicitly passed. This is the case with the latest stable release but next stable release might have already overcome that necessity.

Regarding you comment about being unclear, `stable` is used for stable releases, commonly the latest stable. Recently support was added to install the latest stables from a specific PPA(in case it's available).
The [2014.7 PPA](https://launchpad.net/~saltstack/+archive/ubuntu/salt2014-7) does not include packages for Ubuntu 14.04, hence, the latest stable was the one installed.
