### ISSUE TITLE
Systemd ubuntu 15.04 error

### ISSUE THREAD

**Issue by gruaig** [saltstack/salt-bootstrap#646]
Hey we are using ubuntu 15.04 with up-start and not systemd which is enabled by default.
The problem occurs here  line 2016 

``` sh
if [ -f /bin/systemctl ] && [ "$DISTRO_MAJOR_VERSION" -ge 15 ]; then
            echodebug "There's systemd support while checking salt-$fname"
            systemctl stop salt-$fname > /dev/null 2>&1
            systemctl start salt-$fname.service
```

As installing up-start does not remove the files the bootstrap will actually fail after this. To get around this I removed the /bin/systemctl file. Works fine afterwards.

Maybe we should put in a better check to see if its upstart or systemd that is actually enabled

**Comment by rallytime** [comment]
Hi @gruaig Apologies for never actually responding to you issue here. I am not sure how I missed commenting on this.

I was just going through some of our older issues and came across this. The 15.04 release has reached EOL with Ubuntu, and as such we are no longer supporting it with the bootstrap script or Salt packages either. 

I have updated the bootstrap script and README to be more helpful with docs and error messages in #1002 to reflect this support policy. As such, we won't be fixing this issue. Is it alright with you if we close this issue? Or are you seeing this issue on any of the LTS Ubuntu releases?
