### ISSUE TITLE
Bootstrapping in CentOS not possible because COPR was down.

### ISSUE THREAD

**Issue by bemeyert** [saltstack/salt-bootstrap#651]
Today copr was down for some time. At this time I wasn't able to bootstrap any of my CentOS Vagrant-boxes. Here the last few lines:

```
 *  INFO: Found function install_centos_check_services
 *  INFO: Running install_centos_stable_deps()
 *  INFO: Adding SaltStack's COPR repository
 * ERROR: Failed to run install_centos_stable_deps()!!!
```

Digging through the code I found out that the COPR repo files must be downloaded. Otherwise the scrip fails. Is this the desired behaviour?

**Comment by s0undt3ch** [comment]
It is the desired behavior, but we're getting close to provide a more stable source for the packages we need for the several distributions that we support.

**Comment by bemeyert** [comment]
@s0undt3ch Thanks a lot for the info. There's a light somewhere :-)

**Comment by bemeyert** [comment]
Damn, forgot to close this one....

**Comment by bemosior** [comment]
I encountered this error this evening. In case it's helpful to anyone, I checked http://status.fedoraproject.org/, and there was an entry for COPR stating it would be down for maintenance: https://fedorahosted.org/fedora-infrastructure/ticket/4908
