### ISSUE TITLE
Bootstrap Fails on Joyent Ubuntu 14.04 images

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-bootstrap#652]
This appears to be something going on with upstart on these particular images, as I don't see this on EC2 or Linode Ubuntu images. Basically the daemons fail to start because upstart doesn't think salt exists, even though the files are there. 

Running `/sbin/initctl reload-configuration` manually on the box and then `start salt-minion` allows the minion to start successfully.

I tried adding this change to my bootstrap script to see if it helps, but it's not quite right: https://github.com/s0undt3ch/salt-bootstrap/commit/997c72285076ea27aed4dfa9b830d80a718eb7c3

This might also be the same thing happening in #648. It looks similar and could explain what is happening there.

@s0undt3ch

**Comment by vutny** [comment]
@rallytime Is this still an issue?

**Comment by vutny** [comment]
@rallytime bump

**Comment by rallytime** [comment]
I'm not sure. I haven't had a chance to test this again, but I'll try to get to it in the next couple of days.

**Comment by rallytime** [comment]
Woo! This works now. Thanks for the bump @vutny. Closing.

**Comment by Ch3LL** [comment]
I'm re-opening this again because I'm seeing this error with the bootstrap only on joyent ubuntu14 image:

```
[20:22:49,888][salt.utils.vt.Terminal.PID-2411.STDERR   :657 ][DEBUG   ] Connection to 72.2.114.83 closed.
 * ERROR: salt-minion was not found running
 * ERROR: Failed to run daemons_running()!!!
 * ERROR: salt-minion was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
[20:22:49,889][salt.utils.vt.Terminal.PID-2411.STDOUT   :690 ][DEBUG   ]  * ERROR: salt-minion was not found running
 * ERROR: Failed to run daemons_running()!!!
 * ERROR: salt-minion was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
```

Here is my profile information:

```
[root@li983-166 clouds]# cat /etc/salt/cloud.profiles.d/joyent.conf 
joyent-test:
  provider: joyent-config
  size: Extra Small 512 MB
  image: ubuntu-certified-14.04
  location: us-east-1
  script_args: '-P -Z'
```

**Comment by rallytime** [comment]
It seems these images change somewhat frequently...I tested this again just now and it is working as expected. Closing.
