### ISSUE TITLE
Debian 8 Bootstrap points to old reop

### ISSUE THREAD

**Issue by samhamilton** [saltstack/salt-bootstrap#659]
If you run `# salt-cloud -m cloud.map` for a Debian 8 minion then the bootstrap script uses the old repo address of http://debian.saltstack.com instead of the updated address http://repo.saltstack.com as per your [docs here](https://docs.saltstack.com/en/latest/topics/installation/debian.html) which then means it installed Salt 2015.5.3 instead of the latest 2105.8 which the master (also on Debian) is running.

**Comment by jfindlay** [comment]
@samhamilton, thanks for the report.

**Comment by s0undt3ch** [comment]
The migration of the script to the new repository is scheduled and should soon be complete.

**Comment by alxbse** [comment]
I'm currently stuck on a use-case with this as a blocker. Is there a time estimate on when i might be resolved? Anything I can do to help?

**Comment by gerhardqux** [comment]
here's a temporary patch to get it to work on jessie.
  https://gist.github.com/gerhardqux/099dd81cf424e8757f36

**Comment by s0undt3ch** [comment]
While the work us not complete and it doesn't land in the stable branch, use this:

https://github.com/s0undt3ch/salt-bootstrap/blob/develop/bootstrap-salt.sh

**Comment by jfindlay** [comment]
@samhamilton, @alxbse, #674, updates bootstrap to work with repo.saltstack.com.

**Comment by s0undt3ch** [comment]
#674 was merged. Closing. Please re-open if necessary.
