### ISSUE TITLE
CentOS 6 points to old repo

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-bootstrap#668]
Similar to #659, the bootstrap script points to the [COPR repo](https://copr.fedoraproject.org/coprs/saltstack/salt/) instead of the new updated address http://repo.saltstack.com. This means that 2015.5.2 is getting installed for CentOS 6 (and likely other versions as well) instead of 2015.8.0 or newer.

**Comment by jfindlay** [comment]
This should be fixed by #674.

**Comment by s0undt3ch** [comment]
#674 was merged. Closing. Please re-open if necessary.
