### ISSUE TITLE
Migrate to new Ubuntu repo to allow installation of 2015.8

### ISSUE THREAD

**Issue by dferramosi** [saltstack/salt-bootstrap#672]
The old ppa doesn't have it.

**Comment by jfindlay** [comment]
@dferrantelli, thanks for the report.  With 2015.8.0 and beyond we're providing packages from https://repo.saltstack.com/.  #674 points bootstrap to repo.saltstack.com for the latest ubuntu versions.

**Comment by s0undt3ch** [comment]
#674 was merged. Closing. Please re-open if necessary.
