### ISSUE TITLE
Debian 8 Jessie uses old apt repository

### ISSUE THREAD

**Issue by marek-obuchowicz** [saltstack/salt-bootstrap#675]
While installing on debian 8.0 (jessie), salt-bootsrap uses apt repository:
`deb http://debian.saltstack.com/debian jessie-saltstack main`

which has only 2015.5.3 at the moment.
Official saltstack repository is now:
`deb http://repo.saltstack.com/apt/debian/latest jessie main`

(instead of latest, `2015.8` or `2015.5` can be used to install specific version)

**Comment by jfindlay** [comment]
@marek-obuchowicz, thanks for the report.  This should be fixed by #674.

**Comment by s0undt3ch** [comment]
#674 was merged. Closing. Please re-open if necessary.
