### ISSUE TITLE
Can you build packages for FreeBSD:11 / CURRENT?

### ISSUE THREAD

**Issue by tony** [saltstack/salt-bootstrap#679]
http://repo.saltstack.com/freebsd/

ATM the install script has the function to attempt a freebsd install, but it will end up not not finding a repo since there is only 10 packages.

Is the system used to build the packages kept on gh?

**Comment by jfindlay** [comment]
@tony, thanks for the report.  @cedwards is our FreeBSD maintainer, so I would ask him.  I think we should get FreeBSD 11 support soon in any case.

**Comment by cedwards** [comment]
I can take care of this. I'll try to have it done for you by this weekend..

**Comment by s0undt3ch** [comment]
@cedwards Rocks!

**Comment by cedwards** [comment]
I've got packages built for 9, 10 and 11 now. I just need @UtahDave to replicate them out to the public repo server. Note: These packages are untested as I currently only have 10.x systems.

**Comment by cedwards** [comment]
These repositories are now available at https://repo.saltstack.com/freebsd/. Please, if you can, verify that the 11.x packages work as expected and then I think we can close this ticket.

**Comment by tony** [comment]
Yep.

11-CURRENT adds the package repo and installs everything nicely.

As always thanks for this software @cedwards and the saltstack team.
