### ISSUE TITLE
Unable to start minion

### ISSUE THREAD

**Issue by syedaali** [saltstack/salt-bootstrap#683]
During the last stage of bootstrap when using salt-cloud, I am getting the below error:

Configuration file '/etc/salt/minion'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
 ==> Using current old file as you requested.
salt-minion start/running, process 8726
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
Processing triggers for ureadahead (0.100.0-16) ...
-  INFO: Running install_ubuntu_check_services()
-  INFO: Running install_ubuntu_restart_daemons()
  salt-minion start/running, process 8775
-  INFO: Running daemons_running()
  Connection to X.X.X.X closed.
- ERROR: salt-minion was not found running
- ERROR: Failed to run daemons_running()!!!
- ERROR: salt-minion was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
  Error: There was a profile error: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oKbdInteractiveAuthentication=no -i /etc/salt/salt_cloud_key -p 22 ubuntu@X.X.X>X> \'sudo /tmp/.saltcloud-bb04963d-4c2f-4c42-9e02-e97c0e581a52/deploy.sh -c \'"\'"\'/tmp/.saltcloud-bb04963d-4c2f-4c42-9e02-e97c0e581a52\'"\'"\' -P\'' failed. Exit code: 1

**Comment by syedaali** [comment]
So the problem was the the master is running 2015.8.1 and it was installing 2015.5.3 on the minion. The line 'master_type: str' in /etc/salt/minion is not compatible with 2015.5.3. I forced 2015.8.1. client install using 'script_args: -P git v2015.8.1' in cloud.providers.d and it started to work.

**Comment by jfindlay** [comment]
https://github.com/saltstack/salt/issues/25335
