### ISSUE TITLE
Salt services not enabled?

### ISSUE THREAD

**Issue by thatch45** [saltstack/salt-bootstrap#69]
It does not appear that the salt services are being enabled to start at boot on non-debian based systems, anyone mind if I throw this in?

**Comment by s0undt3ch** [comment]
Well, throw away, it's a bug.

Services should be enabled. What distro was this?

**Comment by thatch45** [comment]
Sorry, I was meaning to get this in, it was on Fedora and RHEL

**Comment by s0undt3ch** [comment]
Thanks! I'll see if I take care of this ASAP.

**Comment by thatch45** [comment]
LOL, I just spent 2 hours trying to bootstrap fedora in salt virt and it does not work because this bug is still open :)

**Comment by s0undt3ch** [comment]
Well, 11 months for ASAP.... Still valid? :smile:

**Comment by s0undt3ch** [comment]
Fixed in 1aea3037740e25b23c7ec14e08171529fb625020
