### ISSUE TITLE
Install Failures With Raspbian Jessie

### ISSUE THREAD

**Issue by mtippett** [saltstack/salt-bootstrap#695]
On attempting to install on raspbian jessie, the following errors are found, they actually appear three times during the different apt-get update stages.

```
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en
W: Failed to fetch http://repo.saltstack.com/apt/debian/latest/dists/jessie/InRelease  Unable to find expected entry 'main/binary-armhf/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
 * ERROR: Failed to run install_debian_8_deps()!!!
```

The installation fails with the final message.

**Comment by mtippett** [comment]
Note that sh `./install_salt.sh -P -b git v2015.8.1` does work

**Comment by wolfpackmars2** [comment]
Doesn't appear the newer repository has the ARM packages available.

The old repository doesn't have the new release of Salt (past 2015.5)

The workaround is to install from Git.  Depending on the level of support for Raspbian, the bootstrapper either needs to be updated to handle Raspbian Jessie to install from git or the ARMHF packages need to be added to the repository.

Old repo:
http://debian.saltstack.com/debian/dists/

New Repo:
http://repo.saltstack.com/apt/debian/8/

**Comment by dmurphy18** [comment]
@wolfpackmars2 At present SaltStack is only building Intel based packages for repo.saltstack.com.  There is a new layout, with backwards support for the previous layout (tried to make sure we didn't break it this time).  Older versions are archived, e.g. http://repo.saltstack.com/staging/apt/debian/8/amd64/archive/2015.5.6

It is intended that other architectures shall be supported (hence the architecture field - amd64) eventually, but we need to complete the build automation tool and release it as open-source before that can occur.

**Comment by vutny** [comment]
@dmurphy18 I think we should mention explicitly in documentation the fact, that Salt binary dependencies for Debian only provided for `amd64` architecture from corporate repo.

**Comment by dmurphy18** [comment]
@vutny I shall bring the issue up. It also applies for Ubuntu as well.

**Comment by vim-zz** [comment]
i have been able to install latest salt only after using the following packages from raspbian:
http://archive.raspbian.org/raspbian/pool/main/s/salt/salt-common_2015.8.5%2bds-1_all.deb
http://archive.raspbian.org/raspbian/pool/main/s/salt/salt-minion_2015.8.5%2bds-1_all.deb

which then also requires to use jessie-backports as python-tornado 4 is not included in jessie

**Comment by vutny** [comment]
@dmurphy18 I've submitted couple of PRs with documentation update for Debian and Ubuntu. One of them is already merged, but the site still contains the old version: https://docs.saltstack.com/en/latest/topics/installation/debian.html
Should it be updated automatically or not?

**Comment by vutny** [comment]
@vim-zz As I see, Raspbian Stretch distribution (current testing) also includes recent Salt version like main Debian archive. Great. At least we could update the documentation to reflect this. Maybe installing packages from _testing_ on _stable_ as well...

**Comment by vutny** [comment]
@mtippett @vim-zz Unfortunately, current salt-bootstrap doen't support installation on Raspbian, but at least we got documentation updated with `salt-minion` installation instructions for Jessie from official Raspbian repo (Stretch package). Check it out (should be updated on the site soon): https://github.com/saltstack/salt/blob/2015.8/doc/topics/installation/debian.rst

**Comment by vim-zz** [comment]
@vutny great

**Comment by vutny** [comment]
Small corrections from PR saltstack/salt#31536 should be applied...

**Comment by rallytime** [comment]
@mtippett We recently added [Rasbian packages](http://repo.saltstack.com/#raspbian) to repo.saltstack.com. I am curious as to how the bootstrap script will run now. #905 is similar to this issue and I'll be working with @Ch3LL to test the bootstrap script out and see what updates need to happen to the bootstrap script.

**Comment by jeremywillden** [comment]
Not exactly solved, but found the source of the problem that I outline below.  Turns out the minions I was testing this on have a distribution of Raspbian older than the current one.  While it would be nice if the dependencies existed in the older distro, it will be easier to upgrade the distro than try to get the newer version of salt to work on the older distro (I think).  Leaving the rest of the comment below for the benefit of others who run into the same issue.

# 

Still having trouble installing even when using the armhf repo:
(used modified version of the instructions at [https://repo.saltstack.com/#debian](https://repo.saltstack.com/#debian) changing armhf out for amd64

```
pi@raspberry-pi> sudo apt-get install salt-minion
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 salt-minion : Depends: python-crypto (>= 2.6.1) but 2.6-4+deb7u3 is to be installed
               Depends: python-zmq (>= 13.1.0) but 2.2.0-1 is to be installed
               Depends: salt-common (= 2016.3.3+ds-1) but 0.10.1-3 is to be installed
               Recommends: dmidecode but it is not installable
E: Unable to correct problems, you have held broken packages.

```
