### ISSUE TITLE
Script flag to enable and use the saltstack provided repos

### ISSUE THREAD

**Issue by rbjorklin** [saltstack/salt-bootstrap#696]
For some of the bigger distributions Saltstack provides [repositories](https://docs.saltstack.com/en/latest/topics/installation/debian.html) with the latest version. It would be good if there was a flag to the bootstrap script to enable these before installation.

**Comment by wolfpackmars2** [comment]
I believe this is already the behavior, unless you explicitly install from GIT using the git option.  By default, the bootstrap script will determine which OS you are using and set up the package repositories accordingly.

**Comment by rbjorklin** [comment]
@wolfpackmars2 I tried using the script on Debian 8 and it installed the packages from the Debian repos and not the ones provided by Saltstack which is why I submitted this ticket.

**Comment by wolfpackmars2** [comment]
The script installs updates and dependencies from the official debian repositories.  It then adds the salt repos to apt, updates the cache, and installs salt.  I don't believe there is a copy of saltstack available in the repositories.  If a salt package was installed on your system, it came from SaltStacks repos. 

When you ran the bootstrap script, you should have seen something like this:
Get:20 http://repo.saltstack.com/apt/debian/latest/ jessie/main salt-minion all 2015.8.3+ds-1 [22.5 kB]

Which indicates salt-minion was installed from the saltstack repository.

If you received something different, then... I would scratch my head on that one.  If you saw something else, please post the output to the script.

**Comment by rbjorklin** [comment]
Could have sworn this wasn't working when I reported it but it seems to be working now.
