### ISSUE TITLE
Broken on Amazon Linux AMI 2015.09

### ISSUE THREAD

**Issue by francoisvdv** [saltstack/salt-bootstrap#703]
Hi,

I get the following:
-  INFO: sh install_salt.sh -- Version 2015.11.09
  -  INFO: System Information:
  -  INFO:   CPU:          GenuineIntel
  -  INFO:   CPU Arch:     x86_64
  -  INFO:   OS Name:      Linux
  -  INFO:   OS Version:   3.14.35-28.38.amzn1.x86_64
  -  INFO:   Distribution: Amazon Linux AMI 2015.09
  -  INFO: Installing minion
  -  INFO: Found function install_amazon_linux_ami_deps
  -  INFO: Found function install_amazon_linux_ami_stable
  -  INFO: Found function install_amazon_linux_ami_stable_post
  -  INFO: Found function install_amazon_linux_ami_restart_daemons
  -  INFO: Found function daemons_running
  -  INFO: Running install_amazon_linux_ami_deps()
    Retrieving http://mirrors.kernel.org/fedora-epel/6/x86_64/epel-release-6-8.noarch.rpm
    Preparing...                          ########################################
    Updating / installing...
    epel-release-6-8                      ########################################
  -  INFO: Adding SaltStack's COPR repository
  - ERROR: Failed to run install_amazon_linux_ami_deps()!!!

Any help is appreciated....

**Comment by abednarik** [comment]
HI @francoisvdv 

 Looks like is falling during salt dependencies installation. Sadly I can't try myself since Amazon Linux is only available in AWS. 

Can you please run that script in  _debug_ mode to gather more information?

``` bash
sh -x bootstrap-salt.sh -D [ whatever option you are suing ]
```

Also you can pass -D to the script, since there is a debug mode.

Cheers.

**Comment by francoisvdv** [comment]
Hi,

Thanks for your reply - but it works again. It seemed the Fedora COPR repository was down and thus the script was not able to download the salt minion...

Kind regards!
