### ISSUE TITLE
Bootstrap fails for Centos 5 systems

### ISSUE THREAD

**Issue by alvaroarb** [saltstack/salt-bootstrap#707]
Hi, i'd like to report a fail when trying to install salt-minion on Centos 5 systems only (Centos 6 installed just fine), the script finishes with the following message:
-  INFO: sh install_salt.sh -- Version 2015.11.09
-  INFO: System Information:
-  INFO:   CPU:          GenuineIntel
-  INFO:   CPU Arch:     x86_64
-  INFO:   OS Name:      Linux
-  INFO:   OS Version:   2.6.18-371.12.1.el5
-  INFO:   Distribution: CentOS 5.10
  ....
-  INFO: Running install_centos_stable_deps()

error: skipping http://dl.fedoraproject.org/pub/epel/5/x86_64/epel-release-5-4.noarch.rpm - transfer failed - Unknown or unexpected error
Retrieving http://dl.fedoraproject.org/pub/epel/5/x86_64/epel-release-5-4.noarch.rpm
- ERROR: Failed to run install_centos_stable_deps()!!!
- DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe
  ...

I  think i know where the problem is, line 2968 inside the function __install_saltstack_rhel_repository() the gpg key indicated there does not exist in your repo (https://repo.saltstack.com/yum/rhel${DISTRO_MAJOR_VERSION}/SALTSTACK-GPG-KEY.pub), the right certificate would be http://repo.saltstack.com/yum/rhel5/SALTSTACK-EL5-GPG-KEY.pub, but changing it in the script would break the Version 6 certificate install since http://repo.saltstack.com/yum/rhel6/SALTSTACK-GPG-KEY.pub actually exists.
An from that point (no repository and no gpg key) things go sideways with the install.
Just my two cents .

**Comment by vutny** [comment]
Hi,

Old `rpm` binary from RHEL/CentOS 5 has horrible HTTP downloading support. Sometimes it fails to fetch from http://dl.fedoraproject.org/ even without 302 redirects.

Maybe upgrading `rpm` package before bootstrapping could fix this.

I suggest the following patch:

``` diff
diff --git a/bootstrap-salt.sh b/bootstrap-salt.sh
index 3820862..5cfbbbd 100755
--- a/bootstrap-salt.sh
+++ b/bootstrap-salt.sh
@@ -2892,9 +2892,8 @@ __install_epel_repository() {
         EPEL_ARCH=$CPU_ARCH_L
     fi
     if [ "$DISTRO_MAJOR_VERSION" -eq 5 ]; then
-        # Use dl.fedoraproject.org to avoid redirect breakage:
-        # https://lists.fedoraproject.org/pipermail/users/2012-February/414558.html
-        rpm -Uvh --force "http://dl.fedoraproject.org/pub/epel/5/${EPEL_ARCH}/epel-release-5-4.noarch.rpm" || return 1
+        _CURL_ARGS="${_CURL_ARGS} -L"
+        __fetch_url "/tmp/epel-release.rpm" "http://download.fedoraproject.org/pub/epel/5/${EPEL_ARCH}/epel-release-5-4.noarch.rpm" && rpm -Uvh --force /tmp/epel-release.rpm || return 1
     elif [ "$DISTRO_MAJOR_VERSION" -eq 6 ]; then
         rpm -Uvh --force "http://download.fedoraproject.org/pub/epel/6/${EPEL_ARCH}/epel-release-6-8.noarch.rpm" || return 1
     elif [ "$DISTRO_MAJOR_VERSION" -eq 7 ]; then
```

We could have the advantage of nearby Fedora mirrors if dl.fedoraproject.org will be (temporarily) unreachable.

@saltstack team, what do you think?

**Comment by jfindlay** [comment]
@vutny, I think that will be a good change to have.  Are you able to open a pull request?

**Comment by vutny** [comment]
@alvaroarb Does latest bootstrap version from `develop` solve your issue? Thanks for you feedback!

**Comment by vutny** [comment]
I guess this could be closed.
