### ISSUE TITLE
RHEL6 repodata incorrect

### ISSUE THREAD

**Issue by sjmh** [saltstack/salt-bootstrap#709]
The RHEL6 repodata is incorrect - it still has the devel packages listed in the filelists.  May need to regenerate that.

We mirror the repo down locally, since we need it on our provisioning networks, which don't have access to the internet and the syncs are failing due to the missing RPMs.

**Comment by dmurphy18** [comment]
@sjmh Thanks for the report.  What url are you using for Redhat 6 ?. The best url to use would be http://repo.saltstack.com/yum/redhat/6/x86_64/latest for the most current version of SaltStack for Redhat 6. If you want a permanent url to a particular version of SaltStack, I recommend using the following for 2015.8.3:
http://repo.saltstack.com/yum/redhat/6/x86_64/archive/2015.8.3
This url should remain for that particular build of SaltStack when new releases are made available.  As new builds are made available, they shall also be archive such that there is a permanent url for them.

**Comment by sjmh** [comment]
@dmurphy18 - I tried both the http://repo.saltstack.com/yum/redhat/6/x86_64/latest and http://repo.saltstack.com/yum/redhat/6Server/x86_64/latest.  The issue appears to be that the 'devel' packages were deleted from the repo, but the repodata wasn't updated - I verified this by downloading the filelists in the repodata and taking a look - it still lists them.

When you try and do a yum sync of the repo, it sees that those files are in the repodata, so tries to grab them, but they don't exist, resulting in the following:

```
Could not retrieve package libsodium-devel-0.4.5-3.el6.x86_64. Error was failure: libsodium-devel-0.4.5-3.el6.x86_64.rpm from saltstack-rhel6-x86_64: [Errno 256] No more mirrors to try.
Could not retrieve package libyaml-devel-0.1.3-4.el6.x86_64. Error was failure: libyaml-devel-0.1.3-4.el6.x86_64.rpm from saltstack-rhel6-x86_64: [Errno 256] No more mirrors to try.
Could not retrieve package openpgm-devel-5.2.122-2.el6.x86_64. Error was failure: openpgm-devel-5.2.122-2.el6.x86_64.rpm from saltstack-rhel6-x86_64: [Errno 256] No more mirrors to try.
Could not retrieve package pciutils-devel-3.1.10-4.el6.x86_64. Error was failure: pciutils-devel-3.1.10-4.el6.x86_64.rpm from saltstack-rhel6-x86_64: [Errno 256] No more mirrors to try.
Could not retrieve package pciutils-devel-static-3.1.10-4.el6.x86_64. Error was failure: pciutils-devel-static-3.1.10-4.el6.x86_64.rpm from saltstack-rhel6-x86_64: [Errno 256] No more mirrors to try.
Could not retrieve package zeromq-devel-4.0.5-4.el6.x86_64. Error was failure: zeromq-devel-4.0.5-4.el6.x86_64.rpm from saltstack-rhel6-x86_64: [Errno 256] No more mirrors to try.
```

Looking in the repo, those files don't seem to exist there anymore.  Probably just a matter of running a quick 'createrepo' to update the repodata.

**Comment by dmurphy18** [comment]
@sjmh I see what you are saying, when the packages were moved from the staging area to the deploy area, the xxx-develop named packages did not get moved. I shall need to review what else our deploy scripts also did not move for all of our various distributions.  This may explain some of the other issues being reported about our repo website.  Thanks for bring this to our attention.

**Comment by dmurphy18** [comment]
@sjmh whoops, I should have typed _-devel_, I can see the packages there, but I shall dig a little deeper into why they could not be retrieved

**Comment by vutny** [comment]
@dmurphy18 
Only `zeromq-devel` packages are not available for now:

```
[repo-saltstack-el6: 118   of 119   ] Downloading zeromq-devel-4.0.5-4.el6.i686.rpm
Could not retrieve package zeromq-devel-4.0.5-4.el6.i686. Error was failure: zeromq-devel-4.0.5-4.el6.i686.rpm from repo-saltstack-el6: [Errno 256] No more mirrors to try.
[repo-saltstack-el6: 119   of 119   ] Downloading zeromq-devel-4.0.5-4.el6.x86_64.rpm
Could not retrieve package zeromq-devel-4.0.5-4.el6.x86_64. Error was failure: zeromq-devel-4.0.5-4.el6.x86_64.rpm from repo-saltstack-el6: [Errno 256] No more mirrors to try.
```

**Comment by dmurphy18** [comment]
@vutny Have  #29812 tracking this issue, can this one be closed since it is a duplicate

**Comment by vutny** [comment]
@sjmh Could you be so kind to close this issue? saltstack/salt#29812 is closed already.

**Comment by vutny** [comment]
Thank you @dmurphy18
