### ISSUE TITLE
size mismatch on debian repo http://repo.saltstack.com/apt/debian/latest/

### ISSUE THREAD

**Issue by timcharper** [saltstack/salt-bootstrap#716]
Been seeing this for a couple of days:

```
Get:1 http://repo.saltstack.com/apt/debian/latest/ jessie/main libzmq3-dev amd64 4.0.5+dfsg-3 [564 kB]
Get:2 http://repo.saltstack.com/apt/debian/latest/ jessie/main libzmq3 amd64 4.0.5+dfsg-3 [436 kB]
Fetched 1,000 kB in 0s (8,989 kB/s)
E: Failed to fetch http://repo.saltstack.com/apt/debian/latest/pool/main/z/zeromq3/libzmq3-dev_4.0.5+dfsg-3_amd64.deb  Size mismatch
```

Looks like the index for the debian apt mirror needs to be refreshed?

**Comment by dmurphy18** [comment]
@timcharper see See bootstrap repo #709 and #29477,  #29812
Problem is with web access and downloading

**Comment by dmurphy18** [comment]
@timcharper given the duplication, could this issue be closed in favor of the above issues which are tracking it.
Thanks

**Comment by timcharper** [comment]
Duplicate of #709
