### ISSUE TITLE
Python-Tornado for PPC64

### ISSUE THREAD

**Issue by alvaroarb** [saltstack/salt-bootstrap#735]
Hi, never used github before (i'm not a developer but a sysadmin), i don't know if this is the right place to do this, but i want to contribute something to this wonderful community.
Recently i was tasked to set up a number of IBM Power 8 Servers with RHEL 7, since they all need to have the same exact configuration i turned to salt for this task, but when trying to install my minions with bootstrap the package python-tornado was not available for my processor architecture, since you guys have the source rpm available on the repo i downloaded it and compiled the rpm in the ppc64
architecture, manually installed it and then bootstrap worked like a charm.

Now, i've tried to upload the file here, several times, but something's happening and "Something went really wrong, and we can’t process that file.  Choose Files", how can i send this rpm file to you?
If you guys consider more packages need to be recompiled this way, so you can proudly announce support for one more platform, i'd be more than happy to do so, i'm aware Power 8 hardware is not that easily available. Just let me know

**Comment by jfindlay** [comment]
@alvaroarb, excellent, thanks for the contribution.  I'm going to move this to salt-pack, as it should be a more appropriate place to discuss this issue.
