### ISSUE TITLE
Install on fedora 23 creates invalid salt repo file

### ISSUE THREAD

**Issue by marun** [saltstack/salt-bootstrap#736]
After successfully bootstrapping on a Fedora 23 host, the following repo file was created at `/etc/yum.repos.d/saltstack-salt-fedora-23.repo`:

```
[saltstack-salt]
name=Copr repo for salt owned by saltstack
baseurl=https://copr-be.cloud.fedoraproject.org/results/saltstack/salt/fedora-$releasever-$basearch/
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/saltstack/salt/pubkey.gpg
enabled=1
```

A subsequent 'dnf update' resulted in the following warning message:

```
Failed to synchronize cache for repo 'saltstack-salt' from 'https://copr-be.cloud.fedoraproject.org/results/saltstack/salt/fedora-23-x86_64/': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling.
```

It appears that salt is distributed by Fedora >= 23 and the extra repo is no longer created or required.

**Comment by vutny** [comment]
@marun Looks like this issue has been resolved in the `develop` branch. Please could you close it?
