### ISSUE TITLE
How to remotely install Salt minion on already existing Windows VM from master 

### ISSUE THREAD

**Issue by anandnevase** [saltstack/salt-bootstrap#740]
I wanted to to remotely installed Salt minion on already existing Windows VM from Salt master running on Debian server. Can any one tell me how can I do that?

**Comment by jfindlay** [comment]
Ping @thebigbear, @twangboy, @UtahDave.

**Comment by TheBigBear** [comment]
@anandxoriant what version of Debian server? Your best bet is probably to get a compiled version of `winexe` from `'http://sourceforge.net/projects/winexe/'`, and then run it using the silent switches on the installer. This is just an idea, I have not tested it. Please let me know how you got on.

**Comment by anandnevase** [comment]
@TheBigBear : I am using Debian 8.2 and  winexe-static-081123.bz2. 
When I am bootstrap VM from template using VMware driver,  VM start with minion installed on it. But currently for Windows VM we can't assign Static IP address, for that I am boot vm in power off mode, then through pyvmomi I am assign Static IP then start VM, but Salt minion not bootstrapped here. So I want to externally bootstrap salt-minion in it. 
Do salt having any utility or tool through which externally Salt-minion-installer.exe copy to windows VM and start minion?

**Comment by amalaguti** [comment]
Yesterday I wrote this "very simple" script, there's room for improvement, it mounts the Windows C$ drive in Linux, copy the Minion installer to the mounted C$ and remotely execute a silent installation using winexe (the minion name is not set in the command line, I'm taking the computer name). Took me a while to get winexe compiled on my Ubuntu platform, but finally got it working.
[winminion-deploy.zip](https://github.com/saltstack/salt-bootstrap/files/106695/winminion-deploy.zip)

**Comment by TheBigBear** [comment]
@anandxoriant I am not sure I follow your logic or exact problem a 100%, what is to stop you from having the minions doing a intial connect and handshake using the automatic and dyna,ic IP, and then once you have them in the salt master, yhou can go about changing and setting the fixed IP they shoudl be getting? But anyway, this is probably not relevant anymore seeing that @amalaguti has solved what I understand you are asking for in the first place anyway? 
Please do report back here on how you get on with this approach and the simple script mentioned above.

+1 to @amalaguti thanks for this, awesome, yest simple contribution.

**Comment by jfindlay** [comment]
There's also https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.ps1, that we can think about reworking into a more general purpose windows bootstrapper.

**Comment by twangboy** [comment]
Depending on the version of salt you are using you can use `pkg.install` to update salt.
