### ISSUE TITLE
Failure on salt-minion apt-get install

### ISSUE THREAD

**Issue by XceligentITDept** [saltstack/salt-bootstrap#749]
apt-get install salt-minion
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  dctrl-tools debconf-utils libmysqlclient18 libpgm-5.1-0 libzmq3 mysql-common
  python-crypto python-dateutil python-jinja2 python-mako python-markupsafe
  python-msgpack python-mysqldb python-tornado python-zmq salt-common
Suggested packages:
  debtags python-crypto-dbg python-crypto-doc python-jinja2-doc python-beaker
  python-mako-doc python-egenix-mxdatetime mysql-server-5.1 mysql-server
  python-mysqldb-dbg python-augeas
The following NEW packages will be installed:
  dctrl-tools debconf-utils libmysqlclient18 libpgm-5.1-0 libzmq3 mysql-common
  python-crypto python-dateutil python-jinja2 python-mako python-markupsafe
  python-msgpack python-mysqldb python-tornado python-zmq salt-common
  salt-minion
0 upgraded, 17 newly installed, 0 to remove and 4 not upgraded.
1 not fully installed or removed.
Need to get 5,255 kB of archives.
After this operation, 25.7 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main mysql-common all 5.5.47-0ubuntu0.14.04.1 [13.5 kB]
Get:2 http://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ trusty/main python-tornado amd64 4.2.1-1 [274 kB]
Get:3 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main libmysqlclient18 amd64 5.5.47-0ubuntu0.14.04.1 [597 kB]
Get:4 http://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ trusty/main salt-common all 2015.8.4+ds-1 [3,108 kB]
Get:5 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/universe libpgm-5.1-0 amd64 5.1.118-1~dfsg-0.1ubuntu3 [156 kB]
Get:6 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/universe libzmq3 amd64 4.0.4+dfsg-2 [129 kB]
Get:7 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/main dctrl-tools amd64 2.23ubuntu1 [101 kB]
Get:8 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/main debconf-utils all 1.5.51ubuntu2 [57.4 kB]
Get:9 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/main python-crypto amd64 2.6.1-4build1 [239 kB]
Get:10 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/main python-dateutil all 1.5+dfsg-1ubuntu1 [48.9 kB]
Get:11 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/main python-markupsafe amd64 0.18-1build2 [14.3 kB]
Get:12 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/main python-jinja2 all 2.7.2-2 [161 kB]
Get:13 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/main python-mako all 0.9.1-1 [59.6 kB]
Get:14 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/main python-msgpack amd64 0.3.0-1ubuntu3 [43.7 kB]
Get:15 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/main python-mysqldb amd64 1.2.3-2ubuntu1 [55.4 kB]
Get:16 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/universe python-zmq amd64 14.0.1-1build2 [175 kB]
Get:17 http://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ trusty/main salt-minion all 2015.8.4+ds-1 [23.7 kB]
Fetched 5,255 kB in 1s (3,165 kB/s)
E: Failed to fetch http://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/pool/main/p/python-tornado/python-tornado_4.2.1-1_amd64.deb  Size mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by jfindlay** [comment]
@XceligentITDept, will you describe how you are running bootstrap and what version of bootstrap you are running?  Thanks.

**Comment by vutny** [comment]
Looks like this was repository metadata issue, not related to the bootstrap.
@jfindlay @s0undt3ch I think it could be safely closed and reopened if needed.

**Comment by vutny** [comment]
Ping @s0undt3ch

**Comment by s0undt3ch** [comment]
Closing as requested.
