### ISSUE TITLE
Do not overwrite configs

### ISSUE THREAD

**Issue by akoumjian** [saltstack/salt-bootstrap#76]
Sometimes people use bootstrap to upgrade a git install, or need to run boostrap for other reasons on an existing installation.

Currently we attempt to copy over configs regardless of whether or not they exist. I recommend we add some kind of force_config flag that will overwrite existing configs when true. The default behavior should be not overwriting existing files.

**Comment by s0undt3ch** [comment]
@akoumjian #95 should fix this issue.

**Comment by josmardias** [comment]
It's still overwriting my config files (/etc/salt/master and minion).

I'm using Ubuntu 12.04 LTS

**Comment by s0undt3ch** [comment]
Could you please provide a full execution output with debug enabled? ie pass `-D` to the script.

**Comment by josmardias** [comment]
```
$ curl -L http://bootstrap.saltstack.org | sudo sh -s -- -D -M -N git v0.15.3
(...)
```

https://gist.github.com/josmardias/6029662

**Comment by josmardias** [comment]
Only the master was overwritten, btw.

**Comment by s0undt3ch** [comment]
Errr, you are correct. This is still a bug!

@josmardias Thanks!

**Comment by s0undt3ch** [comment]
@josmardias If you use the development version, this issue should be fixed. Once again, Thanks!

**Comment by josmardias** [comment]
@s0undt3ch Thanks man : )

**Comment by s0undt3ch** [comment]
Sempre às ordens!

**Comment by josmardias** [comment]
Can we get this on stable?
Valeu!

**Comment by josmardias** [comment]
I just tested installing salt on my VirtualBox running Ubuntu and i get master and minion configs overwritten again : (

I used the last commit of salt-bootstrap devel:

``` bash
$ curl -L https://raw.github.com/saltstack/salt-bootstrap/a9e1d6e0117dc868f5a6dfdd45ae58a2641ada4b/bootstrap-salt.sh | sudo sh -s -- -D -M -N git v0.16.1
(...)
```

https://gist.github.com/josmardias/a2048c234275dd0fdf07

**Comment by josmardias** [comment]
Obs.: I tested twice. For some reason, both were overwritten in the first try, but only master was overwritten in the second try. This gist is about my second try.
