### ISSUE TITLE
Install git develop fails on Centos 6/7 (pull 1b16dd9 into stable)

### ISSUE THREAD

**Issue by unicolet** [saltstack/salt-bootstrap#763]
Install fails with current stable branch of salt-bootstrap but works with develop.

The culprit seem to be [this](https://github.com/saltstack/salt-bootstrap/blob/stable/bootstrap-salt.sh#L3173) line: The prefix option needs to be moved after install.

Salt-bootstrap in the develop branch does not present the issue, so this ticket is more of a friendly reminder to pull [1b16dd9](https://github.com/saltstack/salt-bootstrap/commit/91595528c31205db3c25787d4beee6f1a31cb146) into stable.

**Comment by jfindlay** [comment]
@unicolet, thanks for reporting.  The next release of bootstrap will come out this week, so I am going to close this.
