### ISSUE TITLE
False error "The git revision being installed does not match a Salt version tag."

### ISSUE THREAD

**Issue by AndreiPashkin** [saltstack/salt-bootstrap#767]
Invocation of the script (2015.11.09) with parameters `-P git 2015.8` results to such error:

```
 *  WARN: The git revision being installed does not match a Salt version tag. Shallow cloning disabled
```

And full cloning of the Salt repo.
While a branch with the name `2015.8` is exists.

**Comment by s0undt3ch** [comment]
A branch exists, but if you notice the error it mentions a tag, and a tag by that name does not exist.

**Comment by AndreiPashkin** [comment]
@s0undt3ch, I forgot to mention, that command `git --depth 1 --branch 2015.8 https://github.com/saltstack/salt.git` - actually works. It doesn't require a tag.

**Comment by AndreiPashkin** [comment]
@s0undt3ch, [docs](https://docs.saltstack.com/en/latest/topics/tutorials/salt_bootstrap.html#example-usage) are also states, that you can specify branch as a parameter (CTRL-F "mybranch")

**Comment by s0undt3ch** [comment]
Yes, of course you can, to both statements. :)

But in order to get the correct version information for salt, we need to either clone the full repo and fetch tags, or clone a specific tag.

**Comment by AndreiPashkin** [comment]
What if I want to always install latest minor version using `git` installation method and not wasting time on full clones?

**Comment by AndreiPashkin** [comment]
> But in order to get the correct version information for salt, we need to either clone the full repo and fetch tags, or clone a specific tag.

Why, actually? Interface of the script defines this command as:

```
- git [branch_or_tag] (install from 'develop' by default)
```

It's not says `version`, it says `branch_or_tag`.

**Comment by s0undt3ch** [comment]
The script will not support such behavior(shallow clone from branches) because we the proper version information.

**Comment by AndreiPashkin** [comment]
So, what is the input argument for `git` - Salt version or Git refspec?

**Comment by s0undt3ch** [comment]
Salt gets its version information from `git describe` that's why it either needs a full clone, or a shallow clone _from a git tag_.

**Comment by AndreiPashkin** [comment]
I think, it is also possible to find appropriate tag for given version, by using `git ls-remote`.

**Comment by vutny** [comment]
@AndrewPashkin Latest script from `develop` allows shallow cloning for version branches. Also you could try passing `-f` option (force shallow cloning for git installations). Check it out.

@s0undt3ch Salt version will be displayed almost correctly :-) Like: `2015.8.0-n/a-commithash`.
I think that's acceptable for "non-released" code taken from branch, and we have the speed advantage of shallow cloning.

**Comment by s0undt3ch** [comment]
The problem with almost is when users get back to report bugs, we won't have a clear idea of the version. And I also think that its almost only for recent enough git versions(older git versions will probably be totally off). Git describe needs to be told to get branch information relative to first parent branch...

**Comment by vutny** [comment]
@s0undt3ch Yeah, sounds reasonable. At least, only with major version and commit hash we are able to determine exact version from Git tree.

@AndrewPashkin I think this issue could be closed. Thank you.

**Comment by AndreiPashkin** [comment]
Yes, I'm closing it. 

By the way, I solved my problem, using that obscure shell expression:

``` bash
SALT_VERSION=2015.8; git ls-remote --tags https://github.com/saltstait | sed -n -e "s/.*refs\/tags\/\(v$SALT_VERSION[.0-9]*\)\$/\1/p" | sort | tail -n1 | tr -d '\n'
```

It retrieves a tag, that corresponds to latest minor version for given `SALT_VERSION`. And this tag could be fed to `salt-bootstrap.sh git` subcommand.

**Comment by vutny** [comment]
@AndrewPashkin Nice trick!
But that will only suit if you need latest _released_ version, because there could be some pending changes ahead of tagged revision in `2015.8` branch for example.

**Comment by AndreiPashkin** [comment]
In that case, you can specify `2015.8` as an argument and use `-f` option, I guess.
