### ISSUE TITLE
ERROR: Failed to run install_debian_8_deps()!!!

### ISSUE THREAD

**Issue by arthurzenika** [saltstack/salt-bootstrap#770]
```
After this operation, 976 kB of additional disk space will be used.
Get:1 http://repo.saltstack.com/apt/debian/latest/ jessie/main python-urllib3 all 1.10.4-1 [61.0 kB]
Get:2 http://http.debian.net/debian/ jessie/main libpci3 amd64 1:3.2.1-3 [53.9 kB]
Get:3 http://http.debian.net/debian/ jessie/main procps amd64 2:3.3.9-9 [236 kB]
Get:4 http://repo.saltstack.com/apt/debian/latest/ jessie/main python-requests all 2.7.0-3 [66.4 kB]
Get:5 http://http.debian.net/debian/ jessie/main pciutils amd64 1:3.2.1-3 [257 kB]
Fetched 674 kB in 0s (6077 kB/s)
E: Failed to fetch http://repo.saltstack.com/apt/debian/latest/pool/main/p/python-urllib3/python-urllib3_1.10.4-1_all.deb  Size mismatch

E: Failed to fetch http://repo.saltstack.com/apt/debian/latest/pool/main/r/requests/python-requests_2.7.0-3_all.deb  Size mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
[DEBUG   ] 3 upgraded, 2 newly installed, 0 to remove and 106 not upgraded.
Need to get 674 kB of archives.
After this operation, 976 kB of additional disk space will be used.
Get:1 http://repo.saltstack.com/apt/debian/latest/ jessie/main python-urllib3 all 1.10.4-1 [61.0 kB]
Get:2 http://http.debian.net/debian/ jessie/main libpci3 amd64 1:3.2.1-3 [53.9 kB]
Get:3 http://http.debian.net/debian/ jessie/main procps amd64 2:3.3.9-9 [236 kB]
Get:4 http://repo.saltstack.com/apt/debian/latest/ jessie/main python-requests all 2.7.0-3 [66.4 kB]
Get:5 http://http.debian.net/debian/ jessie/main pciutils amd64 1:3.2.1-3 [257 kB]
Fetched 674 kB in 0s (6077 kB/s)
E: Failed to fetch http://repo.saltstack.com/apt/debian/latest/pool/main/p/python-urllib3/python-urllib3_1.10.4-1_all.deb  Size mismatch

E: Failed to fetch http://repo.saltstack.com/apt/debian/latest/pool/main/r/requests/python-requests_2.7.0-3_all.deb  Size mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

 * ERROR: Failed to run install_debian_8_deps()!!!
[DEBUG   ]  * ERROR: Failed to run install_debian_8_deps()!!!
```

**Comment by arthurzenika** [comment]
Disabling my apt-cacher-ng proxy fixes this. 

I think this is because the files on repo.saltstack.com have changed but you are keeping the same versions. This should never happen in a debian repo. You should have a new file with a debian package version different (for example python-urllib3_1.10.4-1_all.deb becomes python-urllib3_1.10.4-2_all.deb).

If these packages are backports or different from upstream, they should probably have backport version numbers see https://wiki.debian.org/SimpleBackportCreation#Indicate_in_the_changelog_a_backport_revision_number

If I need to report this issue on the main saltstack project, or salt-pack please tell me.

**Comment by dmurphy18** [comment]
@arthurlogilab the Debian files are rebuilt from the Debian sources utilizing the dsc file etc.  They are unchanged from the sources downloaded, only built using pbuilder.

If the packages are only rebuilt, why should the version number for the package change.  I understand that compiler and linker versions may be different from when the original Debian package was built, but functionally it should be the same.

I may have grabbed one or two packages early from testing, back in Debian 8.1 days, but they have probably been superceeded by now with the latest Debian 8.3 release.  However I shall check the versions available from repo.saltstack.com against the latest jessie releases, wehen time permits.

**Comment by jfindlay** [comment]
@arthurlogilab, thanks for reporting.  If this happens again, would you mind reopening at [salt-pack](https://github.com/saltstack/salt-pack/issues/new/)?  Thanks.
