### ISSUE TITLE
Preseeding of key

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt-bootstrap#772]
Is it possible to preseed a key with `salt-bootstrap`? Would it work to simply
1. `mkdir -p /etc/salt/pki/minion`
2. Put the preseeded `minion.pem` and `minion.pub` in the above directory.
3. Calling `salt-bootstrap`. Or will `salt-bootstrap` override the files?

I could obviously, run `salt-bootstrap` and then replace the pregenerated key. They problem is that `salt-bootstrap` starts the minion which will announce a key I will replace a second later (and will have to clean up on master).

**Comment by JensRantil** [comment]
A workaround:
1. Run `salt-bootstrap`, specifying a non-existing master hostname.
2. Stop minion.
3. Update the correct master in configuration.
4. Replace with my preseeded keys.
5. Start minion.

**Comment by jfindlay** [comment]
@JensRantil, it seems that you can preseed a bootstrapped master with minion keys with the `-k` option but not anything else.  The challenge is to get the key onto the VM in a secure manner.  The bootstrap script is intended to run on a single new VM without performing any complex orchestration tasks against remote systems.  If you have a way to generate the minion key independently of bootstrapping the corresponding VM and placing it on the master, then I think we could add support to `-k` to preseed a minion key that is already present on the system.  @s0undt3ch, do you know if there is a reason this is not already done?

**Comment by JensRantil** [comment]
@jfindlay Thanks for input!

> The challenge is to get the key onto the VM in a secure manner.

My proposal is to keep it simple at first: Simply allow referencing a local file will do and have it up to the operator to decide how that key will end up on disk.

> If you have a way to generate the minion key independently of bootstrapping the corresponding VM and placing it on the master, then I think we could add support to -k to preseed a minion key that is already present on the system.

My idea here is to have a script auto-accept a minion with a certain key. This could obviously be done by simply preseeding a key on the master in a more static way, too.

**Comment by JensRantil** [comment]
> @s0undt3ch, do you know if there is a reason this is not already done?

Ping. Any input @s0undt3ch?

**Comment by themalkolm** [comment]
@JensRantil btw, you can bootstrap salt without starting daemons (`-X`). This will prevent key generation. You can then install prepared keys and start daemons.

**Comment by JensRantil** [comment]
@themalkolm That never crossed my mind. Not sure this feature request is needed then. Closing this. Ping this thread if you still think this issue has any relevance and I'll reopen!
