### ISSUE TITLE
Bootstrap and Links & Documentation still broken due to fedoraproject redirect to fedorainfracloud.org

### ISSUE THREAD

**Issue by ninjada** [saltstack/salt-bootstrap#782]
Guys,

The issues since the fedoraproject.org redirect to fedorainfracloud.org with the bootstraps are still broken for me... 

At least this is the case for Amazon Linux.. I just tried the simple task of quickly bootstrapping a bunch of servers over ssh for some super quick testing and ended up bashing my head against a wall for half an hour getting things working... 

Any documentation I hit, the bootstrap commands still do not work either due to this redirect ruining the scripts or the rpm being a html redirect. Pulling the latest salt-bootstrap repo and running the install, doesn't work on Amazon Linux at least. Any first timer coming along and following the bootstrapping docs is in for failure eg:

https://docs.saltstack.com/en/latest/topics/tutorials/salt_bootstrap.html

Every turn breaks at installing amazon linux deps. Seems to be because the saltstack-salt-epel-6.repo file is downloading a redirect and breaking the install. I don't know how its related or why exactly this is still causing issues but still seems to be a major spanner in the works, can it please be updated...

**Comment by matthayes** [comment]
I ran into this same issue on Amazon Linux and worked around it by setting BS_CURL_ARGS so that curl redirects to the new destination.  Why isn't `-L` used by default?  

```
sudo BS_CURL_ARGS="-L" sh install_salt.sh -P git $SALT_VER
```

**Comment by jfindlay** [comment]
@ninjada, @matthayes, thanks for reporting.  We should get this fixed.

**Comment by vutny** [comment]
@ninjada @matthayes I believe this issue was fixed some time ago in `develop`, and now it is already merged into `stable`. So, `salt-cloud` also should use updated version.

Could you please try again?

**Comment by rallytime** [comment]
This should be fixed in the latest stable, so I'll close this. If this issue pops up again, let us know and we can take another look. Thanks!
