### ISSUE TITLE
Lack of HTTPS support for RPM download

### ISSUE THREAD

**Issue by archcloudlabs** [saltstack/salt-bootstrap#784]
[Line 3050](https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh) shows files being insecurely downloaded from download.fedoraproject.org over HTTP.  I've issued a pull request [here](https://github.com/saltstack/salt-bootstrap/pull/783) addressing the issue.

**Comment by vutny** [comment]
I've discovered that `epel-release` packages are already uploaded to the _extras_ repos in recent releases of CentOS:
http://mirror.centos.org/centos/5/extras/x86_64/RPMS/epel-release-5-4.noarch.rpm
http://mirror.centos.org/centos/6/extras/x86_64/Packages/epel-release-6-8.noarch.rpm
http://mirror.centos.org/centos/7/extras/x86_64/Packages/epel-release-7-5.noarch.rpm

Hooray! Finally we are able to install it with regular `yum --enablerepo=extras -y install epel-release` command. No need to download anything, at least in CentOS. RHEL/Oracle/etc are still questionable.

---

Issues #588 and #724 seem related.

**Comment by vutny** [comment]
I guess this is already resolved by #798. Ping @s0undt3ch

**Comment by jfindlay** [comment]
@vutny, we should probably change bootstrap to install the `epel-release` packages.
