### ISSUE TITLE
Bootstrap fails on Ubuntu 15.10

### ISSUE THREAD

**Issue by discotroy** [saltstack/salt-bootstrap#786]
Possibly a duplicate, but I couldn't find any other issues which didn't include other potential complicating factors.

I'm attempting to bootstrap an Ubuntu 15.10 VM provisioned via salt-cloud on VMWare.  The inital provisioning works (after some hoops were jumped through), but the bootstrapping of Salt fails with a message about problems with "install_ubuntu_deps_stable".  This appears to be linked to the repo not containing packages for 15.10, nor even symlinks to the 14.04 packages (which do appear to work).  Firstly, the GPG key cannot be found and, secondly, nor can the packages.

I hard-coded the path to the 14.04 repo in and tried again.  The bootstrap script then failed when checking that the services are enabled.  This seems to be down to the fact that the script doesn't enable the services.  `systemctl is-enabled salt-minion` shows disabled.  `ps` tells me that it is running, as does `service --status-all`.  I hard-coded a `systemctl enable salt-minion` into the service check function, and now the bootstrap works.

I ran through the provisioning process several times using my mangled script, and got positive results each time.

Suggestions:
- Provide a 15.10 repo (even if only populated with 14.04 packages), or amend the bootstrap-salt.sh to look in a known-good location for GPG key and packages rather than building a URL based on OS revision
- Amend the bootstrap-salt.sh to actually enable the service before checking to see if it is enabled

**Comment by jfindlay** [comment]
@discotroy, thanks for reporting.  This looks related to #596.

**Comment by rallytime** [comment]
@discotroy I am just following up here, but I was able to bootstrap an Ubuntu 15.10 VM just now with the latest stable release of the bootstrap script:

```
root@ubuntu:~# sh install_salt.sh
 *  INFO: Running install_ubuntu_stable_post()
 *  INFO: Running install_ubuntu_check_services()
 *  INFO: Running install_ubuntu_restart_daemons()
 *  INFO: Running daemons_running()
 *  INFO: Salt installed!
root@ubuntu:~# sh install_salt.sh -v
install_salt.sh -- Version 2016.06.27
root@ubuntu:~# salt-call --versions
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: 1.1.2
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.2
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.10 (default, Oct 14 2015, 16:09:02)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 15.10 wily
        machine: x86_64
        release: 4.5.5-x86_64-linode69
         system: Linux
        version: Ubuntu 15.10 wily
```

Are you still running into this issue, or can this be closed?

**Comment by rallytime** [comment]
I am going to close this since I haven't heard back here and I was able to install on Ubuntu 15.10 as stated above. If you're still running into this problem, leave a comment and we will gladly re-open. Thanks!
