### ISSUE TITLE
errexit and checking return codes don't work together

### ISSUE THREAD

**Issue by Pewpewarrows** [saltstack/salt-bootstrap#79]
The current head of the bootstrap script is using `set -e` (errexit), which will cause the whole script to stop running if any statement has a non-zero exit code, even if it's part of a pipeline or you intentionally want to check the return code later.

There are several places in the script where `$?` is checked. None of them will work because the script will exit early. See the `set -e` section in this article for how to get around that:

http://www.davidpashley.com/articles/writing-robust-shell-scripts.html

**Comment by s0undt3ch** [comment]
Dam, yes, you are correct, I've removed that but it's still in my fork

**Comment by s0undt3ch** [comment]
This issue is now also fixed in the develop branch
