### ISSUE TITLE
epel repository name for rhel

### ISSUE THREAD

**Issue by Titerote** [saltstack/salt-bootstrap#796]
I have a corporate satelite, which has a different name for the epel repository. I have tested hacking the variable _EPEL_REPO on the bootstrap script, and it works . 

I don't know if there are any plans to provide a way to do this.

**Comment by jfindlay** [comment]
@Titerote, thanks for reporting.  We have [plans](https://github.com/saltstack/salt-bootstrap/issues/728) to provide for overriding the saltstack repo with a private mirror, but not for epel.  You are welcome to submit a pull request to support this.

**Comment by rallytime** [comment]
@Titerote Does the `-R` option do what you need here, implemented in #877? That option is now available in the latest stable release (`2016.06.27`).

**Comment by rallytime** [comment]
@Titerote Just a bump here to check if you saw my comment above.
