### ISSUE TITLE
Bootstrap fails in Debian Squeeze (stable)

### ISSUE THREAD

**Issue by jorgeecardona** [saltstack/salt-bootstrap#8]
Hi, 

I'm using the line:

```
wget -O - http://bootstrap.saltstack.org | sudo sh
```

but it fails in debian 6.0 stable with:

```
Hit http://backports.debian.org squeeze-backports Release
Hit http://backports.debian.org squeeze-backports/main amd64 Packages/DiffIndex
Hit http://backports.debian.org squeeze-backports/main amd64 Packages
Reading package lists...
 * Running install_debian_60_stable()
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package salt-minion
 * Failed to run install_debian_60_stable()!!!
 * Removing the logging pipe /tmp/bootstrap-salt-minion.logpipe
```

Checking in squeeze-backports there is no salt-minion, but there is one in Debian unstable.

Bye.

**Comment by akoumjian** [comment]
I will get to this tonight, sorry for the delay!

**Comment by jorgeecardona** [comment]
Hi, I was trying also using the "git" option:
     ./bootstrap-salt-minion.sh git

but it fails also.

**Comment by akoumjian** [comment]
Yes, this is because the git option uses the apt installation for installing dependencies, then installs over it. Since backports is frozen, they decided to phase out the out of date salt packages in there.

**Comment by s0undt3ch** [comment]
Git installs should not depend on previous salt packages or any salt package for that matter, right @akoumjian?

**Comment by akoumjian** [comment]
Correct, changing it to just grab the deps independently.
