### ISSUE TITLE
SALT-Cloud fails to bootstrap if using a custom configuration location

### ISSUE THREAD

**Issue by benhosmer** [saltstack/salt-bootstrap#802]
Using something like this:

`# salt-cloud -m /path/to/my/map -c /srv/salt`

`deploy.sh` fails to be copied to the newly created minion and the minion is never installed.

I worked around it by adding a `cloud.deploy.d/` with a `deploy.sh` script in `/srv/salt`.

It would be helpful is salt-bootstrap produced an error or at least told the user that this was the problem.

I would get this far:

```
sftp> put  /tmp/tmpUfb_1S /tmp/.saltcloud-1da4a970-a6e0-4713-92d7-e4d757227b63/minion
Uploading /tmp/tmpUfb_1S to /tmp/.saltcloud-1da4a970-a6e0-4713-92d7-e4d757227b63/minion
/tmp/tmpUfb_1S                                                         100% 4800     4.7KB/s   00:00    
[DEBUG   ] sftp> put  /tmp/tmpUfb_1S /tmp/.saltcloud-1da4a970-a6e0-4713-92d7-e4d757227b63/minion
Uploading /tmp/tmpUfb_1S to /tmp/.saltcloud-1da4a970-a6e0-4713-92d7-e4d757227b63/minion
/tmp/tmpUfb_1S
```

But never this:

```
[DEBUG   ] Uploading /tmp/.saltcloud-1da4a970-a6e0-4713-92d7-e4d757227b63/deploy.sh to 52.91.246.21 (sfcp)
```

Until I added the `cloud.deploy.d` to my `/srv/salt`.

I'm creating this issue here because of @jfindlay comment: https://github.com/saltstack/salt/issues/25912

**Comment by jfindlay** [comment]
@benhosmer, thanks for reporting.

**Comment by code42fr** [comment]
Hello, where is the original deploy.sh script ?

**Comment by jfindlay** [comment]
@code42fr, you can find the version of bootstrap that ships with salt at `<prefix>/salt/cloud/deploy/bootstrap-salt.sh`, where `<prefix>` is the directory salt is installed, usually something like `/usr/lib/python2.7/site-packages`.

**Comment by code42fr** [comment]
@jfindlay, thanks for your answer. It was a misunderstood, i didn't manage to install salt minion 2015.8.10 to debian 7 with the bootstrap process. So i've add into my map file : `script_args: stable 2015.8` .
Have a nice day

**Comment by rallytime** [comment]
@code42fr The change in #864 should help resolve this issue for you. It's now in the `develop` branch of salt-bootstrap and will be available in the next official release.
