### ISSUE TITLE
https://bootstrap.saltstack.com is broken for CentOS 7

### ISSUE THREAD

**Issue by BlueMonday** [saltstack/salt-bootstrap#819]
### Description of Issue/Question

The script available at `bootstrap.saltstack.com` refers to an epel RPM which no longer exists. Attempting to bootstrap salt from CentOS 7 currently is not possible. I am attempting to use Packer to provision a virtual machine using salt.

I noticed that there are two urls `bootstrap.saltstack.org` and `bootstrap.saltstack.com`. The `.org` url contains a much more up to date script which does not have the epel RPM problem.

Here is the output from Packer:

```
19-Apr-2016 15:07:34        virtualbox-iso: Downloading saltstack bootstrap to /tmp/install_salt.sh
19-Apr-2016 15:07:34        virtualbox-iso: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
19-Apr-2016 15:07:34        virtualbox-iso: Dload  Upload   Total   Spent    Left  Speed
19-Apr-2016 15:07:35        virtualbox-iso: 100   264  100   264    0     0    289      0 --:--:-- --:--:-- --:--:--   289
19-Apr-2016 15:07:35        virtualbox-iso: 100  209k  100  209k    0     0   138k      0  0:00:01  0:00:01 --:--:--  138k
19-Apr-2016 15:07:35        virtualbox-iso: Installing Salt with command sudo sh /tmp/install_salt.sh
19-Apr-2016 15:07:35        virtualbox-iso: *  INFO:  /tmp/install_salt.sh -- Version 2015.11.09
19-Apr-2016 15:07:35        virtualbox-iso:
19-Apr-2016 15:07:35        virtualbox-iso: *  INFO: System Information:
19-Apr-2016 15:07:35        virtualbox-iso: *  INFO:   CPU:          GenuineIntel
19-Apr-2016 15:07:35        virtualbox-iso: *  INFO:   CPU Arch:     x86_64
19-Apr-2016 15:07:35        virtualbox-iso: *  INFO:   OS Name:      Linux
19-Apr-2016 15:07:35        virtualbox-iso: *  INFO:   OS Version:   3.10.0-327.13.1.el7.x86_64
19-Apr-2016 15:07:35        virtualbox-iso: *  INFO:   Distribution: CentOS 7.2
19-Apr-2016 15:07:35        virtualbox-iso:
19-Apr-2016 15:07:35        virtualbox-iso: *  INFO: Installing minion
19-Apr-2016 15:07:35        virtualbox-iso: *  INFO: Found function install_centos_stable_deps
19-Apr-2016 15:07:35        virtualbox-iso: *  INFO: Found function install_centos_stable
19-Apr-2016 15:07:36        virtualbox-iso: *  INFO: Found function install_centos_stable_post
19-Apr-2016 15:07:36        virtualbox-iso: *  INFO: Found function install_centos_restart_daemons
19-Apr-2016 15:07:36        virtualbox-iso: *  INFO: Found function daemons_running
19-Apr-2016 15:07:36        virtualbox-iso: *  INFO: Found function install_centos_check_services
19-Apr-2016 15:07:36        virtualbox-iso: *  INFO: Running install_centos_stable_deps()
19-Apr-2016 15:07:43        virtualbox-iso: curl: (22) The requested URL returned error: 404 Not Found
19-Apr-2016 15:07:43        virtualbox-iso: error: skipping http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm - transfer failed
19-Apr-2016 15:07:43        virtualbox-iso: Retrieving http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
19-Apr-2016 15:07:43        virtualbox-iso: * ERROR: Failed to run install_centos_stable_deps()!!!
```

**Comment by replicant0wnz** [comment]
Verified wget against the rpm doesn't work:

➜  ~  wget http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
--2016-04-19 09:05:55--  http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
Resolving download.fedoraproject.org (download.fedoraproject.org)... 152.19.134.198, 209.132.181.16, 66.35.62.162, ...
Connecting to download.fedoraproject.org (download.fedoraproject.org)|152.19.134.198|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://mirror.cogentco.com/pub/linux/epel/7/x86_64/e/epel-release-7-5.noarch.rpm [following]
--2016-04-19 09:05:56--  http://mirror.cogentco.com/pub/linux/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
Resolving mirror.cogentco.com (mirror.cogentco.com)... 204.157.3.70
Connecting to mirror.cogentco.com (mirror.cogentco.com)|204.157.3.70|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-04-19 09:05:56 ERROR 404: Not Found.

**Comment by asachs** [comment]
+1 seeing the same here

**Comment by cachedout** [comment]
Thanks. Investigating.

**Comment by replicant0wnz** [comment]
Verified: 

[root@ip-10-244-0-87 ~]# sh bootstrap_salt.sh 
-  INFO: sh bootstrap_salt.sh -- Version 2015.11.09
-  INFO: System Information:
-  INFO:   CPU:          GenuineIntel
-  INFO:   CPU Arch:     x86_64
-  INFO:   OS Name:      Linux
-  INFO:   OS Version:   3.10.0-327.10.1.el7.x86_64
-  INFO:   Distribution: CentOS 7.2
-  INFO: Installing minion
-  INFO: Found function install_centos_stable_deps
-  INFO: Found function install_centos_stable
-  INFO: Found function install_centos_stable_post
-  INFO: Found function install_centos_restart_daemons
-  INFO: Found function daemons_running
-  INFO: Found function install_centos_check_services
-  INFO: Running install_centos_stable_deps()
  Repodata is over 2 weeks old. Install yum-cron? Or run: yum makecache fast
  curl: (22) The requested URL returned error: 404 Not Found
  error: skipping http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm - transfer failed
  Retrieving http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
- ERROR: Failed to run install_centos_stable_deps()!!!
  [root@ip-10-244-0-87 ~]# 
  [root@ip-10-244-0-87 ~]# cat /etc/centos-release
  CentOS Linux release 7.2.1511 (Core) 
  [root@ip-10-244-0-87 ~]#

**Comment by replicant0wnz** [comment]
rpm release version change, it's now epel-release-7-6.noarch.rpm

**Comment by cachedout** [comment]
We've identified the problem and we're working on getting things updated right now. Apologies for the breakage here. We'll have it right shortly.

**Comment by asachs** [comment]
Verified working now - thanks for the quick turnaround

**Comment by cachedout** [comment]
Sure thing. @BlueMonday could you close this when you're ready? Thanks.

**Comment by jfindlay** [comment]
https://bootstrap.saltstack.com/ has been updated, and I have verified by bootstrapping a CentOS 7 VM.

**Comment by BlueMonday** [comment]
> Sure thing. @BlueMonday could you close this when you're ready? Thanks.

Thank you for the quick turnaround!
Have fun at salt conf!
