### ISSUE TITLE
Bootstrap installs outdated version of python-tornado package on Debian Jesse

### ISSUE THREAD

**Issue by thehunmonkgroup** [saltstack/salt-bootstrap#820]
It appears commit 05df2e4186 in the Salt repository broke installs on Debian Jessie.

`from tornado.httputil import parse_response_start_line, HTTPInputError` throws an error.

Jessie includes the python-tornado 3.2.x series in package form, and `parse_response_start_line` doesn't look like it was added until 4.x. I can fix the error by upgrading tornado via pip, and, curious if this should be considered a bug, or if i should just enable the pip-based install option when bootstrapping salt?

**Comment by siccrusher** [comment]
Running into the same problem. From my pov its a bug, as its a version mismatch. The `requirements/base.txt` defines the requirement like this: `tornado>=4.2.1`so it should be fine, if the bootstrap would install salts requirements correctly.

**Comment by jfindlay** [comment]
Thanks for reporting, @thehunmonkgroup, @siccrusher.  Can either of you verify if the fix from @vutny fixes the issue?

**Comment by siccrusher** [comment]
@jfindlay Checked this PR locally in a fresh environment. It worked quite fine.

**Comment by thehunmonkgroup** [comment]
also confirmed as working here, using the PR and latest debian 8.x release

**Comment by jfindlay** [comment]
Excellent, thanks for the confirmation.

**Comment by vutny** [comment]
Cool, looking forward to get #828 merged.

**Comment by jfindlay** [comment]
Ping @s0undt3ch, @rallytime.

**Comment by vutny** [comment]
@thehunmonkgroup #828 was finally merged. Thanks @s0undt3ch. This issue could be closed.
