### ISSUE TITLE
salt-api issue in _get_event method

### ISSUE THREAD

**Issue by seshenli** [saltstack/salt-bootstrap#823]
### Description of Issue/Question

when i call salt-api ,an error occurred,
TypeError: unsupported operand type(s) for +: 'float' and 'unicode'
File "/usr/lib/python2.6/site-packages/salt-2016.3.0-py2.6.egg/salt/utils/event.py", line 465, in _get_event
in line timeout_at = start + wait
add 
if isinstance(wait, basestring):
            wait = float(wait)

**Comment by jfindlay** [comment]
@seshenli, will you reopen this at [salt](https://github.com/saltstack/salt/issues/new/) and also include information such as the master config you're using and the specific query you're sending to salt-api?  Thanks.
