### ISSUE TITLE
Error installing on OpenSuse 13.1 

### ISSUE THREAD

**Issue by l0ris** [saltstack/salt-bootstrap#837]
*_Bootstrap fails on OpenSuse 13.1 *_
### Setup
-  INFO:  /tmp/bootstrap_salt.sh -- Version 1.5.2
-  INFO: System Information:
-  INFO:   CPU:          GenuineIntel
-  INFO:   CPU Arch:     x86_64
-  INFO:   OS Name:      Linux
-  INFO:   OS Version:   3.12.53-40-default
-  INFO:   Distribution: openSUSE project 13.1

Executing the command:

/tmp/bootstrap_salt.sh  -P -c /tmp -c /tmp -M -N stable 
- ERROR: No dependencies installation function found. Exiting...

The OS is detected as "openSUSE project 13.1", I tried with different version of openSuSe and I get the same error.

**Comment by justinta** [comment]
@l0ris This is because we only have support for 13.2 in our repo, http://repo.saltstack.com/opensuse/. Unfortunately right now we only have 12 and 13.2. I believe we just mirror the official Suse repo's here. So it's something that  @dmurphy18 can say more about, I think.

@UtahDave

**Comment by l0ris** [comment]
@jtand Reproduced with OpenSUSE 13.2, but I got the same error

/tmp/bootstrap_salt.sh  -P -c /tmp -c /tmp -M -N stable

Stdout from the command:
-  INFO:  /tmp/bootstrap_salt.sh -- Version 1.5.2
-  INFO: System Information:
-  INFO:   CPU:          GenuineIntel
-  INFO:   CPU Arch:     x86_64
-  INFO:   OS Name:      Linux
-  INFO:   OS Version:   3.16.7-35-default
-  INFO:   Distribution: openSUSE project 13.2
-  INFO: Installing master
-  INFO: Found function config_salt
-  INFO: Found function daemons_running
- ERROR: No dependencies installation function found. Exiting...

**Comment by jfindlay** [comment]
@l0ris, thanks for reporting.  Can you post the output of bootstrap with the `-D` (debug) option?

**Comment by rallytime** [comment]
Hi @l0ris - It looks like this has been fixed. I just tested this again with the most recent stable version of salt bootstrap (`2016.06.27`) and I am able to install on openSUSE 13.2 successfully:

```
linux:~ # sh install_salt.sh
 *  INFO: Running version: 2016.06.27
 *  INFO: Executed by: sh
 *  INFO: Command line: "install_salt.sh "

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   4.5.5-x86_64-linode69
 *  INFO:   Distribution: opensuse 13.2

 *  INFO: Installing minion
 *  INFO: Found function install_opensuse_stable_deps
 *  INFO: Found function install_opensuse_stable
 *  INFO: Found function install_opensuse_stable_post
 *  INFO: Found function install_opensuse_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Found function install_opensuse_check_services
 *  INFO: Running install_opensuse_stable_deps()
<snipped>
 *  INFO: Running install_opensuse_stable_post()
disabled
ln -s '/usr/lib/systemd/system/salt-minion.service' '/etc/systemd/system/multi-user.target.wants/salt-minion.service'
 *  INFO: Running install_opensuse_check_services()
 *  INFO: Running install_opensuse_restart_daemons()
 *  INFO: Running daemons_running()
 *  INFO: Salt installed!
linux:~ #
linux:~ # salt-call --versions
Salt Version:
           Salt: 2015.8.10

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.22
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.0.0
         Python: 2.7.8 (default, Sep 30 2014, 15:34:38) [GCC]
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: 3.3.0
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.0
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.5
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: SuSE 13.2 x86_64
        machine: x86_64
        release: 4.5.5-x86_64-linode69
         system: openSUSE  13.2 x86_64
```

Are you still running into this issue with a newer version of the bootstrap script? (Note that I was able to install successfully using the same script arguments you passed in above, as well.)

**Comment by rallytime** [comment]
Closing since we haven't heard back here and I was able to install successfully on openSUSE 13.2. If this remains a problem for you, leave a comment and we can take another look. Thanks!
