### ISSUE TITLE
Bootstrap does not use repo.bootstrap.com for Debian 7 Wheezy

### ISSUE THREAD

**Issue by Talkless** [saltstack/salt-bootstrap#838]
I just used script from https://bootstrap.saltstack.com to install 2015.8 minion on Wheezy, but actually got only 2015.5.

repo.bootstrap.com has 2015.8 for Wheezy prepared, but bootstrap uses debian.saltstack.com instead:
https://github.com/saltstack/salt-bootstrap/blob/v2016.04.18/bootstrap-salt.sh#L2680

**Comment by jfindlay** [comment]
@Talkless, thanks for the report.

**Comment by vutny** [comment]
@jfindlay I've fixed that in PR #864. Waiting for it to be merged.

**Comment by Talkless** [comment]
Thank you @vutny !
