### ISSUE TITLE
What is the purpose of changing default master/minion names?

### ISSUE THREAD

**Issue by themalkolm** [saltstack/salt-bootstrap#856]
This scripts gives another default values for minion id and master address. Is there really a good reason to do so? In salt configuration we see that default master address is `salt` and minion id is its hostname. This bootstrap script silently changes them to `master` and `salt-minion`. Why?

```
  [Parameter(Mandatory=$false,ValueFromPipeline=$true)]
  [string]$minion = "salt-minion",

  [Parameter(Mandatory=$false,ValueFromPipeline=$true)]
  [string]$master = "master"
```

**Comment by twangboy** [comment]
@themalkolm  I agree. This should probably only send parameters to the installer if they are passed. That way installer defaults will be used... which would be hostname for the minion id and salt for the master id. I'll take a look at it.

**Comment by themalkolm** [comment]
Thanks!

**Comment by twangboy** [comment]
@themalkolm I submitted a PR to address this issue. I also fixed another issue that was causing the config layed down by the installer to be overwritten by a config copied from a Vagrant environment.

**Comment by themalkolm** [comment]
@twangboy is there some kind of automatic tests for Windows bootstrap script? Do you test manually on your PC?

**Comment by twangboy** [comment]
Yeah, I don't think there are any tests. Especially for the powershell script. I just test on my box.

**Comment by jfindlay** [comment]
I am closing this since it appears to have been fixed.  @themalkolm, running continuous tests on windows is one of our short term goals, so when that is ready, I imagine that we will be running windows bootstraps very frequently.
