### ISSUE TITLE
Install fails when new pacman is available on archLinux.

### ISSUE THREAD

**Issue by maru1034sk** [saltstack/salt-bootstrap#86]
The installer fails, if pacman needs to be upgraded.

Pacman is installed then, but the dependencies for salt are not.

**Comment by s0undt3ch** [comment]
So pacman should be upgraded first, correct?

## 

Pedro Algarvio @ phone

----- Reply message -----
De: "Angelo Gründler" notifications@github.com
Para: "saltstack/salt-bootstrap" salt-bootstrap@noreply.github.com
Assunto: [salt-bootstrap] Install fails when new pacman is available on archLinux. (#86)
Data: seg, Mar 11, 2013 12:04
The installer fails, if pacman needs to be upgraded. 

Pacman is installed then, but the dependencies for salt are not. 

&mdash;

**Comment by maru1034sk** [comment]
Right.

Pedro Algarvio notifications@github.com schrieb:

> So pacman should be upgraded first, correct?
> 
> ## 
> 
> Pedro Algarvio @ phone
> 
> ----- Reply message -----
> De: "Angelo Gründler" notifications@github.com
> Para: "saltstack/salt-bootstrap" salt-bootstrap@noreply.github.com
> Assunto: [salt-bootstrap] Install fails when new pacman is available on
> archLinux. (#86)
> Data: seg, Mar 11, 2013 12:04
> The installer fails, if pacman needs to be upgraded. 
> 
> Pacman is installed then, but the dependencies for salt are not. 
> 
> &mdash;
> Reply to this email directly or view it on GitHub.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/saltstack/salt-bootstrap/issues/86#issuecomment-14730658

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by s0undt3ch** [comment]
This is now fixed in the develop branch.
