### ISSUE TITLE
__ubuntu_codename_translation function missing codename translation for Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by andreselliku** [saltstack/salt-bootstrap#862]
### Description of Issue/Question

The function __ubuntu_codename_translation is missing a translation case for Ubuntu 16.04 LTS although the packages are up at repo.saltstack.com. Due to this an incorrect trusty codename is written to the /etc/apt/sources.list.d/saltstack.list file, breaking the script.
### Steps to Reproduce Issue

(Include debug logs if possible, `bootstrap-salt.sh -D`.)
Download bootstrap from repo.saltstack.com and run it on an Ubuntu 16.04 machine
### Versions and Systems

./install_salt.sh -- Version 2016.05.11

**Comment by andreselliku** [comment]
Fix would be to merge pull request #852

**Comment by rallytime** [comment]
@andreselliku Hi! I just merged #852 into develop. Can this issue be closed?

**Comment by andreselliku** [comment]
@rallytime Yep, closing it.
