### ISSUE TITLE
bootstrap-salt.sh fails in chroot environment

### ISSUE THREAD

**Issue by mrichar1** [saltstack/salt-bootstrap#872]
I'm trying to run `bootstrap-salt.sh` on an ubuntu 16.04 client as part of a `preseed`, running the script as part of a `preseed` `late_command` script. This involves chroot-ing into the final install image and running the script there.

When `systemctl`is called to start the salt daemons, it returns `Running in chroot, ignoring request.` and the salt services aren't started. Worse, `systemctl` returns `0`, so the error isn't spotted.

The relevant code block is here: https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L2584-L2591

I'm not sure what the correct solution is here - ubuntu comes with an `ischroot` command which might help in detecting this, but I don't know if this should just be skipped for chroots, flagged as a warn instead of a fail, or dealt with in some other way...

**Comment by vutny** [comment]
Hi @mrichar1 

Just provide `-X -d` options to `bootstrap-salt.sh` script:

```
    -X  Do not start daemons after installation
    -d  Disable check_service functions. Setting this flag disables the
        'install_<distro>_check_services' checks. You can also do this by
        touching /tmp/disable_salt_checks on the target host.
        Default: ${BS_FALSE}
```

**Comment by mrichar1** [comment]
Ahh, thanks - that should fix things.

**Comment by jfindlay** [comment]
@mrichar1, thanks for reporting.  Do you consider @vutny's comment to resolve the issue?

**Comment by mrichar1** [comment]
Yes - these options work fine. I don't know if there's any point in updating the docs to highlight this issue?

**Comment by jfindlay** [comment]
Good idea, let's add it.

**Comment by vutny** [comment]
By the way, I made those options better explained and behave correctly in my PR #867. That actually covers Ubuntu as well.

And just to note: the `-d` option is required only in chroots/containers with `systemd` installed. On older Linux distros it is possible to bootstrap in chroot without it.

**Comment by rallytime** [comment]
I added the "Fixed Pending Verification" label here so we remember to close this once #867 is merged in. Thanks everyone!

**Comment by rallytime** [comment]
#867 has been merged. Closing.
