### ISSUE TITLE
Unable to bootstrap a 16.04 (xenial) machine due to install_ubuntu_check_services

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt-bootstrap#874]
### Description of Issue/Question

Follow up to #873. 

Running 

```
sudo sh bootstrap_salt.sh -A salt.example.com -r
```

Results in:

```
 *  INFO: Running install_ubuntu_stable_post()
 *  INFO: Running install_ubuntu_check_services()
 * DEBUG: Checking if service salt-minion is enabled
 * DEBUG: Service salt-minion is NOT enabled
 * ERROR: Failed to run install_ubuntu_check_services()!!!
 * DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe
```

Manually starting the service works just fine though.

**Comment by ethanmick** [comment]
This seems to occur for me as well (but strangely, only sometimes).

*\* Update **
The minion seemed to be crashing on missing the python `tornado` dependency. Running:

```
pip install tornado
```

Before installing salt allowed the bootstrap to work every time.

**Comment by jfindlay** [comment]
@syphernl, thanks for reporting.  What version of salt are you bootstrapping?  Ubuntu 16.04 is only officially supported on salt 2016.3 and later, but if there are problems with that version of salt, fixing them may make other salt versions work as well.

**Comment by syphernl** [comment]
@jfindlay I'm bootstrapping the stable version (2016.3.0) so I should be fine, its just the bootstrap process which currently fails. If I manually start salt-minion (after the bootstrap fails) everything works just fine.

**Comment by rallytime** [comment]
@syphernl Is this issue still a problem for you? I think this should be fixed by the latest stable release of bootstrap.

**Comment by syphernl** [comment]
@rallytime Verified, works fine now!
