### ISSUE TITLE
Please add Trisquel distro support

### ISSUE THREAD

**Issue by josh-wrale** [saltstack/salt-bootstrap#88]
I am migrating to Trisquel 6.0, which is a free-as-in-freedom derivative of Ubuntu 12.04 LTS.

Here is the /etc/lsb-release file:

DISTRIB_ID=Trisquel
DISTRIB_RELEASE=6.0
DISTRIB_CODENAME=toutatis
DISTRIB_DESCRIPTION="Trisquel 6.0"

I was told today in Trisquel IRC that Ubuntu PPA's are usable with Trisquel.  I was able to run a 's/ubuntu/trisquel/g' on the bootstrap script, which worked, but seemed scary, because it altered the hyperlinks, causing 404's.  It looks like the apt-get installs dropped back to trisquel repos that are the hard-coded in the OS.

Let me know if I might provide any helpful information.

Thanks,
Joshua

**Comment by s0undt3ch** [comment]
@josh-wrale since you already have a Tristel instance running, could you paste the output of:

```
curl -L http://bootstrap.saltstack.org | sudo sh -s -- -D
```

That way I can at least know if Tristel it's properly detected, the rest should be simple since it's Ubuntu based.

**Comment by josh-at-knoesis** [comment]
@s0undt3ch, thanks for the quick reply.  Here is the output you requested

```
 *  INFO: PIPED THROUGH sh -- Version 1.5

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.2.0-38-generic
 *  INFO:   Distribution: Trisquel 6.0

 *  INFO: Installing minion
 * DEBUG: install_trisquel_6_stable_deps not found....
 * DEBUG: install_trisquel_6_0_stable_deps not found....
 * DEBUG: install_trisquel_6_deps not found....
 * DEBUG: install_trisquel_6_0_deps not found....
 * DEBUG: install_trisquel_stable_deps not found....
 * DEBUG: install_trisquel_deps not found....
 * DEBUG: install_trisquel_6_stable not found....
 * DEBUG: install_trisquel_6_0_stable not found....
 * DEBUG: install_trisquel_stable not found....
 * DEBUG: install_trisquel_6_stable_post not found....
 * DEBUG: install_trisquel_6_0_stable_post not found....
 * DEBUG: install_trisquel_6_post not found....
 * DEBUG: install_trisquel_6_0_post not found....
 * DEBUG: install_trisquel_stable_post not found....
 * DEBUG: install_trisquel_post not found....
 * DEBUG: install_trisquel_6_stable_restart_daemons not found....
 * DEBUG: install_trisquel_6_0_stable_restart_daemons not found....
 * DEBUG: install_trisquel_6_restart_daemons not found....
 * DEBUG: install_trisquel_6_0_restart_daemons not found....
 * DEBUG: install_trisquel_stable_restart_daemons not found....
 * DEBUG: install_trisquel_restart_daemons not found....
 * ERROR: No dependencies installation function found. Exiting...
 * DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe
```

**Comment by s0undt3ch** [comment]
That's the desired and expected output, Thanks!

**Comment by s0undt3ch** [comment]
If it's not asking for too much, could you please run the following 3 command lines and report it's success or not?

Stable install:

```
curl -L https://github.com/s0undt3ch/salt-bootstrap/raw/distro-support/trisquel/bootstrap-salt.sh | sudo sh -s -- -D
```

Daily install:

```
curl -L https://github.com/s0undt3ch/salt-bootstrap/raw/distro-support/trisquel/bootstrap-salt.sh | sudo sh -s -- -D daily
```

Git install:

```
curl -L https://github.com/s0undt3ch/salt-bootstrap/raw/distro-support/trisquel/bootstrap-salt.sh | sudo sh -s -- -D git v0.13.2
```

**Comment by josh-wrale** [comment]
Looks like success to me.  Thanks!  Please take a look and confirm:

cmd 1:
http://pastebin.com/raw.php?i=zgKs6VQq

cmd 2:
http://pastebin.com/raw.php?i=1c149Drx

cmd 3:
http://pastebin.com/raw.php?i=kEZJCZFV

-Joshua

**Comment by s0undt3ch** [comment]
@josh-wrale not quite ;)

The 2nd command should also work, after all, Trisquel is still ubuntu.
And the 3rd showed some version issues, it should not(you had tried installing from git previously? or run the command more than once?)

**Comment by s0undt3ch** [comment]
@josh-wrale ok, I've made some more changes. Could you please try and paste the output of the last 2 commands?

Thanks!

**Comment by josh-wrale** [comment]
Right on.  Thanks for following up.  I have been running the commands consecutively, from a blank Trisquel 6.0 VM.  No uninstalls were done between commands.  Let me know if I should alter my testing procedure and re-run.

cmd 2, run 2:
http://pastebin.com/raw.php?i=UhbAhmEn

cmd 3, run 2:
http://pastebin.com/raw.php?i=MetTPFQw

Thanks,
Joshua

**Comment by s0undt3ch** [comment]
Ok, since you've asked for it, and since the bootstrap script can really benefit from it, how about the following commands?

``` console
sudo apt-get update
sudo apt-get install python git
git clone git://github.com/s0undt3ch/salt-bootstrap.git
cd salt-bootstrap
git checkout distro-support/trisquel
sudo python tests/install-testsuite-deps.py
sudo python tests/runtests.py -vv
```

The commands above will run the existing testsuite, if all tests pass, we're good to merge.

**Comment by s0undt3ch** [comment]
**ATTENTION**: The test suite is destructive! Forgot to mention that, run it in that VM you previously used.

**Comment by josh-wrale** [comment]
https://gist.github.com/josh-wrale/5193451

## Excerpt: 

Ran 14 tests in 727.551s

FAILED (failures=1, skipped=1)
root@trisquel-2:~/salt-bootstrap# exit
exit

Thanks,
Joshua

**Comment by s0undt3ch** [comment]
One more run over the testsuite commands? You should only get one skip and then we can merge :smile:

**Comment by josh-wrale** [comment]
https://gist.github.com/josh-wrale/5200282

## Excerpt:

Ran 14 tests in 1395.291s

OK (skipped=1)
root@trisquel-2:~/salt-bootstrap# 

Looks good to me!

Thanks again!
Joshua

**Comment by s0undt3ch** [comment]
Cool!!!

## 

Pedro Algarvio @ phone

----- Reply message -----
De: "josh-wrale" notifications@github.com
Para: "saltstack/salt-bootstrap" salt-bootstrap@noreply.github.com
Cc: "Pedro Algarvio" pedro@algarvio.me
Assunto: [salt-bootstrap] Please add Trisquel distro support (#88)
Data: ter, Mar 19, 2013 21:26
https://gist.github.com/josh-wrale/5200282 

Excerpt: 

Ran 14 tests in 1395.291s 

OK (skipped=1)

root@trisquel-2:~/salt-bootstrap#  

Looks good to me! 

Thanks again!

Joshua 

&mdash;
