### ISSUE TITLE
`sudo` should be optional

### ISSUE THREAD

**Issue by khaije1** [saltstack/salt-bootstrap#880]
A command line switch to indicate that `sudo` is unnecessary would be a nice addition about would solve the problem that I'm experiencing.

The assumption that most people are running `salt-bootstrap` as non-`root` seems reasonable, but it shouldn't be a requirement even when running as `root`.

I'm working around this by disabling the `requiretty` setting in the kickstart file, but this is not ideal because it's a permanent alteration of the operating system only to satisfy the `salt-bootstrap` used during the early provisioning step.

It's a little tricky to explain apologies if this is still vague.

**Comment by khaije1** [comment]
(Ex.) even when running as `root`, `salt-bootstrap` will fail on some distros, (CentOS, RHEL, etc) because of `sudo`'s `requiretty` requirement.

**Comment by jfindlay** [comment]
@khaije1, thanks for reporting.  I think I understand.  This would be a useful feature to have.

**Comment by gdm85** [comment]
I have some personal-use systems (think of embedded, IoT & similar) where I am the only user and `sudo` is a package never installed, they are truly non-multi-user systems and user impersonation via sudo would not be necessary.

**Comment by khaije1** [comment]
This change described in this issue remains desirable.

**Comment by eradman** [comment]
I having trouble understanding this ticket. `bootstrap-salt.sh` doesn't use `sudo` at all. (And most of the time I run it on systems that don't have `sudo` installed.)  Could someone try to rephrase this request?

**Comment by gdm85** [comment]
@eradman I do not remember about the specific issue when I commented (if any), but I believe the problem reported happens only when using `sudo` while if you login as root (or use `su`) the problem does not happen. Can @khaije1 confirm?

In that case a documentation clarification (it currently suggests to use `sudo` in many places) would be enough.

**Comment by rallytime** [comment]
@gdm85 A documentation change clarifying this would be most welcome! Is this something you would be willing to contribute? If not, perhaps @eradman would like to.

**Comment by eradman** [comment]
I actually think the documentation is good as it is!

Any time instructions include `sudo some_cmd` I can also infer that running without `sudo` as root will work as well.

**Comment by rallytime** [comment]
@eradman That's totally fair. Perhaps just a quick note of clarification then is all we need since that will likely help people. I can put something together today.
