### ISSUE TITLE
v2016.06.24 fails to deploy salt minion (inifinte loop?)

### ISSUE THREAD

**Issue by johtso** [saltstack/salt-bootstrap#888]
### Description of Issue/Question

Fails to install salt minion, seems to be in some kind of infinitely loops, possibly with multiple processes running at the same time? (overlapping log output)
### Steps to Reproduce Issue

`curl -L  https://bootstrap.saltstack.com | sudo sh -s -- -i $INSTANCE_NAME -A our-salt-master.com`
Debug logs output: https://gist.github.com/johtso/75d35b70642e9099ba920e6224fe67cc
### Versions and Systems

Running as a user data script on an Amazon ec2 instance. ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-20140927
v2016.06.24 salt bootstrap

**Comment by abednarik** [comment]
I face similar issues yesterday.  The whole process was working but now in Ubuntu 14.04 I  can't bootstrap an instance. In my case, bootstrap scripts fails to start salt-minion. I didn't get the time to get the proper logs. Will do this week.

**Comment by meyerbro** [comment]
Me too... My team in fact...

**Comment by vutny** [comment]
Hey, I've fixed this in #889. Welcome to test!

FYI @jfindlay @rallytime

**Comment by rallytime** [comment]
Hi everyone - thank you for reporting this issue (and for the PR @vutny). I confirmed the looping you are seeing when running the script as a one-liner and confirmed the fix resolves that behavior. I have merged in @vutny's fix into `develop` and we'll be doing another bootstrap release soon.
