### ISSUE TITLE
http://repo.saltstack.com/ broke FreeBSD <= 10.3 support

### ISSUE THREAD

**Issue by msiebeneicher** [saltstack/salt-bootstrap#908]
It's look like that the latest update of http://repo.saltstack.com/freebsd/10amd64-default/All/ brokes the FreeBSD support for all versions under 10.3.

After a confersation with @bapt under https://github.com/freebsd/pkg/issues/1451 his assumption is that you compile the packages with a FreeBSD 10.3 system instead of FreeBSD 10.1.

The result is that the saltstack-bootstrap failed under FreeBSD 10.2 with the following message:

``` sh
[1/13] Installing p5-Socket-2.021...
[1/13] Extracting p5-Socket-2.021: /usr/local/lib/libpkg.so.3: Undefined symbol "utimensat"
 * ERROR: Failed to run install_freebsd_git_deps()!!!
```

**Comment by rallytime** [comment]
Thank you for letting us know @msiebeneicher. 

@cedwards Can you take a look here?

**Comment by cedwards** [comment]
Hi. I spent some time today and rebuilt all the packages for every supported version. 9.3, 10.1, 10.2, 10.3, 11.0-BETA1. We could refresh the existing repo with these new packages, but it may require an update to the documentation / existing install. If the end-goal is to have point release specific repositories it will change the structure of the repo a bit. ...something to think about.

I don't think we need to do that however. It sounds like a priority issue between repositories. Let me look into this a bit more.

**Comment by msiebeneicher** [comment]
@cedwards : 

> Hi. I spent some time today and rebuilt all the packages for every supported version. 9.3, 10.1, 10.2, 10.3, 11.0-BETA1.

How far as i understand @bapt you only need one package repository for a major release. FreeBSD itself have only one repository for FreeBSD 10.x and build the packages with a 10.1 version, which should be also compatible on > 10.1 releases.

**Comment by cedwards** [comment]
@msiebeneicher - you're correct. I don't think we need point-release repositories, but I did build them just in case.

I have submitted a PR to update the FreeBSD documentation (merged). I think removing the `priority` definition in the pkg repo file should help.

**Comment by rallytime** [comment]
@msiebeneicher Is this issue resolved for you now? Can this be closed?

**Comment by msiebeneicher** [comment]
@rallytime: sry for the late response: yes, currently we don't had another issue related to this topic. But until the packages will not compiled under FreeBSD 10.1 it's possible to run into this issue again, i guess.

**Comment by rallytime** [comment]
@msiebeneicher No problem at all. I agree that it is possible to run into this issue again, and please let us know if it happens again. @cedwards Is our FreeBSD packager, so I think now that he knows of this issue, he can adjust his process accordingly so you don't bump into this again.

Thanks again for letting us know!

**Comment by tobiasgies** [comment]
Hi @rallytime and @cedwards, I'm a colleague of @msiebeneicher.

It seems we have a regression of this issue. When trying to install a package on a FreeBSD 10.2 box that uses the pkg built by SaltStack, I receive the following error message:

```
[1/2] Installing py27-setuptools27-28.1.0...
[1/2] Extracting py27-setuptools27-28.1.0:   0%/usr/local/lib/libpkg.so.3: Undefined symbol "utimensat"
```

"utimensat()" was added in FreeBSD 10.3, and the pkg in the SaltStack repo is indeed built with FreeBSD 10.3:

```
usr/local/sbin/pkg: ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), dynamically linked, interpreter /libexec/ld-elf.so.1, for FreeBSD 10.3, FreeBSD-style, stripped
```

Can we get pkg working in FreeBSD 10.2 again? Pretty please? :-)

**Comment by bapt** [comment]
you are using a pkg (the binary) version which is built on 10.3 not on 10.2 which explains your issue.

**Comment by cedwards** [comment]
So I just started work on building a package for 10.2 and I was met with
this:

WARNING: FreeBSD 10.2-RELEASE is approaching its End-of-Life date.
It is strongly recommended that you upgrade to a newer
release within the next 1 month.

EOL for 10.2 is the end of this year... just sayin'.

If you need to stay on 10.2 might I instead suggest easily building your
own package(s) with poudriere.
https://www.freebsd.org/doc/handbook/ports-poudriere.html
https://github.com/freebsd/poudriere/wiki

Thoughts?

Christer

**Comment by bapt** [comment]
yes 10.1 and 10.2 are EOL at the end of the year.

**Comment by lhovo** [comment]
I know 10.2 is now EOL, but having this incompatibly is rather annoying.
We are hoping to get another 6 months from this server before migrating services to the new server.

Is there any work around besides building the packages by hand?

FreeBSD 10.2-RELEASE-p12

Installed packages to be UPGRADED:
        pkg: 1.8.8 -> 1.9.4_1

Installed packages to be UPGRADED:
        vim: 8.0.0019_1 -> 8.0.0134_1
        perl5: 5.20.3_15 -> 5.24.1.r4_1

[1/3] Upgrading perl5 from 5.20.3_15 to 5.24.1.r4_1...
[1/3] Extracting perl5-5.24.1.r4_1:   0%/usr/local/lib/libpkg.so.3: Undefined symbol "utimensat"
