### ISSUE TITLE
Add python-chardet and python-urllib3 to RHEL7 repo

### ISSUE THREAD

**Issue by sjmh** [saltstack/salt-bootstrap#914]
The default repo will fail installing on a RHEL7 box, due to the requests package needing a higher version of python-chardet ( 2.2.1 ) and python-urllib3 ( 1.10 ).

These versions are actually already in the RHEL6 repo, but are not in the RHEL7.  Please get copies over to the RHEL7 repo and recreate the repodata.

**Comment by dmurphy18** [comment]
@sjmh Could you clarify which repo you are referring to when you state 'default repo', given that python-requests and python-urrlib3 are from the RHEL7 base and python-chardet from anaconda ?

**Comment by sjmh** [comment]
@dmurphy18 - Sorry, I probably should have clarified that better.

The default RHEL7 media contains older versions of the python-chardet and python-urllib3 RPMs - older than what are needed by the python-requests RPM that's included in the saltstack RHEL7 repo.  So, if you try to do something like this on RHEL7:

yum -y install --disablerepo=* --enablerepo=saltstack salt-minion

It'll fail, because it can't find the correct versions of python-chardet and python-urllib3.  You'll notice that these are included in the SaltStack RHEL6 repo and are in fact the correct versions that python-requests needs.

This one may be an 'opinion' issue, but I'd like to see the SaltStack repo's at a point where everything SaltStack needs to install on a vanilla install of an OS is included in the repo.  Otherwise, there has to be documentation on the install page, stating that the user also needs to enable a bunch of other OS repos in order for the SaltStack one to work.

Hope that clears things up and where I'm coming from on this.

**Comment by dmurphy18** [comment]
@sjmh I see the problem, that python-requests in redhat/7/x86_64 should not be there, as it is not in the list of packages to build for Redhat 7 (see salt-pack redhat_sls.pkg).  I shall remove in the next point release.  Typically, if a package is in the normal shipping code for a release, for example: base repo, SaltStack does not build that package.

Thank you for bring this to my attention.

**Comment by sjmh** [comment]
@dmurphy18 - I guess that would fix the issue.  I'm not sure I totally agree on that solution though - mostly because the minions that run on RHEL6 are running on different MAJOR versions of python-requests than minions running on RHEL7.  RHEL6 would be running with python-requests 2.6, while RHEL7 would be on 1.1.

Seems like you'd want to try and keep the major version # of the python modules as close as possible for the minions, rather than depending on the OS media to determine the lib version.

Also, python-requests is only part of base in RHEL7, which means, technically, it doesn't have to be installed on a minimal installation ( %packages --nobase ), which again, means that users are going to need to know that the repo doesn't provide every RPM they need to install the salt-minion.

**Comment by dmurphy18** [comment]
@sjmh I understand but have to draw the line at some point for expected packages to be provided by the underlying OS.  SaltStack does provide packages which are usually provided by 'extras' or some by 'base', but these are usually due to some packages not provided in common implementations, for example: on AWS pciutils is not provided.  I believe there  is documentation stating expected packages supported by underlying OS.

python-requests is 2.6.0-1.el7_1 on my Redhat 7 hence wondering if you are limited in your updates for Redhat 7 ?

**Comment by sjmh** [comment]
@dmurphy18 - We're not limited on updates, but I'm talking base OS media.

The base OS media for RHEL7u1 only contains python-requests 1.10.  You'd have to use the updates channel and update your system after the installation to get to python-requests 2.6.  So if we're talking what RHEL7 provides in base, then it doesn't provide python-requests 2.6, only 1.10.

It's not until you get to RHEL7u2 that requests switches over to 2.6 and I think you'll run into plenty of instances where people are installing previous versions of RHEL7 ( ie - u0 or u1 - we offer those OS types to our customers ), which means, at the start, there isn't any access to requests 2.6, until they update the box, and then install salt.  Of course, then there's the chicken/egg issue of people who want to install salt so that they can then run scripts to DO the updates.. :)

I get where you're coming from in that Salt shouldn't be responsible for providing _every_ RPM needed - there has to be some baseline around what you provide and what you don't, but I think it makes sense to include python-requests-2.6 and it's requirements ( chardet and urllib3 ) in the RHEL7 repo, especially since you could possibly get into scenarios where RHEL7 minions would be on ancient versions of requests, while RHEL6 minions wouldn't be.

**Comment by dmurphy18** [comment]
@sjmh Fair point about Redhat 7u1. I shall keep the python-requests and add the requested python-chardet and python-urllib3 for the next point release, which is in the near future.

**Comment by dmurphy18** [comment]
@sjmh Have created a salt-pack issue to provide for the dependencies.

I would like to close this issue here since it will be tracked in salt-pack, if you have no objections

**Comment by sjmh** [comment]
@dmurphy18 Nope, go for it.  Thanks for the discussion.

**Comment by rallytime** [comment]
Thanks for the discussion here, guys! I'll close this in favor of the salt-pack issue: https://github.com/saltstack/salt-pack/issues/119
