### ISSUE TITLE
https://bootstrap.saltstack.com redirecting to a location that doesnt exist.

### ISSUE THREAD

**Issue by doberloh** [saltstack/salt-bootstrap#920]
try to wget: https://bootstrap.saltstack.com

see 301 redirect to: https://bootstrap.saltstack.com/stable/bootstrap-salt.sh

see 404 not found.

**Comment by UtahDave** [comment]
Thanks for notifying us. This should be fixed now. Could you verify it's working for you now?

**Comment by UtahDave** [comment]
I've double checked this and this problem has been resolved. Thanks for notifying us of this issue so we could resolve this quickly.

I'm going to close this issue now. Please feel free to comment here or open another issue if you continue to see this problem.

Thanks!

**Comment by doberloh** [comment]
The issue seemed to resolve itself about an hour after I opened this ticket. Is it recommended to use the link as part of our bootstrap process? We were unable to fully provision nodes while this link was down.
