### ISSUE TITLE
Error when attempting to downgrade salt from 2016.3.1 to 2015.8.11

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-bootstrap#921]
### Description of Issue/Question

When attempting to downgrade from 2016.3.1 to 2015.8.11 I run into the following errors:

```
 *  INFO: Running daemons_running()
 * ERROR: salt-minion was not found running
 * ERROR: salt-master was not found running
 * ERROR: Failed to run daemons_running()!!!
 * ERROR: salt-minion was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
 * ERROR: salt-master was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
```

And when attempting to run salt:

```
root@vagrant-ubuntu-trusty-64:~# salt '*' test.ping
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 455, in salt_main
    import salt.cli.salt
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 9, in <module>
    import salt.utils.job
  File "/usr/lib/python2.7/dist-packages/salt/utils/job.py", line 8, in <module>
    import salt.minion
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 20, in <module>
    from salt.config import DEFAULT_MINION_OPTS
  File "/usr/lib/python2.7/dist-packages/salt/config/__init__.py", line 866, in <module>
    'base': [salt.syspaths.BASE_THORIUM_ROOTS_DIR],
AttributeError: 'module' object has no attribute 'BASE_THORIUM_ROOTS_DIR'
```

The reason this occurs is because during the downgrade the following file stays on the box:

`/usr/lib/python2.7/site-packages/salt/config/__init__.py` which includes the BASE_THORIUM_ROOTS_DIR attribute. If I remove that file it works fine. I think there needs to be a better clean up routine or maybe a better process for downgrading.
### Steps to Reproduce Issue
1.  `sh bootstrap.sh -M -P git v2016.3.1`  (setup the master/minion and make sure commands can be run)
2. `sh bootstrap.sh -g https://github.com/jfindlay/salt.git -M -P git v2015.8.11`
### Versions and Systems

This was tested on both ubuntu14 and centos7 and ran into the same errors.

**Comment by rallytime** [comment]
This is because we need to be able to clear out any stale `.pyc` files before performing the downgrade. I am not sure how to do that off the top of my head presently, but that is why this issue is happening between versions.

@s0undt3ch Have we run into this issue before? Seems like we likely have, but maybe never tested for it.

**Comment by jeffPOG** [comment]
I believe it is still an issue, removing `/usr/lib/python2.7/site-packages/salt/config/__init__.py` did not fix the issue for me.

**Comment by rallytime** [comment]
@Ch3LL and @s0undt3ch ^^

Can you re-open this?

**Comment by Ch3LL** [comment]
@jeffPOG the initial report are both very old versions. are you testing against those versions as well or a newer version?
