### ISSUE TITLE
Remove unsupported PPA:chris-lea repository from bootscript 

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt-bootstrap#926]
### Description of Issue/Question

Using ppa:chris-lea, should be using repo.saltstack.com or preferred overriding repository, see #L2298-2309
see salt https://github.com/saltstack/salt/issues/34122#issuecomment-238823418
### Setup

(Please provide relevant configs (Be sure to remove sensitive info).)
### Steps to Reproduce Issue

(Include debug logs if possible, `bootstrap-salt.sh -D`.)
### Versions and Systems

(`salt --versions-report`, `bootstrap-salt.sh -v`, system type and version,
cloud/VM provider as appropriate.)

**Comment by rallytime** [comment]
References the conversation in https://github.com/saltstack/salt/issues/34122
