### ISSUE TITLE
salt-cloud deploy fails in package update (without helpful error output)

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt-bootstrap#939]
As already in https://github.com/saltstack/salt/issues/35561#issuecomment-240819086 mentioned:

```
root@salt-euc1-01:~# lsb_release -d
Description:    Debian GNU/Linux 8.5 (jessie)
root@salt-euc1-01:~# salt-call --version
salt-call 2016.3.2 (Boron)
root@salt-euc1-01:~# salt-cloud --version
salt-cloud 2016.3.2 (Boron)
```

```
...
Fetched 655 kB in 5s (110 kB/s)
W: Failed to fetch http://cloudfront.debian.net/debian/dists/jessie-backports/main/source/Sources  Hash Sum mismatch

W: Failed to fetch http://cloudfront.debian.net/debian/dists/jessie-backports/main/binary-amd64/PackagesIndex  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
 * ERROR: Failed to run install_debian_8_deps()!!!
[ERROR   ] Failed to deploy 'deploy-euc1-01'. Error: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /srv/pillar/salt-cloud/setup-key.pem -p 22 admin@172.31.9.103 'sudo /tmp/.saltcloud-391d19a3-e884-4d20-aac3-2c4d634822c7/deploy.sh -c '"'"'/tmp/.saltcloud-391d19a3-e884-4d20-aac3-2c4d634822c7'"'"' -U -p curl'' failed. Exit code: 1
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2213, in run_map
    profile, local_master=local_master
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1281, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 2599, in create
    for key, value in six.iteritems(salt.utils.cloud.bootstrap(vm_, __opts__)):
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 528, in bootstrap
    deployed = deploy_script(**deploy_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 1517, in deploy_script
    if root_cmd(deploy_command, tty, sudo, **ssh_kwargs) != 0:
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 2168, in root_cmd
    retcode = _exec_ssh_cmd(cmd, allow_failure=allow_failure, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 1785, in _exec_ssh_cmd
    cmd, proc.exitstatus
SaltCloudSystemExit: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /srv/pillar/salt-cloud/nu3.pem -p 22 admin@172.31.9.103 'sudo /tmp/.saltcloud-391d19a3-e884-4d20-aac3-2c4d634822c7/deploy.sh -c '"'"'/tmp/.saltcloud-391d19a3-e884-4d20-aac3-2c4d634822c7'"'"' -U -p curl'' failed. Exit code: 1
[INFO    ] Complete
[DEBUG   ] LazyLoaded nested.output
deploy-euc1-01:
    ----------
    Error:
        Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /srv/pillar/salt-cloud/setup-key.pem -p 22 admin@172.31.9.103 'sudo /tmp/.saltcloud-391d19a3-e884-4d20-aac3-2c4d634822c7/deploy.sh -c '"'"'/tmp/.saltcloud-391d19a3-e884-4d20-aac3-2c4d634822c7'"'"' -U -p curl'' failed. Exit code: 1
```

It would be nice
-  to get this error message without "-l debug" parameter set ;)
  => perhaps it depends on STDOUT/STDERR output of the bootstrap script?
- to have a stable function in bootstrap script to handle such package repo problems or
- if it make sense e.g. to ignore such package upgrade errors by additional parameter like 

```
    -U  If set, fully upgrade the system prior to bootstrapping salt
    -u  If set, fully upgrade the system prior to bootstrapping salt but ignore problems
```

**Comment by vutny** [comment]
Hi @Reiner030 

This actually means that Salt Bootstrap has failed after it was unable to retrieve correct package indexes, packages upgrade is not relevant in this case.

Generally this means that you're using (temporarily) inconsistent mirror, or the mirror was synchronizing with upstream archive just in that moment when apt tried to fetch files. Most of the times, it does no harm, but installation or upgrade of some packages could be impossible in later steps.
"Fail fast" as they say :-)

It's all the matter of how particular repository mirror is configured and synchronized and has nothing to do with the Salt Bootstrap or Salt Cloud.
Speaking about the [cloudfront.debian.net](https://cloudfront.debian.net), I assume that it's just a CDN cache, so perhaps it could be eventually inconsistent... Never used it myself though.

Anyhow, the check for a successful fetching indexes via `apt-get update` is removed in PR #940, but to address another issue of refreshing repo signing keys. I believe it should work for your case as well.

Try to grab the script from here for the `salt-cloud`:

``` sh
curl -s https://raw.githubusercontent.com/vutny/salt-bootstrap/apt-secure/bootstrap-salt.sh | \
sudo tee /etc/salt/cloud.deploy.d/bootstrap-salt.sh >/dev/null
```

**Comment by Reiner030** [comment]
1. I have to "love" AWS ... ;) and 
2. I have to use initially (which includes salt-bootstrap scriptrun) http://httpredir.debian.org/ 
   since one Jessie update the mantainers of Debian thinks they know what is "best/fastest" 
   mirror for us. :-(
   
   > **How about local/private mirrors?**
   > The redirector can not send users to a local address. Use a caching proxy.

The problem is that a failing bootstrapping causes a failed instance setup which is not nice in production environment / testing cases because it hungs in not clear defined phases (instance is setup by AWS console with tag/name) but not yet known in salt ...

Thx for the script link - actually it works again fine. I would test it on next outage ;)

Btw. I had same problems with GPG keys in January/February so i switched from keyserver to https key URL at this time.

**Comment by rallytime** [comment]
It sounds like the latest bootstrap script will help with the error you're seeing. I'm going to close this issue for now. If you bump into it again, please let us know and we can take another look. Thanks for the discussion here, guys!
