### ISSUE TITLE
Unable to launch a CentOS instance on AWS using Salt Cloud

### ISSUE THREAD

**Issue by Atvo** [saltstack/salt-bootstrap#942]
Hi, I'm trying to launch a new CentOS instance on aws with Salt Cloud, but the bootstrapping seems to fail because of an outdated url. 

Output of `salt-cloud -p <profile> <name1>`
...
-  INFO: /bin/sh /tmp/.saltcloud-dccdaff8-f635-4407-a0f6-30c48d979555/deploy.sh -- Version 2016.04.18
-  INFO: System Information:
-  INFO:   CPU:          GenuineIntel
-  INFO:   CPU Arch:     x86_64
-  INFO:   OS Name:      Linux
-  INFO:   OS Version:   3.10.0-229.20.1.el7.x86_64
-  INFO:   Distribution: CentOS 7.1
-  INFO: Installing minion
-  INFO: Found function install_centos_stable_deps
-  INFO: Found function config_salt
-  INFO: Found function install_centos_stable
-  INFO: Found function install_centos_stable_post
-  INFO: Found function install_centos_restart_daemons
-  INFO: Found function daemons_running
-  INFO: Found function install_centos_check_services
-  INFO: Running install_centos_stable_deps()
  Repodata is over 2 weeks old. Install yum-cron? Or run: yum makecache fast
  Connection to 52.29.104.190 closed.
  curl: (22) The requested URL returned error: 404 Not Found
  error: skipping https://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-7.noarch.rpm - transfer failed
  Retrieving https://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-7.noarch.rpm
- ERROR: Failed to run install_centos_stable_deps()!!!
  Error: There was a profile error: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /etc/salt/dev.pem -p 22 centos@52.29.104.190 'sudo /tmp/.saltcloud-dccdaff8-f635-4407-a0f6-30c48d979555/deploy.sh -c '"'"'/tmp/.saltcloud-dccdaff8-f635-4407-a0f6-30c48d979555'"'"''' failed. Exit code: 1

**Comment by vutny** [comment]
Hi @Atvo 

This issue is already fixed in the latest stable version of Salt Bootstrap. Try to upgrade the script by following instructions from here:
https://docs.saltstack.com/en/latest/topics/cloud/deploy.html#updating-salt-bootstrap

**Comment by rallytime** [comment]
Yes, this should already be fixed. If you're still running into problems after upgrading, please let us know and we can take another look. (Be sure to include the versions output of your bootstrap script  in your comment by running `sh /path/to/your/script.sh -v`.)
