### ISSUE TITLE
Parameter for repository http mirror

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt-bootstrap#946]
Since Debian Jessie has updated this year their default repository location (with in my opinion bad implementation because not configurable in scripted setups) to http://httpredir.debian.org/ repository I got from time to time into trouble like here the possibility to setup a local http mirror.

Debian/Ubuntu has package 
- **polipo** which is commonly a nice lightweight caching proxy service.
  Normally it should be used without problems for this case but when tested several setups with `-H <local proxy>:8123` with above repository URL I run into problems that the hosts behind this URL are very fluctuate so the level of utilisation falls into the deep and I got dozens of duplicated cached files on my proxy :-( ...
- **apt-cacher-ng** which works very well - but mainly for repository packages.
  When tested setups with `-H <local proxy>:3142` I run into problems that the bootscript uses the http_proxy itself for fetching GPG keys and other data which weren't allowd by apt-cacher-ng.
  So parts of bootstrap script fails if used (also later e.g. the java installer by webupd8) and the setup is not possible.

=> It would be nice to have a 2nd repository URL for the repository fetches.
  Depending how RPM based systems can work with proxies it could also for them an interesting option.

**Comment by rallytime** [comment]
Thanks for the request @Reiner030. That would be great to get this working for you so bootstrapping is easier when using `-H`. 

@vutny This one seems right up your alley as you've been making some changes in this area lately.
