### ISSUE TITLE
Fails on Arch with -j or -J because of python3 default

### ISSUE THREAD

**Issue by fizmat** [saltstack/salt-bootstrap#953]
### Description of Issue/Question

When running on Arch with -j or -J there is an error, and another error when reporting the first one.

What actually happens:
all libraries are installed on python2 (correctly) by salt-bootstrap
python is a symlink to python3 on Arch.
__overwriteconfig() uses python -c "~code~"
python3 does not have yaml installed, there's an error
when reporting the error there is again python -c "... print ~something~ ..."
print syntax is different in python3 so there's another error, but the original one is lost
I have a patch, will create a pull request soon.
### Setup

A new vagrant box with terrywang/archlinux
### Steps to Reproduce Issue

sudo sh bootstrap-salt.sh -j '{"master": "example.com"}' -D

```
......
 *  INFO: Running config_salt()
  File "<string>", line 1
    import os; print os.stat('/tmp/salt-config-7qiJA6VC').st_size;
                      ^
SyntaxError: invalid syntax
bootstrap_salt.sh: line 1921: [: : integer expression expected
  File "<string>", line 1
    tmp_file=open('/tmp/salt-config-7qiJA6VC'); print tmp_file.read(); tmp_file.close()
                                                             ^
SyntaxError: invalid syntax
 * DEBUG: 
 * ERROR: Python error encountered. This is likely due to passing in a malformed JSON string. Please use -D to see stacktrace.
 * ERROR: Failed to run config_salt()!!!
 * DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe
 * DEBUG: Killing logging pipe tee's with pid(s): 18473
```

**Comment by rallytime** [comment]
Thanks for finding and fixing this issue @fizmat! I'll close this since I just merged in your fix.
