### ISSUE TITLE
install_ubuntu_git_post() copies rpm service def

### ISSUE THREAD

**Issue by kung-foo** [saltstack/salt-bootstrap#956]
### Description of Issue/Question

[install_ubuntu_git_post](https://github.com/saltstack/salt-bootstrap/blob/v2016.08.16/bootstrap-salt.sh#L2592) copies `/pkg/rpm/salt-${fname}.service` rather than `/pkg/deb/salt-${fname}.service`

Not sure if this is intentional.

Also (though this is probably a salt issue) `pkg/salt-minion.service` and `pkg/deb/salt-minion.service` are different.
### Versions and Systems

bootstrap: v2016.08.16
salt: v2016.3.3

**Comment by rallytime** [comment]
Good catch @kung-foo. We need to fix that up. Should be quick. Thanks!

**Comment by rallytime** [comment]
@kung-foo Please see #965.

**Comment by kung-foo** [comment]
LGTM
