### ISSUE TITLE
multiple keys are generated despite invocation with "-i minion1"

### ISSUE THREAD

**Issue by oz123** [saltstack/salt-bootstrap#959]
I am invoking the bootstrap script as the following:

`sudo sh bootstrap_salt.sh -i ${minion_id} stable 2015.8`

The ${minion_id} is replaced by `terraform apply`.

When the EC2 is created it is automatically joined the cluster. However, when I list the keys on the master
I see that the minion has a key which was generated by script with the correct name, but also with the hostname given by amazon:

```
ubuntu@ip-172-16-80-80:~$ sudo salt-key -L
Accepted Keys:
ip-172-16-80-80.ec2.internal  # unwanted key ...
ip-172-16-91-202.ec2.internal    # unwanted key ...
master1 
minion1
Denied Keys:
Unaccepted Keys:
Rejected Keys:
```

```
$ sudo salt --versions-report
Salt Version:
           Salt: 2015.8.12

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-91-generic
         system: Ubuntu 14.04 trusty

$ bash bootstrap_salt.sh -v
bootstrap_salt.sh -- Version 2016.08.16

```

cloud/VM provider: AWS EC2 (default Ubuntu 14.04.01 version).

**Comment by oz123** [comment]
So in case somebody else is interested, I made a small script based on https://github.com/saltstack/salt/issues/13141 to remove the dead keys:

```
#!/bin/bash

# salt bootstrap start with 2 keys for each minion which causes
# a havoc ...

# $ sudo salt-key -L
# Accepted Keys:
# ip-172-16-80-80.ec2.internal
# ip-172-16-87-138.ec2.internal
# master1
# minion2
#
# sudo salt-run manage.status
#
# down:
#    - ip-172-16-80-80.ec2.internal
#    - ip-172-16-87-138.ec2.internal
# up:
#    - master1
#    - minion2
#

set -e

for key in $(salt-run --out txt manage.status | grep ^down | cut -d : -f 2 | tr -d "[]\'");
do
    # for delete the authenticated key 
    salt-key -d $key -y;
    # delete the pem  file
    if [ -f /etc/salt/pki/master/minions/%key ]
    then
        rm -f /etc/salt/pki/master/minions/$key
    fi
done
```

Or you can use:  [salt-run manage.down removekeys=True](https://docs.saltstack.com/en/2015.8/ref/runners/all/salt.runners.manage.html#salt.runners.manage.down)

**Comment by rallytime** [comment]
@oz123 Apologies for not commenting on this sooner. I meant to look into it, but then time got away from me. We definitely should look into getting this cleaned up. Thanks for posting your work-arounds as well.

I'll put some labels on this for now.

**Comment by brianholland99** [comment]
After being pointed to this ticket by @rallytime , this may be related to the order that the minion_id file and the Salt install is done.

The master configuration file and the minion_id files are dropped after the install is performed, but before the bootstrap script starts the daemons.  However, on Debian derivatives, the install actually starts the daemons and the default uses the FQDN, which would possibly explain why the master saw a minion with an FQDN as the minion ID. Then the minion_id file is dropped to disk and the daemon restarted, which would then connect with the intended minion ID.

Is this a Debian-based minion? (E.g., Debian, Ubuntu)

**Edit::**
Additional information :

I believe that this could be addressed by moving the dropping of the minion_id file to disk prior to installation of Salt packages.  I believe the same could be done for the master address file.

**Comment by oz123** [comment]
@brianholland99, the minion and the master are both Ubuntu. One work around for this problem in debian by creating minion_id and minion config files before the actual  installation of salt (e.g. populating the them with a user_data.sh script on AWS), like you suggested.. 
Further there is a documented work around how to [install a package in Debian, preventing the daemon start](https://major.io/2014/06/26/install-debian-packages-without-starting-daemons/).

**Comment by vutny** [comment]
@oz123 - Thanks for the confirmation. I believe I've fixed this issue in PR #987 with great help from @brianholland99.

Creating the `policy-rc.d` file is a valid and well known approach, but it should be done carefully and  only when user explicitly wants changing the default behavior of his/her system. Previously I had plans to implement this solution, so maybe will try to get back to it.

**Comment by rallytime** [comment]
@oz123 After commenting on #985, @brianholland99 says that the `-i` issues are fixed for them. I think this will be resolved for you as well with PR #987, which I just merged into develop.

@oz123 Would you be able to test this and let us know if this is resolved for you?

**Comment by oz123** [comment]
@rallytime, i will try to get to it next week. I have too many open projects now. If I don't answer until the end of next week, feel free to nag me.

**Comment by oz123** [comment]
@rallytime sorry for the late reply, I tested it, and it seems to work.

**Comment by rallytime** [comment]
Oh, no worries! Glad it's all fixed up for you now.
