### ISSUE TITLE
supporting RHEL 6 workstation distribution

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt-bootstrap#971]
### Setup

Not able to bootstrap on RHEL Enterprise Client 5 OS
Also "RHEL Enterprise Client 6 "
### Steps to Reproduce Issue
```
./bootstrap_salt.sh -- Version 2016.08.16
```
```
[root@ana ~]# ./bootstrap_salt.sh
-  INFO: Running version: 2016.08.16
-  INFO: Executed by: -
-  INFO: Command line: './bootstrap_salt.sh '
-  INFO: System Information:
-  INFO:   CPU:          GenuineIntel
-  INFO:   CPU Arch:     x86_64
-  INFO:   OS Name:      Linux
-  INFO:   OS Version:   2.6.18-348.6.1.el5
-  INFO:   Distribution: Red Hat Enterprise Client 5.9
-  INFO: Installing minion
-  INFO: Found function config_salt
-  INFO: Found function preseed_master
-  INFO: Found function daemons_running
- ERROR: No dependencies installation function found. Exiting...
[root@ana ~]#
```

### workaround
1. add following as /etc/yum.repos.d/stalstack.repo
```
   [saltstack]
   name=SaltStack latest Release Channel for RHEL/CentOS $releasever
   # baseurl=https://repo.saltstack.com/yum/redhat/$releasever/$basearch/latest/
   
   baseurl=https://repo.saltstack.com/yum/redhat/5Workstation/x86_64/2016.3/
   skip_if_unavailable=True
   gpgcheck=1
   # gpgkey=https://repo.saltstack.com/yum/redhat/$releasever/$basearch/latest/SALTSTACK-GPG-KEY.pub
   
   gpgkey=https://repo.saltstack.com/yum/redhat/5Workstation/x86_64/2016.3/SALTSTACK-EL5-GPG-KEY.pub
   enabled=1
   enabled_metadata=1
```
2. run `yum update salt-minion`

**Comment by rallytime** [comment]
Ah, thanks again @tjyang. I think this should be easy to resolve.

**Comment by tjyang** [comment]
@rallytime , I forgot to report that there is "Red Hat Enterprise Client 6.x" also. Beside "5Workstation", "6Workstation" is also needed.

**Comment by rallytime** [comment]
Ah, good to know. Thanks @tjyang!

**Comment by rallytime** [comment]
I have updated the title of this issue to be supporting RHEL 6 workstation distributing instead of RHEL 5.

The upstream RHEL release 5 reached EOL on March 31, 2017, and we are no longer supporting RHEL 5 and its variants. Therefore, we will not be fixing this issue for RHEL 5, only RHEL 6. Issue #1065 and pull request #1070 are related to this issue.

@vutny You might interested in adding support for this for RHEL 6 workstation.
