### ISSUE TITLE
Bootstrap fails on Amazon ECS-optimized AMI 2015.09

### ISSUE THREAD

**Issue by nvtkaszpir** [saltstack/salt-bootstrap#974]
### Description of Issue/Question

Bootstrap fails on Amazon ECS-optimized AMI amzn-ami-2015.09.g-amazon-ecs-optimized, because AMI does not have yum-utils installed.
### Setup

Just spawn any Instance with specific AMI from the list below:
us-east-1: ami-33b48a59
us-west-1: ami-26f78746
us-west-2: ami-65866a05
eu-west-1: ami-77ab1504
eu-central-1: ami-341efb5b
ap-northeast-1: ami-b3afa2dd
ap-southeast-1: ami-0cb0786f
ap-southeast-2: ami-cf6342a

For reference that those are official AWS images - http://thecloudmarket.com/image/ami-26f78746--amzn-ami-2015-09-g-amazon-ecs-optimized
### Steps to Reproduce Issue

Launch instance, ssh to it and execute commands:

``` bash
curl -L https://bootstrap.saltstack.com -o install_salt.sh
sudo sh install_salt.sh -P
```

See how it fails in around `install_amazon_linux_ami_deps()` when it tries to use `/usr/bin/yum-config-manager` which does not exist, because package `yum-utils` is not installed.
### Versions and Systems

``` bash
    /etc/lsb-release
    LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
    /etc/system-release
    Amazon Linux AMI release 2016.09
    /etc/os-release
    NAME="Amazon Linux AMI"
    VERSION="2016.09"
    ID="amzn"
    ID_LIKE="rhel fedora"
    VERSION_ID="2016.09"
    PRETTY_NAME="Amazon Linux AMI 2016.09"
    ANSI_COLOR="0;33"
    CPE_NAME="cpe:/o:amazon:linux:2016.09:ga"
    HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
```

``` bash

lsb_release -a
    LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
    Distributor ID: AmazonAMI
    Description:    Amazon Linux AMI release 2016.09
    Release:    2016.09
    Codename:   n/a
```

bootstrap script:

``` bash
/tmp/install_salt.sh -- Version 2016.08.16
```
### Workaround

Before running bootstrap script install package  `yum-utils`. The best is to do it in cloud-init with `runcmd:` section. Notice that `packages:` section is executed after `runcmd`.
### Fix

Bootstrap script should also install yum-utils package on Amazon Linux systems.

**Comment by rallytime** [comment]
Thanks @nvtkaszpir for letting us know! I'll get that fixed up.

**Comment by rallytime** [comment]
@nvtkaszpir Can you give the change in #977 a try? I was having a hard time getting this particular instance up and running on AWS, so testing that change would be greatly appreciated.

**Comment by nvtkaszpir** [comment]
It's not gonna work, see line 4099 - there's yum-config-manager used there.
While __PACKAGES are used after this.

So two options are available:
- (easy)  add yum install yum-utils in line 4091 before ENABLE_EPEL_CMD
  or
- (more work needed) change the script so that it does not use /usr/bin/yum-config-manager in line 4099 and 4102

**Comment by rallytime** [comment]
@nvtkaszpir Ah, Ok. Please see the new commit I added to #977.
