### ISSUE TITLE
Not able to bootstrap CentOS 5.5

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt-bootstrap#984]
### Description of Issue/Question
Not able to bootstrap centos 5.5
### Setup
I am hoping to be able install salt-minion without upgrade the CentOS 5.5 OS

### Steps to Reproduce Issue

```
sh bootstrap_salt.sh -i `hostname`
* INFO: Running version: 2016.10.25
* INFO: Executed by: sh
* INFO: Command line: 'bootstrap_salt.sh -i 63nis01'

* INFO: System Information:
* INFO: CPU: GenuineIntel
* INFO: CPU Arch: x86_64
* INFO: OS Name: Linux
* INFO: OS Version: 2.6.18-194.el5
* INFO: Distribution: CentOS 5.5

* INFO: Installing minion
* INFO: Found function install_centos_stable_deps
* INFO: Found function config_salt
* INFO: Found function preseed_master
* INFO: Found function install_centos_stable
* INFO: Found function install_centos_stable_post
* INFO: Found function install_centos_restart_daemons
* INFO: Found function daemons_running
* INFO: Found function install_centos_check_services
* INFO: Running install_centos_stable_deps()
* ERROR: Failed to run install_centos_stable_deps()!!!
```

### Versions and Systems
(`salt --versions-report`, `bootstrap-salt.sh -v`, system type and version,
cloud/VM provider as appropriate.)

**Comment by rallytime** [comment]
Hi @tjyang - Hm. Can you tell me which version of the bootstrap script you're using? And can you also run the command with `-D` so we can see the debug logs?

**Comment by tjyang** [comment]
Hi @rallytime , I can't provide the needed information anymore since that server had been upgraded to 5.11 (from 5.5).  After the upgrade the boot strap script worked.  You can comment and close this thread if you want.

**Comment by rallytime** [comment]
Ok, sounds good. I'll close it. If this pops up for anyone else, please leave a comment with the answers to the questions in my post above and we can take another look.
